### ISSUE TITLE
Arch Linux support

### ISSUE THREAD

**Issue by angristan** [angristan/openvpn-install#1]
As requested by @HLFH, I examined the possibility to add the support of Arch Linux.

It seems to be possible, however I need `rc.local` for the iptables rules here : 

- https://github.com/Angristan/OpenVPN-install/blob/master/openvpn-install.sh#L152
- https://github.com/Angristan/OpenVPN-install/blob/master/openvpn-install.sh#L373
- https://github.com/Angristan/OpenVPN-install/blob/master/openvpn-install.sh#L404

`rc.local` is present by default on Debian and Ubuntu, but not Arch Linux.

It is not even present the repositories, but just in the AUR : https://aur.archlinux.org/packages/rc-local/

However, I don't think it would be a great idea to install it from the AUR, because of security issues, but also, if the user does not have the AUR installed, which is probably the case on a server, I don't want to cover its installation.

We are in a dead end, so any idea is welcome 🙄

**Comment by HLFH** [comment]
Or by this way: https://raymii.org/s/tutorials/rc.local_support_on_Arch_Linux_and_systemd.html
AUR is still really useful in an Arch Linux server environment. I'm using [`pacaur`](https://github.com/rmarquis/pacaur) by the way.

**Comment by angristan** [comment]
Discussion for Arch Linux support : https://github.com/Angristan/OpenVPN-install/issues/2
