### ISSUE TITLE
NAT problem

### ISSUE THREAD

**Issue by NicolasLoew** [angristan/openvpn-install#10]
Got a NAT VPS with shared public ipv4 adress and 20 ports I can use.
I used port 101xx (one of my assigned public ports) and for some reason I can connect via ovpn but I dont have internet access :( Any ideas?

Using Ubuntu 14.04

**Comment by angristan** [comment]
When installing, the script should detect that you're NATed, so it will show your private IP adress at the beginning of the setup and then at the end it will ask you your public IPv4. 

Was it the case ?

**Comment by NicolasLoew** [comment]
Yeah. I just didnt realize it would first show the nated ip. Thought I need to enter public ip firsdt :P

**Comment by angristan** [comment]
It can be misleading at first. NP :)
