### ISSUE TITLE
Install OpenVPN 2.3 no connection to reboot

### ISSUE THREAD

**Issue by fuddel18** [angristan/openvpn-install#100]
Hello,

I have used the OpenVPN 2.3 script. Has also everything worked.
But when I restart the server I get no more connection to the OpenVPN server.
Server: Ubuntu 16.04.3, all updates, no other software installed.
The firewall (UFW) is also correctly configured since the first connection works. The connection no longer works immediately after the server has restarted.
does anyone know the problem?

Many thanks for the help.

**Comment by fuddel18** [comment]
A little more:
Have just a fresh Virtual machine with Ubuntu 16.04.3 set up to test the Scrpit again.
Also here I have the problem that he can not connect after a restart.
I then tested the OpenVPN script by the user Nyr and since synonymous reboot the connection.
Error in the OpenVPN app: Waiting for Server ...

**Comment by angristan** [comment]
Did it work for you after or reboot with Nyr's script ?

**Comment by fuddel18** [comment]
Yes, the server has rebooted and it works wonders. I can work with it.

**Comment by fuddel18** [comment]
Yes, the server has rebooted and it works wonders. I can work with it.
Sorry, it did not close.

**Comment by angristan** [comment]
Ok, I will do some testing to see if it applies to all OS. Thanks for reporting
