### ISSUE TITLE
Add support for RHEL/AlmaLinux/RockyLinux 9

### ISSUE THREAD

**Issue by alvise1988** [Angristan/OpenVPN-install#1011]
**Checklist**

- [x] I read the [README](https://github.com/angristan/openvpn-install/blob/master/README.md)
- [x] I read the [FAQ](https://github.com/angristan/openvpn-install/blob/master/FAQ.md)
- [x] I searched the [issues](https://github.com/angristan/openvpn-install/issues?q=is%3Aissue+)
- [x] My issue is about the script, and not OpenVPN itself

First of all, thank you very much for the script, it's incredibly useful and saves you plenty of time if you need to quickly and reliably set up an OpenVPN server.

Now that all RHEL clones have released their version 9, I would be curious to know if there is any plan to add support for these operating systems to the script.

Thank you very much!

**Comment by ehafizoglu** [comment]
Is there any update about the version 9 support?
Thanks

**Comment by angristan** [comment]
Should be OK with https://github.com/angristan/openvpn-install/commit/d2556ff235e9daa5fa10245050c4432f03a0258f!
