### ISSUE TITLE
Config home directory feature

### ISSUE THREAD

**Issue by torbikua** [Angristan/OpenVPN-install#1013]
**I love your script for deploying the server and creating certificates. But I'm missing 2 things:**

1. specifying the storage location of the created configs, you often have to rewrite the script. When I create a new server. It would be cool to put a configuration block at the beginning of the script.

2. also offer to install a small web server like nginx / lighttpd / or something else, so that you can download the config on the client.

**Comment by angristan** [comment]
PRs welcome! Closing for now
