### ISSUE TITLE
Consider setting groups/curves preference with tls-groups instead of forcing a specific curve with ecdh-curve.

### ISSUE THREAD

**Issue by goffy59** [Angristan/OpenVPN-install#1019]
installed openvpn using the script provided here. Works fine, connects fine but im a bit OCD when it comes to the status of services (I try to resolve any random errors/etc).

"● openvpn@server.service - OpenVPN connection to server
     Loaded: loaded (/etc/systemd/system/openvpn@.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2022-08-01 21:38:25 UTC; 2s ago
       Docs: man:openvpn(8)
             https://community.openvpn.net/openvpn/wiki/Openvpn24ManPage
             https://community.openvpn.net/openvpn/wiki/HOWTO
   Main PID: 39389 (openvpn)
     Status: "Initialization Sequence Completed"
      Tasks: 1 (limit: 1033)
     Memory: 1.8M
        CPU: 29ms
     CGroup: /system.slice/system-openvpn.slice/openvpn@server.service
             └─39389 /usr/sbin/openvpn --daemon ovpn-server --status /run/openvpn/server.status 10 --cd /etc/openvpn --script-security 2 --conf>

Aug 01 21:38:25 vpn systemd[1]: Starting OpenVPN connection to server...
Aug 01 21:38:25 vpn ovpn-server[39389]: Consider setting groups/curves preference with tls-groups instead of forcing a specific curve with ecdh>
Aug 01 21:38:25 vpn systemd[1]: Started OpenVPN connection to server.
"

How I can I make "Consider setting groups/curves preference with tls-groups instead of forcing a specific curve with ecdh-curve." go away? Or should I ignore it?

Tried 
chown -R root /etc/openvpn/client /etc/openvpn/server /var/log/openvpn (based on some google searches, was openvpn.network but changed to root cause i can't find the user openvpn.network in my system). Anyhow.. this could be nothing but I like clean status on services running. Sorry if this is completely not important. I love the script and it works great. :)

edit1: using linode server btw. root is default username.. maybe i should have made a user before running script? The docs say to run script as root. Anyhow, any advice is appreciated.

**Comment by TinCanTech** [comment]
`--tls-groups` allows Openvpn to use a selection of elliptic curves, instead of only a specific curve.  You don't need to worry about the message in the log at this time.

I do not know how this script will choose to deploy (or not) that option in the future.

**Comment by goffy59** [comment]
Thanks for the fast response. I will ignore the error. Have a good day!
