### ISSUE TITLE
[ Feature Idea ] Curl an automagically sanitized output of debugging information to self destructing https://hastebin.com

### ISSUE THREAD

**Issue by Leopere** [angristan/openvpn-install#102]
The idea here would be to store debugging information somewhere for a short period of time [ 30 days ] where the logs and relevant system information and configuration stuff can go. 

The benefit of using hastebin over gist is that its paste's are self destructing 30 days after the last time they were accessed.  I could expand on this if it seems like a feature to add to this or if it's out of scope.

**Comment by angristan** [comment]
Sorry, I don't understand what you want to store, and what's the point of it.

**Comment by Leopere** [comment]
It's just always good and possible to get a more automated and streamlined method of reporting bugs is all.

**Comment by angristan** [comment]
I don't really see the need and I don't want to depend on such 3re party service
