### ISSUE TITLE
Headless Users addition is not working - asking for user input 

### ISSUE THREAD

**Issue by abdulmannanbutt** [Angristan/OpenVPN-install#1021]
### Make sure your check these beforehand!

- [X] Issues - https://github.com/angristan/openvpn-install/issues
- [X] README and FAQ - https://github.com/angristan/openvpn-install
- [X] Wiki - https://github.com/angristan/openvpn-install/wiki
- [X] Discussions - https://github.com/angristan/openvpn-install/discussions

### Server OS

Ubuntu 18.04 (LTS) x64

### OpenVPN version

2.4.4

### What is the bug?

I am trying both the BASH script and single-line command to add a new certificate But it is still asking for the USER input. 

**Here is by BASH script:**
```
#!/bin/bash
export AUTO_INSTALL=y
export MENU_OPTION="1"
export CLIENT="nyc83"
export PASS="1"
./openvpn-install.sh
```

**Here is the single-line command:**

`AUTO_INSTALL=y MENU_OPTION="1" CLIENT="nyc83" PASS="1" ./openvpn-install.sh`

Please help to resolve this. 

![vpn1](https://user-images.githubusercontent.com/960569/183252246-dec1debb-800f-4a92-bd5d-3b6b4cad0c97.png)
![VPN2](https://user-images.githubusercontent.com/960569/183252250-455d285c-7368-4a4b-859a-c1059b242d84.png)

### Relevant log output

```shell
No such logs. when I run the bash script or single line command, it ask for user input again by showing a menu.
```

**Comment by abdulmannanbutt** [comment]
@angristan @Nyr @randomshell @dumrauf can someone please help? I need your support urgently.

**Comment by abdulmannanbutt** [comment]
Figured out the issue. Things are working fine. No input is required. Thanks.

**Comment by 0xGodspeed** [comment]
how was it fixed?

**Comment by abdulmannanbutt** [comment]
I was using an older version. It was a mistake at my end.

**Comment by abdulmannanbutt** [comment]
> how was it fixed?


I was using an older version. It was a mistake at my end.

**Comment by 0xGodspeed** [comment]
> > how was it fixed?
> 
> I was using an older version. It was a mistake at my end.

I see, thank you.
For future, if anyone visits this thread, I ended up using https://github.com/mimooh/ovclient/ which is a great tool to do stuff like this.
