### ISSUE TITLE
[Bug]: CN was already found in easy-rsa - Revoked a user and add the user with same name

### ISSUE THREAD

**Issue by iqbalpb** [Angristan/OpenVPN-install#1024]
### Make sure your check these beforehand!

- [X] Issues - https://github.com/angristan/openvpn-install/issues
- [X] README and FAQ - https://github.com/angristan/openvpn-install
- [X] Wiki - https://github.com/angristan/openvpn-install/wiki
- [X] Discussions - https://github.com/angristan/openvpn-install/discussions

### Server OS

ubuntu 20.04

### What is the bug?

I revoked a user and I planned to add him with same name and it showing an error

Note: I created client with password

The specified client CN was already found in easy-rsa, please choose another name.

**Comment by TinCanTech** [comment]
@iqbalpb01 This not a fault for this project, this belongs in https://github.com/OpenVPN/easy-rsa/issues

**Comment by coldsmirk** [comment]
> @iqbalpb01 This not a fault for this project, this belongs in https://github.com/OpenVPN/easy-rsa/issues

I have the same problem.

**Comment by coldsmirk** [comment]
> 

Do you have any other hack solutions? Thanks

**Comment by angristan** [comment]
Duplicate of https://github.com/angristan/openvpn-install/issues/989

**Comment by angristan** [comment]
Fixed with https://github.com/angristan/openvpn-install/commit/bda450948a933224f4f779a24a44c6279e1574a1 + https://github.com/angristan/openvpn-install/pull/1185 🙂
