### ISSUE TITLE
TimeOuts Setting - SIGUSR1[soft,ping-restart] received, process restarting

### ISSUE THREAD

**Issue by ScanCaster** [Angristan/OpenVPN-install#1038]
Thanks for the great script to install, setup and manage OpenVPN...

I have just one glitch... 

Time outs in the middle of use!

Using other OpenVPN servers I don't have this time out issue... 

One two different VPS setups I've got the same thing... about 1 HOUR or so I get:
[server_03XejqL8hd5QMLuq] Inactivity timeout (--ping-restart), restarting
Thu Sep 15 13:30:58 2022 SIGUSR1[soft,ping-restart] received, process restarting

I could be in the middle of playing a video, or any other use, and I everything stops, until this recycles.

I've tried to alter the config for the client and the settings on the server I was pointed to via various searches. 

Nothing changes, I still get this about every 1HR or so... 
There are other instances where things RENEW without issue like these,below. No interruptions to DL's or what not, things just renew and move along, but the ABOVE stalls downloads etc.. 

I'd like to stop the above issue, or make it so the timeout is far greater than 1 HOUR... If this was not in use, I get it... but this could be during active DL's or something... 

These are MY SERVERS, so there is no issue there. 

Any ideas on what I am missing here??? THANK YOU!

Thu Sep 15 15:31:03 2022 VERIFY OK: depth=1, CN=cn_IqWncR8auY4LF5Lg
Thu Sep 15 15:31:03 2022 VERIFY KU OK
Thu Sep 15 15:31:03 2022 Validating certificate extended key usage
Thu Sep 15 15:31:03 2022 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Thu Sep 15 15:31:03 2022 VERIFY EKU OK
Thu Sep 15 15:31:03 2022 VERIFY X509NAME OK: CN=server_03XejqL8hd5QMLuq
Thu Sep 15 15:31:03 2022 VERIFY OK: depth=0, CN=server_03XejqL8hd5QMLuq
Thu Sep 15 15:31:03 2022 Outgoing Data Channel: Cipher 'AES-128-GCM' initialized with 128 bit key
Thu Sep 15 15:31:03 2022 Incoming Data Channel: Cipher 'AES-128-GCM' initialized with 128 bit key
Thu Sep 15 15:31:03 2022 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_AES_256_GCM_SHA384, 256 bit EC, curve: prime256v1
Thu Sep 15 16:31:03 2022 VERIFY OK: depth=1, CN=cn_IqWncR8auY4LF5Lg
Thu Sep 15 16:31:03 2022 VERIFY KU OK
Thu Sep 15 16:31:03 2022 Validating certificate extended key usage
Thu Sep 15 16:31:03 2022 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Thu Sep 15 16:31:03 2022 VERIFY EKU OK
Thu Sep 15 16:31:03 2022 VERIFY X509NAME OK: CN=server_03XejqL8hd5QMLuq
Thu Sep 15 16:31:03 2022 VERIFY OK: depth=0, CN=server_03XejqL8hd5QMLuq
Thu Sep 15 16:31:03 2022 Outgoing Data Channel: Cipher 'AES-128-GCM' initialized with 128 bit key
Thu Sep 15 16:31:03 2022 Incoming Data Channel: Cipher 'AES-128-GCM' initialized with 128 bit key
Thu Sep 15 16:31:03 2022 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_AES_256_GCM_SHA384, 256 bit EC, curve: prime256v1
Thu Sep 15 17:31:04 2022 TLS: soft reset sec=-1 bytes=5773067/-1 pkts=12614/0
Thu Sep 15 17:31:04 2022 VERIFY OK: depth=1, CN=cn_IqWncR8auY4LF5Lg
Thu Sep 15 17:31:04 2022 VERIFY KU OK
Thu Sep 15 17:31:04 2022 Validating certificate extended key usage
Thu Sep 15 17:31:04 2022 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Thu Sep 15 17:31:04 2022 VERIFY EKU OK
Thu Sep 15 17:31:04 2022 VERIFY X509NAME OK: CN=server_03XejqL8hd5QMLuq
Thu Sep 15 17:31:04 2022 VERIFY OK: depth=0, CN=server_03XejqL8hd5QMLuq
Thu Sep 15 17:31:04 2022 Outgoing Data Channel: Cipher 'AES-128-GCM' initialized with 128 bit key
Thu Sep 15 17:31:04 2022 Incoming Data Channel: Cipher 'AES-128-GCM' initialized with 128 bit key
Thu Sep 15 17:31:0

**Comment by angristan** [comment]
Sounds like an OpenVPN issue, please search the web for theses errors 🔍
