### ISSUE TITLE
Peer certificate verification failure

### ISSUE THREAD

**Issue by sirotkaslo** [Angristan/OpenVPN-install#1042]
Hi, 
After two years of everything working as it should, users can't connect connect any more, I get an error msg: Peer certificate verification failure.

Tried a few suggestions I found online, but can't fix this. Do I have to reinstall everything? 
Thanks!

**Comment by sirotkaslo** [comment]
uninstall & reinstall fixed this issue.

**Comment by qwezxcdegen** [comment]
Time could also be the reason. Your openvpn client might not hit the certificate validity time. Your device and server should have the same time.
Thats for the guys who havent found a solution.
