### ISSUE TITLE
[Bug]: Installation Process Client Name unlimited input box

### ISSUE THREAD

**Issue by burakbuylu** [Angristan/OpenVPN-install#1043]
### Make sure your check these beforehand!

- [X] Issues - https://github.com/angristan/openvpn-install/issues
- [X] README and FAQ - https://github.com/angristan/openvpn-install
- [X] Wiki - https://github.com/angristan/openvpn-install/wiki
- [X] Discussions - https://github.com/angristan/openvpn-install/discussions

### Server OS

Debian 11

### What is the bug?

When I try to install its showing unlimited client name option. I cant kill this process:

<img width="522" alt="image" src="https://user-images.githubusercontent.com/5711373/192123750-ad3796d3-0d53-4ee3-a7a0-0b1b7176cbf3.png">

**Comment by angristan** [comment]
You need to input the client name with your keyboard :)
