### ISSUE TITLE
Convert script to unix like doc in case of any syntax error

### ISSUE THREAD

**Issue by mohsenjfar** [Angristan/OpenVPN-install#1045]
In my case of running the script, I had problem locating the sh file (no such file or directory) and also some syntax errors while reading it. I used dos2unix package to convert the script and it worked. So I think it might be a good idea to add this comment to readme file.

[README.md](https://github.com/angristan/openvpn-install/files/9711766/README.md)

**Comment by angristan** [comment]
If you download the script from github directly on the machine, you should not have this issue (this has never been reported, so I assume you did something)
