### ISSUE TITLE
Setup stuck at "Connecting to github.com"

### ISSUE THREAD

**Issue by randomhf398pdhg3** [Angristan/OpenVPN-install#1048]
![image](https://user-images.githubusercontent.com/11629537/194949941-d3ef7cd7-b6c9-490d-8e00-c73d74ff7c46.png)

Debian is installed on a VPS hosted in my country.
It's stuck at this stage for like 20min, I believe its my government censoring something about GitHub but I don't know what exactly.
Any workaround?

**Comment by TinCanTech** [comment]
What happened to: **Doing it yourself** ?

**Comment by randomhf398pdhg3** [comment]
@TinCanTech Well this is my first time using Linux and I don't know anything abt it.
I edited openvpn_install.sh and removed the wget line. then placed the easy-rsa package in the folder manually and its all fine now.
