### ISSUE TITLE
Feature for disabling TLS verification when a server is being created to listen on 127.0.0.1

### ISSUE THREAD

**Issue by kaizushi** [Angristan/OpenVPN-install#1049]
**Checklist**

- [X] I read the [README](https://github.com/angristan/openvpn-install/blob/master/README.md)
- [X] I read the [FAQ](https://github.com/angristan/openvpn-install/blob/master/FAQ.md)
- [X] I searched the [issues](https://github.com/angristan/openvpn-install/issues?q=is%3Aissue+)
- [X] My issue is about the script, and not OpenVPN itself

I was trying to use this script to make a quick job of something simple. I want an OpenVPN server which only binds to 127.0.0.1 using TCP, so that it can provide service over a Tor hidden service. Tor runs on the system and forwards traffic for it's hidden service to the OpenVPN server. This is so that I can use UDP services behind Tor using the OpenVPN server, mostly for DNS which only works properly with both TCP and UDP (and Tor doesn't do UDP). The OpenVPN client I am having issues is connects to the Tor hidden service via a transparent proxy server, which has a DNS server that gives a virtual mapping for the .onion domain name.

Anyway, there are TLS certificate issues with this using this script but it has created the OpenVPN config and TLS certificates and made that part easy. I could not find much help on Google with this issue, and I also could not find any simple answer in the OpenVPN reference manual to disable hostname verification with the certificates. To attempt what I am trying to do here I had to edit the resulting .ovpn file so that it specifies a Tor hidden service.

I therefore recommend that a feature be created so that when someone specifies that the server is listening on 127.0.0.1 that they can then choose to forgo certificate verification and the like, so that such a configuration may work. Tor hidden services already verify why well that the endpoint is trusted, as long as the hidden service address was obtained itself securely. Another use case for this feature would be providing the VPN with TCP using an SSH port forward, where once again the SSH fingerprint would resolve any issues of trust.

And I chose this script because I had good hopes that I could use it this way because it supports TCP already. I really think adding the option when first running the script to forgo certain aspects of TLS verification would be good.

Note: Disabling TLS entirely would not be desirable and it would be preferred in my situation to take hostnames out of the picture.

**Comment by angristan** [comment]
Hello, thanks for the recommendation, this is a very specific need, so I will close this for now 🙂
