### ISSUE TITLE
X509::parse_PEM:error in cert:PEM_routines:get_name:no start line

### ISSUE THREAD

**Issue by Wreeper** [Angristan/OpenVPN-install#1082]
Hello, i installed OpenVPN server using the script. When trying to connect to the VPN, it shows this error: X509::parse_PEM:error in cert:PEM_routines:get_name:no start line

**Comment by oybekmuzropov** [comment]
I faced this error when I used Ubuntu 22.04. I changed to 20.04 and it worked

**Comment by angristan** [comment]
Duplicate of https://github.com/angristan/openvpn-install/issues/1000

**Comment by impishlucy** [comment]
still happens
