### ISSUE TITLE
Create two ovpn config with different passwords

### ISSUE THREAD

**Issue by 0x3ch0** [Angristan/OpenVPN-install#1086]
Hi @angristan first of all thank you so much for the script.

I am just wondering how can I possibly create two ovpn files for two different users with different passwords.

Do I need to run the script twice for this?

**Comment by peterpekny** [comment]
Hello
Just seen your post . Just run the script once again ,, and use add user,
or something like that .. you can also remove users that way..

*Peter Pekný*

*tel:* *(**+420)* 728 060 988|*(**+421)* 949 128 948| *email: *
***@***.***





ne 15. 1. 2023 o 13:28 jesorian ***@***.***> napísal(a):

**Comment by angristan** [comment]
Yes, you need to run the script again, and select the option to add a new user :)
