### ISSUE TITLE
Do you have any plans to add the XOR Patch by TunnelBrick?

### ISSUE THREAD

**Issue by MRizkBV** [angristan/openvpn-install#110]
More and more countries are blocking OpenVPN now. First it was China, then Russia and now Egypt (yesterday night). Do you have any plans to add any kind of security hardening methods (during the handshake part) to make it possible for people like us :(... Maybe something like XOR by TunnelBrick?

**Comment by x0r2d2** [comment]
@MRizkBV 
Try to use openvpn 2.4 with elliptic curves and tls-crypt, check if it is working or not. 
Use this .sh file https://raw.githubusercontent.com/Angristan/OpenVPN-install/da55d77bb1507b494302f3e4997a8ae6e900841e/openvpn-install.sh

**Comment by MRizkBV** [comment]
Run the setup you provided and selected the highest security options available.

Same issue. When I connect the OpenVPN Connect client on Windows gets stuck at "Wed Oct 04 16:20:36 2017 TLS: Initial packet from [AF_INET]SERVER_IP:1194, sid=ddd5763e 91cdf20e"

About a minute later, that is the error I get.
Wed Oct 04 16:24:51 2017 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Wed Oct 04 16:24:51 2017 TLS Error: TLS handshake failed
Wed Oct 04 16:24:51 2017 SIGUSR1[soft,tls-error] received, process restarting
Wed Oct 04 16:24:51 2017 MANAGEMENT: >STATE:1507127091,RECONNECTING,tls-error,,,,,
Wed Oct 04 16:24:51 2017 Restart pause, 5 second(s)

**Comment by x0r2d2** [comment]
Udp or tcp?

**Comment by mohatt** [comment]
@MRizkBV Did you manage to get it working somehow? I have the same issue as you, I live in Egypt and have my private OpenVPN server but I cannot connect to it anymore.

**Comment by MRizkBV** [comment]
@hybtoy Sorry never got an email notification. That was UDP. TCP has been blocked a long time ago, also at the TLS handshaking step.

@mdkholy Nope. None of the methods mentioned here, or the security options available in the new script helped make it run. We are the new China, except we are not even as technologically advanced as them, or have an economy as good as theirs.

**Comment by angristan** [comment]
Are you talking about this? https://github.com/clayface/openvpn_xorpatch

If yes, it's a patch for the OpenVPN source code, however we don't and won't compile OpenVPN in this script. Also, it applies to a specific version of OpenVPN (2.3.12) and we're using different versions (soon 2.4)

**Comment by x0r2d2** [comment]
@angristan 
Thinking about of implementing this?

**Comment by angristan** [comment]
Yes, I think VPNs are most useful in countries where DPI is made, so it would make sense to help these users.

**Comment by x0r2d2** [comment]
@angristan 
Thank you very much. I am using openvpn with XOR patch already. It really helps me to bypass DPI.
https://forums.lawrencesystems.com/t/how-to-set-up-openvpn-server-using-tunnelblicks-xor-patch/526
https://github.com/lfrazer/OpenVPN_Obfuscated

**Comment by angristan** [comment]
I'll close this one for #374. I understand that bypassing DPI is important.
