### ISSUE TITLE
Adgurd dns

### ISSUE THREAD

**Issue by ghoshben** [angristan/openvpn-install#111]
This is not an issue but a request to add adgurd dns option (https://adguard.com/en/adguard-dns/overview.html).

**Comment by angristan** [comment]
Thanks for the suggestion, done in https://github.com/Angristan/OpenVPN-install/commit/db182bc741c1b6face4330794a0c69bc5a973989 and https://github.com/Angristan/OpenVPN-install/commit/dccbe2f71d9b2f96874730cfb07dc4c5924b42c7
