### ISSUE TITLE
Cannot ping clients from server or from other clients

### ISSUE THREAD

**Issue by brantleyforrest** [Angristan/OpenVPN-install#1121]
I cannot ping connected clients from the server computer or from any other computer on the network, and I also cannot ping clients from other clients. 

I am using this script with a fresh install of Debian. Here are the different settings that I have changed and/or verified:
- IP Forwarding is turned on
- client-to-client has been added to the config file
- I've added a "push route" line to the config file
- I've set up static routing in my network router
- I've done a fresh OS install, re-installed OpenVPN through the script, and re-applied all of the above settings

**Comment by bafben10** [comment]
I also just tried this on Ubuntu and ran into the same issue

**Comment by arthmost** [comment]
Same issue!!!

**Comment by bafben10** [comment]
In case anyone needs this functionality in the meantime, it seems to be working with Turnkey Wireguard and Turnkey OpenVPN.

**Comment by EricVu39** [comment]
Same here, did you found a solutions ?

**Comment by brantleyforrest** [comment]
@SMUEric1127 I never did find a way to make it work with this script, so I ended up going with the TurnKey OpenVPN container.

**Comment by EricVu39** [comment]
hey sorry for re-open it! after a while, i figured out that it's fairly very easy. The installation just didnt include client-to-client in the configuration.

So after add that line to the end of the openvpn configuration, then restarted it. It all got working! But yours seems also like a great alternative, I will check it out tonight!

**Comment by brantleyforrest** [comment]
I'm not very familiar with OpenVPN so I hadn't heard of that configuration. After some basic research it sounds like adding this to the config doesn't solve the issue of the server host OS not being able to reach the clients, which is the main issue I was facing. It's nice to know that exists though.
