### ISSUE TITLE
Is there a way to set up multiple remotes on one ovpn client config file?

### ISSUE THREAD

**Issue by kaovodich** [Angristan/OpenVPN-install#1148]
How to set up multiple remotes on one client configuration file so that when one server crashes, it can automatically switch to the next one? Anyone with experience, please point me to what I need to learn. Thanks!

**Comment by AddaxSoft** [comment]
there are mutiple ways. One way is to setup a jumping server. You would set your DNS pointing to it and then it watches which vpn server is alive and redirect you to it.

The jumping server can be a monitor system setting the correct DNS records for example for the VPN server that the client connects to.

**Comment by etzl** [comment]
You need to learn load balancing algorithms
