### ISSUE TITLE
Script not working on fedora

### ISSUE THREAD

**Issue by micartey** [Angristan/OpenVPN-install#1149]
Hello guys,

I used this script on debian and no issues at all, but I had to use a different server which uses fedora and after configuration the openvpn service doesn't start...

Has anyone faced the same issues?

**Comment by BlackRNG** [comment]
care to share logs?

**Comment by b1ek** [comment]
Logs are retrieved by command `sudo journalctl -xeu openvpn-server@server.service`

Or `sudo journalctl -xeu openvpn-server@server.service --no-pager` if you dont like the pager

**Comment by vzsoares** [comment]
probably related to https://github.com/OpenVPN/openvpn3-linux/issues/171
> basically openvpn3 is only working with glic >= 2.74.6

**Comment by micartey** [comment]
I honestly forgot about this issue and am using a different vpn server.

I suggest to close the issue as it is not very informative and doesn't seem to be wide spread issue.
