### ISSUE TITLE
Autoaccepting the defaults

### ISSUE THREAD

**Issue by ghost** [angristan/openvpn-install#115]
Hello.

Thank you for such a wonderful script. I would have contact you the other way but I do not know your contacts.

I would like to run this script automatically right after the installation of my DigitalOcean droplet. In fact I inserted this script into the 'user-data' field on the DO control panel which basically does the running part. 

The problem is that due to the lack of my knowledge I do not know how to pass the arguments to the script so that it is executed without prompts with default arguments, or if possible with the custom ones.

Can you help me and others with such of a request? Or maybe gave some directions who to implement this feature?

It would be really nice to have to spin up a droplet/vps within a minute and connect to the VPN service inside it in another minute.

Thank you very much.

**Comment by angristan** [comment]
I don't think I'll implement that into the script, but here's how to do it : 

Starting from [here](https://github.com/Angristan/OpenVPN-install/blob/master/openvpn-install.sh#L199), remove the `while`s and `read`s and set the variables yourself.

For instance : `DNS=2`, and the same for `CIPHER`, `PORT`, `IP`, `PROTOCOL`, `RSA_KEY_SIZE`, etc

I'm closing this but you can ask for help if you need to :)
