### ISSUE TITLE
May not launch openvpn service only on ArchLinux

### ISSUE THREAD

**Issue by GazimSoliev** [Angristan/OpenVPN-install#1155]
```
Job for openvpn-server@server.service failed because the control process exited with error code.
See "systemctl status openvpn-server@server.service" and "journalctl -xeu openvpn-server@server.service" for details.
```
I got this error on 3 devices: AcrhLinux server, Manjaro on my pc and ArchLinux on friend's pc

**Comment by GazimSoliev** [comment]
![image](https://user-images.githubusercontent.com/63443274/236690796-a4ec499e-694c-4a2e-8d96-91cd877f6d2e.png)

**Comment by GazimSoliev** [comment]
I found solution, I made this steps:
1. Remove user and group fields in `/etc/openvpn/server.conf`:
`sudo nano /etc/openvpn/server.conf`
3. Execute this command:
`sudo chown -R openvpn:network /etc/openvpn/* /var/log/openvpn/`
4. Restart service:
`sudo systemctl restart openvpn-server@server.service`

**Comment by mozo78** [comment]
A life saver! Thank you!

**Comment by flying-x** [comment]
The solution is great! This problem unfortunately is still there today. Should this script just handle it or arch should fix this issue?
