### ISSUE TITLE
VPN at scaleway

### ISSUE THREAD

**Issue by Hugo-Trentesaux** [angristan/openvpn-install#116]
Hi, I have a fresh ubuntu install on a scaleway aarch64 server (Ubuntu Xenial (16.04 LTS) (GNU/Linux 4.4.88-mainline-rev1 aarch64 ))
I launched your script successfully as I did before on an other server and tried to connect via my openvpn client but it keeps failing to connect.
Do you have any idea of what could cause this issue ?

**Comment by angristan** [comment]
Was the installation successful?

**Comment by angristan** [comment]
I tried with a ARM64-2GB running Ubuntu 16.04, no issue while connecting from Windows.

The problem's probably on your side, what kind of error do you have?

**Comment by Hugo-Trentesaux** [comment]
The installation was successful. I downloaded my client config file "hugo.ovpn".
When I launch `sudo openvpn hugo.ovpn` from my manjaro desktop I get : 
```
Thu Oct 26 18:43:06 2017 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Thu Oct 26 18:43:06 2017 TLS Error: TLS handshake failed
Thu Oct 26 18:43:06 2017 SIGUSR1[soft,tls-error] received, process restarting
Thu Oct 26 18:43:06 2017 Restart pause, 5 second(s)
Thu Oct 26 18:43:11 2017 TCP/UDP: Preserving recently used remote address: [AF_INET]xx.xx.xxx.xxx:1194
Thu Oct 26 18:43:11 2017 Socket Buffers: R=[212992->212992] S=[212992->212992]
Thu Oct 26 18:43:11 2017 UDP link local: (not bound)
Thu Oct 26 18:43:11 2017 UDP link remote: [AF_INET]xx.xx.xxx.xxx:1194
```
And It restarts in a loop.
I did not find a solution through basic browsing, so I thought it could be linked to my particular case and I had like to know if you already heard something similar.

**Comment by Hugo-Trentesaux** [comment]
D'ailleurs, on peut parler français, c'est plus simple ^^ (je crois qu'on s'est déjà rencontré sur diaspora)

**Comment by angristan** [comment]
Au début de l'installation il te demande ton IP et affiche l'IP privée en 10.x.x.x (qu'il faut laisser), puis à la fin il te demande de rentrer ton IP publique à la main. Tu n'as peut-être pas fait attention à ça :)

**Comment by Hugo-Trentesaux** [comment]
Il me semble que si, mais je vais retenter l'installation. J'ai déjà utilisé ton script avec succès sur mon précédent serveur chez OVH.

**Comment by Hugo-Trentesaux** [comment]
Après quelques bidouillages hasardeux et une réinstallation, ça fonctionne. J'ai dû louper une étape à un moment, tu as raison. Pourtant, je suis plutôt attentif à ce que je fais en généra ^^

**Comment by angristan** [comment]
Pas de souci :)
