### ISSUE TITLE
Multiple Sessions per User

### ISSUE THREAD

**Issue by MeSeraj** [Angristan/OpenVPN-install#1168]
How to enable Multiple Sessions per User?

**Comment by IroN404** [comment]
Add this line in your `/etc/openvpn/server.conf` file :

`duplicate-cn`

It will let you have multiple sessions per user, as exemple if you have user_1, you connect a first time with its profile, you will be connected and get the IP 10.1.0.1 ( let's say that you have the 10.1.0.0/24 range for this exemple), then if you connect with this profile a second time, you will get the IP 10.1.0.2, or any available address that is not used at this moment, etc...
