### ISSUE TITLE
DNS Suggestion

### ISSUE THREAD

**Issue by Shadowcrit** [angristan/openvpn-install#117]
I wanted to suggest a neutral anonymous log anycast DNS provider.

http://dnsrec.meo.ws/

I will be using this one my self.

**Comment by drphr4ud** [comment]
Why trust a third party with your DNS lookups when we have

https://github.com/Angristan/Local-DNS-resolver

?

**Comment by Shadowcrit** [comment]
Didn't know it was a thing yet. It showed local DNS is coming soon. Also, it asked for any recommendations.

**Comment by angristan** [comment]
Regarding OpenNIC servers: https://github.com/Angristan/OpenVPN-install/issues/4

Also yeah, local DNS server is a way better idea. Hopefully I'll get to work on it soon.
