### ISSUE TITLE
Server will not start in OpenVZ and related containers

### ISSUE THREAD

**Issue by garikaib** [angristan/openvpn-install#118]
I am not sure if this has been fixed yet but I had a problem starting the server after rebooting on a pristine Ubuntu 16.04. 
Even on a pristine install the server will fail to start upon reboot using the command:
`systemctl start openvpn@server`
This means upon rebooting the server you will not be able to connect to VPN service.
# Solution
The solution to this is to edit `/lib/systemd/system/openvpn@.service` and commenting out the line with `LimitNPROC` by adding a `#` before the line.
This stems from this[ issue.](https://github.com/systemd/systemd/issues/6011)
## Script fix
It would be nice for the install script to check for  check for existence of `/proc/user_beancounters` and comment out the line automatically

**Comment by angristan** [comment]
Seems to be related to https://github.com/Angristan/OpenVPN-install/commit/c703d41795def39b81b4a4ec6b2bda3f144b2a0a

**Comment by angristan** [comment]
I'll do some tests to see what Ubuntu versions it affects besides 16.04, thanks for the issue

**Comment by angristan** [comment]
What error do you have ?

Also does OpenVPN start with `/etc/init.d/openvpn start` or `systemctl start openvpn@server` ?

**Comment by angristan** [comment]
To clear things up : on reboot, OpenVPN does not start. But if you start manually, does it work?

**Comment by angristan** [comment]
Fixed a issue on reboot : https://github.com/Angristan/OpenVPN-install/commit/a7a277e2dc5e6d77a355a4cb60bb85032d724c65

Also I was already modifying the systemd service for OpenVZ : https://github.com/Angristan/OpenVPN-install/blob/master/openvpn-install.sh#L570

**Comment by garikaib** [comment]
Thanks at @Angristan it seems the problem has been fixed indeed. Starting manually before did not work using systemd but it worked when done directly.
