### ISSUE TITLE
Nice to have: support customized profile name when generating ovpn client file

### ISSUE THREAD

**Issue by piejanssens** [Angristan/OpenVPN-install#1186]
When I create a profile it shows up as "<IP/HOSTNAME> [<CLIENT NAME>]" in OpenVPN Connect.
I would like the possibility to specify a friendly name to show up as "<FRIENDLY HOST NAME> [CLIENT NAME]".

**Comment by angristan** [comment]
Sounds like a OpenVPN Connect thing? What could the script do about it? 🤔

**Comment by piejanssens** [comment]
Indeed. I thought this was part of config in the ovpn profile, but it's not.
