### ISSUE TITLE
Authenticate/Decrypt packet error

### ISSUE THREAD

**Issue by atulsian89** [angristan/openvpn-install#12]
Thank you so much for an awesome script.

I have installed latest version of your script on Debian 8 64 bit and after successful running it for couple of hours (mainly browsing), I started downloading a file and after a minute or so, my download speed went down. I checked the logs, I have the below errors. I'm on 50Mbps dual. 

Please let me know if you need more logs.

> Sun Dec 11 19:23:49 2016 open_tun, tt->ipv6=0
Sun Dec 11 19:23:49 2016 TAP-WIN32 device [Ethernet] opened: \\.\Global\{07AF53CD-3A45-43C7-AA9A-F6BF94B58B0B}.tap
Sun Dec 11 19:23:49 2016 TAP-Windows Driver Version 9.21 
Sun Dec 11 19:23:49 2016 Set TAP-Windows TUN subnet mode network/local/netmask = 10.8.0.0/10.8.0.2/255.255.255.0 [SUCCEEDED]
Sun Dec 11 19:23:49 2016 Notified TAP-Windows driver to set a DHCP IP/netmask of 10.8.0.2/255.255.255.0 on interface {07AF53CD-3A45-43C7-AA9A-F6BF94B58B0B} [DHCP-serv: 10.8.0.254, lease-time: 31536000]
Sun Dec 11 19:23:49 2016 Successful ARP Flush on interface [2] {07AF53CD-3A45-43C7-AA9A-F6BF94B58B0B}
Sun Dec 11 19:23:49 2016 Blocking DNS using WFP
Sun Dec 11 19:23:54 2016 TEST ROUTES: 1/1 succeeded len=0 ret=1 a=0 u/d=up
Sun Dec 11 19:23:54 2016 C:\WINDOWS\system32\route.exe ADD 185.XX.XX.XX MASK 255.255.255.255 192.168.1.1
Sun Dec 11 19:23:54 2016 ROUTE: CreateIpForwardEntry succeeded with dwForwardMetric1=25 and dwForwardType=4
Sun Dec 11 19:23:54 2016 Route addition via IPAPI succeeded [adaptive]
Sun Dec 11 19:23:54 2016 C:\WINDOWS\system32\route.exe ADD 0.0.0.0 MASK 128.0.0.0 10.8.0.1
Sun Dec 11 19:23:54 2016 ROUTE: CreateIpForwardEntry succeeded with dwForwardMetric1=20 and dwForwardType=4
Sun Dec 11 19:23:54 2016 Route addition via IPAPI succeeded [adaptive]
Sun Dec 11 19:23:54 2016 C:\WINDOWS\system32\route.exe ADD 128.0.0.0 MASK 128.0.0.0 10.8.0.1
Sun Dec 11 19:23:54 2016 ROUTE: CreateIpForwardEntry succeeded with dwForwardMetric1=20 and dwForwardType=4
Sun Dec 11 19:23:54 2016 Route addition via IPAPI succeeded [adaptive]
Sun Dec 11 19:23:54 2016 Initialization Sequence Completed
Sun Dec 11 19:23:54 2016 MANAGEMENT: >STATE:1481464434,CONNECTED,SUCCESS,10.8.0.2,185.XX.XXX
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40738 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40739 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40740 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40741 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40742 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40743 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40744 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40745 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40746 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40747 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40748 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40749 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40750 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40751 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40752 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40753 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40754 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40755 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40756 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40757 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40758 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40759 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40760 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40761 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40762 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40763 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40764 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40765 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40766 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40767 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40768 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40769 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40770 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40771 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40772 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40773 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40774 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40775 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40776 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40777 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40778 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40779 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40780 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40781 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40782 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40783 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40784 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40785 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40786 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40787 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40788 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40789 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40790 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40791 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40792 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40793 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40794 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40795 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40796 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40797 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40798 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40799 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40800 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40801 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40802 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40803 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40804 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40805 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40806 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40807 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40808 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Dec 11 19:24:39 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #40809 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings

>

**Comment by angristan** [comment]
I got this error too with other OpenVPN servers not installed with my script. I don't know why it happens. I didn't see any impact on speed tough.

**Comment by angristan** [comment]
Not related with to the script AFAIK. Any help is welcome.
