### ISSUE TITLE
doubts

### ISSUE THREAD

**Issue by 76789m** [angristan/openvpn-install#120]
1.how to automatic revoked the client after 30 days not 3650 by default ?

which line the script to change ?

2.how to add password on client ?

thank you happy christmas

**Comment by angristan** [comment]
1. Remove `EASYRSA_CRL_DAYS=3650` on these lines: https://github.com/Angristan/OpenVPN-install/commit/603d6747b9bc7663bfbc5b0d6d785084c83f5d74

2. It's not possible, [yet](https://github.com/Angristan/OpenVPN-install/issues/9)

Happy Christmas :)

**Comment by 76789m** [comment]
Hi Angristan,

iḿ sorry not understend Can easyrsa auto expire user cert after n (ex 30)days?

Thanks.

**Comment by angristan** [comment]
Sorry, I misunderstood. 

I don't know about any auto-expire feature in easy-rsa, sorry :/

**Comment by abpatwa** [comment]
Need script to revoke the user certificate and update the crl.pem
Can anybody help for the same?

**Comment by randshell** [comment]
Run again `openvpn-install.sh` and select revoke client.
