### ISSUE TITLE
Is there a simple way to enable Static Key instead?

### ISSUE THREAD

**Issue by MRizkBV** [angristan/openvpn-install#121]
So I just found out that Egypt hasn't completely blocked OpenVPN, installations with static key still work fine but I am not able to get it working with this script. I keep following guides online but it always fails for some reason. 

Looking for an advice. Thanks :)

**Comment by angristan** [comment]
What do you mean by static key?

**Comment by Weeka89** [comment]
I guess he means this https://openvpn.net/index.php/open-source/documentation/miscellaneous/78-static-key-mini-howto.html unfortunately I'm failing to use it too.

**Comment by angristan** [comment]
What is failing for you ?
