### ISSUE TITLE
Amazon Linux - Installer

### ISSUE THREAD

**Issue by Asshad** [angristan/openvpn-install#128]
Hi,

I was wondering if the installer can support Amazon Linux. Would love if there's any 👍

**Comment by angristan** [comment]
Hi, did you try on AWS? Did you encounter any issue?

**Comment by Asshad** [comment]
Hi. I tried Ubuntu on AWS, it has no issue but not for Amazon Linux.

**Comment by Asshad** [comment]
@Angristan I managed to get it work on Amazon linux. Just add the amazon system release in the family.

Line43:
elif [[ -e /etc/centos-release || -e /etc/redhat-release || **-e /etc/system-release** ]]; then

**Comment by chamunks** [comment]
It looks like it may be a RHEL variant using the YUM package installer.[ref](https://aws.amazon.com/amazon-linux-ami/faqs/)

**Comment by Leopere** [comment]
Can this be closed?

**Comment by Asshad** [comment]
Hi. Sure this can be closed.

**Comment by angristan** [comment]
Is this fixed though? 

@Asshad I didn't realize you were talking about Amazon Linux, the OS. As it's based on CentOS, it should work well. Is the change you suggested the only change required?

**Comment by Asshad** [comment]
@Angristan Yes. That's the only line we need to add, as the rest it follows CentOS.

**Comment by angristan** [comment]
Thanks @Asshad, I added it.

**Comment by Asshad** [comment]
@Angristan 👌

**Comment by glucee** [comment]
@Asshad I tried on the AWS EC2 Ubuntu, why doesn't work on there? The connection is there, but no data is transferred

**Comment by Asshad** [comment]
@glucee Is UDP 1194 port open on Security Group?
