### ISSUE TITLE
Problem running on OpenVZ

### ISSUE THREAD

**Issue by karl-j** [angristan/openvpn-install#129]
**Error:** 
```Job for openvpn@server.service failed because the control process exited with error code. See "systemctl status openvpn@server.service" and "journalctl -xe" for details.```

Output of `systemctl status openvpn@server.service`:
```
Nov 28 11:58:51 Basic systemd[1]: Starting OpenVPN connection to server...
Nov 28 11:58:51 Basic ovpn-server[30414]: OpenVPN 2.3.10 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [MH] [IPv6] built on 
Nov 28 11:58:51 Basic ovpn-server[30414]: library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08
Nov 28 11:58:51 Basic ovpn-server[30414]: daemon() failed or unsupported: Resource temporarily unavailable (errno=11)
Nov 28 11:58:51 Basic ovpn-server[30414]: Exiting due to fatal error
Nov 28 11:58:51 Basic systemd[1]: openvpn@server.service: Control process exited, code=exited status=1
Nov 28 11:58:51 Basic systemd[1]: Failed to start OpenVPN connection to server.
Nov 28 11:58:51 Basic systemd[1]: openvpn@server.service: Unit entered failed state.
Nov 28 11:58:51 Basic systemd[1]: openvpn@server.service: Failed with result 'exit-code'.
```

**OS:** Ubuntu 16.04 x64 running on OpenVZ

**Workaround:**
1. comment out the LimitNPROC line in /lib/systemd/system/openvpn@.service
2. systemctl daemon-reload  
    
  
**Credits:**
* https://github.com/lxc/lxd/issues/3336
* https://askubuntu.com/questions/747023/systemd-fails-to-start-openvpn-in-lxd-managed-16-04-container/747146#747146
* https://askubuntu.com/questions/798221/openvpn-in-lxc-failed-to-set-devices-allow

**Comment by angristan** [comment]
Thanks for the issue. There was the same issue with Debian 9.

Could you try this branch? https://github.com/Angristan/OpenVPN-install/blob/systemd-openvz-fix/openvpn-install.sh

**Comment by michaelfresco** [comment]
@Angristan 
Off topic, but the the link to the branch you posted, SOLVED ALL MY PROBLEMS! - I spent 6 hours on getting OpenVPN to work. You are my hero! :)

**Comment by angristan** [comment]
@michaelfresco Nice to hear, were you using OpenVZ?

**Comment by michaelfresco** [comment]
@Angristan Yes, I was using OpenVZ. All the time I could not get traffic through openvpn, even though I did successfully connect to it. It was a major headache honestly. I tried to ping 8.8.4.4, but got no relpy. The script from the **systemmd-openvz** branch fixed it all though! Real magic!

**Comment by angristan** [comment]
@michaelfresco Thanks for the feedback! What os are you using BTW?

**Comment by michaelfresco** [comment]
@Angristan Debian GNU/Linux 8.9 (jessie). With uname -r: `2.6.32-042stab116.2` (OpenVZ)

**Comment by angristan** [comment]
@michaelfresco ok, thanks

**Comment by angristan** [comment]
No news from @karl-j, I merged https://github.com/Angristan/OpenVPN-install/pull/139 so please re-open this if it doesn't fix it

**Comment by StuckUpCreations** [comment]
> **Error:**
> `Job for openvpn@server.service failed because the control process exited with error code. See "systemctl status openvpn@server.service" and "journalctl -xe" for details.`
> 
> Output of `systemctl status openvpn@server.service`:
> 
> ```
> Nov 28 11:58:51 Basic systemd[1]: Starting OpenVPN connection to server...
> Nov 28 11:58:51 Basic ovpn-server[30414]: OpenVPN 2.3.10 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [MH] [IPv6] built on 
> Nov 28 11:58:51 Basic ovpn-server[30414]: library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08
> Nov 28 11:58:51 Basic ovpn-server[30414]: daemon() failed or unsupported: Resource temporarily unavailable (errno=11)
> Nov 28 11:58:51 Basic ovpn-server[30414]: Exiting due to fatal error
> Nov 28 11:58:51 Basic systemd[1]: openvpn@server.service: Control process exited, code=exited status=1
> Nov 28 11:58:51 Basic systemd[1]: Failed to start OpenVPN connection to server.
> Nov 28 11:58:51 Basic systemd[1]: openvpn@server.service: Unit entered failed state.
> Nov 28 11:58:51 Basic systemd[1]: openvpn@server.service: Failed with result 'exit-code'.
> ```
> 
> **OS:** Ubuntu 16.04 x64 running on OpenVZ
> 
> **Workaround:**
> 
>     1. comment out the LimitNPROC line in /lib/systemd/system/openvpn@.service
> 
>     2. systemctl daemon-reload
> 
> 
> **Credits:**
> 
>     * [lxc/lxd#3336](https://github.com/lxc/lxd/issues/3336)
> 
>     * https://askubuntu.com/questions/747023/systemd-fails-to-start-openvpn-in-lxd-managed-16-04-container/747146#747146
> 
>     * https://askubuntu.com/questions/798221/openvpn-in-lxc-failed-to-set-devices-allow

just installed debian 9 on a openvz server and can confirm commenting this line out fixes this issue :) i will conect later with my client to confirm data flow and everything is corret, but atleast now the openvpn@server service started :)
