### ISSUE TITLE
Recommend AES > 256

### ISSUE THREAD

**Issue by Kcchouette** [angristan/openvpn-install#13]
For OpenVPN 2.4, the standard and recommended cipher will be AES-256-CBC.

So I think the best way is to not give the choice of cipher less than AES 256.

**Comment by angristan** [comment]
No. 

> Of the currently supported ciphers, OpenVPN currently recommends using AES-256-CBC or AES-128-CBC. OpenVPN 2.4 and newer will also support GCM. For 2.4+, we recommend using AES-256-GCM or AES-128-GCM.

(https://community.openvpn.net/openvpn/wiki/SWEET32)

Please read the Readme and the OpenVPN wiki and search online before suggesting things like that. It took hours to write the readme and justify the choices I made regarding encryption, so please at least read what I've done....

**Comment by Kcchouette** [comment]
Oh, I forgot to write my source, for information: https://github.com/Nyr/openvpn-install/commit/597d16d094319cd330ccd7996d1eb8a7ebe1f10f

**Comment by angristan** [comment]
Please read https://github.com/Angristan/OpenVPN-install/blob/master/README.md. I explained my choice. There is no reason to use AES 256 over 128.

**Comment by Kcchouette** [comment]
thanks :-)
