### ISSUE TITLE
AdGuard DNS Remove?

### ISSUE THREAD

**Issue by jacost22** [angristan/openvpn-install#131]
hi.
i cannot find Adguard DNS in script, it's remove?

![dns](https://user-images.githubusercontent.com/29556507/33424447-75fb8e84-d5ee-11e7-8004-e06950492368.png)

**Comment by angristan** [comment]
Update your script. Your screenshot shows NTT even though I deleted over a year and a half ago (https://github.com/Angristan/OpenVPN-install/commit/1bf105e809b709b2cd9efbb3001f33e98c272e55)
