### ISSUE TITLE
Multiple IP adresses support

### ISSUE THREAD

**Issue by 45236** [angristan/openvpn-install#137]
Hello,

my server has 2 IPV4 addresses. With the first IP I can connect to OpenVPN, there are no problems.
But if I do the setup with the second IP, I can not connect to this IP.

If I want to connect via the Openvpn client, I get the following error message:

**Client Log:**

```
Sat Dec 09 15:13:55 2017 OpenVPN 2.4.4 x86_64-w64-mingw32 [SSL (OpenSSL)] [LZO] [LZ4] [PKCS11] [AEAD] built on Sep 26 2017
Sat Dec 09 15:13:55 2017 Windows version 6.2 (Windows 8 or greater) 64bit
Sat Dec 09 15:13:55 2017 library versions: OpenSSL 1.0.2l  25 May 2017, LZO 2.10
Sat Dec 09 15:13:55 2017 MANAGEMENT: TCP Socket listening on [AF_INET]127.0.0.1:25340
Sat Dec 09 15:13:55 2017 Need hold release from management interface, waiting...
Sat Dec 09 15:13:55 2017 MANAGEMENT: Client connected from [AF_INET]127.0.0.1:25340
Sat Dec 09 15:13:55 2017 MANAGEMENT: CMD 'state on'
Sat Dec 09 15:13:55 2017 MANAGEMENT: CMD 'log all on'
Sat Dec 09 15:13:55 2017 MANAGEMENT: CMD 'echo all on'
Sat Dec 09 15:13:55 2017 MANAGEMENT: CMD 'hold off'
Sat Dec 09 15:13:55 2017 MANAGEMENT: CMD 'hold release'
Sat Dec 09 15:13:56 2017 Outgoing Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC authentication
Sat Dec 09 15:13:56 2017 Incoming Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC authentication
Sat Dec 09 15:13:56 2017 TCP/UDP: Preserving recently used remote address: [AF_INET]XXX.XX.XXX.XX:1194
Sat Dec 09 15:13:56 2017 Socket Buffers: R=[65536->65536] S=[65536->65536]
Sat Dec 09 15:13:56 2017 UDP link local: (not bound)
Sat Dec 09 15:13:56 2017 UDP link remote: [AF_INET]XXX.XX.XXX.XX:1194
Sat Dec 09 15:13:56 2017 MANAGEMENT: >STATE:1512828836,WAIT,,,,,,
```

here are the configs:

**server.conf:**

```
port 1194
proto udp
dev tun
user nobody
group nogroup
persist-key
persist-tun
keepalive 10 120
topology subnet
server 10.8.0.0 255.255.255.0
ifconfig-pool-persist ipp.txt
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.4.4"
push "redirect-gateway def1 bypass-dhcp"
crl-verify crl.pem
ca ca.crt
cert server.crt
key server.key
tls-auth tls-auth.key 0
dh dh.pem
auth SHA256
cipher AES-128-CBC
tls-server
tls-version-min 1.2
tls-cipher TLS-DHE-RSA-WITH-AES-128-GCM-SHA256
status openvpn.log
verb 3
```

**client.ovpn:**

```
client
proto udp
remote XXX.XX.XXX.XX 1194
dev tun
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
auth SHA256
auth-nocache
cipher AES-128-CBC
tls-client
tls-version-min 1.2
tls-cipher TLS-DHE-RSA-WITH-AES-128-GCM-SHA256
setenv opt block-outside-dns
verb 3
```

**/etc/network/interfaces**

```
# The primary network interface
allow-hotplug eth0
iface eth0 inet static
        address XXX.XX.XXX.XXX     **<---- openvpn works**
        netmask 255.255.255.0
        network XXX.XX.XXX.X
        broadcast XXX.XX.XXX.255
        gateway XXX.XX.XXX.1
        # dns-* options are implemented by the resolvconf package, if installed
        dns-nameservers 8.8.8.8 8.8.4.4
        dns-search example.com

auto eth0:1
allow-hotplug eth0:1
iface eth0:1 inet static
        address XXX.XX.XXX.XX     **<---- openvpn does not work**
        netmask 255.255.255.255
```
_I replaced the IP with XXX for Github._

Both IP addresses are reachable.

Everything works with the main IP. only the second IP makes problems.

can someone help?

**Comment by angristan** [comment]
I reverted the PR since, but could you try to use the local option with your secondary IP like in https://github.com/Angristan/OpenVPN-install/pull/91?

**Comment by 45236** [comment]
I hope I got it right. My English is not good.

I wrote "local secondary IP" to server.conf, but it still does not work. I am still connected to my main IP when I make an IP check.

in the client.ovpn is the secondary IP in it.

**Comment by angristan** [comment]
Well the goal of the script is not really to support this kind of setup...

**Comment by Leopere** [comment]
Would it be possible to support multiple externally facing IP addresses?  It would be somewhat nice to be able to cherry pick various IP's from your VPS.  

A valid usage case would be:
```
Imagine you use your VPS while you travel.  You don't want to necessarily associate your traffic while abroad to the usual IP address so you decide to use a normally unused IP address so as to leave some degree of ambiguity between the varying traffic. 
```
 In this case you would still link your metadata to the old IP if you weren't careful to avoid using accounts that you don't want associated but if you think about it this way it wouldn't be out of the ordinary to imagine a valid usage case for something like this.

**Comment by angristan** [comment]
@45236 Could you try to hardcode your secondary interface [here](https://github.com/Angristan/OpenVPN-install/blob/master/openvpn-install.sh#L94)? Or re-run this command [here](https://github.com/Angristan/OpenVPN-install/blob/master/openvpn-install.sh#L567) with this interface?

Also, what's the output of:

`ip -4 route ls`

**Comment by angristan** [comment]
@chamunks Considering this:

`Client <- IP 1 -> server <- IP 2 -> Internet.`

Currently, both IPs are identical. Which one would you like to have the possibility to change?

**Comment by Leopere** [comment]
@Angristan, it's not entirely necessary but it would be good to be able to change both if it's that flexible but I guess ingress IP for travel would make the most sense. But separate accounts would want egress to be changeable. 

@cezar97 fair enough maybe if it was a feature that I was looking for I could open a new ticket for that.

**Comment by cezar97** [comment]
As a workaround you can have a tunnel with stunnel or anything similar running on the second ip that redirects traffic on the primary one that's the one openvpn is running on. That's only for the traveling use case. @chamunks
