### ISSUE TITLE
Improve security by enabling DH to use PFS

### ISSUE THREAD

**Issue by aalmenar** [angristan/openvpn-install#138]
The current script does configure "dh none". 

By creating a DH file:

openssl dhparam -out dh2048.pem -2 2048

and setting dh to this file, will enable PFS on the VPN.

**Comment by aalmenar** [comment]
Im sorry, i used the script here:

https://github.com/Angristan/OpenVPN-install/blob/openvpn-2.4-update/openvpn-install.sh

Also configured ECDH certificates.

**Comment by angristan** [comment]
Yes, if an ECDH key is chosen, we add ecdh-curve in the config and the dh parameter is set to none.
