### ISSUE TITLE
DNS configuration is not working as expacted

### ISSUE THREAD

**Issue by pantchox** [angristan/openvpn-install#14]
Hi,

First great script thanks for doing it (or forking it ;) )
I created a server on digital ocean and ran the script, generated a client.ovpn file.

I tested the client.ovpn on my android and it works.

Testing the client.ovpn on my raspberry pi Raspbian distro did not work, requests to any host wont work since the DNS resolver is not wokring.
I had to staticly configure the interface of my wireless to use a specific dns 8.8.8.8 of google to make it work.

Any idea why is this happening? 
Thanks.

**Comment by angristan** [comment]
What DNS servers did you choose in the setup ?

**Comment by pantchox** [comment]
google ones

**Comment by angristan** [comment]
Please try again and use the dig command with differents resolvers.

**Comment by angristan** [comment]
No feedback, closing.
