### ISSUE TITLE
IP Blocklists

### ISSUE THREAD

**Issue by Leopere** [angristan/openvpn-install#141]
It might be interesting to see if at some point people would want to add IP blocklists to this.  I don't really know how to implement them via the command line but I'm certain that there should be some way.

This may be vastly out of scope of course.  But if we're working on privacy VPN, DNSCrypt and IP Blocklists would probably be about as far as you could easily go.  Without starting to dip into trying to funnel traffic through things like I2P or TOR at the VPS/Server you have setup as your VPN but that's a run on issue so I'll stop here.

**Comment by angristan** [comment]
What's your threat model with this kind of blocklist?

**Comment by Leopere** [comment]
Just extending on the concept of DNS services that block IP's based on malicious intent or advertising.  There are huge lists of IP's that you could block on the machine itself from https://www.iblocklist.com/lists it just drops any connections attempting to make connections to or from IP's in these lists.  It doesn't prevent 100% of any of these things but it definitely helps reduce issues.

*Edit: Additional information on potential solutions.

https://wiki.archlinux.org/index.php/Ipset
https://gist.github.com/vinctux/62aa986f8906e64ea3a77e227386e671

**Comment by Leopere** [comment]
Also, another major reason behind potentially wanting to select a blocklist to impose on the egress point of your VPN is that you're probably installing this for the purpose of increasing your privacy so why not just block known tracking agencies.  It reduces your overall noisiness on the internet.  There is an awful lot of background radiation on your computers these days.  I, myself have had to install about 256 or so firewall rules on my localhost just to maintain relative control over what my computers talk to.  Of these 256 rules, I'm probably already granting access to many things that I don't really want to but have no insights into.

**Comment by cezar97** [comment]
@chamunks Editing `/etc/hosts.deny` should do it for services that support TCP Wrappers.
Here more info: https://askubuntu.com/questions/23163/how-to-edit-hosts-deny-and-hosts-allow.

**Comment by Leopere** [comment]
You're not wrong but I'd rather outright block the hosts file could be
ignored.

**Comment by cezar97** [comment]
Found that ipset could be a perfect alternative to `hosts.deny`, specially because it relays on iptables for blocking. It's easy to scale too, just `cat blacklist.txt | xargs ipset add blacklist`.
Here the link: https://linux-audit.com/blocking-ip-addresses-in-linux-with-iptables/.

**Comment by Leopere** [comment]
I would imagine IPSet would be the Ideal here.  Maybe we should commit an early example of just a list of the commands required to install and uninstall these things at some point if we want them.
