### ISSUE TITLE
How to allow client-to-client Communications - Open VPN server install on Ubuntu 16.04 LTS?

### ISSUE THREAD

**Issue by gaurishpatil** [angristan/openvpn-install#147]
Installed Open VPN server using,
`wget https://raw.githubusercontent.com/Angristan/OpenVPN-install/master/openvpn-install.sh`
`chmod +x openvpn-install.sh`
on Ubuntu 16.04.03 LTS. Server created in DigitalOcean Cloud.

Created two client, **Client-1: 10.8.0.2** and **Client-2: 10.8.0.3**

My `/etc/rc.local` looks like,

```
#!/bin/sh -e
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# By default this script does nothing.

#iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE

iptables -I FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -I FORWARD -s 10.8.0.0/24 -j ACCEPT
iptables -I INPUT -p udp --dport 1194 -j ACCEPT

exit 0
```

`/etc/openvpn/server.conf` look like,

```
port 1194
proto udp
dev tun
user nobody
group nogroup
persist-key
persist-tun
keepalive 10 120
topology subnet
server 10.8.0.0 255.255.255.0
ifconfig-pool-persist ipp.txt
push "dhcp-option DNS [ServerDNS]"
push "dhcp-option DNS [ServerDNS]"
push "redirect-gateway def1 bypass-dhcp"
crl-verify crl.pem
ca ca.crt
cert server.crt
key server.key
tls-auth tls-auth.key 0
dh dh.pem
auth SHA256
cipher AES-128-CBC
tls-server
tls-version-min 1.2
tls-cipher TLS-DHE-RSA-WITH-AES-128-GCM-SHA256
status openvpn.log
verb 3
```

But, **Client-1: 10.8.0.2** cannot ping **Client-2: 10.8.0.3** , timed out.

Even my **Server: 10.0.8.1** not able to ping any client.

Tried adding client-to-client at the bottom of server.conf next line to verb3  using nano, doesn't work.

**Comment by cezar97** [comment]
Can you try this https://github.com/pivpn/pivpn/issues/436#issuecomment-354087541 ?

For me client to client connections works out of the box with the default 
```server.conf```, so I didn't even add ```client-to-client``` in that file.

**Comment by gaurishpatil** [comment]
That was more windows firewall issue. 
Followed steps to create firewall, which allowed client to client communication
https://superuser.com/questions/1106907/windows-firewall-doesnot-allow-to-connect-from-vpn

thanks @cezar97  @Angristan  this worked perfect.

**Comment by ghost** [comment]
That was more windows firewall issue.
Followed steps to create firewall, which allowed client to client communication
https://superuser.com/questions/1106907/windows-firewall-doesnot-allow-to-connect-from-vpn

thanks @cezar97 @Angristan this worked perfect.
