### ISSUE TITLE
Configure internal portforwarding, 443 -> 1194 and the like?

### ISSUE THREAD

**Issue by henkgist** [angristan/openvpn-install#148]
Thank you for this very nice project! Already running on my server. It is much less work than before and I really like the default security config.

What I'd like to see here is enabling of port forwarding. Some networks block ports like 1194, other block 53, 443 is often possible but a bit slower - in short: it would be nice to have a couple of ports to connect to, doing that with internal port forwarding. I'm too noob-ish to do that myself. What I'd do is to remove the installation and run the installer again from scratch ... but maybe there's a better solution, a script asking for forwarded ports to configure during the installation?

Thanks again, great work!

**Comment by xiagw** [comment]
firewalld: 
	firewall-cmd --zone=public --add-port=443/tcp
	firewall-cmd --permanent --zone=public --add-port=443/tcp
	firewall-cmd --zone=trusted --add-source=10.8.0.0/24
	firewall-cmd --permanent --zone=trusted --add-source=10.8.0.0/24
iptables:
	iptables -I INPUT -p tcp --dport 443 -j ACCEPT
	iptables -I FORWARD -s 10.8.0.0/24 -j ACCEPT
	iptables -I FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT

**Comment by angristan** [comment]
In case you didn't know you can already change your port in the server and client config as much as you like.

I agree it would be a great feature, however I wonder if this wouldn't be a bit out of the scope of this script.

**Comment by henkgist** [comment]
Yes, that might be! Thanks a lot for the help with the rules. I'll try that in the next days.
