### ISSUE TITLE
Ability to change the subnet of the OpenVPN network

### ISSUE THREAD

**Issue by Dofamin** [angristan/openvpn-install#153]
Good day!
Could you, in the next version of the script, give users the opportunity to change the IP address of the network?
And will there be future support for tcp & udp as a daemon?

**Comment by angristan** [comment]
Hi do you mean the client's IP address, or the subnet (10.8.0.0/24)?

**Comment by Dofamin** [comment]
Hi, yes.

**Comment by angristan** [comment]
Yes to which one? :)

**Comment by Dofamin** [comment]
To both :)

**Comment by Dofamin** [comment]
- I apologize for the inaccurate wording of my request.
It was meant to configure the DHCP range on the server side.
That would be when installing an openvpn server, it was possible to change the DCHP range.
Instead of the standard 10.0.8.0/25, you could put 172.16.0.0/25 for example.
- And about tcp and udp. Will it be possible to run a server with TCP and UDP ports working together as a service?
Unfortunately, not all devices support the udp connection, the example can serve as the same MirkoTik.

**Comment by angristan** [comment]
Indeed it would be a nice feature.

As for your second request, see https://github.com/Angristan/OpenVPN-install/issues/28 (not done yet)

**Comment by randshell** [comment]
> Instead of the standard 10.0.8.0/25, you could put 172.16.0.0/25 for example.

Fixed by #550
