### ISSUE TITLE
Daemon() failed or unsupported: Resource temporarily unavailable

### ISSUE THREAD

**Issue by SkyEmie** [angristan/openvpn-install#155]
Hi, sorry to ask help but i've a problem with our script, i've tested on seveal server and i've always the same error : 

```
Tue Jan 30 01:20:13 2018 OpenVPN 2.3.10 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [MH] [IPv6] built on Jun 22 2017
Tue Jan 30 01:20:13 2018 library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08
Tue Jan 30 01:20:13 2018 daemon() failed or unsupported: Resource temporarily unavailable (errno=11)
Tue Jan 30 01:20:13 2018 Exiting due to fatal error
```

What causes it ?
Tanks ;)

**Comment by angristan** [comment]
Hello, are you getting this error in an LXC container by any chance?

**Comment by jadia** [comment]
The same issue happens when OpenVPN runs on OpenVZ VM/containers.

The solution is posted on [Stackoverflow](https://askubuntu.com/questions/747023/systemd-fails-to-start-openvpn-in-lxd-managed-16-04-container)

**Comment by angristan** [comment]
@th3karkota https://github.com/angristan/openvpn-install/blob/dea1d6db2b6611b88d7b4e94f014621fb2ad4cec/openvpn-install.sh#L824
