### ISSUE TITLE
Stunnel support

### ISSUE THREAD

**Issue by nazim** [angristan/openvpn-install#16]
First of all, the script is awesome.
I recommend that you add a feature. Stunnel support. It is very necessary for internet users in countries like Turkey. The udp and tcp port are very slow.

**Comment by angristan** [comment]
Thanks :)

This script is focused on OpenVPN so I won't add support for stunnel or any other VPN/Proxy service ATM.

Anyway, as it's a TLS tunnel, it's using TCP right ? Why would it be faster ? 🤔

**Comment by EsmailELBoBDev2** [comment]
it won't be faster but at least it will work for cases like these https://www.reddit.com/73zc61 and https://www.reddit.com/r/VPN/comments/73zc61/comment/dnuapdk

my connection on both wireguard and openvpn stuck in handshake
