### ISSUE TITLE
Android 3.0.0-870 App - "No shared cipher"

### ISSUE THREAD

**Issue by spy0r** [angristan/openvpn-install#164]
Hi,
since the last android update i was not able anymore to connect to my openvpn, created with your script (thanks anyway for your work)!
The Errorlog is:

> TLS error: The server has no TLS ciphersuites in common with the client. Your --tls-cipher setting might be too restrictive.

So tried to uncomment the "tls-cipher TLS-DHE-RSA-WITH-AES-128-GCM-SHA256" line in my server config. Then i can reconnect with the android clients. So i'm not an expert, but i think the tls-cipher line "forces" some kind of cipher, right?
So is it a problem in the android app not supporting this selected tls-cipher?

Is there anything i can do unless i don't want to completely uncomment the line?

Thanks in advance,
stef

**Comment by spy0r** [comment]
i read https://community.openvpn.net/openvpn/wiki/Hardening#Useof--tls-cipher and the "best" i can use with the current android app seems to be "TLS-DHE-RSA-WITH-AES-256-CBC-SHA" 
Is this "completely insecure" or suitable in these days?

**Comment by Kcchouette** [comment]
@spy0r What is your android openvpn client?

**Comment by spy0r** [comment]
Hi, i tried to define that in the summary, i use the "OpenVPN Connect" in the Version 3.0.0-870!

**Comment by Kcchouette** [comment]
@spy0r Can you try the client ["OpenVPN for Android"](https://play.google.com/store/apps/details?id=de.blinkt.openvpn)?

**Comment by spy0r** [comment]
Yeah, with this App the connection works with:
Control Channel: TLSv1.2, cipher TLSv1/SSLv3 DHE-RSA-AES128-GCM-SHA256, 3072 bit RSA

**Comment by Kcchouette** [comment]
So, changing openvpn client fixes this issue?

**Comment by spy0r** [comment]
Yes it does, i don't know why i didn't try another android client on my own, i only tried the thinkpad, so i was sure the update of the android app broke the connection. 
Thanks!

**Comment by angristan** [comment]
Another person reported that the update of the client broke the connection.

I'll take a look, but anyway, OpenVPN for Android is a better client as @Kcchouette said :)

**Comment by spy0r** [comment]
After todays 3.0.1 Update from the PlayStore they fixed the GCM connection Thing in the "official App". Thanks to everyone for your help.
Regards, Stef
