### ISSUE TITLE
Creds: UsernameEmpty/PasswordEmpty Error..

### ISSUE THREAD

**Issue by yomun** [angristan/openvpn-install#165]
Currently, the BASH script seem can't generate autologin ovpn..
So, the new 'OpenVPN Connect' can't use this ovpn.
It will get 
Creds: UsernameEmpty/PasswordEmpty Error..

**Comment by angristan** [comment]
On Android?

**Comment by yomun** [comment]
yes. I hope you can fix this..

**Comment by angristan** [comment]
Use OpenVPN for Android if this still happens
