### ISSUE TITLE
script for router firmware openwrt

### ISSUE THREAD

**Issue by lucascaw** [angristan/openvpn-install#166]
Thank you very much. The script installs the ovpn server on my Ubuntu pc very smoothly. 
Do you have plans to make the same script for the open source router firmware Openwrt / Lede?
Regards, Lucas

**Comment by angristan** [comment]
Hello,

Do you mean install the OpenVPN server on the router or to connect from the router?

**Comment by lucascaw** [comment]
Hello @Angristan, 

Yes, an openvpn server on the router, so that with my mobile phone  outdoor  a) I can make a public wifi secure and b) I can use my ovpn abroad with my home IP.
advantage of a router with vpn server compared to an ubuntu pc is that the router is always up and uses less energy.
Openwrt is a linux distro based on Debian with the same possibilities as Debian and Ubuntu. Apt-get, Apt  is called opkg.  Many commands are about the same, so I thought it would be "easy" for you guys to make such a script. ;-))
Regards, Lucas

**Comment by angristan** [comment]
I understand it would be a nice feature for the script, however I don't plan to support (OpenWrt) routers. I don't even have one myself so I can't test. Sorry :/

**Comment by lucascaw** [comment]
Tnx for the reply.
