### ISSUE TITLE
Not Connecting for OpenVPN

### ISSUE THREAD

**Issue by AMD-Threadripper** [angristan/openvpn-install#167]
Hello,

I have the following problem.
Have now installed the OpenVPN 2.4 update script. Unfortunately, no connection could be established.

Then I installed the OpenVPN master script. Here I immediately got a connection.

System: VPS Ubuntu 16.04. LTS

Can you help me with that?

Many Thanks.

![ovpn app 2 4](https://user-images.githubusercontent.com/36647494/36399679-4164f29a-15cd-11e8-8511-2c750a6a824b.jpg)
![ovpn app log 2 4_1](https://user-images.githubusercontent.com/36647494/36399680-418488da-15cd-11e8-90a2-5ae899251115.jpg)
![ovpn app log 2 4_2](https://user-images.githubusercontent.com/36647494/36399681-41a136ce-15cd-11e8-82e6-9ddd17e3978f.jpg)

**Comment by orazioedoardo** [comment]
OpenVPN Connect [doesn't support](https://forums.openvpn.net/viewtopic.php?f=36&t=25597) elliptic curves for the certificates, only for the key exchange.

**Comment by AMD-Threadripper** [comment]
Thanks, I did not know that. It works on my ipad.

Does anyone know when it will work on Android?

**Comment by cezar97** [comment]
Use OpenVPN by Arne Schwabe.

**Comment by yomun** [comment]
Use old ver OpenVPN Client..
https://play.google.com/store/apps/details?id=de.blinkt.openvpn

Because currently the BASH script not support generate 'autologin' ovpn file.
That's why you got Error in log..

Creds: UsernameEmpty/PasswordEmpty Error..

**Comment by yomun** [comment]
We can install
https://openvpn.net/index.php/access-server/download-openvpn-as-sw.html
https://openvpn.net/index.php/access-server/docs/quick-start-guide.html

**Comment by AMD-Threadripper** [comment]
Ok. Thx. :)
