### ISSUE TITLE
Fedora 27 systemd service is broken

### ISSUE THREAD

**Issue by shtam** [angristan/openvpn-install#168]
I was getting errors that it couldn't find 'server.conf'. I got it working by manually run these lines (plus commenting out the LimitNProc line mentioned elsewhere):

https://github.com/Angristan/OpenVPN-install/blob/f252614a365ccb8b4a08339af3f77443aa69c0b3/openvpn-install.sh#L630-L634

**Comment by yomun** [comment]
We can install
https://openvpn.net/index.php/access-server/download-openvpn-as-sw.html
https://openvpn.net/index.php/access-server/docs/quick-start-guide.html

**Comment by angristan** [comment]
Thanks @shtam for reporting this. This is the correct solution, I will do more tests to implement it.

**Comment by angristan** [comment]
Turns out the issue was because $OS equals `centos`
