### ISSUE TITLE
OpenVPN Server cannot ping client IP, but client can ping server IP

### ISSUE THREAD

**Issue by Vanguard4893** [angristan/openvpn-install#17]
Pinging the server IP (10.8.0.1) from any client works fine. However pinging a client IP (eg 10.8.0.10) from the server end fails.

I suspect this is a simple routing issue, but I've hit a brick wall with attempting to fix this problem.

**Comment by angristan** [comment]
This is not related to the script but to OpenVPN, and I don't find anything to enable the ping on client side

**Comment by javasboy** [comment]
Hi all.
I found myself compiling and installing openvpn 2.4.0,and the client also can not ping 10.8.0.1,server can not ping client ip. 
And  other client  ip also can not ping.
when i add a rule to iptables on server,Then Server can ping my phone client ip,but server can not ping my win 7 client ip.
win 7 clinet can ping the server getway ip 10.8.0.1

iptables -A INPUT -i tun+ -m comment --comment "Allow TUN interface connections to OpenVPN server" -j ACCEPT
