### ISSUE TITLE
Error Line 566

### ISSUE THREAD

**Issue by AMD-Threadripper** [angristan/openvpn-install#171]
Hello,

Have the script Openvpn 2.4 update install.
Get the following error:
```
line 566: syntax error near unexpected token `elif'
line 566: `	elif [[ "$OS" = 'centos' || "$OS" = 'fedora' ]]; then'
```

**Comment by angristan** [comment]
Thanks for reporting, let me check.

**Comment by cezar97** [comment]
Line 521 shouldn't exist, is it?

**Comment by cezar97** [comment]
Also with line 520 there will be an update twice ( see line 533 ).

PS: In scripts apt-get it's used over apt as it's have a stable cli.

**Comment by Angristan** [comment]
I can't reproduce the bug :thinking:

**Comment by Angristan** [comment]
@cezar97 Are you talking about the master branch? https://github.com/Angristan/OpenVPN-install/blob/master/openvpn-install.sh#L521

**Comment by Angristan** [comment]
Wow ok a lot of conflicts there

**Comment by angristan** [comment]
Thanks @AMD-Threadripper @cezar97
