### ISSUE TITLE
Feature : Full IPv6 tunneling or 6to4/4to6

### ISSUE THREAD

**Issue by ghost** [angristan/openvpn-install#173]
Hi,
It would be great if we can manage V6 with the same script. Some DNS providers have already IPv6 enabled resolvers for domain resolution.
What if we could make tunnel client v6 (an Android) through Server v6 using DNS resolver v6.

Notice that some Webhosters deliver a customised patch of the kernel that makes routing v6 a little bit hard.

If the present script manages already v6, please consider closing this issue.
Thank you.

**Comment by angristan** [comment]
That probably won't happen anytime soon, but yes, it would be.

https://github.com/Angristan/OpenVPN-install/issues/51
