### ISSUE TITLE
Doesn't work on archlinux

### ISSUE THREAD

**Issue by Vortelf** [angristan/openvpn-install#175]
Fix your directories, constantly switches between ```/etc/openvpn``` and current dir and ends up with files nott being found.

**Comment by Vortelf** [comment]
Also, can't be removed properly.
Script removes openvpn completely without even asking if I want to.
Need a proper clean-up script.

**Comment by Vortelf** [comment]
Doesn't check for packages and always asks to install them

**Comment by letroll** [comment]
I have better result with https://github.com/Angristan/OpenVPN-install/pull/196 and applying my comment on it in archlinux @Vortelf
