### ISSUE TITLE
Support Quad9 9.9.9.10 to bypass censured list

### ISSUE THREAD

**Issue by lakano** [angristan/openvpn-install#176]
Hi !
Thanks for your very useful script!
The default 9.9.9.9 protect from some URLs that install malwares, but it's still a censured list managed by IBM.
They propose alternative IP addresses to not use the black list, and now they support DNSSEC ( https://www.quad9.net/faq/#Is_there_a_service_that_Quad9_offers_that_does_not_have_the_blocklist_or_other_security )

Could you propose in your script another Quad9 option « Quad9 without blacklist » please and point to DNS IP addresses: 9.9.9.10, 149.112.112.10, 2620:fe::10

Thanks!

**Comment by angristan** [comment]
That would be great, thanks :)

**Comment by cezar97** [comment]
@Angristan can you add the secondary quad9 IP 149.112.112.112 along with the existing 9.9.9.9 ? I found it reading their FAQ.

**Comment by ghost** [comment]
Just as a clarification, the 9.9.9.9 domain block list is not managed by IBM, it's the aggregate of nineteen different threat-intelligence providers, of which IBM is one, with some reputation scoring of the different sources, and a white-list subtracted out.  So if there are any things that you think shouldn't be blocked, please report them for inclusion in the white-list.

Also, please include 2620:FE::FE, the IPv6 address of the service.

**Comment by cezar97** [comment]
@bwoodcock at the moment the script does not support ipv6.

**Comment by angristan** [comment]
Done: https://github.com/angristan/openvpn-install/commit/73c52daf849c723ba5c732b0cbbafd69a9fe9fd7
