### ISSUE TITLE
Revoking a client certificate or uninstalling OpenVPN does not remove OVPN file

### ISSUE THREAD

**Issue by jellemdekker** [angristan/openvpn-install#177]
When revoking a client's certificate using option 2 in the script, the certificate is revoked and the PKI is cleaned up by removing numerous file ([lines 143 to 145](https://github.com/Angristan/OpenVPN-install/blob/master/openvpn-install.sh#L143)). The OVPN files in the home directory is still left behind, however. These should be deleted during client revocation as well.

The same goes for when option 3 is used to uninstall OpenVPN, [the installation directory is deleted](https://github.com/Angristan/OpenVPN-install/blob/master/openvpn-install.sh#L191), but the (now invalid) OVPN files in the home directory are left behind.

**Comment by jellemdekker** [comment]
I currently don't have time to work on this. If someone else gets around to implementing this before I do, you have my sincerest gratitude.

**Comment by angristan** [comment]
I think it needs "Fix #177" but in the commit. Anyway, thanks!

**Comment by cezar97** [comment]
Oh, Thank You! I didn't remember how I've done it last time.
