### ISSUE TITLE
How should we manage upgrades to security settings.

### ISSUE THREAD

**Issue by Leopere** [angristan/openvpn-install#179]
I occasionally uninstall this and re-generate OpenVPN using this script so that I'm sure that I have the latest security features.  I mainly do it because I see the repo getting a lot of commits and figure there's probably some good benefits that I could be reaping.  

I wonder if we could be making some kind of thing to let us know if we should consider upgrading the install.

**Comment by cezar97** [comment]
Same here. But
 actually it can be accomplished with `git clone` and `git pull` instead of simply downloading the installer. This way it is easier to see changes, too (`git log`) and if only little changes were made just replacing it should be enough.

**Comment by angristan** [comment]
This is a default of the script, but clearly managing updates is out of the question and would require too much work

**Comment by Leopere** [comment]
The most convenient way to handle an upgrade would just be to do a forklift upgrade and just add a function to just uninstall and reinstall with clean & new settings.  Potentially attempt to re-create the keys that were added before if nothing else.  Of course, this isn't obligatory but it would be potentially nice to add some git magic to the upgrade script as well.

*Thanks for the work on this installer @Angristan I really appreciate the way you think with how this whole package is designed.
