### ISSUE TITLE
OpenVPN 2.4.0 stable - Encryption improvements

### ISSUE THREAD

**Issue by m0r0n** [angristan/openvpn-install#18]
Hey,

finally 2.4.0 seems to be there!
https://build.openvpn.net/downloads/releases/openvpn-2.4.0.tar.gz

Will you extend the installer to support TLS 1.2 by default et cetera?

Cheers

**Comment by angristan** [comment]
When it will be available in the repos yes

**Comment by m0r0n** [comment]
I am so looking forward to it! You have done a great job with this repo. I am excited how big the speed difference really is in the end, especially when ran on low end hardware (like travel routers)

**Comment by atulsian89** [comment]
Also,  please look in to the new option - - TLS-crypt    as this looks like an replacement to tls-authkey and is suggested here in the below link

https://community.openvpn.net/openvpn/changeset/c6e24fa3e16c32f9b427e360fd07102f613aa5c6/

**Comment by camjac251** [comment]
I believe it is available now. I could install it fine on Ubuntu 16.04
https://community.openvpn.net/openvpn/wiki/OpenvpnSoftwareRepos

I had added the package repo `http://build.openvpn.net/debian/openvpn/stable xenial main` and the version number reads `OpenVPN 2.4.0 x86_64-pc-linux-gnu `

**Comment by angristan** [comment]
It's available for Ubuntu, Debian and Arch. Waiting for CentOS (via EPEL ?)

**Comment by angristan** [comment]
I'll probably have to change more things for Arch tough : https://www.archlinux.org/news/openvpn-240-update-requires-administrative-interaction/

**Comment by angristan** [comment]
Hey guys, please check out PR https://github.com/Angristan/OpenVPN-install/pull/33 for the OpenVPN 2.4 update (WIP)
