### ISSUE TITLE
Ability to optionally use 2ton.com.au for DH param generation

### ISSUE THREAD

**Issue by yivo** [angristan/openvpn-install#182]
https://2ton.com.au/dhtool/ provides database with millions of pregenerated DH params and provides public API since 2015. Maybe it will be a good idea to use their work to speed up the slowest part of this script – DH param generation. What are your thoughts about it?

**Comment by angristan** [comment]
Definitely a big no.

But I understand this is a pain, that's why we'll use ECDH by default in https://github.com/Angristan/OpenVPN-install/pull/96, which is instantaneous.
