### ISSUE TITLE
View client log

### ISSUE THREAD

**Issue by ByMikko** [angristan/openvpn-install#184]
Where i can find client log? Thanks

**Comment by angristan** [comment]
On your client

**Comment by ByMikko** [comment]
And it is possible find client log on server where is openvpn server is running?

**Comment by angristan** [comment]
No, there is only the server log on /etc/openvpn/openvpn.log

**Comment by Leopere** [comment]
Wait, are you serious?  This guy must be a troll.  If you're actually this new at computers you can have a basic definition of some primary school computer terms are. Here explaining basic English behind [Server and Client](https://stackoverflow.com/a/11679722)
