### ISSUE TITLE
Unable to use DNS on local network for some reason

### ISSUE THREAD

**Issue by ishmumx** [angristan/openvpn-install#185]
During install, I made sure to choose the option for use DNS in /etc/resolv.conf

My ubuntu installation is set to use a 192.168 pi hole DNS that I have setup. 

I can connect using the openvpn PC client fine, but the second I try to go to a website, it will fail with a DNS error. Anyone know why?

**Comment by cezar97** [comment]
Can you try doing the same as described in #142?

**Comment by cezar97** [comment]
Also in `server.conf` for dns put the pi-hole ip directly.

**Comment by ishmumx** [comment]
Thank you! Your second suggestion worked a treat :)

Any idea if this behavior or the option to choose your own DNS during setup can be made in the future? Thanks again.

**Comment by cezar97** [comment]
For sure in the future we will have a wiki explaining this type of setup.
