### ISSUE TITLE
Just Thank you!

### ISSUE THREAD

**Issue by benedikt90** [angristan/openvpn-install#188]
Hi!

Sorry, for abusing the issue tracker for this, but I wanted to say thank you for your work. This script made it soooo easy and simple to setup and manage my OpenVPN instance. Last time I had to do it by hand, now it was so painless and fast. 

Thanks so much! :)

**Comment by angristan** [comment]
I'm glad it helped! :D

**Comment by cezar97** [comment]
@Angristan Why not adding https://saythanks.io/to/Angristan to the Readme? There's a lot of people out there that may want to say thank you and for sure it will make you feel better :wink:.
