### ISSUE TITLE
Combine with Monitor

### ISSUE THREAD

**Issue by PakTam** [angristan/openvpn-install#189]
is the possible to track client usage and so on?
or combine with this monitor
http://openvpn-monitor.openbytes.ie/

**Comment by cezar97** [comment]
Client status is available in `/etc/openvpn/openvpn.log`, just tail it.
For more detailed info such as geoip you can give a try at the above mentioned openvpn monitor.

**Comment by Leopere** [comment]
I think for the most part this is a cool idea but probably not in the scope of the project, it's probably just another vector for attack throwing an HTTP(s) server into the mix just for a data visualization panel.  

Granted I did mention PiHole for visually managing DNS queries I was more implying that we should consider the functionality to some extent.

**Comment by cezar97** [comment]
@chamunks you could make apache listen only on localhost or better on the VPN interface 10.8.0.1.

**Comment by angristan** [comment]
Out of scope indeed. Anything web related is not going into the script, that's not the goal
