### ISSUE TITLE
I wonder if we could include a IDS like Tripwire.

### ISSUE THREAD

**Issue by Leopere** [angristan/openvpn-install#192]
This may also be out of scope but an Intrusion Detection System like Tripwire might be a cool value add. 

[https://www.digitalocean.com/community/tutorials/how-to-use-tripwire-to-detect-server-intrusions-on-an-ubuntu-vps](https://www.digitalocean.com/community/tutorials/how-to-use-tripwire-to-detect-server-intrusions-on-an-ubuntu-vps) the guide is deprecated but it's likely still fine.  It's not really the end of the world to not have this but it might be cool to get an early warning if someone's gone and meddled with your VPN node without you knowing.  You could set it up so that the output is Pushed to your mobile or emailed or pretty much whatever.

**Comment by angristan** [comment]
> This may also be out of scope

Yes

**Comment by cezar97** [comment]
Try to hack a VPN server. It's nearly impossible thanks to things like packets signed by hmac and also public / private certificates instead of a static shared key. :smiley:

**Comment by Leopere** [comment]
@Angristan thanks for the response.

@cezar97 the front door isn't always the easiest way in but you're right.
