### ISSUE TITLE
multiple listening ports for clients connections

### ISSUE THREAD

**Issue by jermsmit** [angristan/openvpn-install#194]
Hi, I am looking to have multiple listening ports for clients to connect to on networks.
I once used OpenVPNAS (paid product) for openvpn and it allowed for this.  Is there a modification to your script to have multiple configs where one is listening on port 53, another on 443, etc...

Or a way I can accomplish this 

Thanks,
Jermal

**Comment by cezar97** [comment]
Sure! The support for this is planned, but until someone get it done take a look here to have it done manually : #28.

**Comment by angristan** [comment]
:arrow_up:
