### ISSUE TITLE
Print a list of IP's on the host for selection during installation.

### ISSUE THREAD

**Issue by Leopere** [angristan/openvpn-install#195]
Just a concept which could also help reduce or eliminate user breakage in the installation process is to scan for a list of IP addresses on the host then offer them for auto-config then prefer this method to a manual one which would still be an option.

**Comment by cezar97** [comment]
Sorry if I got it wrong, but this isn't the Ansible use case?

**Comment by angristan** [comment]
What would this fix?

**Comment by Leopere** [comment]
It's been a while since I've re-run the script ( congrats on making so wonderfully stable. ) I recall when you install it fresh it asks you to manually input the IP address you want OpenVPN bound to.  If you could enumerate the IP addresses of the host machine and offer them maybe a manual input option it could potentially be a plus.  

Keep in mind this enhancement would really just be catering to the lazy and the unenlightened.

**Comment by angristan** [comment]
It already does this :) https://github.com/Angristan/OpenVPN-install/blob/master/openvpn-install.sh#L216
