### ISSUE TITLE
[Enhancement] At some point I might make an attempt to add an AppArmor profile for this.

### ISSUE THREAD

**Issue by Leopere** [angristan/openvpn-install#197]
Since we're using Ubuntu, we should consider having AppArmor enabled to protect the system from OpenVPN process.  OpenVPN may be set up with the ideal settings via this script ( at least hopefully is our goal ) but we don't have future x-ray vision so I'd love to see something for this.

Maybe we could have a thing running on a CI server somewhere for aa-genprof and testing.

This would be a non-trivial feature addition.

**Comment by angristan** [comment]
Seems very overkill for me
