### ISSUE TITLE
[[: not found

### ISSUE THREAD

**Issue by tsunamaru** [angristan/openvpn-install#199]
Hi. Just trying to run script on my new VPS and got this:

![screenshot_95](https://user-images.githubusercontent.com/37580200/38853253-5c80b9b8-4225-11e8-8964-4b173c887230.png)

**Comment by tsunamaru** [comment]
Sorry, this is my mistake, no need write `sh` before `./openvpn-install.sh`

Issue closed.

**Comment by angristan** [comment]
Yes you can do `bash openvpn-install.sh` or `./openvpn-install.sh`
