### ISSUE TITLE
Unable to ping client from server

### ISSUE THREAD

**Issue by camjac251** [angristan/openvpn-install#20]
I wasn't sure whether to open this on Nyr's page or this one, but I'm using your fork of the script.

I have been trying to forward a port over from the OpenVPN server to a client but I haven't been able to get it to work. I have net.ipv4.ip_forward = 1 for both the client and server, at first it was just the server and it didn't work still. I'm running OpenVPN on an openvz vps with Tun/tap, PPP, and IPSec enabled, at first it was just tun/tap.
Host is running Centos 7, Client is Ubuntu 16.04, I didn't run this script on the client, only server. I had followed this tutorial for setting up OpenVPN on the client though [ http://www.htpcguides.com/force-torrent-traffic-vpn-split-tunnel-debian-8-ubuntu-16-04/](http://www.htpcguides.com/force-torrent-traffic-vpn-split-tunnel-debian-8-ubuntu-16-04/)

I am able to connect to the vpn and ping ip addresses and domain names, as well as ping the server from the client. I can't however ping the client from the server. 10.8.0.2 is my client IP and 10.8.0.1 is the server IP from within the VPN. 

At first using the default script without modifying, When I would try to ping the client from server, it wouldnt show anything, like it was blocking ping but still resolving. I had then tried this [http://securityblog.gr/2131/forward-ports-to-openvpn-clients-in-centos/](http://securityblog.gr/2131/forward-ports-to-openvpn-clients-in-centos/) with no luck, using the openvz version. So I had tried out this on Nyr's issue page [Nyr/openvpn-install#190](https://github.com/Nyr/openvpn-install/issues/190) and [https://github.com/Nyr/openvpn-install/issues/211#issuecomment-258063856](https://github.com/Nyr/openvpn-install/issues/211#issuecomment-258063856) but then after doing that, pinging the client shows 
```Bash
From 10.8.0.2 icmp_seq=5 Destination Port Unreachable
``` 
instead. I'm not sure what to do now. I basically wanted to port forward the port 32400 to the client from server to use by the client.

**Comment by Kcchouette** [comment]
Same as #17?

**Comment by angristan** [comment]
I can ping a client from the server as of now.

**Comment by jet-deployer** [comment]
Please check this repo:
https://github.com/arezaie14/openvpn-over-icmp
its easily to run openvpn server and tunnel it between 2 server if you needed if you didn't have any ping from yout client to server
