### ISSUE TITLE
Change DH-size & RSA size after installation

### ISSUE THREAD

**Issue by heikoh81** [angristan/openvpn-install#201]
Hi,

I set up OpenVPN with your script and used as suggested
3072 bits for Diffie Hellman
3072 bits for RSA
I now discovered that my endpoints (Raspberry Pi 3, Raspberry Pi 3B+) do not have enough CPU power to encrypt with my full VDSL-Speed (10 Mbit Upload). Thus, I'm stuck at 8,5 Mbit Throughput.
CPU load especially on the older Raspberry Pi 3 ist often at 25%, so one of four cores is maxed out.

This is still ok, but with my previous installation I had 2048 bit on both DH & RSA and no performance problems.

How can I change the sizes for both RSA & DH back to 2048 on my running setup?
Or would I have to use the uninstall option and do the installation again?

Best regards,

Heiko (Germany)

**Comment by cezar97** [comment]
If the speed and the load is the problem, I would suggest you to give a try to the openvpn2.4-update branch which has support for elliptic curves.

**Comment by cezar97** [comment]
If you want to change the dh key, just regenerate another with `openssl dhparam -out dh.pem 2048` and move it in `/etc/openvpn/`, `mv dh.pem /etc/openvpn/`.
For the rsa key, all the clients and server keys have to be regenerated so here it's easier uninstalling and installing again.

**Comment by heikoh81** [comment]
Thanks for the reply.
Will uninstall completely remove all previous certificates and stuff so it will be a clean start?

**Comment by cezar97** [comment]
If you use the uninstall option from the script, openvpn and everything related ( certificates, ovpn files, keys ) are removed. So yes, it's a clean start.

**Comment by heikoh81** [comment]
Thanks for your answer.
