### ISSUE TITLE
Multiple Server Instances on DO

### ISSUE THREAD

**Issue by mep85** [angristan/openvpn-install#202]
I'm having trouble starting multiple instances of the server on a Digital Ocean droplet.
Let's say the first server is called "server" and the second server is called server2.  After creating server2.conf, server2 to fail to start.

The first server runs fine (the one set up by the script), but subsequent ones all fail with the error that the port is already in use. Running systemctl status openvpn@server2.service yields the error:
`TCP/UDP: Socket bind failed on local address [AF_INET]10.10.0.6:443: Address already in use`
My first instance runs on port 443, but my server2.conf states a different port/protocol for the second server.

It seems that server2.conf isn't being read at all, and running systemctl start openvpn@server2.service is still parsing server.conf and not server2.conf.

Running systemctl status openvpn@server2.service seems to confirm this, as it shows:
`ExecStart=/usr/sbin/openvpn --daemon ovpn-%i --status /run/openvpn/%i.status 10 --cd /etc/openvpn --script-security 2 --config /etc/openvpn/server.conf`

**Comment by cezar97** [comment]
Yeah, the script hard-codes that `server.conf` so it's the only one parsed. See #28 for a solution.
