### ISSUE TITLE
It doesn't work anymore on Android Phone & ASUS router

### ISSUE THREAD

**Issue by realjohnny** [angristan/openvpn-install#203]
Hi,
I was running this OpenVPN install on Ubuntu 14.04 VPS on vultr. All was working fine till I re-installed the server with exact same configuration and configuration option in this script, now OpenVPN has stopped working. It shows connected in Android (I generated a file for mobile phone) and in ASUS Router (a separated client file was generated for it).

I tried with different DNS servers options (number 9 which shows but you can't choose) with no luck. I followed advice in another thread where user was facing problem with ASUS router with no luck. I have flashed ASUS router with latest Merlin firmware and in recent past these configurations were working flawlessly.

I faced the same issue 3-4 months back and then it started working with so many installations and un-installation.

Just now I installed Nyr script and it is working.

**Comment by angristan** [comment]
Please explain "It doesn't work". I suppose you mean you're connected but you can't access the internet?

**Comment by realjohnny** [comment]
Yes it connects but I just noticed that it isnt completely dead but in fact very slow in browsing or any internet activity. Most of web page show dns error or page load errors and some open very slowly.

This is both on Android phone with openvpn client and on any device connected with Asus router.

**Comment by realjohnny** [comment]
I am not a tech savy but I can assume that this script and Nyr script are working on the same source files or code and therefore both are not working at all anymore.

With the same scenario on vultr VPS (exactly same) both scripts on different OS (Debian, Ubuntu and CentOS, different versions) do not provide any web activity but only show as connected.

Unfortunately switching to other commercial VPN will be option left for a less techie person like me.

**Comment by cezar97** [comment]
I'm sorry we couldn't help. May I suggest you to try pivpn before the commercial alternative? @realjohnny
