### ISSUE TITLE
Limited control channel cipher -- DDWRT Incompatibility

### ISSUE THREAD

**Issue by HarvsG** [angristan/openvpn-install#205]
![image](https://user-images.githubusercontent.com/11440490/39281597-65a17d78-48fd-11e8-811e-abae43dda7a5.png)
When trying to add a DD-WRT router as a client. None of the available options matches the chosen control channel cipher (`TLS-DHE-RSA-WITH-AES-128-GCM-SHA256`), causing incompatibility. 
https://github.com/Angristan/OpenVPN-install/blob/61d89e3ba20af7b4530dde08ebb4a73a6c84f1fe/openvpn-install.sh#L691
https://github.com/Angristan/OpenVPN-install/blob/61d89e3ba20af7b4530dde08ebb4a73a6c84f1fe/openvpn-install.sh#L561
https://github.com/Angristan/OpenVPN-install/blob/61d89e3ba20af7b4530dde08ebb4a73a6c84f1fe/README.md#L226

**Comment by angristan** [comment]
The choice will be available in https://github.com/Angristan/OpenVPN-install/pull/96

In the meantime you can change it yourself in the server and client config file.

**Comment by HarvsG** [comment]
Thank you!

I went with TLS-DHE-RSA-WITH-AES-256-GCM-SHA384 and it is working beautifully on various clients.

**Comment by wdbartram** [comment]
Hi great work thanks I was looking to solve the TLS-CRYPT problem with the original MIT release. Just wondering if you had got around to solving the DDWRT issue? I guess you mean release 96? AGAIN great work THANKS
