### ISSUE TITLE
Second/another Confing file for the same server

### ISSUE THREAD

**Issue by loadcorp** [angristan/openvpn-install#206]
When I try to connect my second laptop to my vpn server my first laptop always disconnecting.

Tell me please how could I create another config for my another device? Is ti possbile to use several config files for one vpn server?

**Comment by cezar97** [comment]
To create another config for a device just run the script again and select option 1 ( add cert for new user ).
Yes, every device has it's own config file: this provides better security and also you have the ability to revoke a lost config so no one can use it to connect anymore ( that's option 2 ).

**Comment by loadcorp** [comment]
Thank you very much. All is working!
