### ISSUE TITLE
File locations

### ISSUE THREAD

**Issue by iambenmitchell** [angristan/openvpn-install#209]
Hello, I am trying to use this: https://github.com/iphoting/ovpnmcgen.rb to get a iOS install profile so users do not have to install the open vpn app. but I don't know where the locations to the files I need are. 

Also if you feel like doing it maybe you could create a fork of https://github.com/iphoting/ovpnmcgen.rb and add it to the script so that you can choose between a .ovpn and a .mobilconfig : )

**Comment by cezar97** [comment]
Everything is stored all together within the ovpn profile the scripts generates. It is in the user's home directory.

**Comment by iambenmitchell** [comment]
I mean the CA cert, Server Cert etc

**Comment by cezar97** [comment]
BTW, it seems that you can pass directly the ovpn file instead 9s extracting cert, key, ca and tls-auth. See `--ovpnconfigfile ` option.

**Comment by iambenmitchell** [comment]
Thats for getting the keys and strings (custom data)

**Comment by cezar97** [comment]
> I mean the CA cert, Server Cert etc

You need the CA, cert, key and tls-auth. They are stored in the ovpn file in the form:
```
...
<cert>
</cert>
<key>
</key>
....
```
So I think you have to copy and write them in separate files to pass that script.

**Comment by cezar97** [comment]
```/etc/openvpn/client-template.txt
/etc/openvpn/easy-rsa/pki/ca.crt
/etc/openvpn/easy-rsa/pki/issued/$1.crt
/etc/openvpn/easy-rsa/pki/private/$1.key
/etc/openvpn/tls-auth.key
```
`$1` is the name of the client.

**Comment by iambenmitchell** [comment]
thanks!
