### ISSUE TITLE
Crash on multiple distros

### ISSUE THREAD

**Issue by ejbolt** [angristan/openvpn-install#210]
Upon running the script, I get a crash when the script tries to get something from github 
![image](https://user-images.githubusercontent.com/21202046/39492368-f557a39c-4d54-11e8-852f-592d31c4b57c.png)

Have tried on Debian, Fedora, Ubuntu, and CentOS

**Comment by angristan** [comment]
What do you mean by crash? Nothing happens after your screenshot?

**Comment by ejbolt** [comment]
Meaning the machine is frozen.  I'm doing this in virtual machines so they
stop responding.  A couple times I've gotten a kernel panic as well.

**Comment by angristan** [comment]
Oh. Did you take a look at `/var/log/kern.log`?

**Comment by ejbolt** [comment]
Will do that on next attempt and let you know :).  Hopefully it's not an
issue with my ESXi server that I'm running the VMs on..

**Comment by angristan** [comment]
At least it seems to be a very specific issue 🤔
