### ISSUE TITLE
Windows 10: TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity) 

### ISSUE THREAD

**Issue by Moris-Shalon** [angristan/openvpn-install#211]
Everything works ok on Ubuntu 16.04, but I can't connect to my server from Windows 10, using official openvpn app. Firewall is disabled both on server and client.

----------Here is the log----------
Wed May 02 04:21:27 2018 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Wed May 02 04:21:27 2018 TLS Error: TLS handshake failed
Wed May 02 04:21:27 2018 SIGUSR1[soft,tls-error] received, process restarting
Wed May 02 04:21:27 2018 MANAGEMENT: >STATE:1525224087,RECONNECTING,tls-error,,,,,
Wed May 02 04:21:27 2018 Restart pause, 5 second(s)
Wed May 02 04:21:32 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]95.216.140.175:1194
Wed May 02 04:21:32 2018 Socket Buffers: R=[65536->65536] S=[65536->65536]
Wed May 02 04:21:32 2018 UDP link local: (not bound)
Wed May 02 04:21:32 2018 UDP link remote: [AF_INET]95.216.140.175:1194
Wed May 02 04:21:32 2018 MANAGEMENT: >STATE:1525224092,WAIT,,,,,,
Wed May 02 04:22:32 2018 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Wed May 02 04:22:32 2018 TLS Error: TLS handshake failed
Wed May 02 04:22:32 2018 SIGUSR1[soft,tls-error] received, process restarting
Wed May 02 04:22:32 2018 MANAGEMENT: >STATE:1525224152,RECONNECTING,tls-error,,,,,
Wed May 02 04:22:32 2018 Restart pause, 5 second(s)
Wed May 02 04:22:37 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]95.216.140.175:1194
Wed May 02 04:22:37 2018 Socket Buffers: R=[65536->65536] S=[65536->65536]
Wed May 02 04:22:37 2018 UDP link local: (not bound)
Wed May 02 04:22:37 2018 UDP link remote: [AF_INET]95.216.140.175:1194
Wed May 02 04:22:37 2018 MANAGEMENT: >STATE:1525224157,WAIT,,,,,,
Wed May 02 04:22:39 2018 write UDP: Unknown error (code=10051)

----------Here is my .ovpn file's content----------
client
proto udp
remote 95.216.140.175 1194
dev tun
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
verify-x509-name server_XtJrEMJvSsZ98eJT name
auth SHA256
auth-nocache
cipher AES-128-CBC
tls-client
tls-version-min 1.2
tls-cipher TLS-DHE-RSA-WITH-AES-128-GCM-SHA256
setenv opt block-outside-dns
verb 3
script-security 2 
dhcp-option DNS 213.133.100.100
dhcp-option DNS 213.133.98.98
dhcp-option DNS 213.133.99.99 

Please, help to solve this problem.

**Comment by angristan** [comment]
The issue seems to be:

```
Wed May 02 04:22:37 2018 UDP link remote: [AF_INET]95.216.140.175:1194
Wed May 02 04:22:37 2018 MANAGEMENT: >STATE:1525224157,WAIT,,,,,,
Wed May 02 04:22:39 2018 write UDP: Unknown error (code=10051)
```

What version of openvpn are you running on W10?

**Comment by Moris-Shalon** [comment]
> What version of openvpn are you running on W10?

Latest OpenVPN 2.4.6 from 24th april and OpenVPN GUI 11.10.0.0
library versions: OpenSSL 1.1.0h  27 Mar 2018, LZO 2.10

**Comment by angristan** [comment]
To me it seems your computer just can't access the server. Have you tried ping, telnet, etc to check the connectivity ?

**Comment by ZChuckMoris** [comment]
I am experiencing no problems connecting to the server. Moreover, at the same time proxy and ssh works perfectly.

**Comment by Moris-Shalon** [comment]
I am not experiencing any problems connecting to the server. Moreover, at the same time proxy and ssh (putty on windows) work perfectly.

**Comment by Moris-Shalon** [comment]
Formatted all data on VPS and reinstalled Ubuntu 16.04.4. With clean install everything works fine.
Sorry for disturb

**Comment by ghost** [comment]
Same here. Moreover - the same error is in the server's log

**Comment by ghost** [comment]
@ZChuckMoris you may want to edit out your ip adress

**Comment by ghost** [comment]
Okay, so I solved this. I needed to add a static route allowing connection to my server, somehow it wouldn't get through, even though I swear I saw those error messages in my server's log

**Comment by ghost** [comment]
hmmm, this also happens after suspend. thoughts?

**Comment by angristan** [comment]
Please use Nyr's script and report if it happens with it too

**Comment by PrimordialHelios** [comment]
I've used both scripts and can confirm that it happens on both, still trying to figure everything out.

**Comment by ghost** [comment]
I've used both scripts and can confirm this happens with both. No idea how to fix it yet. Ports are open and forwarded properly.

EDIT: Nevermind, it was a firewall issue.

**Comment by Super-Gil** [comment]
Hello angristan,
I 've got the same issue here but I don't think it's a firewall issue.
I opened my ports on my ubuntu 18.04 machine and also my Windows 10 computer and even shut down my firewall for a while but it still displaying TLS errors.
I didn't install any other softwares on the server.
It's quite strange that in the same network conditions, the VPN sometimes works but sometimes get error for TLS handshake failed... I searched and read all the instructions on google but none of them solved my problem... So I am here to request for help.

**Comment by Super-Gil** [comment]
This is my client log 
Every time there is an error, I would suck here.
After a minute it would display TLS error...


Thu Aug 15 15:43:38 2019 OpenVPN 2.4.7 x86_64-w64-mingw32 [SSL (OpenSSL)] [LZO] [LZ4] [PKCS11] [AEAD] built on Feb 21 2019
Thu Aug 15 15:43:38 2019 Windows version 6.2 (Windows 8 or greater) 64bit
Thu Aug 15 15:43:38 2019 library versions: OpenSSL 1.1.0j  20 Nov 2018, LZO 2.10
Thu Aug 15 15:43:38 2019 MANAGEMENT: TCP Socket listening on [AF_INET]127.0.0.1:25344
Thu Aug 15 15:43:38 2019 Need hold release from management interface, waiting...
Thu Aug 15 15:43:39 2019 MANAGEMENT: Client connected from [AF_INET]127.0.0.1:25344
Thu Aug 15 15:43:39 2019 MANAGEMENT: CMD 'state on'
Thu Aug 15 15:43:39 2019 MANAGEMENT: CMD 'log all on'
Thu Aug 15 15:43:39 2019 MANAGEMENT: CMD 'echo all on'
Thu Aug 15 15:43:39 2019 MANAGEMENT: CMD 'bytecount 5'
Thu Aug 15 15:43:39 2019 MANAGEMENT: CMD 'hold off'
Thu Aug 15 15:43:39 2019 MANAGEMENT: CMD 'hold release'
Thu Aug 15 15:43:39 2019 Outgoing Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Thu Aug 15 15:43:39 2019 Outgoing Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Thu Aug 15 15:43:39 2019 Incoming Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Thu Aug 15 15:43:39 2019 Incoming Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Thu Aug 15 15:43:39 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]13.231.193.254:59343
Thu Aug 15 15:43:39 2019 Socket Buffers: R=[65536->65536] S=[65536->65536]
Thu Aug 15 15:43:39 2019 UDP link local: (not bound)
Thu Aug 15 15:43:39 2019 UDP link remote: [AF_INET]13.2**.***.*54:5***3
Thu Aug 15 15:43:39 2019 MANAGEMENT: >STATE:1565855019,WAIT,,,,,,
Thu Aug 15 15:43:41 2019 MANAGEMENT: >STATE:1565855021,AUTH,,,,,,
Thu Aug 15 15:43:41 2019 TLS: Initial packet from [AF_INET]13.2**.***.*54:5***3, sid=22de8660 81b64820
Thu Aug 15 15:43:41 2019 VERIFY OK: depth=1, CN=cn_hWssFPTk1p3Wk8Cv
Thu Aug 15 15:43:41 2019 VERIFY KU OK
Thu Aug 15 15:43:41 2019 Validating certificate extended key usage
Thu Aug 15 15:43:41 2019 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Thu Aug 15 15:43:41 2019 VERIFY EKU OK
Thu Aug 15 15:43:41 2019 VERIFY X509NAME OK: CN=server_QbY60****zdBwd4q
Thu Aug 15 15:43:41 2019 VERIFY OK: depth=0, CN=server_QbY60****zdBwd4q

**Comment by Super-Gil** [comment]
I have error both with my DigitalOcean VPS and my AWS E2 instances. I would appreciate it a lot if someone could help me solve this issue!
Regards,
Gil.
