### ISSUE TITLE
Package 'gpg' has no installation candidate

### ISSUE THREAD

**Issue by iambenmitchell** [angristan/openvpn-install#217]
Package gpg is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'gpg' has no installation candidate

**Comment by cezar97** [comment]
Oh, it's `gnupg2`.
Why the commit was made as `gpg`? @Angristan

**Comment by angristan** [comment]
@MrBenFTW what OS are you using?

**Comment by iambenmitchell** [comment]
16.04

**Comment by iambenmitchell** [comment]
ubuntu(16.04)

**Comment by angristan** [comment]
Indeed I've tried with multiple Debian/Ubuntu versions and it's not consistent, let's go with `gnupg`

**Comment by angristan** [comment]
(`gnupg2` is basically a symlink to `gnupg` https://packages.debian.org/stretch/gnupg2)

**Comment by angristan** [comment]
Thanks for the report @MrBenFTW

**Comment by FBIanderson** [comment]
so how to slove this problem @angristan
