### ISSUE TITLE
openvpn doesn't work after a server reboot

### ISSUE THREAD

**Issue by surihost** [angristan/openvpn-install#218]
Hi

I notice that the vps doesn't work/start after a server reboot?
How to restart it?
Its on ubuntu 14.04 vps

**Comment by Leopere** [comment]
Is there a specific reason you're using a 4 year old version of Ubuntu and
not 18.04?

**Comment by cezar97** [comment]
Speaking of 18.04, can someone confirm the script still works? I saw some changes in others openvpn installs due to the new Ubuntu Release.

**Comment by Split7fire** [comment]
@chamunks I think @surihost using vpscheap services with their most cheap solution. This plan has Ubuntu 14.04

**Comment by surihost** [comment]
It for client who runs an app which only works in ubuntu 14.04 properly so that's why for the old ubuntu.

**Comment by angristan** [comment]
Ubuntu 14.04 is not supported anymore. Also next time please provides logs.
