### ISSUE TITLE
open vpn bridge mode install scripts for static public ip 

### ISSUE THREAD

**Issue by fibron85** [angristan/openvpn-install#220]
Hello sir i would like to request you to make a scripts for openvpn installation with static public ip for client.

like i have a server with 16 ip address 173.22.xx.20 and  1 ip 173.22.xx.20 will be use for openvpn server. Now i want 173.22.xx.21-25 ip to assign my openvpn client. is it possible for you make me a scripts for this.

**Comment by cezar97** [comment]
It is called bridge or tap mode what are you asking for.

**Comment by fibron85** [comment]
Hello sir its maybe tap mode. i just need public static ip for my each and every client. so i need to setup the openvpn as i told you before 1 ip will be use for server main ip. and other ip will be offline. once client connected to openvpn server client will get the assigned public ip to him. otherwise that ip should be offline.

**Comment by fibron85** [comment]
I can do it now with openvpn access server setup but its having only 2 user license only but i need something more then 20 user license which is costly.

**Comment by HarvsG** [comment]
I too would be interested in a TAP + Bridge mode
