### ISSUE TITLE
personally, I would stay very far away from elliptic curves

### ISSUE THREAD

**Issue by UnixJunkie** [angristan/openvpn-install#222]
better stick with older stuffs that are well known and well studied.

**Comment by cezar97** [comment]
Well, I've preferred safe curves instead, as posted on #96. But it seems there's no phone support...

**Comment by angristan** [comment]
There is choice in #96. And personal opinions are not really enough when talking crypto :)

**Comment by cezar97** [comment]
@Angristan personal opinions aren't enough anywhere if we talk about security.
Regarding that, I don't think safe curves requires an explanation or an intro as there's already a lot of material on the Internet. And yeah, just to be sure, a lot of people stick with RSA and all the good and well studied stuff as @UnixJunkie said. There's still a lot of discussion around Curves...

**Comment by angristan** [comment]
Sure, both RSA and EC are ok, so that's why we're going to propose them both

**Comment by UnixJunkie** [comment]
Can you default to RSA then?
Sure, leaving a choice to users is nice.
But having sound defaults is even nicer.
This is not my personal opinion:
"Why Is the NSA Moving Away from Elliptic Curve Cryptography?"
https://www.schneier.com/blog/archives/2015/10/why_is_the_nsa_.html

**Comment by cezar97** [comment]
On master, RSA is the default.
On the OpenVPN-2.4 branch, EC are recommended instead due to the speed and "security" ( that's more a bits fact ). Anyway there is still the user choice, even if it's heavily influenced by this "recommended ( faster )" or similar. So yeah, average users / non technical users will stick with the defaults.

**Comment by angristan** [comment]
With EC the script can be done in 15 seconds. If you're worried about the NSA not using EC, then this script isn't meant for you.
