### ISSUE TITLE
Not working @school

### ISSUE THREAD

**Issue by ngx3** [angristan/openvpn-install#223]
The script, everything works great at cafes, public places etc.. but it does not work at my school? On the other side of things, this looks like the connection is stating it is a vpn, some vpns make it inconspicuous that it is not a vpn?

Anyway can I make it seem like my vpn is not a vpn? In other words, hide my vpn traffic so they can see it's not a vpn.

**Comment by cezar97** [comment]
Yeah, schools are likely to block VPNs. Solution? Supposing that they're not blocking the VPS' IP, first try running OpenVPN on a common port like 80/TCP or 443/TCP. If this doesn't work for you, then set up stunnel to "hide" the traffic and make it look like TLS encrypted connection. Details here https://github.com/pivpn/pivpn/issues/525.
Note that if you have to setup stunnel, then give it the 80/TCP or the 443/TCP and something else to the VPN. Anyway I'll recommend 443/TCP as the port.

**Comment by ngx3** [comment]
Can I set port 443 on UDP or it has to be TCP? Because of the speed.

**Comment by iProdigy** [comment]
I'd try UDP first but TCP is less likely to be restricted.

**Comment by ngx3** [comment]
2 questions.

1.Does OpenVPN obtain the new public IP from my vps as it changes?
2.To change port or udp to tcp I need to remove OpenVPN and start from the beginning (reinstalling)? I was thinking to make a port 443 TCP config just for school and other configs for elsewhere (UDP).

**Comment by cezar97** [comment]
1) Usually, VPS have static IP's. If it's dynamic you could register for a DDNS service ( there are many free ) and use the DDNS domain in your configs ( only in the ovpn profiles is necessary ).
2) Edit `/etc/openvpn/server.conf` and change `proto` to udp or tcp. You also have to do the same thing with your ovpn profile.

**Comment by ngx3** [comment]
During ovpn installation it got the private IP, and behind a NAT it would automatically retrieve the new IP? Wana be sure of that.

**Comment by cezar97** [comment]
On NAT just configure port forwarding on the router and then register the DDNS with the public IP. In the ovpn then put the DDNS domain.
No, currently there is udp or tcp only, as your server config is. For multiple server there's an issue open that could help you. Also make sure to restart the openvpn server after changing configs.

**Comment by ngx3** [comment]
Thanks!

**Comment by ngx3** [comment]
@cezar97 I can't find server.conf in /lib/systemd/system/openvpn@.service? Following what paccerdk said.

**Manually changing server.conf back to %i.conf in /lib/systemd/system/openvpn@.service fixes support for multiple instances**

**Comment by ngx3** [comment]
That's what I mean, I can't find server.conf in the openvpn@.service file.

**Comment by ngx3** [comment]
10 /char

**Comment by ngx3** [comment]
I changed the word /etc/openvpn/**server**.conf to config /etc/openvpn/**%i**.conf (where boldded below)

> ExecStart=/usr/sbin/openvpn --daemon ovpn-%i --status /run/openvpn/%i.status 10 --cd /etc/openvpn --script-security 2 --config /etc/openvpn/**server.conf** --writepid /run/openvpn/%i.pid

$ sudo service openvpn@server restart
Warning: openvpn@server.service changed on disk. Run 'systemctl daemon-reload' to reload units.

Used a UDP config (changed prot to UDP in the .ovpn file) Still doesn't work.

**Comment by angristan** [comment]
Did you try UDP on port 53?

**Comment by angristan** [comment]
And yes as you pointed out don't forget to run `systemctl daemon-reload` before restarting the service

**Comment by ngx3** [comment]
I ran `systemctl daemon-reload` before restarting openvpn service, this was the first attempt and I had copied it to the clipboard beforehand and didn't want to remove it.

Neither UDP port 53/443 is connecting, there is no info about the connection, it's just blank. I installed Openvpn with TCP and port 443, if this info is of any value. Even chaning it to udp doesn't work.

In my .ovpn
```
proto udp-client
remote X.X.X.X 53dev tun
```

**Comment by angristan** [comment]
FYI with TCP it's `proto tcp` on the server and `proto tcp-client` on the client. For UDP, it's `proto udp` on both. I don't know if that will help though.

**Comment by ngx3** [comment]
I was hoping! Unfortunately not :/ Do I need to make another server conf file? For udp and possibly if I ever want to connect via another port, other than 443?


This edit was for not having to have 2 instances of Openvpn on the vps and use more than one config?I'm sure the edit below is correct? --config /etc/openvpn/%i.conf is what is edited.

```
 [Unit]
Description=OpenVPN connection to %i
PartOf=openvpn.service
ReloadPropagatedFrom=openvpn.service
Before=systemd-user-sessions.service
Documentation=man:openvpn(8)
Documentation=https://community.openvpn.net/openvpn/wiki/Openvpn23ManPage
Documentation=https://community.openvpn.net/openvpn/wiki/HOWTO

[Service]
PrivateTmp=true
KillMode=mixed
Type=forking
ExecStart=/usr/sbin/openvpn --daemon ovpn-%i --status /run/openvpn/%i.status 10 --cd /etc/openvpn --script-security 2 --config /etc/openvpn/%i.conf --writepid /run/openvpn/%i.pid
PIDFile=/run/openvpn/%i.pid
ExecReload=/bin/kill -HUP $MAINPID
WorkingDirectory=/etc/openvpn
ProtectSystem=yes
CapabilityBoundingSet=CAP_IPC_LOCK CAP_NET_ADMIN CAP_NET_BIND_SERVICE CAP_NET_RAW CAP_SETGID CAP_SETUID CAP_SYS_CHROOT CAP_DAC_READ_SEARCH CAP_AUDIT_WRITE
#LimitNPROC=10
DeviceAllow=/dev/null rw
DeviceAllow=/dev/net/tun rw

[Install]
WantedBy=multi-user.target
```

**Comment by ngx3** [comment]
Is this a prerequisite to allow multi port/protocol? I would need another config?

**Comment by angristan** [comment]
See https://github.com/Angristan/OpenVPN-install/issues/28 for running multiple servers
