### ISSUE TITLE
LZ4 Compression?

### ISSUE THREAD

**Issue by anonymouz4** [angristan/openvpn-install#225]
Any option to enable lz4 compression?

**Comment by angristan** [comment]
Use `compress`. https://community.openvpn.net/openvpn/wiki/Openvpn24ManPage

There is an option in https://github.com/Angristan/OpenVPN-install/pull/96

**Comment by anonymouz4** [comment]
I know how to do that. My point was to put this option to select in the setup script!

**Comment by angristan** [comment]
Then you have an answer for this too 😃

**Comment by anonymouz4** [comment]
Well its not implemented in the setup process yet

**Comment by angristan** [comment]
Yes but it will be when https://github.com/Angristan/OpenVPN-install/pull/96 in merged, as it's a 2.4 feature.

**Comment by anonymouz4** [comment]
Oh then this is my bad. I didn't notice that this script doesn't have full 2.4 support
