### ISSUE TITLE
OpenVPN 2.4.0 update requires administrative interaction on Arch

### ISSUE THREAD

**Issue by yolateng0** [angristan/openvpn-install#23]
>The upgrade to OpenVPN 2.4.0 makes changes that are incompatible with previous configurations. Take special care if you depend on VPN connectivity for remote access! Administrative interaction is required:

 > Configuration is expected in sub directories now. Move your files from /etc/openvpn/ to /etc/openvpn/server/ or /etc/openvpn/client/.

https://www.archlinux.org/news/openvpn-240-update-requires-administrative-interaction/

**Comment by angristan** [comment]
Yep, I'll take care of that.

**Comment by ShaunPCcom** [comment]
I was wondering if the fix for Arch is still on the way? Currently, this script isn't working on Arch as a result of this required intervention.
