### ISSUE TITLE
Set UFW DEFAULT_FORWARD_POLICY="ACCEPT"

### ISSUE THREAD

**Issue by thelatinist** [angristan/openvpn-install#233]
For those with UFW installed with the default configuration (at least on Ubuntu 18.04 LTS), the value of DEFAULT_FORWARD_POLICY is "DROP", which results in failed DNS.  If this could be detected and changed in /etc/default/ufw, I suspect it would save many others a headache.

**Comment by 07stuntar1** [comment]
Thank You,
For some reason on my new 16.04.4 it was set to DROP as default as well. I've ran the script in the past and never had a problem until recently.

**Comment by angristan** [comment]
Thanks for the report

**Comment by angristan** [comment]
Is this only for Ubuntu 18.04?

Enabling forward can also be done with `ufw default allow FORWARD`, but I don't know what exactly we should check before doing do?

**Comment by cezar97** [comment]
@Angristan both https://www.digitalocean.com/community/tutorials/how-to-set-up-an-openvpn-server-on-ubuntu-18-04 and https://www.digitalocean.com/community/tutorials/how-to-set-up-an-openvpn-server-on-ubuntu-16-04 edit it from DROP.
So yeah, both Xenial and Bionic seems to be affected. Anyway only some users report DROP as default on 16.04.

**Comment by angristan** [comment]
#249 should fix this, please give some feedback!

**Comment by angristan** [comment]
Thanks for the feedback 🤔

Anyway, it should be fixes with the rework: https://github.com/angristan/openvpn-install/pull/291

**Comment by zer0byte** [comment]
Thank you! This was helpful for my OpenVpn setup on debian based VPS.

**Comment by slhck** [comment]
I just installed the most recent version on an Ubuntu 18.04 machine, and I have

```
DEFAULT_FORWARD_POLICY="DROP"
```

in `/etc/default/ufw`.

When connecting, I couldn't reach any Internet address. I had:

```
➜  ~ ufw status verbose
Status: active
Logging: on (low)
Default: deny (incoming), allow (outgoing), deny (routed)
New profiles: skip

…
```

What fixed it for me was running this on the server:

```
ufw default allow FORWARD
ufw reload
```

Shouldn't this have been taken care of via the script?
