### ISSUE TITLE
Migrate from one hoster to another host

### ISSUE THREAD

**Issue by GeeBee93** [angristan/openvpn-install#234]
Hey,

first thank you very much for that awesome script - worked flawlessly for me! :+1: 

I just need to move my OpenVPN installation from one host to another host. Is it possible to just copy /etc/openvpn and install openvpn on the new host and then continue use it with the "old" certficiates? Hostname and everything else will be the same.

Thank you!

**Comment by ghost** [comment]
Why not just install your new server and then edit the old certificates to /etc/openvpn/server.conf. Backup your client and server configs.

**Comment by angristan** [comment]
Yes you can, just make sure to change the IP address in the clients' config

**Comment by nxtreaming** [comment]
@angristan 
I get the following error when I migrate openvpn to a new vps

TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
TLS Error: TLS handshake failed

**Comment by nxtreaming** [comment]
sorry, it's the firewall issue.

closed
