### ISSUE TITLE
Client connects to VPN server but internet doesn't work

### ISSUE THREAD

**Issue by aliweb** [angristan/openvpn-install#237]
I installed this on a Debian 9 OpenVZ VPS where TUN/TAP is enabled.

I am able to connect to VPN on my Windows 10 machine but the internet doesn't work. IP is assigned and icon turns green but I am unable to open any website on my machine. At first, I thought this could be some issue with the machine that maybe I messed up some setting but I tried the same on an Android phone and it has the same problem i.e. it is able to connect to VPN but after that internet doesn't work.

How can I troubleshoot this issue? Are there any logs on the server which I can check to see what is causing this issue?

It used to work fine on another VPS where I installed it last year.

**Comment by angristan** [comment]
Hello, can you do:

`iptables -t nat -L -n -v`

**Comment by aliweb** [comment]
`VM:~$ sudo iptables -t nat -L -n -v`

> Chain PREROUTING (policy ACCEPT 1116K packets, 58M bytes)
>  pkts bytes target     prot opt in     out     source               destination                                                                                         
> 
> Chain POSTROUTING (policy ACCEPT 1068 packets, 65085 bytes)
>  pkts bytes target     prot opt in     out     source               destination                                                                                         
> 
> Chain OUTPUT (policy ACCEPT 1069 packets, 66585 bytes)
>  pkts bytes target     prot opt in     out     source               destination

**Comment by aliweb** [comment]
Also displayed below is ufw status. 29710 is VPN port.

`VM:~$ sudo ufw status verbose`

> Status: active
> Logging: on (low)
> Default: deny (incoming), deny (outgoing), deny (routed)
> New profiles: skip
> 
> To                         Action      From
> --                         ------      ----
> 80                         ALLOW IN    Anywhere
> 29710                      ALLOW IN    Anywhere
> 80 (v6)                    ALLOW IN    Anywhere (v6)
> 29710 (v6)                 ALLOW IN    Anywhere (v6)
> 
> 80                         ALLOW OUT   Anywhere
> 443                        ALLOW OUT   Anywhere
> 21                         ALLOW OUT   Anywhere
> 53                         ALLOW OUT   Anywhere
> 465                        ALLOW OUT   Anywhere
> 587                        ALLOW OUT   Anywhere
> 993                        ALLOW OUT   Anywhere
> 6969                       ALLOW OUT   Anywhere
> 25                         ALLOW OUT   Anywhere
> 80 (v6)                    ALLOW OUT   Anywhere (v6)
> 443 (v6)                   ALLOW OUT   Anywhere (v6)
> 21 (v6)                    ALLOW OUT   Anywhere (v6)
> 53 (v6)                    ALLOW OUT   Anywhere (v6)
> 465 (v6)                   ALLOW OUT   Anywhere (v6)
> 587 (v6)                   ALLOW OUT   Anywhere (v6)
> 993 (v6)                   ALLOW OUT   Anywhere (v6)
> 6969 (v6)                  ALLOW OUT   Anywhere (v6)
> 25 (v6)                    ALLOW OUT   Anywhere (v6)

**Comment by angristan** [comment]
Mmh OK. Can you try to run this command: https://github.com/Angristan/OpenVPN-install/blob/b8f0b44c55861a2805b48f080ac24200648afa35/openvpn-install.sh#L586 (replacing $NIC with your interface)

**Comment by aliweb** [comment]
First I ran the following command to get list of interface. I guess **venet0** is the interface from below.

`VM:~$ ip link show`

> 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT
>     link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
> 2: venet0: <BROADCAST,POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT
>     link/void
> 3: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN mode DEFAULT qlen 100
>     link/none

Then I ran the command you sent but it doesn't do anything. When I run this command, the control returns without any error or success message.

`VM:~$ sudo iptables -t nat -A POSTROUTING -o venet0 -s 10.8.0.0/24 -j MASQUERADE`

> VM:~$

**Comment by angristan** [comment]
Indeed it is venet0.

Yes, the command doesn't return anything, it just enables NAT.

You should see it by running `sudo iptables -t nat -L -n -v`.

But most importantly, do you have access to the internet via the VPN now?

**Comment by aliweb** [comment]
No internet access. It is same as before.

Here's the result of that command.

`VM:~$ sudo iptables -t nat -L -n -v`

> Chain PREROUTING (policy ACCEPT 1017 packets, 52777 bytes)
>  pkts bytes target     prot opt in     out     source               destination                                                                                         
> 
> Chain POSTROUTING (policy ACCEPT 0 packets, 0 bytes)
>  pkts bytes target     prot opt in     out     source               destination                                                                                         
>    46  8574 MASQUERADE  all  --  *      venet0  10.8.0.0/24          0.0.0.0/0                                                                                          
>     0     0 MASQUERADE  all  --  *      venet0  10.8.0.0/24          0.0.0.0/0                                                                                          
>     0     0 MASQUERADE  all  --  *      venet0  10.8.0.0/24          0.0.0.0/0                                                                                          
>     0     0 MASQUERADE  all  --  *      tun0    10.8.0.0/24          0.0.0.0/0                                                                                          
> 
> Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
>  pkts bytes target     prot opt in     out     source               destination

**Comment by aliweb** [comment]
I have another VPS from some other provider. I will try it on that one and post results here.

**Comment by angristan** [comment]
Your NAT table now contains too much rules. Reboot, look at `sudo iptables -t nat -L -n -v`, if there is nothing do `sudo iptables -t nat -A POSTROUTING -o venet0 -s 10.8.0.0/24 -j MASQUERADE`

**Comment by aliweb** [comment]
I fired up new Debian 9 based VPS and it has something similar problem. After connecting to VPN, I was only able to open google.com and bing.com. No other website opens. In fact bing.com didn't open in first try and I had to refresh a couple of times to open.
This is very strange.

**Comment by tsunamaru** [comment]
I just encountered a simular problem. Brand new VPS, Ubuntu 16.04.4, OpenVZ
```
[~] root@2ch-riga > uname -a
Linux 2ch-riga 2.6.32-042stab127.2 #1 SMP Thu Jan 4 16:41:44 MSK 2018 x86_64 x86_64 x86_64 GNU/Linux
```

I also found out that the **tun0** interface dropping many packets:
```
[~] root@2ch-riga > ifconfig
lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:89793 errors:0 dropped:0 overruns:0 frame:0
          TX packets:89793 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:506057991 (506.0 MB)  TX bytes:506057991 (506.0 MB)

tun0      Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  
          inet addr:10.8.0.1  P-t-P:10.8.0.1  Mask:255.255.255.0
          inet6 addr: fd5e:81fc:9ab8:a893::1/64 Scope:Global
          UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1500  Metric:1
          RX packets:194432 errors:0 dropped:0 overruns:0 frame:0
          TX packets:291679 errors:0 dropped:27147 overruns:0 carrier:0
          collisions:0 txqueuelen:100 
          RX bytes:12492743 (12.4 MB)  TX bytes:394924065 (394.9 MB)

venet0    Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  
          inet addr:127.0.0.2  P-t-P:127.0.0.2  Bcast:0.0.0.0  Mask:255.255.255.255
          inet6 addr: <my_public_ipv6_here> Scope:Global
          UP BROADCAST POINTOPOINT RUNNING NOARP  MTU:1500  Metric:1
          RX packets:2217729 errors:0 dropped:0 overruns:0 frame:0
          TX packets:2086680 errors:0 dropped:33 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:2035351009 (2.0 GB)  TX bytes:1994498994 (1.9 GB)

venet0:0  Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  
          inet addr:<my_public_ipv4_here>  P-t-P:<my_public_ipv4_here>  Bcast:<my_public_ipv4_here>  Mask:255.255.255.255
          UP BROADCAST POINTOPOINT RUNNING NOARP  MTU:1500  Metric:1

```

When client connecting, i can see his IP addr in management console on server, but from client side internet doesn't work at all, or working with very high latency. By looking through the parameters in the client configuration, I found out that in some cases, commenting line `setenv opt block-outside-dns` will increase the performance, but it does not always work.

P.S.: Sorry for my bad English.

**Comment by paz** [comment]
Having a similar issue.
Using the generated client config, and cloudflare dns, on an internet connection on both sides that is unrestricted.
- disabled all firewalls (ufw, iptables,)
still nothing.

connects successfully, but then no internet access.
additionally, when trying to connect initially it wouldn't work until I disabled ufw. maybe the commands to set the rules in the script are incorrect?

**Comment by 07stuntar1** [comment]
Did you try setting the /etc/default/ufw to 
UFW DEFAULT_FORWARD_POLICY="ACCEPT"

mine was on "DROP" and I had the same problem..

**Comment by aliweb** [comment]
I changed it to ACCEPT from DROP but the issue remains the same.

**Comment by nikhilmozika** [comment]
Same issue:

Command - iptables -t nat -L -n -v

```
Chain PREROUTING (policy ACCEPT 297 packets, 19283 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain INPUT (policy ACCEPT 6 packets, 416 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 13 packets, 1079 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain POSTROUTING (policy ACCEPT 13 packets, 1079 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 MASQUERADE  all  --  *      eth0    10.8.0.0/24          0.0.0.0/0           

Chain DOCKER (0 references)
 pkts bytes target     prot opt in     out     source               destination        
```

ufw is disabled, can anyone guide me towards the right path!

```
root@ip-172-26-0-107:/# uname -a
Linux ip-172-26-0-107 4.4.0-1062-aws #71-Ubuntu SMP Fri Jun 15 10:07:39 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
root@ip-172-26-0-107:/# ifconfig
docker0   Link encap:Ethernet  HWaddr 02:42:41:c7:ee:24  
          inet addr:172.17.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

eth0      Link encap:Ethernet  HWaddr 02:fe:5b:da:a8:00  
          inet addr:172.26.0.107  Bcast:172.26.15.255  Mask:255.255.240.0
          inet6 addr: fe80::fe:5bff:feda:a800/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:3028019 errors:0 dropped:0 overruns:0 frame:0
          TX packets:4792952 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:2664639370 (2.6 GB)  TX bytes:5555444152 (5.5 GB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:148962 errors:0 dropped:0 overruns:0 frame:0
          TX packets:148962 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1 
          RX bytes:148349778 (148.3 MB)  TX bytes:148349778 (148.3 MB)

tun0      Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  
          inet addr:10.8.0.1  P-t-P:10.8.0.1  Mask:255.255.255.0
          UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1500  Metric:1
          RX packets:2825 errors:0 dropped:0 overruns:0 frame:0
          TX packets:5 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:100 
          RX bytes:185264 (185.2 KB)  TX bytes:80 (80.0 B)

```

**Comment by nikhilmozika** [comment]
Simply did a uninstall & reinstall VPN works again though this took me 20 mins but worth it.

The difference I note is in the iptables:

```
Chain POSTROUTING (policy ACCEPT 237 packets, 14674 bytes)
 pkts bytes target     prot opt in     out     source               destination         
  955 77405 MASQUERADE  all  --  *      eth0    10.0.0.0/8           0.0.0.0/0           
  470 32597 MASQUERADE  all  --  *      eth0    0.0.0.0/0            0.0.0.0/0           
    0     0 MASQUERADE  all  --  *      eth0    10.8.0.0/24          0.0.0.0/0    
```       

This is what the command shows now instead of this earlier:

```
Chain POSTROUTING (policy ACCEPT 13 packets, 1079 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 MASQUERADE  all  --  *      eth0    10.8.0.0/24          0.0.0.0/0  
```

Hope this may sort out the issues.

**Comment by aliweb** [comment]
It seems the issue is related to Debian 9 only because today I installed it on Debian 8 and VPN worked perfectly.

**Comment by Snake16547** [comment]
same problem here on debian 9

**Comment by MrHash** [comment]
Also having this problem on RPI3 Debian 9. Worked before reboot.

**Comment by MrHash** [comment]
https://github.com/Angristan/OpenVPN-install/issues/237#issuecomment-398919259 worked for me

**Comment by angristan** [comment]
Duplicate of https://github.com/angristan/openvpn-install/issues/233

Fixed with https://github.com/angristan/openvpn-install/pull/291
