### ISSUE TITLE
How to change subnet mask or route from 10.1.1.1/32 to 10.1.1.1/24

### ISSUE THREAD

**Issue by umeshuday95** [angristan/openvpn-install#239]
hello guys 
every thing is set up in RASPBERRY pi openvpn
client is able to connect to open vpn server
-connected through my pc and my mobile to RASPBERRY pi
(the only problem is that internet is not working after the connection is established on client side)

IN RASPBERRYPI
(User is able to ping www.google.com)

192.168.1.85/32 and if the route is 32 user is not able to ping
192.168.1.85/24 and if the route is 24 user is  able to ping

**Comment by umeshuday95** [comment]
pi as server at 192.168.1.85
my Pc as client 192.168.1.99

MY PC LOG
===========================================================
Mon Jun 11 06:59:27 2018 do_ifconfig, tt->did_ifconfig_ipv6_setup=0
Mon Jun 11 06:59:27 2018 /sbin/ip link set dev tun0 up mtu 1500
Mon Jun 11 06:59:27 2018 /sbin/ip addr add dev tun0 10.8.0.3/24 broadcast 10.8.0.255
**Mon Jun 11 06:59:27 2018 /sbin/ip route add 192.168.1.85/32 dev ens192**
Mon Jun 11 06:59:27 2018 /sbin/ip route add 0.0.0.0/1 via 10.8.0.1
Mon Jun 11 06:59:27 2018 /sbin/ip route add 128.0.0.0/1 via 10.8.0.1
Mon Jun 11 06:59:27 2018 Initialization Sequence Completed



NEED TO CHANGE  TO  192.168.1.85/32  to  192.168.1.85/24
Mon Jun 11 06:59:27 2018 /sbin/ip route add 192.168.1.85/24 dev ens192



AND UR NEW VPN FILE IS NOT WORKING  EVEN FOR SETTING UP VPN I HAVE USED UR OLD VPN SCRIPT
MY SYSTEM _FEDORA 27 XFCE
AND IN MY OFFICE CYBERoAm FILEWALL IS THERE 
AND I NEED TO LOGIN FOR ACCESSING INTERNET

**Comment by angristan** [comment]
Change netmask on the server at `/etc/openvpn/server.conf` on the `server` line
