### ISSUE TITLE
IPv6 Support?

### ISSUE THREAD

**Issue by rhbkweb** [angristan/openvpn-install#24]
Hi. Is IPv6 supported? I have a VPS with 1 IPv4 + 1IPv6. Should I also use the IPv6 with the VPN or disable it? Thanks

**Comment by angristan** [comment]
Hi, IPv6 is not yet supported and will probably never be, because of the many IPv6 configurations out there. As for now I don't have the time or knowledge to implement it, so unless there is a PR, don't wait for IPv6 :)
