### ISSUE TITLE
Password protected key

### ISSUE THREAD

**Issue by freeroute** [angristan/openvpn-install#240]
I successfully installed in a VPS server this VPN service. 
It works. Thanks the script.
Is it possible to protect the login session with password? I mean when I connect from my Android mobile phone to the VPN, its not required to enter a password.
I use also free vpnbook service. When I try to connect,  I have to type a password to access the VPN server.

Thanks

**Comment by angristan** [comment]
https://github.com/Angristan/OpenVPN-install/pull/160
