### ISSUE TITLE
Slow VPN Speed

### ISSUE THREAD

**Issue by rhbkweb** [angristan/openvpn-install#241]
Hi @Angristan and all others,

I'm having speed issues. Tryed to add the @biffalo advice at: https://github.com/Angristan/OpenVPN-install/issues/31 by adding the following lines to the opvn client file and it help a lot, but speed is still slow.

sndbuf `393216
rcvbuf 393216
push "sndbuf 393216"
push "rcvbuf 393216"

Before adding the lines I could not get more than 10Mbps and now Im able to get 20Mbps average. But this is still slow, since I have a internet connection of 200Mbps and I tested my VPS download speed that is around 70Mbps.

VPN is installed on a new and clean Debian 9 64bit VPS server. Anyone has any advice or suggestion?

Thanks

**Comment by Alphabc** [comment]
Did you do it on your server config file as well? (and restart your vpn, of course)
see  https://winaero.com/blog/speed-up-openvpn-and-get-faster-speed-over-its-channel/
Works on my side (100 Mbps wifi card, vpn connexion at 40Mbps instead of 2 before the config changes)
Cheers

**Comment by rhbkweb** [comment]
Hi @Alphabc 

Thanks for the advice. I have edit the /etc/openvpn/server.conf on the server by adding the following lines at the end, but the results are still the same. I have tryied multiple ways with the same config on both client and server file. 

sndbuf 393216
rcvbuf 393216
push "sndbuf 393216"
push "rcvbuf 393216"
tun-mtu 1400 (I have also tried without this line)
mssfix 1360 (I have also tried without this line)

One strange thing I noticed is that the VPN is fast on a old Thinkpad X201 laptop, but on my recent and more powerfull Thinkpad T430 and also on my Android phone the VPN is slow. So it seems the issue is on client side on some devices. Any ideas?

Thanks!

**Comment by iandk** [comment]
Same problem here

**Comment by angristan** [comment]
Feel free to discuss speed issues here or in #31, but this is likely not related to the script

**Comment by CHazz** [comment]
same problem here .. without encryption is still slow
cpu usage on both device < 10%
network usage < 50%
