### ISSUE TITLE
Creating local only clients

### ISSUE THREAD

**Issue by tanja84dk** [angristan/openvpn-install#244]
Are there a way to create a client there is able to talk to the others on the vpn but dont route all its trafic over the vpn ( like not getting its default gateway changed )

**Comment by angristan** [comment]
You can remove `push "redirect-gateway def1 bypass-dhcp"` from the server conf and add it to the client configs on a per client basis.

**Comment by tanja84dk** [comment]
Unfortunally that is not working here is the server.conf where you see that I have commented out dns and dhcp and the server has been restarted just in case but for some reason my linux laptop is still routing the internet even that I dont want it to do it

port 1194
proto udp
dev tun
user nobody
group nogroup
persist-key
persist-tun
keepalive 10 120
topology subnet
server 10.8.0.0 255.255.255.0
ifconfig-pool-persist ipp.txt
#push "dhcp-option DNS 8.8.8.8"
#push "dhcp-option DNS 8.8.4.4"
#push "redirect-gateway def1 bypass-dhcp" 
crl-verify crl.pem
ca ca.crt
cert server_O1mcqOSz7fghHAJr.crt
key server_O1mcqOSz7fghHAJr.key
tls-auth tls-auth.key 0
dh dh.pem
auth SHA256
cipher AES-128-CBC
tls-server
tls-version-min 1.2
tls-cipher TLS-DHE-RSA-WITH-AES-128-GCM-SHA256
status openvpn.log
verb 3

**Comment by cezar97** [comment]
As I agree with Angristan solution and the configs seems good, are you sure ipleak.net shows your VPN server IP?

**Comment by tanja84dk** [comment]
Yes Its detecting the vpn server. I have even tested route -n and noticed it still pushes the routes to the client. And both the server and client have been rebooted just in case after the changes on the server config. Btw the client is a old macbook still called it but running xubuntu

┌─[tanja@macbook]─[~]
└──╼ $route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         0.0.0.0         0.0.0.0         U     50     0        0 tun0
0.0.0.0         192.168.1.1     0.0.0.0         UG    600    0        0 wlp2s0
10.8.0.0        0.0.0.0         255.255.255.0   U     50     0        0 tun0
139.162.216.106 192.168.1.1     255.255.255.255 UGH   600    0        0 wlp2s0
169.254.0.0     0.0.0.0         255.255.0.0     U     1000   0        0 wlp2s0
192.168.0.0     0.0.0.0         255.255.252.0   U     600    0        0 wlp2s0
192.168.1.1     0.0.0.0         255.255.255.255 UH    600    0        0 wlp2s0

**Comment by tanja84dk** [comment]
Here is a screenshoot from route -n just to make it easier to see the output formatted
[https://cloud.tanja84.dk/index.php/s/XyOMYKqb1c81GF7](https://cloud.tanja84.dk/index.php/s/XyOMYKqb1c81GF7)

**Comment by cezar97** [comment]
Not sure...
BTW here I see the same thing as suggested https://www.digitalocean.com/community/tutorials/how-to-set-up-an-openvpn-server-on-ubuntu-18-04.

**Comment by tanja84dk** [comment]
Yeah I could easily set it up from scratch and get it to work. But the reason I hoped Angristan could help was because then I would have a easy way create and revoke certificates. But yeah I guess the only way is then to set it up from scratch myself

**Comment by angristan** [comment]
Weird that it's still pushing the routes :(
