### ISSUE TITLE
Pages fail to load and some pings fail.

### ISSUE THREAD

**Issue by HarvsG** [angristan/openvpn-install#245]
I recently had an issue when connecting from a new WiFi network, I had had the same issue when connecting _to_ a VPN on this network and so I thought I'd give the same solution a try and it worked.
https://github.com/pivpn/pivpn/issues/54
Adding this to the bottom of `/etc/openvpn/server.conf` fixed the issue:
```
tun-mtu 1400
mssfix 1360
```
It seems this may be a router/network specific issue?

My symptoms were:

- Pages fail to load, in the background they just load very slowly.
- Some pings to outside world fail
- Connects to VPN absolutely fine.

[This website](https://www.sonassi.com/help/troubleshooting/setting-correct-mtu-for-openvpn) seems to describe the issue well. I have noted that the currently set (and optimum) MTU size on this problematic network is 1432.

Edit: [This discussion](https://blog.hambier.lu/post/solving-openvpn-mtu-issues) is even better.

**Comment by HarvsG** [comment]
Note when using these changes, these warning pop up in the connection logs:
```
Tue Jul 03 23:41:41 2018 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1569', remote='link-mtu 1469'
Tue Jul 03 23:41:41 2018 WARNING: 'tun-mtu' is used inconsistently, local='tun-mtu 1500', remote='tun-mtu 1400'
```
Which is strange because I can't find any other MTU settings in the `server.conf` or client configs.

**Comment by angristan** [comment]
Thanks for sharing!
