### ISSUE TITLE
How to generate ovpn file for OpenVPN Connect on IOS? 

### ISSUE THREAD

**Issue by AntonP1337** [angristan/openvpn-install#250]
Id like to generate a profile that's protected with  a passhprase but I have been unable to get it to work on OpenVPN connect on iOS - has anyone else been able to do this?

**Comment by cezar97** [comment]
I don't have much information so I'll just paste you the faq https://docs.openvpn.net/connecting/connecting-to-access-server-with-apple-ios/faq-regarding-openvpn-connect-ios/.

**Comment by angristan** [comment]
The feature is now available in the script : https://github.com/Angristan/OpenVPN-install/pull/160
