### ISSUE TITLE
Enhancement - Create a version of the script that doesn't have encryption

### ISSUE THREAD

**Issue by throwaway4960** [angristan/openvpn-install#252]
Could you create a version of the script that doesn't have the encryption bits and just fixes the location and ISP leak issues of Nyr/OpenVPN-install

**Comment by cezar97** [comment]
It's out of scope. But here's the solution https://openvpn.net/archive/openvpn-users/2006-06/msg00145.html.

**Comment by angristan** [comment]
Yeah that would be pretty weird to have this option in the script 🙄.
