### ISSUE TITLE
Add a "switch DNS" menu entry (after setup)

### ISSUE THREAD

**Issue by hunterpl** [angristan/openvpn-install#253]
Hello,

Can you add option in menu like " switch dns " for switching to another DNS custom or build in menu from start up?

Best Regards
Mateusz

**Comment by cezar97** [comment]
There was a PR for that #208. But the contributor is opening another one in the next days.

**Comment by angristan** [comment]
There are 2 different things:

- Custom DNS upon setup
- Switching DNS after setup

**Comment by angristan** [comment]
See #258

**Comment by angristan** [comment]
Modifying `/etc/openvpn/server.conf` is simpler tbh.
