### ISSUE TITLE
Client configuration with Windows 10

### ISSUE THREAD

**Issue by knowhowseeker** [angristan/openvpn-install#255]
I had a VPN in Windows running with a Commercial VPN Provider. Now I used the script to run my own VPN-Server. The Servers seems to be running. My understanding is now, that I can use the same Client.ovpn on the Client to start up the VPN. I tried that in Windows 10 and failed. 
Thanks for some help.
![report_w10](https://user-images.githubusercontent.com/41070573/42645830-57093708-85ff-11e8-88b0-6cbc2bd5cb1f.PNG)

**Comment by HirbodBehnam** [comment]
Have you tried TCP and 443 port?

**Comment by knowhowseeker** [comment]
Sorry my fault. I used an LXC Container and there I cannot setup an openvpn. I changed to a root server and erverthing works.

**Comment by angristan** [comment]
Thanks for the feedback
