### ISSUE TITLE
How to use the latest release of OpenVPN(2.4.6)?

### ISSUE THREAD

**Issue by nxtreaming** [angristan/openvpn-install#257]
I installed OpenVPN by your great script in Ubuntu 16.04 LTS, but I found the installed OpenVPN is 2.3.10 which is released in 2016

So How to use the latest release OpenVPN in your script?

Thanks.

**Comment by cezar97** [comment]
Use the script from 2.4-update branch ( https://github.com/Angristan/OpenVPN-install/raw/openvpn-2.4-update/openvpn-install.sh ), that adds an external repo with openvpn 2.4 and also has options for 2.4 only like elliptic curves and LZ4. It's a bit outdated regarding features merged on master, but there's a PR ( #246 ) for that.

**Comment by angristan** [comment]
See https://community.openvpn.net/openvpn/wiki/OpenvpnSoftwareRepos to update your repo and use 2.4.6. As @cezar97 said, new features brought by OpenVPN 2.4 are the subject of another PR.
