### ISSUE TITLE
Fully automatic installation (without user input)

### ISSUE THREAD

**Issue by sayem314** [angristan/openvpn-install#261]
Update codes to support advanced/automatic installation. This step will reduce the time of installation for the users that install very often. This will suppress any prompts as part of automatic installation process.

Here is an example how it will be done:

    auto=yes ./openvpn-install.sh

And all the default values will be used for installation process. Also I will add the ability to add custom option too!

**Comment by sayem314** [comment]
@Angristan are you interested to see this?

**Comment by angristan** [comment]
Yes I'm interested, although I've considered this out-of-scope until now... 

If this is added to the script it has to be clean, maintainable and not add bloat.

This is not my priority, but if a PR is made I'll consider adding it to the script.

**Comment by sayem314** [comment]
I lost my interest over the month.

/s

**Comment by cliffcotino** [comment]
I created a pull request to be able to support this #390

**Comment by angristan** [comment]
I merged the PR made by @cliffcotino. It was easier than expected :)

**Comment by angristan** [comment]
I think it would be even better to be able to do:

```sh
export AUTO_INSTALL=y
./openvpn-install.sh
```

And then a simple condition a the beginning of the script would set all these variables for us (in place of the manual exports)

**Comment by angristan** [comment]
Note that password-protected clients are not supported by this, because of easy-rsa. I have not found a workaround for this.

**Comment by luizluca** [comment]
easyrsa can now accept passwords as arguments:
https://github.com/OpenVPN/easy-rsa/commit/c794d5ebaae7ec911e638a4f2c21137a3fb5ec9c
