### ISSUE TITLE
Script masks and uninstalls firewalld and then enables iptables

### ISSUE THREAD

**Issue by catatung** [angristan/openvpn-install#263]
Hello,

I've used your script on Fedora 28.  It works well - but afterwards I had noticed firewalld had been masked and disabled.  Iptables was enabled and running instead.

After the script was completed and everything was working correctly, I disabled iptables and then unmasked firewalld and re-enabled it.  Everything seems to still work correctly -- however I wanted to ask if there is anything I should be looking out for, any problems doing this may cause? 

Thanks

**Comment by angristan** [comment]
Hello, thanks for the feedback!

I was wondering this when the support for fedora was added: https://github.com/Angristan/OpenVPN-install/pull/134#issuecomment-352185405

I will test on Fedora to see if firewalld causes issues.

**Comment by angristan** [comment]
Unmasking and enabling firewalld don't cause any issue, indeed. But when you start it (or reboot the server), the trafic is blocked.
