### ISSUE TITLE
Multiple configurations

### ISSUE THREAD

**Issue by liveinno** [angristan/openvpn-install#266]
How to make multiple configurations with different ports?
When opening ыр, the question is only about adding new certificates or deleting. Thank you
![default](https://user-images.githubusercontent.com/29046741/43359133-32164d24-92a6-11e8-84a7-c3cb3145b51c.png)
https://camo.githubusercontent.com/be9e09731aa2b72418a4522ca0a6594356e843b6/68747470733a2f2f692e696d6775722e636f6d2f416c57396737742e706e67

**Comment by cezar97** [comment]
See #28.

**Comment by liveinno** [comment]
Hello!
Solution 28 does not work!
I made two different configurations, on different ports and different protocols

```
 tcp        0      0 0.0.0.0:3201            0.0.0.0:*               LISTEN      3555/openvpn        
udp        0      0 0.0.0.0:3200            0.0.0.0:*                           7736/openvpn   
```

I changed the IP address in the configuration:
```
server1.conf
port 3201
proto tcp
server 10.8.1.0 255.255.255.0

server2.conf
port 3200
proto udp
server 10.8.3.0 255.255.255.0

```

I connected to server1.conf configuration, everything worked. all perfectly

Then I tried to connect to the server2.conf configuration, and got errors:

```
Aug  2 11:32:27 localhost openvpn: Thu Aug  2 11:32:27 2018 Authenticate/Decrypt packet error: packet HMAC authentication failed
Aug  2 11:32:27 localhost openvpn: Thu Aug  2 11:32:27 2018 TLS Error: incoming packet authentication failed from [AF_INET]11.12.13.14:49445
Aug  2 11:32:29 localhost openvpn: Thu Aug  2 11:32:29 2018 Authenticate/Decrypt packet error: packet HMAC authentication failed
Aug  2 11:32:29 localhost openvpn: Thu Aug  2 11:32:29 2018 TLS Error: incoming packet authentication failed from [AF_INET]11.12.13.14:49445
Aug  2 11:32:34 localhost openvpn: Thu Aug  2 11:32:34 2018 Authenticate/Decrypt packet error: packet HMAC authentication failed
Aug  2 11:32:34 localhost openvpn: Thu Aug  2 11:32:34 2018 TLS Error: incoming packet authentication failed from [AF_INET]11.12.13.14:49445
Aug  2 11:32:41 localhost openvpn: Thu Aug  2 11:32:41 2018 Authenticate/Decrypt packet error: packet HMAC authentication failed
Aug  2 11:32:41 localhost openvpn: Thu Aug  2 11:32:41 2018 TLS Error: incoming packet authentication failed from [AF_INET]11.12.13.14:49445
```

I looked at the script  https://github.com/Angristan/OpenVPN-install/blob/master/openvpn-install.sh : 

```
# Create the PKI, set up the CA, the DH params and the server + client certificates
	./easyrsa init-pki
	./easyrsa --batch build-ca nopass
	openssl dhparam -out dh.pem $DH_KEY_SIZE
	./easyrsa build-server-full $SERVER_NAME nopass
	./easyrsa build-client-full $CLIENT nopass
	EASYRSA_CRL_DAYS=3650 ./easyrsa gen-crl
	# generate tls-auth key
openvpn --genkey --secret /etc/openvpn/tls-auth.key
```

I do not understand so well at openvpn. But it seemed to me that the script generates each time a new dh.pem.

I have a question:
Openvpn for different configurations(multiple conf) can use one dh.pem tls-auth.key ?

**Comment by angristan** [comment]
This is currently not supported (#28)

**Comment by butaford** [comment]
http://thomas.gouverneur.name/2014/02/openvpn-listen-on-tcp-and-udp-with-tun/
cp server.conf server2.conf and edit
