### ISSUE TITLE
Anyone know how to setup automatically assigned IP, this IP is not used for VPN connections

### ISSUE THREAD

**Issue by nanedi** [angristan/openvpn-install#270]
Anyone know how to setup automatically assigned IP, this IP is not used for VPN connections?

OpenVPN IP 192.168.1.1 -> (connection) -> get 192.168.100.1 to Public IP -> Internet

**Comment by angristan** [comment]
Sorry, I don't understand.

**Comment by nanedi** [comment]
Some like VyprVPN Purevpn, if you already have connected OpenVPN, so it will assign you a different IP.

OpenVPN IP 192.168.1.1 -> (connected VPN) -> assign 192.168.100.1 to you -> Internet

**Comment by angristan** [comment]
If I understand correctly, you want to have a different IP address than the server's.

This is out of scope.

**Comment by nanedi** [comment]
yes
