### ISSUE TITLE
Restrict hosts for users.

### ISSUE THREAD

**Issue by alexpantyukhin** [angristan/openvpn-install#272]
I'm not sure that this is the correct place to ask this question, but I already despaired to find the answer :). 

For example. I have some *.ovpn and I want to map some .ovpn to allowed hosts which could be available using this *.ovpn. In other words I would like to restrict addresses (host names) for some .ovpn s .

**Comment by angristan** [comment]
You can try to do this with your firewall with the help of the clients' (.ovpn) local IP addresses, using them as "source" in your rules... Good luck
