### ISSUE TITLE
How do I view logs?

### ISSUE THREAD

**Issue by ishmumx** [angristan/openvpn-install#273]
Just want to have a little file that shows who connected from what IP and what time. That is all. Thank you!

**Comment by ishmumx** [comment]
Found out how to to it! Edit /etc/openvpn/server.conf and add the last line

![Found out how to to it! Edit /etc/openvpn/server.conf and add the last line](https://i.imgur.com/Tw60a4p.png)

**Comment by angristan** [comment]
Thanks for the issue, added here: https://github.com/Angristan/OpenVPN-install/commit/d8d0bbb5dad57efd0b962d46bdaa7d0ed6319c85

**Comment by waynehoover** [comment]
@angristan Isn't logging an anti-feature? Maybe it would be best to ask the user if they want logs or not. 

To disable logging is pretty easy though: `rm /var/log/openvpn/status.log && ln -s /dev/null /var/log/openvpn/status.log`

**Comment by angristan** [comment]
Since you're in control of your server, logs should be fine.
