### ISSUE TITLE
net.ipv4.ip_forward = 1

### ISSUE THREAD

**Issue by LeVuHoang** [angristan/openvpn-install#274]
Hi all,

FYI.

I upgraded to Ubuntu 18.4 last week and found an issue today.

People can connect to VPN server but can't ping local servers. 

I found ip_forward in /etc/sysctl.conf is commented.

Therefore, if you can't ping/connect to local network, try to check /etc/sysctl.conf
`net.ipv4.ip_forward = 1`

**Comment by angristan** [comment]
It should be enabled by the script. https://github.com/Angristan/OpenVPN-install/blob/master/openvpn-install.sh#L648

**Comment by DrXala** [comment]
Hi @LeVuHoang 

I guess it's your update that changed the system setting.

**Comment by LeVuHoang** [comment]
Yes, I think the upgrade from old version to 18.04 changed the system setting.

I takes me a while to find out, so I put it here to save time for all who has a same issue.
