### ISSUE TITLE
log-append prevents OpenVPN from starting

### ISSUE THREAD

**Issue by loadcorp** [angristan/openvpn-install#275]
Yesterday when I used your installer all was been allright, even today in morning.

But after you last update (about 2 hours ago) something goes wrong and now any generated client.ovpn not working in any devices.

Tell me please, what did you change in your last update?

I am using this script on Debian 9 /x64.

**Comment by loadcorp** [comment]
I founded the problem.

In some reason this 2 lines was been the problem:
'
status /var/log/openvpn/status.log
log-append /var/log/openvpn/server.log
'

I deleted them and all is working now correctly again.

**Comment by angristan** [comment]
Thanks I will check right now

**Comment by angristan** [comment]
Should be fixed for now. I don't understand how `log-append` worked for me when I tested.

**Comment by loadcorp** [comment]
Thank you very much for your fix! Now all working correct.

If you interested in how did I found this bug, you can do this steps:

1. Create Droplet in Vultr.com with Debian 9x64 (RAM: 1024 MB - in future of course I will increase, but not now).
2. In installation process choose this:
Port: 443
Diffie-Hellman: 1
RSA key: 1
(all others by default)

Maybe this steps will help to find out what is the problem.

**Comment by angristan** [comment]
It's ok, I tested and could reproduce the issue
