### ISSUE TITLE
Passwords may cached in memory

### ISSUE THREAD

**Issue by timberd00dle5** [angristan/openvpn-install#277]
The script creates a client file which causes the following warning on my Android phone:

WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this

As the warning suggests, adding 'auth-nocache' to the config helps me getting rid of the warning.

Do others get the same warning as well? And if so, should 'auth-nocache' be added to every config by the script?

**Comment by billyprice1old** [comment]
Yea i get that warning it's fine

**Comment by angristan** [comment]
Weird, since we added it here: https://github.com/angristan/openvpn-install/pull/92

Do you have `auth nocache` in your config file?

**Comment by angristan** [comment]
Also, can someone confirm they also have the warning?

**Comment by iProdigy** [comment]
Not an issue on our end. The config properly includes the option, the Android app simply doesn't parse it from the config. This is documented here: https://github.com/schwabe/ics-openvpn/issues/935

To fix the issue, the user must click on edit config, go to the advanced tab, edit custom options, and add auth-nocache.

**Comment by angristan** [comment]
Thanks @iProdigy!
