### ISSUE TITLE
DNS local resolver and DNS TLS

### ISSUE THREAD

**Issue by yunti** [angristan/openvpn-install#278]
Sorry if this has been mentioned before (but I couldn't find it in the issue log).  The readme mentions that a local dns server `Soon : local resolver :D` is coming.  Is this https://github.com/Angristan/Local-DNS-resolver and is currently included in the script and the readme is just not updated? (it's hard to tell from https://github.com/angristan/openvpn-install/issues/5 what was concluded.

Will this include DNS over TLS or is that made redundant as it's directly using DNSSEC? (Note unbound server does mention it used DNS over TLS.

**Comment by genayaku** [comment]
Is local resolver included in initial installation? I did not see that in menu options. Please, advise

**Comment by angristan** [comment]
This is not yet implemented.

**Comment by yunti** [comment]
Thanks for confirming
