### ISSUE TITLE
Running two servers with different configuration

### ISSUE THREAD

**Issue by PitStains** [angristan/openvpn-install#28]
Hello,
I'm wondering you could have 2 server keys. 
I'd like to have 1 client be on a fast, less-secure, UDP connection.
And I'd like to have 1 client be on a most-secure, TCP connection.

I'm not sure if this is even possible on the same OpenVPN server?? I know you can edit the .ovpn client file, but that wouldn't have the secure-ness of the server key.

**Comment by angristan** [comment]
I would like that too. I know it's possible, so I keep this open.

**Comment by PitStains** [comment]
Cool thanks!
I wonder if I just rename all the /etc/openvpn folder and run the script again, and then merge the files? Or is it more involved in getting the server to accept 2 simultaneous connections. I've seen people on the Stack say they've accomplished this scenario, but haven't seen how.

**Comment by PitStains** [comment]
On openvpn.net: https://openvpn.net/index.php/open-source/documentation/howto.html

>  If you want to run multiple OpenVPN instances on the same machine, each using a different configuration file, it is possible if you:
>     Use a different port number for each instance (the UDP and TCP protocols use different port spaces so you can run one daemon listening on UDP-1194 and another on TCP-1194).
>     If you are using Windows, each OpenVPN configuration taneeds to have its own TAP-Windows adapter. You can add additional adapters by going to Start Menu -> All Programs -> TAP-Windows -> Add a new TAP-Windows virtual ethernet adapter.
>     If you are running multiple OpenVPN instances out of the same directory, make sure to edit directives which create output files so that multiple instances do not overwrite each other's output files. These directives include log, log-append, status, and ifconfig-pool-persist.
>

**Comment by actuallymentor** [comment]
AFAIK you just need to set up 2 servers. In the case of this script you need to run it twice. Once for your fast UDP and once for your secure TCP.

This should produce 2 server configs, and 2 client configs.

You wil still only have one openvpn package installed, but it will be listening on multiple ports the same way nginx might run multiple website from multiple configs.

**Comment by paccerdk** [comment]
This should normally work out of the box (at least for systemd based distributions) when having different configuration files in /etc/openvpn/*.conf

The following line breaks this functionality and hard-codes all service instances to use server.conf only:
https://github.com/Angristan/OpenVPN-install/blob/f681c0bd3426cc0f825345d483a283da537d34d2/openvpn-install.sh#L621

Is this strictly necessary for the script? if not, it should be removed.

Manually changing server.conf back to %i.conf in /lib/systemd/system/openvpn\@.service fixes support for multiple instances

**Comment by angristan** [comment]
Wow indeed, @paccerdk, thanks.

```
root@server:~# netstat -paunt | grep openvpn
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      841/openvpn
udp        0      0 0.0.0.0:1194            0.0.0.0:*                           850/openvpn

root@server:~# ps ffaux | grep openvpn
root      1088  0.0  0.0  12784   948 pts/0    S+   11:51   0:00          \_ grep openvpn
nobody     841  0.0  0.5  48144  5640 ?        Ss   11:48   0:00 /usr/sbin/openvpn --daemon ovpn-server2 --status /run/openvpn/server2.status 10 --cd /etc/openvpn --config /e
tc/openvpn/server2.conf --writepid /run/openvpn/server2.pid
nobody     850  0.0  0.5  48144  5524 ?        Ss   11:48   0:00 /usr/sbin/openvpn --daemon ovpn-server3 --status /run/openvpn/server3.status 10 --cd /etc/openvpn --config /e
tc/openvpn/server3.conf --writepid /run/openvpn/server3.pid
```

I don't remember why I hardcoded it, I'll take a look.

**Comment by ookangzheng** [comment]
I hardcoded like this 
1. After a clean install with UDP mode
2. clone server.conf into server2.conf (manual edit UDP => TCP mode)
3. in server2.conf, change ip 10.8.0.1 to 10.9.0.1
4. add `10.9.0.1` in IPtables
5. at line 838 or close to it, add 
`sed -i 's|server2.conf' /lib/systemd/system/openvpn/server2.service`
6. `service openvpn@server restart` and `service openvpn@server2 restart`
7. try `lsof -i:1194` your port number, you will see both UDP & TCP openvpn services are running

**Comment by cezar97** [comment]
@ookangzheng why there's the need to hard-code server2? In my opinion instead of point 5, the @paccerdk solution should be used as it's also scalable friendly.

**Comment by ngx3** [comment]
I changed the line: `ExecStart=/usr/sbin/openvpn --daemon ovpn-%i --status /run/openvpn/%i.status 10 --cd /etc/openvpn --script-security 2 --config /etc/openvpn/**server**.conf --writepid /run/openvpn/%i.pid`


$ sudo service openvpn@server restart
Warning: openvpn@server.service changed on disk. Run 'systemctl daemon-reload' to reload units.

**Comment by randshell** [comment]
@angristan this issue is not only about different configuration (ex. running OpenVPN both on TCP and UDP) but also different keys, one more and the other one less secure. Other issues linked, like #266, are only about a different configuration for using multiple ports.

I'm specifying this because managing different keys too requires, eventually, having multiple subdirectories for better management, for example `/etc/openvpn/server1` and `/etc/openvpn/server2`.

So here there should be two options:
- Add new client with different config but same keys.
- Add new client with different config and different keys.

Did I get it right?

**Comment by angristan** [comment]
@randomshell I think you got it right :)

**Comment by randshell** [comment]
So, are we going to support them both?

**Comment by angristan** [comment]
I don't know. It will be hard to install and maintain in both cases. I don't know if it's worth supporting it.

**Comment by angristan** [comment]
I'm reducing the scope of the script because I already spend a lot of time maintaining it.

I'm closing this, until someone implement a **simple and easy-to-maintain** solution, which will likely not happen.

This was a feature I wanted too, but the script is already over 900 lines.

**Comment by paccerdk** [comment]
@angristan, couldn't you remove the line mentioned in my https://github.com/angristan/openvpn-install/issues/28#issuecomment-357861492 ?

I see no reason for the hard coding, and you didn't provide any reason either. (comment after linked one)

This would restore expected OpenVPN functionality at least.

**Comment by angristan** [comment]
See https://github.com/angristan/openvpn-install/pull/294.

**Comment by jam-2000** [comment]
@angristan 
Hi, angristan.

Is it possible to add functionality with openvpn server listen on both UDP and TCP at the same time like this:
https://thomas.gouverneur.name/2014/02/openvpn-listen-on-tcp-and-udp-with-tun/

Thanks for answer)
