### ISSUE TITLE
cat /dev/urandom doesn't work in unprivileged LXC containers (e.g. Proxmox)

### ISSUE THREAD

**Issue by billyprice1old** [angristan/openvpn-install#280]
hi there sometime when i do this on it get stuck at downloading the easyrsa tar.gz file does anyone know why but it work's fine on nyr

**Comment by iProdigy** [comment]
Can you try running:
`wget -O ~/EasyRSA-3.0.4.tgz https://github.com/OpenVPN/easy-rsa/releases/download/v3.0.4/EasyRSA-3.0.4.tgz`

(Nyr's script [falls-back to curl](https://github.com/Nyr/openvpn-install/blob/master/openvpn-install.sh#L229) when wget doesn't work while this script only uses wget. If you aren't able to wget that file, this script will need to include a similar fall back).

**Comment by angristan** [comment]
Hi @billyprice1 are you getting any error?

**Comment by billyprice1old** [comment]
HI there @angristan  i am still getting this issue it just get stuck here https://i.imgur.com/gw6sxbt.png yet on the nyr installer it works

**Comment by angristan** [comment]
Wow that's weird. But I can't say for sure if this is `wget` or a command afterwards.

Can you try executing these few lines by hand and see if you can reproduce the issue ?

https://github.com/angristan/openvpn-install/blob/master/openvpn-install.sh#L533#L547

**Comment by billyprice1old** [comment]
Hmm it don't seem to break there SERVER_CN="cn_$(tr -dc 'a-zA-Z0-9' < /dev/urandom | fold -w 16 | head -n 1)"  is where it stops  and experience the same behavior also  if it helps i am running lxc with proxmox and ubuntu 16.04 it only seem to happen with that like on scaleway etc it works but even on my dedi it happens in lxc

**Comment by angristan** [comment]
Maybe a `/dev/urandom` issue then. Does it exist inside your container?

See https://lists.linuxcontainers.org/pipermail/lxc-users/2015-June/009402.html

**Comment by angristan** [comment]
I found this: https://github.com/QuickBox/QB/issues/50

**Comment by angristan** [comment]
Can you test these 3 commands inside you container:
```sh
tr -dc 'a-zA-Z0-9' < /dev/urandom | fold -w 16 | head -n 1
cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 16 | head -n 1
head /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 16 | head -n 1
```

**Comment by billyprice1old** [comment]
head /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 16 | head -n 1 this command run but the other 2 does not

**Comment by angristan** [comment]
OK. What kind of output does it give you ? A random alphanumeric string?

If it does, I will update the script to address your use case.

**Comment by billyprice1old** [comment]
It gives me a string of charaters

**Comment by angristan** [comment]
OK, thanks

**Comment by billyprice1old** [comment]
Are you going to make a custom branch for lxc or something or change the main branch and use  head instead of tr

**Comment by angristan** [comment]
I'm going to use head on master
