### ISSUE TITLE
Authenticate/Decrypt packet error: bad packet ID Error Message

### ISSUE THREAD

**Issue by rosealex90** [angristan/openvpn-install#281]
Hi,
I've configured my openvpn, it's working well but I'm getting a frequently message after udp connection as shown:
**" Authenticate/Decrypt packet error: bad packet ID (may be a replay)  ... "**  

Please, any Explanation ?

**Comment by angristan** [comment]
See https://openvpn.net/archive/openvpn-users/2004-07/msg00361.html (there are hundreds of topics about this in the web). Don't worry, it's just a warning, a not related to the script, but oftentimes packet loss + openvpn.

**Comment by rosealex90** [comment]
After search I've seen that it may be an attack!.
From your experience in openvpn, is that possible?

**Comment by angristan** [comment]
Yes, on 0.0001% of the time. Chances are it's just packet loss. It happens to me a lot when I download torrents
