### ISSUE TITLE
Traffic not routed propperly 

### ISSUE THREAD

**Issue by johnappletree** [angristan/openvpn-install#284]
Hi there, I have following problem with my OpenVPN server. I can connect with my openVPN server from the same lan, but I don’t have an internet connection. I can ping the internal adresses but no external ones. For example: ping 8.8.8.8 does not work. 

Router 192.168.1.1 subnet 192.168.1.X  (openwrt based system) 
Openvpn server 192.168.1.6 subnet 192.168.3.X (lxc container) version  2.3.10 
Client 192.168.1.99   (currently, no fixed ip) (Macbook pro, iPhone)

My iptable rules: Chain FORWARD (policy ACCEPT): 1    ACCEPT     all  --  192.168.3.0/24  anywhere   
Chain POSTROUTING (policy ACCEPT) :1    MASQUERADE  all  --  192.168.3.0/24    anywhere    

Tried to solve problem, by adding following lines to server.conf: push “route 192.168.3.0 255.255.255.0“ or push “route 192.168.3.0 255.255.255.0 192.168.1.6“ However it did not work. I am looking to for a solution that my VPN works (with internet connection) when I’m in my own internal network and outside! anybody know where I should start such that i can keep my vpn connected?

Network diagram  https://ibb.co/jVx8Pe

**Comment by angristan** [comment]
Does the LXC container have internet? What are its routes?

**Comment by johnappletree** [comment]
@angristan Yes, LXC container has an internet connection. I have an internet connection when i am connected from an external adress. Routing table looks like this:

```
 route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.1.1     0.0.0.0         UG    0      0        0 eth0
192.168.1.0     0.0.0.0         255.255.255.0   U     0      0        0 eth0
192.168.3.0     0.0.0.0         255.255.255.0   U     0      0        0 tun0
```

**Comment by angristan** [comment]
What do you mean "I have an internet connection when i am connected from an external address."

**Comment by johnappletree** [comment]
For example: When I am on data with my mobile phone, and connect to the openvpn server everything works as excepted. I can ping 8.8.8.8 browse websites and access internal LAN devices/services. 
See my network diagram from my first post.

**Comment by angristan** [comment]
Ok, so this has to be a NAT issue somehow 🤔

**Comment by johnappletree** [comment]
@angristan how can I test this? what should I change?

**Comment by angristan** [comment]
Can you send `iptables -vnL -t nat`?

**Comment by johnappletree** [comment]
Chain PREROUTING (policy ACCEPT 405K packets, 68M bytes)
 pkts bytes target     prot opt in     out     source               destination         
```
Chain INPUT (policy ACCEPT 23673 packets, 3850K bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 46 packets, 2925 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain POSTROUTING (policy ACCEPT 150 packets, 9697 bytes)
 pkts bytes target     prot opt in     out     source               destination         
 4903  334K MASQUERADE  all  --  *      eth0    192.168.3.0/24       0.0.0.0/0           
```

**Comment by angristan** [comment]
Try something like

```
iptables -t nat -A POSTROUTING -o eth0 -s 192.168.1.0/24 -d 192.168.3.0/24 -j MASQUERADE
```

But i'm not sure 🤔

**Comment by johnappletree** [comment]
On the openvpn server right? unfortunately did not work...

**Comment by angristan** [comment]
Try to do `traceroute 8.8.8.8` from your mac when connected to the VPN

**Comment by johnappletree** [comment]
unfortunately doesn't show useful information. I tried it with and without your suggested iptable rule in place. response: 
```
traceroute to 8.8.8.8 (8.8.8.8), 64 hops max, 52 byte packets
 1  * * *
 2  * * *
 3  * * *
 4  * * *
```

**Comment by johnappletree** [comment]
unfortunately doesn't show useful information. I tried it with and without your suggested iptable rule in place. response: 
```
traceroute to 8.8.8.8 (8.8.8.8), 64 hops max, 52 byte packets
 1  * * *
 2  * * *
 3  * * *
 4  * * *
```

**Comment by angristan** [comment]
I dont't know, sorry. This is an unusual setup.
