### ISSUE TITLE
[request] Add mikrotik cert client support

### ISSUE THREAD

**Issue by aVitomin** [angristan/openvpn-install#285]
mikrotik support OpenVPN tcp only

Maybe it help u: https://github.com/missinglink/mikrotik-openvpn-client

**Comment by iProdigy** [comment]
The script already prompts you on whether you wish to use UDP or TCP... is anything else necessary?

**Comment by angristan** [comment]
Yeah we should support everything that's necessary already.

**Comment by no-replies** [comment]
It would be nice if the options were presented so can use with Mikrotik idiotic setup. 

Is there an option to disable the TLS Auth components

Sourced from:
https://projects.hypa.space/2018/01/openvpn-for-mikrotik-client/ 
https://github.com/missinglink/mikrotik-openvpn-client
http://wiki.mikrotik.com/wiki/OpenVPN
