### ISSUE TITLE
Client.ovpn issue

### ISSUE THREAD

**Issue by BelleNottelling** [angristan/openvpn-install#287]
I used this installer running on centOS 7 x64 running on Vultr cloud, and from what I can tell it installed without any issues, but the client.ovpn file that it generated doesn't seem to work. I've tried using both the `openVPN GUI` client and the `Pritunl `client and both do the same thing. Without modifying the file they both give an error like this:
```
Fri Sep 14 08:58:26 2018 ERROR: Endtag </ca> missing
Fri Sep 14 08:58:26 2018 Exiting due to fatal error
```
If I add `</ca>` after the `-----END CERTIFICATE-----` line it then says
```
Options error: No client-side authentication method is specified.  You must use either --cert/--key, --pkcs12, or --auth-user-pass
Use --help for more information.
```
How can I fix this? I'm on windows 10 x64. I'd rather not upload my `client.ovpn` file, but I will if it's needed
edit: I've also regenerated a new client.ovpn file and the same issue was persisting.

**Comment by randomshell** [comment]
It looks like after copying the `client-template.txt` he only echoes `<ca>` and nothing more. Is it possible it doesn't like the `{...} >> $1.ovpn` syntax @sayem314 ?

It may be helpful uploading the ovpn profile, too. Of course, you can edit the sensitive details.

**Comment by BelleNottelling** [comment]
I hadn't thought of removing sensitive data.
```
client
proto udp
remote server port
dev tun
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
verify-
auth SHA256
auth-nocache
cipher AES-128-CBC
tls-client
tls-version-min 1.2
tls-cipher 
setenv opt block-outside-dns
verb 3
<ca>
-----BEGIN CERTIFICATE-----

-----END CERTIFICATE-----
</ca>
```
hopefully I didn't remove non sensitive data, I'm new to open VPN/VPNs in general

**Comment by angristan** [comment]
You `client.ovpn` should look like this:

```
client
proto udp
remote xxx 1194
dev tun
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
verify-x509-name xxx name
auth SHA256
auth-nocache
cipher AES-128-CBC
tls-client
tls-version-min 1.2
tls-cipher TLS-DHE-RSA-WITH-AES-128-GCM-SHA256
setenv opt block-outside-dns
verb 3
<ca>
-----BEGIN CERTIFICATE-----

-----END CERTIFICATE-----
</ca>
<cert>
blablabla
-----BEGIN CERTIFICATE-----

-----END CERTIFICATE-----
</cert>
<key>
-----BEGIN PRIVATE KEY-----

-----END PRIVATE KEY-----
</key>
key-direction 1
<tls-auth>
#
# 2048 bit OpenVPN static key
#
-----BEGIN OpenVPN Static key V1-----

-----END OpenVPN Static key V1-----
</tls-auth>

**Comment by angristan** [comment]
I tested on Vultr + CentOS 7 and the client file is correct. You must have not copied it properly :)

**Comment by BelleNottelling** [comment]
Oops, you seem to be right. Not sure how I missed that haha. Thanks, I'll close this now
On a unrelated note when I tried to set the encryption to the lowest possible (during install), the client file was missing the keys. Unfortunately I've redone the install and replaced the client.ovpn so I can't show it 
edit: I did it again and now it's fine
