### ISSUE TITLE
Detect IP Automatically

### ISSUE THREAD

**Issue by JohnDotOwl** [angristan/openvpn-install#289]
Hi,

Is there anyway we could let openvpn server automatically detect the host IP. Because what i'm doing is making a copy , I wondering if there's anyway to not setup or edit after doing it once? 

I assume the .ovpn needs to be re-generated when the server ip changes?

Please advice.

**Comment by randshell** [comment]
For security reasons copies aren't recommended.
No, there is no way to automatically detect server public IP. You can use a DDNS if you don't want to make any edits, but you have to change the IP of that domain every time you want to connect to another server. So I don't think this can help you.

**Comment by angristan** [comment]
If there server's IP change, you have to update your .ovpn files with the new IP and import them again.
