### ISSUE TITLE
IPV6 NATTED

### ISSUE THREAD

**Issue by billyprice1old** [angristan/openvpn-install#292]
Hi i have tried this on vultr and hetzner with ipv6 enabled on vultr it made it so ipv4 was not able to comnnect as well as ipv6  i don't know if this is a one of case but i don't think the ipv6 natted thing is working correctly i might be wrong if someone else got a vultr account can you please let me know
Thanks
BIlly-Geroge

**Comment by angristan** [comment]
Hello,

I can confirm that it's working on Vultr.

Please explain your issue clearly.

**Comment by billyprice1old** [comment]
Im going to deploy another instance and see if i experiance  the same issue

**Comment by angristan** [comment]
OK. I will test on Hetzner later.

**Comment by billyprice1old** [comment]
https://i.imgur.com/OENg92a.png this is what happens

**Comment by billyprice1old** [comment]
I can't ping anything only 10.8.0.1  i don't know why this happens

**Comment by billyprice1old** [comment]
I can also ping 45.77.59.239 and i get ICMP responsves when i ping sites but i can't connect to them

My isp is Sky

**Comment by angristan** [comment]
Can you try to install without enabling IPv6 support?

**Comment by billyprice1old** [comment]
Sure

**Comment by billyprice1old** [comment]
I have done this now https://i.imgur.com/XSspb06.png ipv6 traffic work but not ipv4 now the template i use is ubuntu 16.04
Thanks
Billy-George

**Comment by angristan** [comment]
- What is you server's OS
- What is you client's OS
- Go to http://ipv6-test.com/. Is the IPv6 your ISP's or you server's?

**Comment by angristan** [comment]
This doesn't seen to be related to IPv6 at all.

**Comment by billyprice1old** [comment]
Server os s ubuntu 16.o4 
Client os  Linux mint 18.04
And yes isp does supprt ipv6

**Comment by angristan** [comment]
can you send the output of 

On the server and client:
```
ufw status verbose
```

On the server only:
```
iptables -nvL
```

```
iptables -nvL -t nat
```

**Comment by billyprice1old** [comment]
https://pastebin.ubuntu.com/p/HS4cQ2Sgq3/

**Comment by angristan** [comment]
On the server, please do:

```
iptables -F
iptables -X
iptables -t nat -F
bash /etc/iptables/add-openvpn-rules.sh
```

**Comment by billyprice1old** [comment]
I have done that tried reconnecting to the vpn and still the same issue i think it might be due to im using ubuntu 16.04 the old script before you made the new update works without any issue

**Comment by angristan** [comment]
Ah... Ok so the latest version of the script works?

**Comment by billyprice1old** [comment]
No the old one does

**Comment by angristan** [comment]
![](https://i.giphy.com/media/Ysce790SgjJK0/giphy.gif)

**Comment by billyprice1old** [comment]
What a good meme the new script does not work

**Comment by angristan** [comment]
what does `sysctl --sytem` outputs?

**Comment by billyprice1old** [comment]
https://pastebin.ubuntu.com/p/fgr2WWbSVt/ i assume you mean sysctl --system

**Comment by angristan** [comment]
OK. To be honest I don't see what isn't working since the rules are correct and forwarding is enabled.

**Comment by billyprice1old** [comment]
It most prob just me can you try to deploy the same setup as me i had ubuntu 16.04 in the uk on vultr 

Thanks anyway we  will see if its just me with this issue

**Comment by angristan** [comment]
Fixed, see https://github.com/angristan/openvpn-install/issues/296

**Comment by angristan** [comment]
See https://github.com/angristan/openvpn-install/issues/295 for IPv6 on Hetzner
