### ISSUE TITLE
IPv6 not working with Hetzner

### ISSUE THREAD

**Issue by angristan** [angristan/openvpn-install#295]

**Comment by angristan** [comment]
OK, this is not related to the script.

I already noticed the issue while playing with bridges and LXD and reported it to Hetzner but they don't care.

Let's take an example:

```
root@debian-2gb-nbg1-1 ~ # ip a
...
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 96:00:00:10:8d:b4 brd ff:ff:ff:ff:ff:ff
    inet 159.69.198.162/32 brd 159.69.198.162 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 2a01:4f8:1c1c:7b7a::1/64 scope global deprecated
       valid_lft forever preferred_lft 0sec
    inet6 fe80::9400:ff:fe10:8db4/64 scope link
       valid_lft forever preferred_lft forever
```

You can see that our public IPv6 has `valid_lft forever preferred_lft 0sec`. I don't exactly know what triggers this, but when you *do something related to IPv6*, the kernel may drop the IPv6 since it has a TTL of 0 sec.

To fix this, in our case:

```sh
ip -6 addr change 2a01:4f8:1c1c:7b7a::1/64 dev eth0 preferred_lft forever
```

To permanently fix it:

```sh
root@debian-2gb-nbg1-1 ~ # cat /etc/network/interfaces.d/50-cloud-init.cfg
# This file is generated from information provided by
# the datasource.  Changes to it will not persist across an instance.
# To disable cloud-init's network configuration capabilities, write a file
# /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg with the following:
# network: {config: disabled}
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet dhcp
    dns-nameservers 213.133.99.99 213.133.98.98 213.133.100.100

auto eth0:0
iface eth0:0 inet6 static
    address 2a01:4f8:1c1c:7b7a::1/64
    gateway fe80::1
    post-up route add -A inet6 default gw fe80::1%eth0 || true
    pre-down route del -A inet6 default gw fe80::1%eth0 || true
    post-up ip -6 addr change 2a01:4f8:1c1c:7b7a::1/64 dev eth0 preferred_lft forever
```

**Comment by angristan** [comment]
To do:

- [x] Find what exactly breaks IPv6 here: another `inet6` interface
- [x] Add this to the FAQ: https://github.com/angristan/openvpn-install/commit/1cd80a5cc743651e12e295c3d6d44f834f310dbf
- [ ] Make a blog post about it

**Comment by nilava** [comment]
Thank you! Thanks a lot! I was going crazy trying to figure why ipv6 wasn't working with OpenVPN, you are a lifesaver!

**Comment by angristan** [comment]
Actually 0 = forever so it's not a preferred_lft issue.

Just issuing `ip -6 addr change <ipv6>/64 dev eth0` works

**Comment by angristan** [comment]
https://angristan.xyz/fix-ipv6-hetzner-cloud/
