### ISSUE TITLE
it stuck on TLS: Initial Packet...

### ISSUE THREAD

**Issue by AbanoubNassem** [angristan/openvpn-install#297]
I have used this script before like 3 months ago or so , and it worked perfectly , then I wanted to upgrade the script and the authentications , so as You mentioned I have to remove the openvpn using your script then, update the script , and after that I rerun the configurations , and that exactly what happened, but since then I can't connect to the server , it stuck on 

`"..TLS:  Initial packet from [AF_INET6]..."`

I also tried to install it on a fresh install of Ubuntu 16.4 , but same issue , any clue what causing this?!

**Comment by angristan** [comment]
Hello,

Please provide more logs than `"..TLS: Initial packet from [AF_INET6]..."`

**Comment by AbanoubNassem** [comment]
> * openvpn@server.service - OpenVPN connection to server
>    Loaded: loaded (/lib/systemd/system/openvpn@.service; enabled; vendor preset: enabled)
>    Active: active (running) since Wed 2018-09-19 22:12:53 EET; 1h 50min ago
>      Docs: man:openvpn(8)
>            https://community.openvpn.net/openvpn/wiki/Openvpn23ManPage
>            https://community.openvpn.net/openvpn/wiki/HOWTO
>   Process: 5730 ExecStart=/usr/sbin/openvpn --daemon ovpn-%i --status /run/openvpn/%i.status 10 --cd /etc/openvpn --script-security 2 --config /etc/openvpn/%i.conf --writepid /run/openvpn/%i.pid (code=exited, status=0/SUCCESS)
>  Main PID: 5735 (openvpn)
>    CGroup: /system.slice/system-openvpn.slice/openvpn@server.service
>            `-5735 /usr/sbin/openvpn --daemon ovpn-server --status /run/openvpn/server.status 10 --cd /etc/openvpn --script-security 2 --config /etc/openvpn/server.conf --writepid /run/openvpn/server.pid
> 
> Sep 19 22:15:29 vmi89168.host ovpn-server[5735]: ::ffff:xx.xxx.xxx.xxx TLS Error: TLS handshake failed
> Sep 19 22:15:29 vmi89168.host ovpn-server[5735]: ::ffff:xx.xxx.xxx.xxx SIGUSR1[soft,tls-error] received, client-instance restarting
> Sep 19 23:57:50 vmi89168.host ovpn-server[5735]: ::ffff:xx.xxx.xxx.xxx TLS: Initial packet from [AF_INET6]::ffff:xx.xxx.xxx.xxx:25213, sid=7a7bb80e 6f956981
> Sep 19 23:58:50 vmi89168.host ovpn-server[5735]: ::ffff:xx.xxx.xxx.xxx TLS: Initial packet from [AF_INET6]::ffff:xx.xxx.xxx.xxx:25296, sid=4f196da9 f6415403
> Sep 19 23:58:50 vmi89168.host ovpn-server[5735]: ::ffff:xx.xxx.xxx.xxx TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
> Sep 19 23:58:50 vmi89168.host ovpn-server[5735]: ::ffff:xx.xxx.xxx.xxx TLS Error: TLS handshake failed
> Sep 19 23:58:50 vmi89168.host ovpn-server[5735]: ::ffff:xx.xxx.xxx.xxx SIGUSR1[soft,tls-error] received, client-instance restarting
> Sep 19 23:59:50 vmi89168.host ovpn-server[5735]: ::ffff:xx.xxx.xxx.xxx TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)

xx.xxx.xxx.xxx is my laptop ip trying to connect

**Comment by angristan** [comment]
That means your laptop can't contact the server.

- Can you ping the server?
- Is openvpn running on the server? (`ps faux | grep openvpn`)
- Is there some kind of firewall or NAT on the server?
- Can you do a nmap? (`sudo nmap -sU -p 1194 <ip>`)
- `cat /etc/openvpn/server.conf`
- `iptables -nvL`

**Comment by randomshell** [comment]
@Angristan nmap can't be used here because of OpenVPN tls-auth / tls-crypt.

**Comment by AbanoubNassem** [comment]
Can you ping the server?
Yes

Is openvpn running on the server? (ps faux | grep openvpn)

```
root@vmi89168:~# ps faux | grep openvpn
root      5471  0.0  0.3 538924 38072 tty1     Sl   Sep19   0:04 mousepad /etc/openvpn/server.conf
root      7304  0.0  0.0  16664  2100 pts/8    S+   10:14   0:00      \_ grep --color=auto openvpn
nobody    5735  0.0  0.0  43880  5548 ?        Ss   Sep19   0:01 /usr/sbin/openvpn --daemon ovpn-server --status /run/openvpn/server.status 10 --cd /etc/openvpn --script-security 2 --config /etc/openvpn/server.conf --writepid /run/openvpn/server.pid
```

Is there some kind of firewall or NAT on the server?
NOPE

Can you do a nmap? (sudo nmap -sU -p 1194 <ip>)
```

Host is up.
PORT     STATE         SERVICE
1194/udp open|filtered openvpn

Nmap done: 1 IP address (1 host up) scanned in 2.24 seconds
```

cat /etc/openvpn/server.conf
```

port 1194
proto udp6
dev tun
user nobody
group nogroup
persist-key
persist-tun
keepalive 10 120
topology subnet
server 10.8.0.0 255.255.255.0
ifconfig-pool-persist /etc/openvpn/ipp.txt
push "dhcp-option DNS 9.9.9.9"
push "dhcp-option DNS 149.112.112.112"
push "redirect-gateway def bypass-dhcp" 
server-ipv6 fd42:42:42:42::/112
tun-ipv6
push tun-ipv6
push "route-ipv6 2000::/3"
push "redirect-gateway ipv6"
crl-verify /etc/openvpn/crl.pem
ca /etc/openvpn/ca.crt
cert /etc/openvpn/server_dxay7Ay5T2qC2jkP.crt
key /etc/openvpn/server_dxay7Ay5T2qC2jkP.key
tls-auth /etc/openvpn/tls-auth.key 0
dh /etc/openvpn/dh.pem
auth SHA256
cipher AES-128-CBC
tls-server
tls-version-min 1.2
tls-cipher TLS-DHE-RSA-WITH-AES-128-GCM-SHA256
status /var/log/openvpn/status.log
verb 3
```

iptables -nvL

```
Chain INPUT (policy ACCEPT 2121K packets, 175M bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 ACCEPT     all  --  tun0   *       0.0.0.0/0            0.0.0.0/0           
   46  4067 ACCEPT     udp  --  eth0   *       0.0.0.0/0            0.0.0.0/0            udp dpt:1194

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 ACCEPT     all  --  eth0   tun0    0.0.0.0/0            0.0.0.0/0           
    0     0 ACCEPT     all  --  tun0   eth0    0.0.0.0/0            0.0.0.0/0           

Chain OUTPUT (policy ACCEPT 2061K packets, 1841M bytes)
 pkts bytes target     prot opt in     out     source               destination         
```

**Comment by angristan** [comment]
@randomshell yes it can

**Comment by angristan** [comment]
Thanks @AbanoubNassem. Can you remove OpenVPN and reinstall it without IPv6?

**Comment by AbanoubNassem** [comment]
@angristan 

I did, and rerun all the commands you gave me before , it's same result actually

server.conf
```

port 1194
proto udp
dev tun
user nobody
group nogroup
persist-key
persist-tun
keepalive 10 120
topology subnet
server 10.8.0.0 255.255.255.0
ifconfig-pool-persist ipp.txt
push "dhcp-option DNS 9.9.9.9"
push "dhcp-option DNS 149.112.112.112"
push "redirect-gateway def1 bypass-dhcp" 
crl-verify crl.pem
ca ca.crt
cert server_4JoCfyRzAcuYzYJm.crt
key server_4JoCfyRzAcuYzYJm.key
tls-auth tls-auth.key 0
dh dh.pem
auth SHA256
cipher AES-128-CBC
tls-server
tls-version-min 1.2
tls-cipher TLS-DHE-RSA-WITH-AES-128-GCM-SHA256
status /var/log/openvpn/status.log
verb 3

``` 

iptables -nvL
```

Chain INPUT (policy ACCEPT 172K packets, 59M bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 ACCEPT     all  --  tun0   *       0.0.0.0/0            0.0.0.0/0           
    5   386 ACCEPT     udp  --  eth0   *       0.0.0.0/0            0.0.0.0/0            udp dpt:1194

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 ACCEPT     all  --  eth0   tun0    0.0.0.0/0            0.0.0.0/0           
    0     0 ACCEPT     all  --  tun0   eth0    0.0.0.0/0            0.0.0.0/0           

Chain OUTPUT (policy ACCEPT 220K packets, 101M bytes)
 pkts bytes target     prot opt in     out     source               destination         

```

```
root@vmi89168:~/Desktop# ps faux | grep openvpn
root     15145  0.0  0.0  16664  2072 pts/2    S+   11:57   0:00          |       \_ grep --color=auto openvpn
nobody   12781  0.0  0.0  43748  5564 ?        Ss   11:53   0:00 /usr/sbin/openvpn --daemon ovpn-server --status /run/openvpn/server.status 10 --cd /etc/openvpn --script-security 2 --config /etc/openvpn/server.conf --writepid /run/openvpn/server.pid

```

any more suggestions ?

**Comment by angristan** [comment]
You seem to have the same issue: https://serverfault.com/questions/765521/openvpn-issue-tls-key-negotiation-failed-to-occur-within-60-seconds#765562

**Comment by AbanoubNassem** [comment]
@angristan , it's weird because even using TCP connection isn't working! it stuck at the same 

`TLS: Initial packet from [AF_INET6]...`

it was working perfectly fine before , I have no clue what happened!

**Comment by angristan** [comment]
Weird 🤔

**Comment by randshell** [comment]
@Angristan sorry, I thought it was from another host, not local.

**Comment by angristan** [comment]
@randomshell It is from another host, to see if the port 1194 is open for UDP :)

**Comment by angristan** [comment]
@randomshell It is from another host, to see if the port 1194 is open for UDP :)

**Comment by angristan** [comment]
See the FAQ: https://openvpn.net/index.php/open-source/faq/79-client/253-tls-error-tls-key-negotiation-failed-to-occur-within-60-seconds-check-your-network-connectivity.html

**Comment by randshell** [comment]
@Angristan shouldn't it ignore not signed packets, then? ( tls-auth in fact)

**Comment by angristan** [comment]
@randomshell I assume the packets will be rejected by OpenVPN, but they won't be dropped before being checked by OpenVPN so nmap can find that the port is opened.

**Comment by angristan** [comment]
@AbanoubNassem Have you tried https://github.com/Nyr/openvpn-install?

**Comment by AbanoubNassem** [comment]
@angristan

same issue :( , wanna look at through TeamViewer or something!?

**Comment by ArthurAttout** [comment]
Could this be reopened ? Exact same issue. 

```
Aug  9 00:01:04 debian ovpn-server[421]: 94.109.204.148:22670 TLS: Initial packet from [AF_INET]94.109.204.148:22670, sid=a41718dd 4df45992
Aug  9 00:02:04 debian ovpn-server[421]: 94.109.204.148:22670 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Aug  9 00:02:04 debian ovpn-server[421]: 94.109.204.148:22670 TLS Error: TLS handshake failed
Aug  9 00:02:04 debian ovpn-server[421]: 94.109.204.148:22670 SIGUSR1[soft,tls-error] received, client-instance restarting

```

iptables -nvL 
```

Chain INPUT (policy ACCEPT 65970 packets, 4211K bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain FORWARD (policy ACCEPT 2 packets, 664 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy ACCEPT 218K packets, 321M bytes)
 pkts bytes target     prot opt in     out     source               destination

```

No firewall inbetween. Connection initiated from openvpn profile imported into OpenVPN Android

**Comment by angristan** [comment]
This means the server can't be reached from the client. 

- OpenVPN is not running
- A firewall is blocking the connection
- The client can't access the server via the internet
- The port is closed on the client's network

So it's probably not an issue with openvpn-install here.

**Comment by ArthurAttout** [comment]
This log is taken from the server. The TLS initial packet is received by the server (and sent by the client obviously) , so nothing seems to block the connection, so that seems like a server-side issue

**Comment by angristan** [comment]
Oh ok. What's the client?

**Comment by ArthurAttout** [comment]
Tried both on the OpenVPN Android App and OpenVPN client on Debian. I'll keep on looking through this today and keep you in touch

**Comment by ArthurAttout** [comment]
I managed to get some kind of exchange further than the initial packet by setting the `local` key in `server.conf`

The file now looks like this 

```
port 1194
proto udp
dev tun
sndbuf 0
rcvbuf 0
ca ca.crt
cert server.crt
key server.key
dh dh.pem
auth SHA512
tls-auth ta.key 0
topology subnet
server 10.8.0.0 255.255.255.0
ifconfig-pool-persist ipp.txt
local 192.168.1.85
push "redirect-gateway def1 bypass-dhcp"
push "dhcp-option DNS 192.168.1.1"
keepalive 10 120
cipher AES-256-CBC
user nobody
group nogroup
persist-key
persist-tun
status openvpn-status.log
verb 3
crl-verify crl.pem

```


From now on, an exchange seems to establish, but with another error
```

Fri Aug  9 13:57:16 2019 Unrecognized option or missing or extra parameter(s) in newclient.ovpn:14: block-outside-dns (2.4.7)
Fri Aug  9 13:57:16 2019 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 20 2019
Fri Aug  9 13:57:16 2019 library versions: OpenSSL 1.1.1c  28 May 2019, LZO 2.10
Fri Aug  9 13:57:16 2019 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
Fri Aug  9 13:57:16 2019 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
Fri Aug  9 13:57:16 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]80.200.161.203:1194
Fri Aug  9 13:57:16 2019 Socket Buffers: R=[212992->212992] S=[212992->212992]
Fri Aug  9 13:57:16 2019 UDP link local: (not bound)
Fri Aug  9 13:57:16 2019 UDP link remote: [AF_INET]80.200.161.203:1194
Fri Aug  9 13:57:17 2019 TLS: Initial packet from [AF_INET]80.200.161.203:1194, sid=3115f06a b116ff9a
Fri Aug  9 13:57:17 2019 VERIFY ERROR: depth=1, error=self signed certificate in certificate chain: CN=ChangeMe
Fri Aug  9 13:57:17 2019 OpenSSL: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
Fri Aug  9 13:57:17 2019 TLS_ERROR: BIO read tls_read_plaintext error
Fri Aug  9 13:57:17 2019 TLS Error: TLS object -> incoming plaintext read error
Fri Aug  9 13:57:17 2019 TLS Error: TLS handshake failed
Fri Aug  9 13:57:17 2019 SIGUSR1[soft,tls-error] received, process restarting
Fri Aug  9 13:57:17 2019 Restart pause, 5 second(s)
Fri Aug  9 13:57:18 2019 SIGINT[hard,init_instance] received, process exiting
```

I don't know if that's making the issue go any better or worse yet, but that's the only progress I managed to do in almost 5 hours.

**Comment by ArthurAttout** [comment]
I can now confirm that after completely uninstalling and re-installing PiVPN, adding  `local <YOUR_LOCAL_IP_ADDRESS>` in `server.conf` fixed the issue, and the TLS handshake finally completed. 

Unless this is some bad practice or a temporary hack, I'd recommend adding this on the default `server.conf`. I'll let @angristan close this issue if it fits.

**Comment by angristan** [comment]
We added it: https://github.com/angristan/openvpn-install/commit/ad3c223385a9aa323227633fcc5e456d1235e873 and reverted it: https://github.com/angristan/openvpn-install/commit/a7a277e2dc5e6d77a355a4cb60bb85032d724c65 because it had side effects in some cases

**Comment by ajayyy** [comment]
Can confirm this solution. Thank you so much, this took too long to find.

> adding local <YOUR_LOCAL_IP_ADDRESS> in server.conf fixed the issue, and the TLS handshake finally completed.

Note: I used https://github.com/Nyr/openvpn-install which this seems to be a fork of? I'm not sure. I'll leave this here so it is accessible in Google Searches though.

**Comment by ax-meyer** [comment]
Having the same issue. It worked perfeclty a month or so ago, and suddenly today it does not.

The log says: 
```
Dec  5 10:20:00 SERVER ovpn-server[28828]: library versions: OpenSSL 1.1.1d  10 Sep 2019, LZO 2.10
Dec  5 10:20:00 SERVER ovpn-server[28828]: Outgoing Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Dec  5 10:20:00 SERVER ovpn-server[28828]: Outgoing Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Dec  5 10:20:00 SERVER ovpn-server[28828]: Incoming Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Dec  5 10:20:00 SERVER ovpn-server[28828]: Incoming Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Dec  5 10:20:00 SERVER ovpn-server[28828]: TLS-Auth MTU parms [ L:1621 D:1156 EF:94 EB:0 ET:0 EL:3 ]
Dec  5 10:20:00 SERVER ovpn-server[28828]: TUN/TAP device tun0 opened
Dec  5 10:20:00 SERVER ovpn-server[28828]: TUN/TAP TX queue length set to 100
Dec  5 10:20:00 SERVER ovpn-server[28828]: do_ifconfig, tt->did_ifconfig_ipv6_setup=0
Dec  5 10:20:00 SERVER ovpn-server[28828]: /sbin/ip link set dev tun0 up mtu 1500
Dec  5 10:20:00 SERVER ovpn-server[28828]: /sbin/ip addr add dev tun0 10.8.0.1/24 broadcast 10.8.0.255
Dec  5 10:20:00 SERVER ovpn-server[28828]: Data Channel MTU parms [ L:1621 D:1450 EF:121 EB:406 ET:0 EL:3 ]
Dec  5 10:20:00 SERVER ovpn-server[28828]: Socket Buffers: R=[212992->212992] S=[212992->212992]
Dec  5 10:20:00 SERVER ovpn-server[28828]: setsockopt(IPV6_V6ONLY=0)
Dec  5 10:20:00 SERVER ovpn-server[28828]: UDPv6 link local (bound): [AF_INET6][undef]:1194
Dec  5 10:20:00 SERVER ovpn-server[28828]: UDPv6 link remote: [AF_UNSPEC]
Dec  5 10:20:00 SERVER ovpn-server[28828]: GID set to nogroup
Dec  5 10:20:00 SERVER ovpn-server[28828]: UID set to nobody
Dec  5 10:20:00 SERVER ovpn-server[28828]: MULTI: multi_init called, r=256 v=256
Dec  5 10:20:00 SERVER ovpn-server[28828]: IFCONFIG POOL: base=10.8.0.2 size=252, ipv6=0
Dec  5 10:20:00 SERVER ovpn-server[28828]: Initialization Sequence Completed
Dec  5 10:20:06 SERVER ovpn-server[28828]: MULTI: multi_create_instance called
Dec  5 10:20:06 SERVER ovpn-server[28828]: <v6clientaddr>:9543 Re-using SSL/TLS context
Dec  5 10:20:06 SERVER ovpn-server[28828]: <v6clientaddr>:9543 Control Channel MTU parms [ L:1621 D:1156 EF:94 EB:0 ET:0 EL:3 ]
Dec  5 10:20:06 SERVER ovpn-server[28828]: <v6clientaddr>:9543 Data Channel MTU parms [ L:1621 D:1450 EF:121 EB:406 ET:0 EL:3 ]
Dec  5 10:20:06 SERVER ovpn-server[28828]: <v6clientaddr>:9543 Local Options String (VER=V4): 'V4,dev-type tun,link-mtu 1569,tun-mtu 1500,proto UDPv4,cipher AES-256-CBC,auth SHA256,keysize 256,key-method 2,tls-server'
Dec  5 10:20:06 SERVER ovpn-server[28828]: <v6clientaddr>:9543 Expected Remote Options String (VER=V4): 'V4,dev-type tun,link-mtu 1569,tun-mtu 1500,proto UDPv4,cipher AES-256-CBC,auth SHA256,keysize 256,key-method 2,tls-client'
Dec  5 10:20:06 SERVER ovpn-server[28828]: <v6clientaddr>:9543 TLS: Initial packet from [AF_INET6]<v6clientaddr>:9543:59052, sid=47ae6ce4 45128a4f
```

However using local <localv6server> does not fix it for me.
The log then states 

```
Dec  5 10:25:04 USERVER ovpn-server[6063]: library versions: OpenSSL 1.1.1d  10 Sep 2019, LZO 2.10
Dec  5 10:25:04 USERVER ovpn-server[6063]: Outgoing Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Dec  5 10:25:04 USERVER ovpn-server[6063]: Outgoing Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Dec  5 10:25:04 USERVER ovpn-server[6063]: Incoming Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Dec  5 10:25:04 USERVER ovpn-server[6063]: Incoming Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Dec  5 10:25:04 USERVER ovpn-server[6063]: TLS-Auth MTU parms [ L:1621 D:1156 EF:94 EB:0 ET:0 EL:3 ]
Dec  5 10:25:04 USERVER ovpn-server[6063]: TUN/TAP device tun0 opened
Dec  5 10:25:04 USERVER ovpn-server[6063]: TUN/TAP TX queue length set to 100
Dec  5 10:25:04 USERVER ovpn-server[6063]: do_ifconfig, tt->did_ifconfig_ipv6_setup=0
Dec  5 10:25:04 USERVER ovpn-server[6063]: /sbin/ip link set dev tun0 up mtu 1500
Dec  5 10:25:04 USERVER ovpn-server[6063]: /sbin/ip addr add dev tun0 10.8.0.1/24 broadcast 10.8.0.255
Dec  5 10:25:04 USERVER ovpn-server[6063]: Data Channel MTU parms [ L:1621 D:1450 EF:121 EB:406 ET:0 EL:3 ]
Dec  5 10:25:04 USERVER ovpn-server[6063]: Socket Buffers: R=[212992->212992] S=[212992->212992]
Dec  5 10:25:04 USERVER ovpn-server[6063]: setsockopt(IPV6_V6ONLY=0)
Dec  5 10:25:04 USERVER ovpn-server[6063]: TCP/UDP: Socket bind failed on local address [AF_INET6]<localv6server>:1194: Invalid argument (errno=22)
Dec  5 10:25:04 USERVER ovpn-server[6063]: Exiting due to fatal error
Dec  5 10:25:04 USERVER ovpn-server[6063]: Closing TUN/TAP interface
Dec  5 10:25:04 USERVER ovpn-server[6063]: /sbin/ip addr del dev tun0 10.8.0.1/24
```

Any ideas? Reopen the issue?

**Comment by ronnyz** [comment]
I was having the same issue, and this was the first result in Google when searching for the solution, so I wanted to share my solution. 

In my case it was simply incorrect date/time setting on client side which was causing TLS certificate verification to fail.

**Comment by developmenttlpk** [comment]
in my case it was isp.

**Comment by SasSam** [comment]
> Having the same issue. It worked perfeclty a month or so ago, and suddenly today it does not.
> 
> The log says:
> 
> ```
> Dec  5 10:20:00 SERVER ovpn-server[28828]: library versions: OpenSSL 1.1.1d  10 Sep 2019, LZO 2.10
> Dec  5 10:20:00 SERVER ovpn-server[28828]: Outgoing Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
> Dec  5 10:20:00 SERVER ovpn-server[28828]: Outgoing Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
> Dec  5 10:20:00 SERVER ovpn-server[28828]: Incoming Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
> Dec  5 10:20:00 SERVER ovpn-server[28828]: Incoming Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
> Dec  5 10:20:00 SERVER ovpn-server[28828]: TLS-Auth MTU parms [ L:1621 D:1156 EF:94 EB:0 ET:0 EL:3 ]
> Dec  5 10:20:00 SERVER ovpn-server[28828]: TUN/TAP device tun0 opened
> Dec  5 10:20:00 SERVER ovpn-server[28828]: TUN/TAP TX queue length set to 100
> Dec  5 10:20:00 SERVER ovpn-server[28828]: do_ifconfig, tt->did_ifconfig_ipv6_setup=0
> Dec  5 10:20:00 SERVER ovpn-server[28828]: /sbin/ip link set dev tun0 up mtu 1500
> Dec  5 10:20:00 SERVER ovpn-server[28828]: /sbin/ip addr add dev tun0 10.8.0.1/24 broadcast 10.8.0.255
> Dec  5 10:20:00 SERVER ovpn-server[28828]: Data Channel MTU parms [ L:1621 D:1450 EF:121 EB:406 ET:0 EL:3 ]
> Dec  5 10:20:00 SERVER ovpn-server[28828]: Socket Buffers: R=[212992->212992] S=[212992->212992]
> Dec  5 10:20:00 SERVER ovpn-server[28828]: setsockopt(IPV6_V6ONLY=0)
> Dec  5 10:20:00 SERVER ovpn-server[28828]: UDPv6 link local (bound): [AF_INET6][undef]:1194
> Dec  5 10:20:00 SERVER ovpn-server[28828]: UDPv6 link remote: [AF_UNSPEC]
> Dec  5 10:20:00 SERVER ovpn-server[28828]: GID set to nogroup
> Dec  5 10:20:00 SERVER ovpn-server[28828]: UID set to nobody
> Dec  5 10:20:00 SERVER ovpn-server[28828]: MULTI: multi_init called, r=256 v=256
> Dec  5 10:20:00 SERVER ovpn-server[28828]: IFCONFIG POOL: base=10.8.0.2 size=252, ipv6=0
> Dec  5 10:20:00 SERVER ovpn-server[28828]: Initialization Sequence Completed
> Dec  5 10:20:06 SERVER ovpn-server[28828]: MULTI: multi_create_instance called
> Dec  5 10:20:06 SERVER ovpn-server[28828]: <v6clientaddr>:9543 Re-using SSL/TLS context
> Dec  5 10:20:06 SERVER ovpn-server[28828]: <v6clientaddr>:9543 Control Channel MTU parms [ L:1621 D:1156 EF:94 EB:0 ET:0 EL:3 ]
> Dec  5 10:20:06 SERVER ovpn-server[28828]: <v6clientaddr>:9543 Data Channel MTU parms [ L:1621 D:1450 EF:121 EB:406 ET:0 EL:3 ]
> Dec  5 10:20:06 SERVER ovpn-server[28828]: <v6clientaddr>:9543 Local Options String (VER=V4): 'V4,dev-type tun,link-mtu 1569,tun-mtu 1500,proto UDPv4,cipher AES-256-CBC,auth SHA256,keysize 256,key-method 2,tls-server'
> Dec  5 10:20:06 SERVER ovpn-server[28828]: <v6clientaddr>:9543 Expected Remote Options String (VER=V4): 'V4,dev-type tun,link-mtu 1569,tun-mtu 1500,proto UDPv4,cipher AES-256-CBC,auth SHA256,keysize 256,key-method 2,tls-client'
> Dec  5 10:20:06 SERVER ovpn-server[28828]: <v6clientaddr>:9543 TLS: Initial packet from [AF_INET6]<v6clientaddr>:9543:59052, sid=47ae6ce4 45128a4f
> ```
> 
> However using local does not fix it for me. The log then states
> 
> ```
> Dec  5 10:25:04 USERVER ovpn-server[6063]: library versions: OpenSSL 1.1.1d  10 Sep 2019, LZO 2.10
> Dec  5 10:25:04 USERVER ovpn-server[6063]: Outgoing Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
> Dec  5 10:25:04 USERVER ovpn-server[6063]: Outgoing Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
> Dec  5 10:25:04 USERVER ovpn-server[6063]: Incoming Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
> Dec  5 10:25:04 USERVER ovpn-server[6063]: Incoming Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
> Dec  5 10:25:04 USERVER ovpn-server[6063]: TLS-Auth MTU parms [ L:1621 D:1156 EF:94 EB:0 ET:0 EL:3 ]
> Dec  5 10:25:04 USERVER ovpn-server[6063]: TUN/TAP device tun0 opened
> Dec  5 10:25:04 USERVER ovpn-server[6063]: TUN/TAP TX queue length set to 100
> Dec  5 10:25:04 USERVER ovpn-server[6063]: do_ifconfig, tt->did_ifconfig_ipv6_setup=0
> Dec  5 10:25:04 USERVER ovpn-server[6063]: /sbin/ip link set dev tun0 up mtu 1500
> Dec  5 10:25:04 USERVER ovpn-server[6063]: /sbin/ip addr add dev tun0 10.8.0.1/24 broadcast 10.8.0.255
> Dec  5 10:25:04 USERVER ovpn-server[6063]: Data Channel MTU parms [ L:1621 D:1450 EF:121 EB:406 ET:0 EL:3 ]
> Dec  5 10:25:04 USERVER ovpn-server[6063]: Socket Buffers: R=[212992->212992] S=[212992->212992]
> Dec  5 10:25:04 USERVER ovpn-server[6063]: setsockopt(IPV6_V6ONLY=0)
> Dec  5 10:25:04 USERVER ovpn-server[6063]: TCP/UDP: Socket bind failed on local address [AF_INET6]<localv6server>:1194: Invalid argument (errno=22)
> Dec  5 10:25:04 USERVER ovpn-server[6063]: Exiting due to fatal error
> Dec  5 10:25:04 USERVER ovpn-server[6063]: Closing TUN/TAP interface
> Dec  5 10:25:04 USERVER ovpn-server[6063]: /sbin/ip addr del dev tun0 10.8.0.1/24
> ```
> 
> Any ideas? Reopen the issue?

I have the same issue on Edgerouter-X. The config worked for a week or so, and today it just stopped working. It's the same error. It happened before as well. I had to reinstall the router at that time as I couldn't find a solution. After reinstalling it, it started working again, and it worked up until yesterday. Now the VPN doesn't work again. Very annoying!
