### ISSUE TITLE
Cannot use hostname instead of IP

### ISSUE THREAD

**Issue by wuuei** [angristan/openvpn-install#299]
Hello,

The commit a0ff4d7cf92a08cf028a5b16c02380bebdb75e06 made it impossible to use a hostname in the "Public IPv4 address" question.

Previously I've used that to specify a ddns hostname for an OpenVPN server that was on a residential connection that changes IP every so often.

Is the current behavior the correct one? If so, is there a recommended way to use this script on a connection with dynamic IP assignment?

**Comment by angristan** [comment]
Thanks for the issue. I added it back in https://github.com/angristan/openvpn-install/commit/cfa5eed6bd562e563d2efa64eff7a31fe4ffc6e0.

**Comment by wuuei** [comment]
Thank you very much.
Also, thank you for the great script. It made it really easy to set up a VPN to my server at home.

**Comment by cezar1324** [comment]
Hello guys, i know this is an old reply, but if I wanted to also use my hostname how would Iwrite it down, right now i am using my public ip address like this(example)
: "80.182.12.16", i tried to put my hostname like this :"cezar123"  and it disnt work , how would you write it down if my hostname is cezar123 ?
