### ISSUE TITLE
client.ovpn not being created

### ISSUE THREAD

**Issue by cagmz** [angristan/openvpn-install#3]
I ran the installer, as well as Nyr's, on a fresh Debian server install using sudo and the client configs aren't being created. Any ideas?

**Comment by angristan** [comment]
What does `find / -name "*.ovpn"` gives you ?

Can you post the install log ?

**Comment by cagmz** [comment]
Ah, turns out the *.ovpn files are being created in /root/! Thanks

Solution: Debian server is strict with environment variables when using sudo, so I used:

    sudo -E ./openvpn-install.sh

for preserving environment variables from my regular user account.

**Comment by angristan** [comment]
Thanks for the information, I'll take a look into it.
