### ISSUE TITLE
New update

### ISSUE THREAD

**Issue by billyprice1old** [angristan/openvpn-install#300]
Hi there,
I don't know how to explain this but the openvpn service is failing to turn on since the new script update running ubuntu 16.04 i don't know if its just me i did 1 for every option with custom encryiption
Sorry for another issue report

**Comment by angristan** [comment]
Please post the output of 

```
systemctl status openvpn@server.service
```

**Comment by billyprice1old** [comment]
https://pastebin.ubuntu.com/p/p2vFzgbb4k/

**Comment by angristan** [comment]
Please put the full ouput

**Comment by angristan** [comment]
```
journalctl -u openvpn@server --no-pager
```

**Comment by billyprice1old** [comment]
https://pastebin.ubuntu.com/p/WN4w2kKj3g/ here the output

**Comment by angristan** [comment]
Thanks 👍

**Comment by billyprice1old** [comment]
Also i love this project so much is there a way to donate or something like a patron or something i really wanna support it how ever i can

**Comment by angristan** [comment]
Fixed in https://github.com/angristan/openvpn-install/commit/e2906fd5e4892b539f1cdd2f5dc5aebda178494e

**Comment by angristan** [comment]
@billyprice1 Yeah I have https://www.patreon.com/Angristan. 

Thanks for reporting bugs 👍

**Comment by billyprice1old** [comment]
HI there Again,
I made a fresh instance and tried to reinstall it
and i get 
sed: can't read /lib/systemd/system/openvpn@.service: No such file or directory
sed: can't read /lib/systemd/system/openvpn@.service: No such file or directory
Failed to restart openvpn@server.service: Unit openvpn@server.service not found.
Failed to execute operation: No such file or directory
Created symlink from /etc/systemd/system/multi-user.target.wants/iptables-openvpn.service to /etc/systemd/system/iptables-openvpn.service.

**Comment by billyprice1old** [comment]
but if i do service openvpn start it start working

**Comment by angristan** [comment]
-> https://github.com/angristan/openvpn-install/commit/ef30d3c9dfa9f965420174d08a6bfc800ab04aa2

**Comment by angristan** [comment]
And https://github.com/angristan/openvpn-install/commit/8de3957afb1dc58b5fdcc28f482b9cb3cef130f6
