### ISSUE TITLE
secp256r1 --> secp256k1

### ISSUE THREAD

**Issue by kimberct** [angristan/openvpn-install#302]
Curve labeled secp256r1 needs to be secp256k1.  At least on 2.4.6.

Nice job on the script.  Really glad to see the 2.4-update branch pulled in.

**Comment by angristan** [comment]
Good catch. `secp256r1` is in fact `prime256v1`. `secp256k1` is a Koblitz curve,

**Comment by angristan** [comment]
FTR:

- easy-rsa handles the misuse like this: `using curve name prime256v1 instead of secp256r1`
- OpenVPN: `Failed to use supplied curve (UNDEF), using secp384r1 instead.`

**Comment by angristan** [comment]
Fixed in https://github.com/angristan/openvpn-install/commit/70ebe5620db5c0f9ca218d72832962b159397da7

**Comment by iProdigy** [comment]
@Angristan I'd rather recommend k1 as it's less likely to be botched by the NSA

**Comment by angristan** [comment]
NSA is not this script's threat model.

**Comment by iProdigy** [comment]
Understood. Would you be open to adding the k1 option to this script (I don't mind making the PR)?

**Comment by angristan** [comment]
I will do some tests.

**Comment by iProdigy** [comment]
Also wanted to note that: if there does, in fact, exist some vulnerability in P-256, it has the potential to be stolen from the NSA, putting many users at risk when there are alternative ciphers with more sensible parameters.

**Comment by angristan** [comment]
Let's talk again when there is, in fact, a vulnerability in P-256. :)

**Comment by iProdigy** [comment]
Hah, alright - it's not implausible given the Dual_EC_DRBG fiasco and strange parameter choice.

**Comment by angristan** [comment]
Elliptic Curves are kind of a mess... ^^

**Comment by iProdigy** [comment]
yeah, I'd much rather prefer Curve25519 or Ed448-Goldilocks but they require [openssl 1.1.1](https://www.openssl.org/blog/blog/2018/09/11/release111/) (which clients are unlikely to have updated to yet)...

**Comment by iProdigy** [comment]
We should keep an eye on this ticket: https://community.openvpn.net/openvpn/ticket/1116
