### ISSUE TITLE
The New Update works before the reboot, after the reboot there is no access to the VM

### ISSUE THREAD

**Issue by ayton** [angristan/openvpn-install#306]
New Update is installed and everything works fine, but only before rebooting the VM, after rebooting there is no access to the VM, there is no ping. If you install older versions, there are no such problems, everything works perfectly.
What's wrong?

**Comment by angristan** [comment]
Please provide more information:
- where is your vm
- is there any boot issue
- is it a network issue

The script does not mess with the boot process and the iptables rules only allow stuff.

**Comment by ayton** [comment]
When using your earlier versions, I did not experience such problems, everything worked perfectly.
VM - https://www.ihor.ru localization Russia, there are no problems with boot, the new update is installed fine and works until the reboot. After the reboot, the connection to the VM is lost, there is no ping. Now installed the old version, everything works. After reboot, VM access is available.

**Comment by ayton** [comment]
> Please provide more information:
> 
> * where is your vm
> * is there any boot issue
> * is it a network issue
> 
> The script does not mess with the boot process and the iptables rules only allow stuff.
When using your earlier versions, I did not experience such problems, everything worked perfectly.
VM - https://www.ihor.ru localization Russia, there are no problems with boot, the new update is installed fine and works until the reboot. After the reboot, the connection to the VM is lost, there is no ping. Now installed the old version, everything works. After reboot, VM access is available.

**Comment by angristan** [comment]
Can you try to add these rules one by one:

https://github.com/angristan/openvpn-install/blob/e4a9851b4fe3ceca6fdc3a33f2322f84d5c1ef3c/openvpn-install.sh#L843#L847

**Comment by ayton** [comment]
> Can you try to add these rules one by one:
> 
> https://github.com/angristan/openvpn-install/blob/e4a9851b4fe3ceca6fdc3a33f2322f84d5c1ef3c/openvpn-install.sh#L843#L847

It did not help...
But the system change from Debian 8 to Ubuntu 16.04 helped. Probably something is wrong with compatibility with the Debian 8 distribution. On Ubuntu 16.04, the new update works. Thanks for the support. 
Great work ...))

**Comment by angristan** [comment]
Thanks for the feedback :)
