### ISSUE TITLE
Default server config disables Internet access from client

### ISSUE THREAD

**Issue by saidmasoud** [angristan/openvpn-install#310]
Server: 
- OS: Ubuntu 18.04
- Cloud provider: AWS

Client:
- OS: Mac OSX 10.12.6
- OpenVPN client: Tunnelblick 3.7.6a

Issue:

When connected to the VPN server after installing, I cannot access external Internet sites from my client. I resolved the issue by commenting out the following line from `/etc/openvpn/server.conf`:

```
#push "redirect-gateway def1 bypass-dhcp"
```

**Comment by angristan** [comment]
Check the DNS resolvers used by the client: https://stackoverflow.com/questions/2541161/redirect-gateway-def1

**Comment by saidmasoud** [comment]
That makes sense. We have a custom DNS config on our clients which can't be routed through the VPN. I'll just leave the line commented out for now, thanks!
