### ISSUE TITLE
Auto update script

### ISSUE THREAD

**Issue by chocolateshirt** [angristan/openvpn-install#319]
It would be great if there is feature to get the latest update of the script without download latest script and reinstall it manually.

The example, if you run `./openvpn-install.sh` after installation, there will be new menu like this:

```
Welcome to OpenVPN-Install!

OpenVPN-Install ver. xxx
The git repository is available at: https://github.com/angristan/openvpn-install

What do you want to do?
   1) Add a new user
   2) Revoke existing user
   3) Update script
   4) Remove OpenVPN
   5) Exit
Select an option [1-5]:
```

**Comment by FevLoad** [comment]
I second this opinion, that would be great if the coder could consider doing it.

**Comment by xiagw** [comment]
Yes, have a good reference: [https://github.com/Neilpang/acme.sh](https://github.com/Neilpang/acme.sh)
Can update itself.

**Comment by xiagw** [comment]
[git@github.com:Neilpang/acme.sh.git](url)

**Comment by Leopere** [comment]
At the moment all you need to do currently is do a guy pull.

I mean I guess it would be trivial to add something that runs that command
for you but it seems moot-ish

**Comment by xiagw** [comment]
Ref: [https://github.com/alexanderepstein/bsupdate](https://github.com/alexanderepstein/bsupdate)

**Comment by Firerouge** [comment]
Updating the script doesn't help unless it can also upgrade the generated configs made by older versions of the script as well.

That'd largely be changing existing lines in the ovpn files, and prompting the user if they'd like to enable newly available options. Which means you have to push your new ovpn configs to any and all clients to see most of the benefits.

I think there's something to be said for regenerating the configuration files while persisting your current keys. But simply updating the script (as in a git pull) as described here would still require you to remove openvpn and rerun the install script to get the benefits of changes to the script

**Comment by Leopere** [comment]
What if there was just an answers.env file that would be saved with the responses given to the installer and then the update script would just uninstall and reinstall with the answers and potential backups of certs etc.

**Comment by angristan** [comment]
See https://github.com/angristan/openvpn-install/issues/179#issuecomment-389820907

**Comment by randshell** [comment]
We all commented about some upgrade code but after reading Pivpn's [wiki](https://github.com/pivpn/pivpn/wiki/Upgrading) I understand @angristan has a point, even if he didn't go in as much details.

That's about the code. Regarding the process of upgrading, even if manual, I think it _could_ be a little more friendly for the user if some more work is done from the dev side.
This would include versioning the script and possibly using the release feature of Github. There are two reasons for this. First, Github recently added the email notification for new releases only, so you don't need to subscribe and be notified for every comment or commit this repo gets, just releases. Second, in the release description you would have the change list in a more readable and faster way than scrolling through commit names, it's more understandable for the end user what changed too. Here a reinstall info can be added if necessary by the changes.
These are just first thoughts, someone can come with a better idea.

The other way around this but not for every user could be the following. Don't curl the script but clone the repo instead. When you need to upgrade, copy the current commit sha, do a git pull and then a git log comparing changes between the copied commit and the latest. This leaves the user to decide what changed and if he needs a reinstall, assuming all commits have meaningful names.

**Comment by angristan** [comment]
Indeed, using tags/releases would be great. I've thought about it multiple times but I'm not sure about the versioning scheme to use.

**Comment by randshell** [comment]
Something based on the date, like youtube-dl?

**Comment by angristan** [comment]
It's pretty redundant with the commits though. I think the main reason it's useful for youtube-dl is because it's being packaged by many distros.
