### ISSUE TITLE
No internet after connecting to VPN

### ISSUE THREAD

**Issue by csib** [angristan/openvpn-install#320]
Hi.

I have a stock Debian 9.1, I have installed your script, (ran without errors)

I have successfully joined to the VPN server, but there is no internet access. I cant ping 8.8.8.8 and the name resolution is also not working.

I have choosed the default values during the setup.

I's a VPS so I have added this:
iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j SNAT --to-source xxx.xxx.xxx.xxx
But still no internet.

**Comment by angristan** [comment]
Hello,

Can you post the output of 

- `iptables -nvL`
- `iptables -nvL -t nat`
- `ip a`
- `apt policy openvn`
