### ISSUE TITLE
Add support for DNSCrypt

### ISSUE THREAD

**Issue by Kcchouette** [angristan/openvpn-install#321]
Hi
Can you please add support of DNSCrypt for the DNS service?

**Comment by iProdigy** [comment]
In a sense it is already supported; you can install it on your clients and have it work, you may just need to remove the block-outside-dns from windows configs. Similarly, you can select "system resolver" in the script, install dnscrypt, and have it working server-side.

**Comment by angristan** [comment]
⬆️ Yes.

**Comment by Kcchouette** [comment]
@iProdigy @angristan It was more like "please add the possibility to install dnscrypt using your DNS-install script"
