### ISSUE TITLE
Port change is ignored after initial setup

### ISSUE THREAD

**Issue by JohnyBeGood** [angristan/openvpn-install#327]
During the install at the port selection screen I chose default 1194. Later after testing I decided to change (**/etc/openvpn/server.conf**) it to something else and restarted OpenVPN server. 
When I generated new client and tried to connect it was still embedding old default port (**remote xxx.xxx.xx.xx 5xxxx**). It completely ignores port change.
Uninstalled it and this time chose other custom port and when I generated new client this time it included new port.
This is on Ubuntu 18.04

**Comment by angristan** [comment]
Change the port in `/etc/openvpn/client-template.txt` if you want your new clients to use another port.

**Comment by JohnyBeGood** [comment]
Thanks! Please include that reference in the FAQ.
