### ISSUE TITLE
Options error: Unrecognized option or missing or extra parameter(s) in surface.ovpn:19

### ISSUE THREAD

**Issue by JohnyBeGood** [angristan/openvpn-install#328]
I was trying to find solution for very slow speed. I'm on 150/5 connection but only getting about 1.5/0.9
Found this thread https://serverfault.com/questions/686286/very-low-tcp-openvpn-throughput-100mbit-port-low-cpu-utilization
and tried adding 
`sndbuf 393216
rcvbuf 393216
push "sndbuf 393216"
push "rcvbuf 393216"`
and
`sndbuf 0
rcvbuf 0`
to `client-template.txt` and `server.conf`
but started to get 
`Options error: Unrecognized option or missing or extra parameter(s) in surface.ovpn:19: ---BEGIN (2.4.6)
Use --help for more information.
`
Even after I removed above parameters and restarted OpenVPN I'm still getting above error

https://www.photobox.co.uk/my/photo/full?photo_id=501131714636

**Comment by angristan** [comment]
- The thread is about TCP. You should use UDP for speed.
- This is not related to the script
- Please post line 19 of `surface.ovpn`, otherwise we can't guess what option isn't valid
- Please upload files on github directly, your link doesn't work

**Comment by JohnyBeGood** [comment]
Thanks! I was already using UDP but still really slow.
Did not realize that 19 was referring to error line. That line has `-----BEGIN CERTIFICATE-----`
![surface](https://user-images.githubusercontent.com/1755800/46651996-9691d100-cbc3-11e8-9cd1-d3e8fc24ef0a.JPG)

![capture](https://user-images.githubusercontent.com/1755800/46651877-3ac74800-cbc3-11e8-87e8-08989a8b5912.JPG)

**Comment by JohnyBeGood** [comment]
Ok, I've figured out what the issue is.
When I was using WinSCP to edit `client-template.txt` I guess cursor was at right after `verb 3` which when certs were generated added `<ca>` right after 3 and that caused error on line 19.
Not sure if this has anything to do with the script, OpenVPN or WinSCP?
![cursor](https://user-images.githubusercontent.com/1755800/46652558-3865ed80-cbc5-11e8-8661-6e8567b0a896.JPG)

**Comment by angristan** [comment]
Yes that's the issue. It certainly happened when you edited the file

**Comment by JohnyBeGood** [comment]
Thanks for your help!
