### ISSUE TITLE
Internal Routing

### ISSUE THREAD

**Issue by bruffdj** [angristan/openvpn-install#329]
Hi,

I'd like to enable internal routing (i.e. I want the clients to be able to communicate, and the server to be able to contact the clients).  I think [Nyr describes what I'm after here](https://github.com/Nyr/openvpn-install/issues/190#issuecomment-244614857), but I'm not sure how to modify your script correctly.  

Can anyone suggest the changes I should make?

Thanks

**Comment by xiagw** [comment]
Just modify the file server.conf:

`client-to-client`
