### ISSUE TITLE
easy-rsa can't utilize .rnd and index.txt.attr

### ISSUE THREAD

**Issue by GoliathLabs** [angristan/openvpn-install#330]
System: Arch Linux

`Using configuration from ./safessl-easyrsa.cnf
Can't load /etc/openvpn/easy-rsa/pki/.rnd into RNG
140692602155520:error:2406F079:random number generator:RAND_load_file:Cannot open file:crypto/rand/randfile.c:88:Filename=/etc/openvpn/easy-rsa/pki/.rnd
Can't open /etc/openvpn/easy-rsa/pki/index.txt.attr for reading, No such file or directory
140692602155520:error:02001002:system library:fopen:No such file or directory:crypto/bio/bss_file.c:72:fopen('/etc/openvpn/easy-rsa/pki/index.txt.attr','r')
140692602155520:error:2006D080:BIO routines:BIO_new_file:no such file:crypto/bio/bss_file.c:79:`
Script is still working even with the errors above.

Full trace:
https://hastebin.com/ejicacuvoz.sql

Cheers

**Comment by angristan** [comment]
Yep! This is a known issue that has no impacts on the script.
