### ISSUE TITLE
WireGuard Support

### ISSUE THREAD

**Issue by holdit** [angristan/openvpn-install#331]
@angristan Do you have any plans to add WireGuard support to this script (or create another one just fore WG)? It's better than OpenVPN in terms of performance and works better on mobile devices (eg: lower battery usage, better speeds on weak hardware, no issues moving between data and wifi).

While we can use Streisand or Algo, both can be hard to use as installation is done locally. Not to mention that solutions like Streisand install more than just WireGuard.

**Comment by angristan** [comment]
I love Wireguard and I'm using it for my servers. I've thought about making a script (which would be on another repo). I can't guarantee anything but I'll think about it!

**Comment by angristan** [comment]
See https://github.com/angristan/wireguard-install for a WIP 😬
