### ISSUE TITLE
HTTP timeout while connected to the VPN

### ISSUE THREAD

**Issue by FevLoad** [angristan/openvpn-install#333]
I set up the script and did everything as it should be, the only thing which is not working for me 
when I connected to the VPN, it only connected, I can not browse the net or anything 

but when I use another VPN service it works as it should be.
could someone please help me with setting it up in the correct way?

**Comment by angristan** [comment]
You you post the output of `iptables -nvL` and `iptables -nvL -t nat` of the server?

**Comment by FevLoad** [comment]
iptables -nvL command
`Chain INPUT (policy ACCEPT 33949 packets, 4007K bytes)
 pkts bytes target     prot opt in     out     source               destination 
    0     0 ACCEPT     all  --  tun0   *       0.0.0.0/0            0.0.0.0/0   
  224 63281 ACCEPT     tcp  --  ens3   *       0.0.0.0/0            0.0.0.0/0            tcp dpt:1194

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination 
  181 49231 ACCEPT     all  --  ens3   tun0    0.0.0.0/0            0.0.0.0/0   
  364 42488 ACCEPT     all  --  tun0   ens3    0.0.0.0/0            0.0.0.0/0   

Chain OUTPUT (policy ACCEPT 32750 packets, 2359K bytes)
 pkts bytes target     prot opt in     out     source               destination `

iptables -nvL -t nat command 

> ah@vps580311:~$ sudo iptables -nvL
[sudo] password for ah:
Chain INPUT (policy ACCEPT 33949 packets, 4007K bytes)
 pkts bytes target     prot opt in     out     source               destination 
    0     0 ACCEPT     all  --  tun0   *       0.0.0.0/0            0.0.0.0/0   
  224 63281 ACCEPT     tcp  --  ens3   *       0.0.0.0/0            0.0.0.0/0            tcp dpt:1194

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination 
  181 49231 ACCEPT     all  --  ens3   tun0    0.0.0.0/0            0.0.0.0/0   
  364 42488 ACCEPT     all  --  tun0   ens3    0.0.0.0/0            0.0.0.0/0   

Chain OUTPUT (policy ACCEPT 32750 packets, 2359K bytes)
 pkts bytes target     prot opt in     out     source               destination 
ah@vps580311:~$ sudo iptables -nvL -t nat
Chain PREROUTING (policy ACCEPT 25107 packets, 891K bytes)
 pkts bytes target     prot opt in     out     source               destination 

Chain INPUT (policy ACCEPT 25030 packets, 883K bytes)
 pkts bytes target     prot opt in     out     source               destination 

Chain OUTPUT (policy ACCEPT 80 packets, 6402 bytes)
 pkts bytes target     prot opt in     out     source               destination 

Chain POSTROUTING (policy ACCEPT 80 packets, 6402 bytes)
 pkts bytes target     prot opt in     out     source               destination 
   77  8448 MASQUERADE  all  --  *      ens3    10.8.0.0/24          0.0.0.0/0 


Using OVH VPS

**Comment by angristan** [comment]
Seems OK, what about `ip a`? (You can hide your public IP address)

**Comment by FevLoad** [comment]
> Seems OK, what about `ip a`? (You can hide your public IP address)

ah@vps580311:~$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: ens3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether fa:16:3e:66:a1:89 brd ff:ff:ff:ff:ff:ff
    inet 5X.X5.1X.2X3/32 scope global dynamic ens3
       valid_lft 63216sec preferred_lft 63216sec
    inet6 fe80::f816:3eff:fe66:a189/64 scope link
       valid_lft forever preferred_lft forever
5: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN group default qlen 100
    link/none
    inet 10.8.0.1/24 brd 10.8.0.255 scope global tun0
       valid_lft forever preferred_lft forever
    inet6 fe80::1da3:24b3:e625:32c9/64 scope link stable-privacy
       valid_lft forever preferred_lft forever

**Comment by angristan** [comment]
what about `uname -a` `lsb_release -a`

**Comment by genbushi** [comment]
had a similar snag on a Debian 9 based instace on Vultr - connect okay but wasn't passing interwebz traffic - simple fix, manually added the masquerade/postrouting/forwarding/input tun & interface ipTables rules.

iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE
iptables -A INPUT -i tun0 -j ACCEPT
iptables -A FORWARD -i eth0 -o tun0 -j ACCEPT
iptables -A FORWARD -i tun0 -o eth0 -j ACCEPT


I didn't troubleshoot why they did not auto load as intended though, just integrated them in to my pre-existing firewall script after determining that was the issue.

**Comment by genbushi** [comment]
actually - looking at mine, it may have been the whole Debian sh/dash/bash dealio.

**Comment by angristan** [comment]
@genbushi That's weird! Next time look at the status of `systemctl status openvpn-iptables`

**Comment by aliweb** [comment]
@Respectme Can you check if you are able to open bing.com and wikipedia.com ?

I am facing a similar issue. After the recent changes, the script is not working on Debian 8 (tested on VirMach and Vultr). The client successfully connects but I am only able to open a handful of sites like bing.com and wikipedia.com.

Previously this issue was only happening with Debian 9 but now Debian 8 is also affected.

**Comment by angristan** [comment]
@aliweb Is it a DNS issue? (can you ping 1.1.1.1?)

**Comment by aliweb** [comment]
Yes seems like a DNS issue but I am unable to pinpoint the exact cause. Ping to 1.1.1.1 is working fine:

> C:\Users\Ali-PC>ping 1.1.1.1
> 
> Pinging 1.1.1.1 with 32 bytes of data:
> Reply from 1.1.1.1: bytes=32 time=274ms TTL=52
> Reply from 1.1.1.1: bytes=32 time=274ms TTL=52
> Reply from 1.1.1.1: bytes=32 time=274ms TTL=52
> Reply from 1.1.1.1: bytes=32 time=279ms TTL=52
> 
> Ping statistics for 1.1.1.1:
>     Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
> Approximate round trip times in milli-seconds:
>     Minimum = 274ms, Maximum = 279ms, Average = 275ms

**Comment by aliweb** [comment]
Looks like some problem with my ISP. I used a different ISP and it is working fine. When I use my regular ISP then I face this problem. Wonder what can I do to solve this DNS issue?

**Comment by angristan** [comment]
weird!

Try to do a `nslookup` to see what DNS servers you're using while connected to the VPN

**Comment by aliweb** [comment]
**Without VPN**
```
C:\Users\Ali-PC>nslookup
Default Server:  UnKnown
Address:  192.168.1.1

> bing.com
Server:  UnKnown
Address:  192.168.1.1

Non-authoritative answer:
Name:    bing.com
Addresses:  204.79.197.200
          13.107.21.200

> google.com
Server:  UnKnown
Address:  192.168.1.1

Non-authoritative answer:
Name:    google.com
Addresses:  2a00:1450:4006:807::200e
          172.217.18.238
```

**With VPN**
```
C:\Users\Ali-PC>nslookup
Default Server:  one.one.one.one
Address:  1.0.0.1

> bing.com
Server:  one.one.one.one
Address:  1.0.0.1

Non-authoritative answer:
Name:    bing.com
Addresses:  13.107.21.200
          204.79.197.200

> google.com
Server:  one.one.one.one
Address:  1.0.0.1

Non-authoritative answer:
Name:    google.com
Addresses:  2607:f8b0:4006:811::200e
          216.58.219.206
```

**Comment by angristan** [comment]
So ping and DNS work fine... What is not working for you?

**Comment by aliweb** [comment]
google.com and many other sites won't open. Here's the screenshot. Notice that URL has changed from **www.google.com** (which I wrote in the browser) to **www.google.com/?gws_rd=ssl** which means the site has been found and then it keeps trying for some time by saying **Establishing secure connection....** and later it shows error **ERR_TIMED_OUT**

https://i.imgur.com/UrHsnUU.jpg

**Comment by angristan** [comment]
That's really weird. In your initial message you mentioned it happened only with specific distributions (Debian 8/9?). Is it still the case?

**Comment by aliweb** [comment]
At first, I thought the issue is with Debian 9 only but now it appears to be affecting Debian 8 also BUT it's only happening in case of one ISP.
When I use it at home then this problem happens. This is my primary internet connection.
When I use it at work then VPN works fine.
When I use my mobile internet then again VPN works fine.

**Comment by jooooohn** [comment]
I had the same issue as @aliweb: no HTTPS sites were loading (could not complete TLS handshake, stuck at Client Hello).
Switching from UDP to TCP did the trick.
This does not happen on other VPN configurations / servers of mine.

**Comment by jozuenoon** [comment]
In my case ip forwarding was disabled:
```
echo 1 > /proc/sys/net/ipv4/ip_forward
```
Edit `/etc/sysctl.conf` to persist, uncomment: `net.ipv4.ip_forward = 1`

I think in general script should make this change happen in system anyway (if this is unrelated to OP problem)

**Comment by angristan** [comment]
@jozuenoon IPv4 forwarding is already enabled in the script and is not related the issue.
