### ISSUE TITLE
Don't route traffic thru VPN

### ISSUE THREAD

**Issue by GNUGradyn** [angristan/openvpn-install#337]
Hello, I'm new to openVPN. I used this script and amazon AWS to make myself a personal VPN to protect myself from people my school WiFi, my friends stalkerish techy parents, and any other malicious users sharing a network with me. I also realized I can use this to SSH into my laptop even when it's not on a network that is within my control. I also have a personal server with a samba share and such on it running from my home.

I want to connect my home server to the openVPN server on AWS so that I can SSH from my server into my laptop, no matter where my laptop is, and so my laptop can access the samba share. However I don't want to route all my servers traffic thru the VPN, I just want it to be connected.

NOTE: I don't need firewall help, I can do that myself, I simply need to know how to prevent traffic from being routed thru the VPN

**Comment by BelleNottelling** [comment]
So you only want port 22 to go through the VPN? Why don't you Google search it as that's more of a question of openvpn's support and documentation than an issue with this install script

**Comment by angristan** [comment]
You should remove `push "redirect-gateway def1 bypass-dhcp"` from `/etc/openvpn/server.conf`
