### ISSUE TITLE
Concern about iptables

### ISSUE THREAD

**Issue by Patlol** [angristan/openvpn-install#34]
On Ubuntu 16.04.1 LTS, after execution of the script I have an` iptables -L` empty, before and even after a reboot.  
`Chain INPUT (policy ACCEPT)`  
`target     prot opt source               destination `
`Chain FORWARD (policy ACCEPT)`
`target     prot opt source               destination` 
`Chain OUTPUT (policy ACCEPT)`
`target     prot opt source               destination `

it's ok for nat tab  
`iptables -t nat -n -L`  
........
`Chain POSTROUTING (policy ACCEPT)`
`target     prot opt source               destination   `      
`SNAT       all  --  10.8.0.0/24          0.0.0.0/0            to:xx.xxx.xx.xxx`

You enter the rules  
`487 sed -i "1 a\iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -j SNAT --to $IP" $RCLOCAL ` 
`518	sed -i "1 a\iptables -I FORWARD -s 10.8.0.0/24 -j ACCEPT" $RCLOCAL  `
`519	sed -i "1 a\iptables -I FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT" $RCLOCAL`

Only the first rule is in /etc/rc.local
`#!/bin/sh -e`
`iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -j SNAT --to xx.xxx.xx.xxx`
`#`
`# rc.local`
.....
`# By default this script does nothing.`
`exit 0`

For the other two it makes sense since the test is false, grep can not find reject or drop on a fresh server.
`if iptables -L -n | grep -qE 'REJECT|DROP' `

The first time I had run your script I did not see this problem, the firewall being already set up with drop rules: the last two rules were present.  I was on debian this time.
There is something I do not understand

on peut continuer en français si tu veux ...

**Comment by DrXala** [comment]
I don't understand what you don't understand but I can explain what happens ;)

After a reboot, iptables is "cleaned", so no rules or policy sets, he is empty. The policies are in "ACCEPT" by default, which means that it accepts all traffic.
```
# iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
```
And if you execute `iptables -L -n | grep -E 'REJECT|DROP'` on your server, you have no return.
```
# iptables -L -n | grep -E 'REJECT|DROP'
# echo $?
1
```

So, the script defines in the rc.local, and iptables config, the rules of the filter (INPUT and FORWARD) table if it finds a "reject" or a "drop" in your iptables config.

If the iptables config is empty, then the script doesn't add the "INPUT" and "FORWARD" rules, either in the iptables config or in the rc.local. This explains the absence of these lines in your rc.local. Normal behavior because if you don't have a "reject" or a "drop", you don't need to add rules that allow already authorized traffic :)

On my server, the script would have added the rules because I have a drop rule.
```
# iptables -L -n | grep -E 'REJECT|DROP'
LOG        all  --  0.0.0.0/0            0.0.0.0/0            LOG flags 0 level 4 prefix "INPUT DROP "
DROP       all  --  0.0.0.0/0            0.0.0.0/0
```

Did I answer your misunderstandings?

**Comment by Patlol** [comment]
Thank you for your answer and your explanation.
Sorry for my aproximative English ... But I understood all this and my misunderstanding is not there, but why do this way? I give you an example :

- You just received your server, the web host installed debian or other, your firewall is "ACCEPT" everywhere.
- You install different things and run Andristan's script, your firewall is still accept everywhere. The script detects this state and does not place the tow iptables rules in rc.local. OK ?
- Well, you're happy and now you take care of iptables ... but you do not know / do not think about the specific vpn rules (a script is also made for non experts!). What's going to happen?

If the rules had placed in rc.local anyway, of course they would not serve anything, but they would be there and automatically efficient when launching the firewall with drops no? I think it would be better.

Is this correct?

**Comment by DrXala** [comment]
It correct. As you can see, there is no need to add rules in rc.local if the firewall already accepts traffic. 

In don't know why Angristan doesn't add the "input" and "forward" rules even if the firewall configuration doesn't include "drop". But I think it's to avoid fucking the mess in your machine. The purpose of the script is to make the installation of a VPN server operational in all cases.

Personally, I do not find it "clean" to have its iptables rules in the rc.local. If you want to deepen the configuration of your firewall, I invite you to read about the subject. I wrote a number of papers in French that could help you.
 * [iptables](https://www.openbrain.fr/index.php?article8/iptables)
 * [firewalling](https://www.openbrain.fr/index.php?article9/iptables-firewalling)
 * [more](https://www.openbrain.fr/index.php?article10/iptables-partage-connexion-et-plus)

**Comment by Patlol** [comment]
> But I think it's to avoid fucking the mess in your machine. The purpose of the script is to make the installation of a VPN server operational in all cases.

Ok actually putting rules into an ACCEPT configuration is perfectly useless, but the firewell is not intended to remain like that. The fact of putting these rules does not put the bazaar, as far as I know, but I'm not an iptables specialist.

> Personally, I do not find it "clean" to have its iptables rules in the rc.local

Yes it is not very orthodox, but quite effective :)

> I wrote a number of papers in French that could help you.

Thanks for the links I will consult them! (Especially if it's in French !!!)
