### ISSUE TITLE
Fallback to IPv4 in less than a second

### ISSUE THREAD

**Issue by AmirOVH** [angristan/openvpn-install#340]
Hello. When I connect to the profile it doesn't use IPv6 by default regarding to ipv6-test.com
![image](https://user-images.githubusercontent.com/25551672/47254321-49ceb580-d461-11e8-892e-1212fdd67c93.png)

and test-ipv6.com
![image](https://user-images.githubusercontent.com/25551672/47254332-6c60ce80-d461-11e8-89cf-4dcc00ec4e0d.png)

**Comment by angristan** [comment]
Yes, I noticed this too.

I assume it is because we're using NAT IPv6.

**Comment by AmirOVH** [comment]
Actually it's a NAT IPv4 dedicated IPv6 LXC container.

**Comment by angristan** [comment]
Yes, but your client uses NAT IPv6 (= the same IPv6 as your container)

**Comment by AmirOVH** [comment]
Any plans to figure that in the next versions?

**Comment by angristan** [comment]
No, this is not an issue we can address.

**Comment by AmirOVH** [comment]
Is it because OpenVPN architecture or something?

**Comment by angristan** [comment]
It is because there is no other way to do IPv6 NAT with OpenVPN, and I don't plan on supporting "real" IPv6. I don't know the exact reason why this happens (I am interested to know), but since I don't plan to fix/change anything regarding IPv6, nothing will change regarding this issue.
