### ISSUE TITLE
Tries to access `/home/root` directory

### ISSUE THREAD

**Issue by Barafu** [angristan/openvpn-install#343]
I downloaded script to `/root` folder, logged in as root, and started script directly. Installation goes fine, byt when creating a user file, I get this:

```
Tell me a name for the client.
Use one word only, no special characters.
Client name: tower

Do you want to protect the configuration file with a password?
(e.g. encrypt the private key with a password)
   1) Add a passwordless client
   2) Use a password for the client
Select an option [1-2]: 1

Note: using Easy-RSA configuration from: ./vars

Using SSL: openssl OpenSSL 1.0.2g  1 Mar 2016
Generating a 256 bit EC private key
writing new private key to '/etc/openvpn/easy-rsa/pki/private/tower.key.T2Chj6gbYB'
-----
Using configuration from ./safessl-easyrsa.cnf
Check that the request matches the signature
Signature ok
The Subject's Distinguished Name is as follows
commonName            :ASN.1 12:'tower'
Certificate is to be certified until Oct  9 10:49:36 2021 GMT (1080 days)

Write out database with 1 new entries
Data Base Updated
cp: cannot create regular file '/home/root/tower.ovpn': No such file or directory
./openvpn-install.sh: line 939: /home/root/tower.ovpn: No such file or directory

Client tower added, the configuration file is available at /home/root/tower.ovpn.
Download the .ovpn file and import it in your OpenVPN client.
```
You should add a special case: root's home is `/root`, not `/home/root`. I guess, you always tested with sudo?

**Comment by angristan** [comment]
No, I actually always test with root. What OS are you running?

**Comment by Barafu** [comment]
Ubuntu 16.04 as provided by OpenVZ cloud hosting. Downloaded script to /root, logged in as root over SSH and launched it.

**Comment by angristan** [comment]
Can you run this?

```sh
CLIENT="tower"

if [ -e "/home/$CLIENT" ]; then
	echo "1"
	homeDir="/home/$CLIENT"
elif [ "${SUDO_USER}" ]; then
	echo "2"
	homeDir="/home/${SUDO_USER}"
else
	echo "3"
	homeDir="/root"
fi
```

**Comment by Barafu** [comment]
Sorry, I've missed notification from Github. 
Your script chooses 3. 
Adding a user after that does place file in '/root'

**Comment by Shmuel83** [comment]
I had a same issue with Debian Jessie hosted by OVH. 'root' directory not existed
After create this directory, That's run !

**Comment by angristan** [comment]
Please run the script with `bash -x openvpn-install.sh` if it happens again!

**Comment by Shahbaz-Akram** [comment]
bash -x openvpn-install.sh working fine for me. Thanks.

**Comment by kmskrishna** [comment]
@angristan I also faced the same issue. It occurs if you use **sudo** while you are root.

If you run it directly like ./openvpn-install.sh it is not causing any probelm.
