### ISSUE TITLE
iptables: FORWARD rules should be at the top

### ISSUE THREAD

**Issue by newsera** [angristan/openvpn-install#346]
No access to Internet after successful VPN session. 

Suspecting NAT issue as I could ping tun0 interface IP (10.8.0.1) fine. 

```
C:\Users\n>tracert 8.8.4.4

Tracing route to 8.8.4.4 over a maximum of 30 hops

  1   204 ms   206 ms   205 ms  10.8.0.1
  2     *        *        *     Request timed out.
  3     *        *        *     Request timed out.
  4     *        *        *     Request timed out.
  5     *     ^C

C:\Users\n>ping 10.8.0.1

Pinging 10.8.0.1 with 32 bytes of data:
Reply from 10.8.0.1: bytes=32 time=205ms TTL=64
Reply from 10.8.0.1: bytes=32 time=208ms TTL=64
Reply from 10.8.0.1: bytes=32 time=206ms TTL=64
Reply from 10.8.0.1: bytes=32 time=205ms TTL=64

Ping statistics for 10.8.0.1:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 205ms, Maximum = 208ms, Average = 206ms

root@r:~# route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         router.asus.com 0.0.0.0         UG    202    0        0 eth0
10.8.0.0        0.0.0.0         255.255.255.0   U     0      0        0 tun0
192.168.7.0     0.0.0.0         255.255.255.0   U     202    0        0 eth0

root@r:~# ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.7.11  netmask 255.255.255.0  broadcast 192.168.7.255
        inet6 fe80::a54e:1f9e:b54c:4de8  prefixlen 64  scopeid 0x20<link>
        ether b8:27:eb:10:e8:4d  txqueuelen 1000  (Ethernet)
        RX packets 1322910  bytes 468261096 (446.5 MiB)
        RX errors 0  dropped 68  overruns 0  frame 0
        TX packets 1052275  bytes 627633033 (598.5 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 132033  bytes 9050552 (8.6 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 132033  bytes 9050552 (8.6 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

tun0: flags=4305<UP,POINTOPOINT,RUNNING,NOARP,MULTICAST>  mtu 1500
        inet 10.8.0.1  netmask 255.255.255.0  destination 10.8.0.1
        inet6 fe80::1483:b198:20c:1a03  prefixlen 64  scopeid 0x20<link>
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 100  (UNSPEC)
        RX packets 431  bytes 30176 (29.4 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 648 (648.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

root@raspbx:~# iptables -nvL -t nat
Chain PREROUTING (policy ACCEPT 673 packets, 85213 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain INPUT (policy ACCEPT 74 packets, 39245 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 21 packets, 1330 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain POSTROUTING (policy ACCEPT 21 packets, 1330 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 MASQUERADE  all  --  *      eth0    192.168.42.0/24      0.0.0.0/0           
  363 24142 MASQUERADE  all  --  *      eth0    192.168.43.0/24      0.0.0.0/0            policy match dir out pol none
    0     0 MASQUERADE  all  --  *      eth0    10.8.0.0/24          0.0.0.0/0           
```

I could see that counters for 10.8.0.0/24 was not incrementing at all (stuck at 0) in Chain POSTROUTING

I removed the package and installed Nyr OpenVPN and it worked fine. 

But I noticed a difference in the NAT table with an entry added for SNAT (no counters seen incrementing for that rule though). Note that my host is behind NAT. 

```
root@r:~# iptables -t nat -L -n -v
Chain PREROUTING (policy ACCEPT 142 packets, 20713 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain INPUT (policy ACCEPT 24 packets, 12297 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 1 packets, 60 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain POSTROUTING (policy ACCEPT 1 packets, 60 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 MASQUERADE  all  --  *      eth0    192.168.42.0/24      0.0.0.0/0           
  710 86425 MASQUERADE  all  --  *      eth0    192.168.43.0/24      0.0.0.0/0            policy match dir out pol none
  116  7668 MASQUERADE  all  --  *      eth0    10.8.0.0/24          0.0.0.0/0           
    0     0 SNAT       all  --  *      *       10.8.0.0/24         !10.8.0.0/24          to:192.168.7.11
```

**Comment by newsera** [comment]
This will mislead the bug fix. Hence deleting..

**Comment by newsera** [comment]
https://github.com/angristan/openvpn-install/blob/master/openvpn-install.sh#L852

For some reasons, accept rules were added after the drop rule causing the whole confusion here. 

Would be nice if you can modify the script to add the rules at the top as the explicit deny could be at the bottom. 

Insert at the appropriate position by running

```
iptables -L -v --line-number
```

```
iptables -I FORWARD 1 -i $NIC -o tun0 -j ACCEPT
iptables -I FORWARD 1 -i tun0 -o $NIC -j ACCEPT
```

In my case $NIC was eth0 (you can know the physical interface name by running ifconfig)

```
Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
   32  1448 DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0            ctstate INVALID
    0     0 ACCEPT     all  --  eth0   ppp+    0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
    0     0 ACCEPT     all  --  ppp+   eth0    0.0.0.0/0            0.0.0.0/0           
    0     0 ACCEPT     all  --  ppp+   ppp+    192.168.42.0/24      192.168.42.0/24     
 108K  146M ACCEPT     all  --  eth0   *       0.0.0.0/0            192.168.43.0/24      ctstate RELATED,ESTABLISHED
60324 3834K ACCEPT     all  --  *      eth0    192.168.43.0/24      0.0.0.0/0           
 1982  148K DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0           
    0     0 ACCEPT     all  --  eth0   tun0    0.0.0.0/0            0.0.0.0/0           
    0     0 ACCEPT     all  --  tun0   eth0    0.0.0.0/0            0.0.0.0/0 
```

**Comment by newsera** [comment]
Reinstalled Angristan OpenVPN and modified the position as per the above and the issue has been fixed.

**Comment by mavgink** [comment]
As a total nitwit, what exactly do I need to change in this script if I'm having the same issue? Currently I'm only able to access my private network. I'm not able to browse the internet while connected with VPN. Thanks in advance.

[EDIT] appearantly, if I connect with the Android openvpn app. All is fine. So it must be a problem on my end with the way I connect my ubuntu desktop.

**Comment by jozuenoon** [comment]
In my case ip forwarding was disabled:
```
echo 1 > /proc/sys/net/ipv4/ip_forward
```

Edit `/etc/sysctl.conf` to persist, uncomment: `net.ipv4.ip_forward = 1`

I think in general script should make this change happen in system anyway (if this is unrelated to OP problem)

**Comment by matidev** [comment]
> In my case ip forwarding was disabled:
> 
> ```
> echo 1 > /proc/sys/net/ipv4/ip_forward
> ```
> Edit `/etc/sysctl.conf` to persist, uncomment: `net.ipv4.ip_forward = 1`
> 
> I think in general script should make this change happen in system anyway (if this is unrelated to OP problem)

Yes, just run this command `echo 1 > /proc/sys/net/ipv4/ip_forward`, the problem is resolved.
Thank you.

**Comment by angristan** [comment]
This is done in the script:

```sh
# Enable routing
echo 'net.ipv4.ip_forward=1' >> /etc/sysctl.d/20-openvpn.conf
if [[ "$IPV6_SUPPORT" = 'y' ]]; then
	echo 'net.ipv6.conf.all.forwarding=1' >> /etc/sysctl.d/20-openvpn.conf
fi
# Avoid an unneeded reboot
sysctl --system
```

But unrelated to the original issue.

**Comment by newsera** [comment]
For those who are facing this issue, please check the position of the rules at the FORWARD chain table: 

Good rule look as follows: 

iptables -L -v --line-number

```
Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
num   pkts bytes target     prot opt in     out     source               destination         
1     1864 1415K ACCEPT     all  --  eth0   tun0    anywhere             anywhere            
2     1381  204K ACCEPT     all  --  tun0   eth0    anywhere             anywhere            
```

You can always position it at 1 by running

```
iptables -I FORWARD 1 -i eth0 -o tun0 -j ACCEPT
iptables -I FORWARD 1 -i tun0 -o eth0 -j ACCEPT
```

It is assumed that you are using eth0. Please confirm your interface name by running ifconfig

**Comment by penCsharpener** [comment]
for what it's worth I had a similar issue:
* assumes that you want to route your internet entirely through VPN
* connected successfully to VPN server
* could access IPs on the other side
* client PC had no more internet connection

solution: hardware firewall on VPN server network blocked subnet 10.8.0.0/24. After adding it the internet was working again on client.

**Comment by jiaaozang** [comment]
> https://github.com/angristan/openvpn-install/blob/master/openvpn-install.sh#L852
> 
> 出于某些原因，在删除规则之后添加了接受规则，从而导致整个混乱。
> 
> 如果您可以修改脚本以在顶部添加规则，那将是很好的，因为显式拒绝可能位于底部。
> 
> 通过运行插入适当的位置
> 
> ```
> iptables -L -v --line-number
> ```
> ```
> iptables -I FORWARD 1 -i $NIC -o tun0 -j ACCEPT
> iptables -I FORWARD 1 -i tun0 -o $NIC -j ACCEPT
> ```
> 在我的情况下，$ NIC是eth0（您可以通过运行ifconfig来了解物理接口名称）
> 
> ```
> Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
>  pkts bytes target     prot opt in     out     source               destination         
>    32  1448 DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0            ctstate INVALID
>     0     0 ACCEPT     all  --  eth0   ppp+    0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
>     0     0 ACCEPT     all  --  ppp+   eth0    0.0.0.0/0            0.0.0.0/0           
>     0     0 ACCEPT     all  --  ppp+   ppp+    192.168.42.0/24      192.168.42.0/24     
>  108K  146M ACCEPT     all  --  eth0   *       0.0.0.0/0            192.168.43.0/24      ctstate RELATED,ESTABLISHED
> 60324 3834K ACCEPT     all  --  *      eth0    192.168.43.0/24      0.0.0.0/0           
>  1982  148K DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0           
>     0     0 ACCEPT     all  --  eth0   tun0    0.0.0.0/0            0.0.0.0/0           
>     0     0 ACCEPT     all  --  tun0   eth0    0.0.0.0/0            0.0.0.0/0 
> ```

nice job, I fix my issue by this method, thanks.

**Comment by hrvylein** [comment]
> For those who are facing this issue, please check the position of the rules at the FORWARD chain table:
> 
> Good rule look as follows:
> 
> iptables -L -v --line-number
> 
> ```
> Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
> num   pkts bytes target     prot opt in     out     source               destination         
> 1     1864 1415K ACCEPT     all  --  eth0   tun0    anywhere             anywhere            
> 2     1381  204K ACCEPT     all  --  tun0   eth0    anywhere             anywhere            
> ```
> 
> You can always position it at 1 by running
> 
> ```
> iptables -I FORWARD 1 -i eth0 -o tun0 -j ACCEPT
> iptables -I FORWARD 1 -i tun0 -o eth0 -j ACCEPT
> ```
> 
> It is assumed that you are using eth0. Please confirm your interface name by running ifconfig

I can confirm that this worked for me too. Maybe this fix can be merged into master.
