### ISSUE TITLE
connect but no internet

### ISSUE THREAD

**Issue by kuntsman** [angristan/openvpn-install#348]
i am using vultr to setup a VPN server. 
my issue is that it is setup successfully and connect but i cant access the internet
I've tried it with Fedora 28 x64,CentOS 7 x64,Debian 9 x64,Ubuntu 18.04 x64,Ubuntu 18.10 x64,Ubuntu 16.04 x64
with same problem connect but no internet access
I've follow many tutorial on web about installing OpenVPN especially this one
https://www.cyberciti.biz/faq/centos-7-0-set-up-openvpn-server-in-5-minutes/

+when i install OpenVPN access-server from application in vultr its working very well "connect with access to the internet" which mean's its not an issue with vultr network

this is my VPN client version 
OpenVPN 2.4.6 x86_64-redhat-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Apr 26 2018
library versions: OpenSSL 1.1.0i-fips  14 Aug 2018, LZO 2.08

**Comment by angristan** [comment]
I confirm it works on Vultr.

What client are you using?

**Comment by kuntsman** [comment]
@angristan yes , the problem is on my client , but what is the compatible client i should use in fedora 28?
i've install openvpn client from the package manager

> this is my VPN client version
OpenVPN 2.4.6 x86_64-redhat-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Apr 26 2018
library versions: OpenSSL 1.1.0i-fips 14 Aug 2018, LZO 2.08

the config works very well on the android client

**Comment by angristan** [comment]
Weird! Can you connect on the command line (`openvpn yourclientname.ovpn`) and post the output?

**Comment by kuntsman** [comment]
> $ sudo openvpn server4.ovpn 
Thu Nov  1 19:34:14 2018 Unrecognized option or missing or extra parameter(s) in server4.ovpn:14: block-outside-dns (2.4.6)
Thu Nov  1 19:34:14 2018 OpenVPN 2.4.6 x86_64-redhat-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Apr 26 2018
Thu Nov  1 19:34:14 2018 library versions: OpenSSL 1.1.0i-fips  14 Aug 2018, LZO 2.08
Thu Nov  1 19:34:14 2018 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
Thu Nov  1 19:34:14 2018 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
Thu Nov  1 19:34:14 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]140.82.32.201:1194
Thu Nov  1 19:34:14 2018 Socket Buffers: R=[212992->212992] S=[212992->212992]
Thu Nov  1 19:34:14 2018 UDP link local: (not bound)
Thu Nov  1 19:34:14 2018 UDP link remote: [AF_INET]140.82.32.201:1194
Thu Nov  1 19:34:20 2018 TLS: Initial packet from [AF_INET]140.82.32.201:1194, sid=b6e0d8e9 58038167
Thu Nov  1 19:34:20 2018 VERIFY OK: depth=1, CN=ChangeMe
Thu Nov  1 19:34:20 2018 VERIFY KU OK
Thu Nov  1 19:34:20 2018 Validating certificate extended key usage
Thu Nov  1 19:34:20 2018 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Thu Nov  1 19:34:20 2018 VERIFY EKU OK
Thu Nov  1 19:34:20 2018 VERIFY OK: depth=0, CN=server
Thu Nov  1 19:34:20 2018 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 2048 bit RSA
Thu Nov  1 19:34:20 2018 [server] Peer Connection Initiated with [AF_INET]140.82.32.201:1194
Thu Nov  1 19:34:21 2018 SENT CONTROL [server]: 'PUSH_REQUEST' (status=1)
Thu Nov  1 19:34:24 2018 PUSH: Received control message: 'PUSH_REPLY,redirect-gateway def1 bypass-dhcp,dhcp-option DNS 8.8.8.8,dhcp-option DNS 8.8.4.4,route-gateway 10.8.0.1,topology subnet,ping 10,ping-restart 120,ifconfig 10.8.0.2 255.255.255.0,peer-id 2,cipher AES-256-GCM'
Thu Nov  1 19:34:24 2018 OPTIONS IMPORT: timers and/or timeouts modified
Thu Nov  1 19:34:24 2018 OPTIONS IMPORT: --ifconfig/up options modified
Thu Nov  1 19:34:24 2018 OPTIONS IMPORT: route options modified
Thu Nov  1 19:34:24 2018 OPTIONS IMPORT: route-related options modified
Thu Nov  1 19:34:24 2018 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
Thu Nov  1 19:34:24 2018 OPTIONS IMPORT: peer-id set
Thu Nov  1 19:34:24 2018 OPTIONS IMPORT: adjusting link_mtu to 1624
Thu Nov  1 19:34:24 2018 OPTIONS IMPORT: data channel crypto options modified
Thu Nov  1 19:34:24 2018 Data Channel: using negotiated cipher 'AES-256-GCM'
Thu Nov  1 19:34:24 2018 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Thu Nov  1 19:34:24 2018 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Thu Nov  1 19:34:24 2018 ROUTE_GATEWAY 192.168.1.1/255.255.255.0 IFACE=wlo1 HWADDR=3c:a9:f4:3e:dc:b0
Thu Nov  1 19:34:24 2018 TUN/TAP device tun0 opened
Thu Nov  1 19:34:24 2018 TUN/TAP TX queue length set to 100
Thu Nov  1 19:34:24 2018 do_ifconfig, tt->did_ifconfig_ipv6_setup=0
Thu Nov  1 19:34:24 2018 /sbin/ip link set dev tun0 up mtu 1500
Thu Nov  1 19:34:24 2018 /sbin/ip addr add dev tun0 10.8.0.2/24 broadcast 10.8.0.255
Thu Nov  1 19:34:24 2018 /sbin/ip route add 140.82.32.201/32 via 192.168.1.1
Thu Nov  1 19:34:24 2018 /sbin/ip route add 0.0.0.0/1 via 10.8.0.1
Thu Nov  1 19:34:24 2018 /sbin/ip route add 128.0.0.0/1 via 10.8.0.1
Thu Nov  1 19:34:24 2018 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Thu Nov  1 19:34:24 2018 Initialization Sequence Completed

**Comment by jam-2000** [comment]
hi
i have similar problem on ubuntu 16.04-18.04 (openvpn 2.4.4) and on fresh install of manjaro.
connection is quick and without errors, but there is no dns resolving.
no matter if i use GoogleDNS or remote office dns server.

at the same time i have no problems with MacOS, Windows and Android clients.

**Comment by angristan** [comment]
@kuntsman After connecting this way, did you have any issue?

Can you install the `bind-utils` package and post the output of the `dig` command?

**Comment by angristan** [comment]
@jam-2000 Same for you, can you post the output of `dig` while being connected to the VPN?

**Comment by jam-2000** [comment]
`
; <<>> DiG 9.11.3-1ubuntu1.2-Ubuntu <<>>
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 19081
;; flags: qr rd ra; QUERY: 1, ANSWER: 13, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;.				IN	NS

;; ANSWER SECTION:
.			6678	IN	NS	f.root-servers.net.
.			6678	IN	NS	j.root-servers.net.
.			6678	IN	NS	i.root-servers.net.
.			6678	IN	NS	d.root-servers.net.
.			6678	IN	NS	a.root-servers.net.
.			6678	IN	NS	h.root-servers.net.
.			6678	IN	NS	l.root-servers.net.
.			6678	IN	NS	c.root-servers.net.
.			6678	IN	NS	b.root-servers.net.
.			6678	IN	NS	m.root-servers.net.
.			6678	IN	NS	g.root-servers.net.
.			6678	IN	NS	e.root-servers.net.
.			6678	IN	NS	k.root-servers.net.

;; Query time: 0 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Thu Nov 01 23:20:23 EET 2018
;; MSG SIZE  rcvd: 239

`

**Comment by jam-2000** [comment]
so ...
when i replace nameserver in resolv.conf with ip of office's DNS server, then i can use internet and office's intranet 

p.s.: sorry for my poor english ;|

**Comment by angristan** [comment]
Is `resolvconf` installed? (`apt-cache policy resolvconf`)

**Comment by jam-2000** [comment]
no, resolvconf is not installed 0_o

resolvconf:
Installed: (none)

**Comment by angristan** [comment]
Interesting. In an other issue, installing the `resolvconf` package solved the issue. Without it, the DNS servers pushed by OpenVPN were ignored. Can you try to install it?

**Comment by jam-2000** [comment]
find in internet:
"you don't need resolvconf on 18.04, /etc/resolv.conf is a symlink to systemd-resolved instead"

**Comment by angristan** [comment]
Yes, that's why I think. But it seems systemd-resolved doesn't do well with OpenVPN.

**Comment by jam-2000** [comment]
i have installed already resolvconf, but it not fix issue.
to make dns to work i need to edit resolv.conf manually ;\

**Comment by angristan** [comment]
https://wiki.archlinux.org/index.php/OpenVPN#Update_systemd-resolved_script

**Comment by angristan** [comment]
Also what is the output of `systemd-resolve --status`?

**Comment by jam-2000** [comment]
`Global
          DNSSEC NTA: 10.in-addr.arpa
                      16.172.in-addr.arpa
                      168.192.in-addr.arpa
                      17.172.in-addr.arpa
                      18.172.in-addr.arpa
                      19.172.in-addr.arpa
                      20.172.in-addr.arpa
                      21.172.in-addr.arpa
                      22.172.in-addr.arpa
                      23.172.in-addr.arpa
                      24.172.in-addr.arpa
                      25.172.in-addr.arpa
                      26.172.in-addr.arpa
                      27.172.in-addr.arpa
                      28.172.in-addr.arpa
                      29.172.in-addr.arpa
                      30.172.in-addr.arpa
                      31.172.in-addr.arpa
                      corp
                      d.f.ip6.arpa
                      home
                      internal
                      intranet
                      lan
                      local
                      private
                      test

Link 22 (tun0)
      Current Scopes: none
       LLMNR setting: yes
MulticastDNS setting: no
      DNSSEC setting: no
    DNSSEC supported: no

Link 3 (wlp9s0)
      Current Scopes: DNS
       LLMNR setting: yes
MulticastDNS setting: no
      DNSSEC setting: no
    DNSSEC supported: no
         DNS Servers: 192.168.43.1

Link 2 (enp8s0)
      Current Scopes: none
       LLMNR setting: yes
MulticastDNS setting: no
      DNSSEC setting: no
    DNSSEC supported: no
`

**Comment by jam-2000** [comment]
i found this solution from arch forum when faced with this issue ...
i don't try it yet ...
but, if both scripts from arch forum (update-resolv-conf & update-systemd-resolved) will work,
then i will need to generate 3 config files:
1. for Linux with resolvconf
2. for Linux with systemd
3. for other systems (MacOS, iOS, Windows, Android, etc ...)

not good solution :\
because i have already 30 config files for 30 clients, and there will be more ...

i hope you can fix it somehow in more elegant way

**Comment by jam-2000** [comment]
so, in Ubuntu 18.04 i have to install the openvpn helper script for systemd-resolved:
sudo apt install openvpn-systemd-resolved

and in user.ovpn i need to add:
script-security 2
up /etc/openvpn/update-systemd-resolved
down /etc/openvpn/update-systemd-resolved

and after this steps everything starts to work ...
any way it's bad bug and it's not good solution

**Comment by kuntsman** [comment]
> @kuntsman After connecting this way, did you have any issue?
> 
> Can you install the `bind-utils` package and post the output of the `dig` command?
no it works fine and i can connect to the VPN  server, but i can't access the internet
this is my dig output

`$ dig

; <<>> DiG 9.11.4-P2-RedHat-9.11.4-10.P2.fc28 <<>>
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 1474
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 13, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1452
;; QUESTION SECTION:
;.				IN	NS

;; ANSWER SECTION:
.			112	IN	NS	c.root-servers.net.
.			112	IN	NS	d.root-servers.net.
.			112	IN	NS	e.root-servers.net.
.			112	IN	NS	f.root-servers.net.
.			112	IN	NS	g.root-servers.net.
.			112	IN	NS	h.root-servers.net.
.			112	IN	NS	i.root-servers.net.
.			112	IN	NS	j.root-servers.net.
.			112	IN	NS	k.root-servers.net.
.			112	IN	NS	l.root-servers.net.
.			112	IN	NS	m.root-servers.net.
.			112	IN	NS	a.root-servers.net.
.			112	IN	NS	b.root-servers.net.

;; Query time: 179 msec
;; SERVER: 192.168.1.1#53(192.168.1.1)
;; WHEN: Fri Nov 02 06:34:37 +03 2018
;; MSG SIZE  rcvd: 431`

i've installed this package https://github.com/jonathanio/update-systemd-resolved now and applied the configuration to the client i have , and its not resolved my problem

**Comment by kuntsman** [comment]
i dont think its a dns issue , i can't even ping 8.8.8.8

> $ ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
^C
--- 8.8.8.8 ping statistics ---
28 packets transmitted, 0 received, 100% packet loss, time 27668ms

**Comment by kuntsman** [comment]
look at this

> $ ping google.com
PING google.com (172.217.18.142) 56(84) bytes of data.
^C
--- google.com ping statistics ---
21 packets transmitted, 0 received, 100% packet loss, time 20482ms

**Comment by angristan** [comment]
@kuntsman Can you post the output of `ip r` on the client?

**Comment by kuntsman** [comment]
before connect 

> $ ip r
default via 192.168.1.1 dev wlo1 proto dhcp metric 600 
172.16.1.0/24 dev vmnet1 proto kernel scope link src 172.16.1.1 
172.16.51.0/24 dev vmnet8 proto kernel scope link src 172.16.51.1 
192.168.1.0/24 dev wlo1 proto kernel scope link src 192.168.1.108 metric 600 
192.168.122.0/24 dev virbr0 proto kernel scope link src 192.168.122.1 linkdown


after connect

> $ ip r
0.0.0.0/1 via 10.8.0.1 dev tun0 
default via 192.168.1.1 dev wlo1 proto dhcp metric 600 
10.8.0.0/24 dev tun0 proto kernel scope link src 10.8.0.2 
128.0.0.0/1 via 10.8.0.1 dev tun0 
140.82.32.201 via 192.168.1.1 dev wlo1 
172.16.1.0/24 dev vmnet1 proto kernel scope link src 172.16.1.1 
172.16.51.0/24 dev vmnet8 proto kernel scope link src 172.16.51.1 
192.168.1.0/24 dev wlo1 proto kernel scope link src 192.168.1.108 metric 600 
192.168.122.0/24 dev virbr0 proto kernel scope link src 192.168.122.1 linkdown

**Comment by angristan** [comment]
Seem ok.

On the server, what is the output of `iptables -nvL` and `iptables -nvL -t nat`?

**Comment by kuntsman** [comment]
> [root@vultr ~]# iptables -nvL
> Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
>  pkts bytes target     prot opt in     out     source               destination         
> 4493K  743M ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
>     0     0 ACCEPT     all  --  lo     *       0.0.0.0/0            0.0.0.0/0           
> 64175 5164K INPUT_direct  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
> 64175 5164K INPUT_ZONES_SOURCE  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
> 64157 5162K INPUT_ZONES  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
>  3775  399K DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0            ctstate INVALID
> 47243 3351K REJECT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            reject-with icmp-host-prohibited
> 
> Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
>  pkts bytes target     prot opt in     out     source               destination         
> 9370K 7695M ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
>     0     0 ACCEPT     all  --  lo     *       0.0.0.0/0            0.0.0.0/0           
>  149K   12M FORWARD_direct  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
>  149K   12M FORWARD_IN_ZONES_SOURCE  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
>     0     0 FORWARD_IN_ZONES  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
>     0     0 FORWARD_OUT_ZONES_SOURCE  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
>     0     0 FORWARD_OUT_ZONES  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
>     0     0 DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0            ctstate INVALID
>     0     0 REJECT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            reject-with icmp-host-prohibited
> 
> Chain OUTPUT (policy ACCEPT 6244K packets, 7654M bytes)
>  pkts bytes target     prot opt in     out     source               destination         
> 6250K 7655M OUTPUT_direct  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
> 
> Chain FORWARD_IN_ZONES (1 references)
>  pkts bytes target     prot opt in     out     source               destination         
>     0     0 FWDI_public  all  --  +      *       0.0.0.0/0            0.0.0.0/0           [goto] 
> 
> Chain FORWARD_IN_ZONES_SOURCE (1 references)
>  pkts bytes target     prot opt in     out     source               destination         
>  149K   12M FWDI_trusted  all  --  *      *       10.8.0.0/24          0.0.0.0/0           
> 
> Chain FORWARD_OUT_ZONES (1 references)
>  pkts bytes target     prot opt in     out     source               destination         
>     0     0 FWDO_public  all  --  *      +       0.0.0.0/0            0.0.0.0/0           [goto] 
> 
> Chain FORWARD_OUT_ZONES_SOURCE (1 references)
>  pkts bytes target     prot opt in     out     source               destination         
>     0     0 FWDO_trusted  all  --  *      *       0.0.0.0/0            10.8.0.0/24         
> 
> Chain FORWARD_direct (1 references)
>  pkts bytes target     prot opt in     out     source               destination         
> 
> Chain FWDI_public (1 references)
>  pkts bytes target     prot opt in     out     source               destination         
>     0     0 FWDI_public_log  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
>     0     0 FWDI_public_deny  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
>     0     0 FWDI_public_allow  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
>     0     0 ACCEPT     icmp --  *      *       0.0.0.0/0            0.0.0.0/0           
> 
> Chain FWDI_public_allow (1 references)
>  pkts bytes target     prot opt in     out     source               destination         
> 
> Chain FWDI_public_deny (1 references)
>  pkts bytes target     prot opt in     out     source               destination         
> 
> Chain FWDI_public_log (1 references)
>  pkts bytes target     prot opt in     out     source               destination         
> 
> Chain FWDI_trusted (1 references)
>  pkts bytes target     prot opt in     out     source               destination         
>  149K   12M FWDI_trusted_log  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
>  149K   12M FWDI_trusted_deny  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
>  149K   12M FWDI_trusted_allow  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
>  149K   12M ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0           
> 
> Chain FWDI_trusted_allow (1 references)
>  pkts bytes target     prot opt in     out     source               destination         
> 
> Chain FWDI_trusted_deny (1 references)
>  pkts bytes target     prot opt in     out     source               destination         
> 
> Chain FWDI_trusted_log (1 references)
>  pkts bytes target     prot opt in     out     source               destination         
> 
> Chain FWDO_public (1 references)
>  pkts bytes target     prot opt in     out     source               destination         
>     0     0 FWDO_public_log  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
>     0     0 FWDO_public_deny  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
>     0     0 FWDO_public_allow  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
> 
> Chain FWDO_public_allow (1 references)
>  pkts bytes target     prot opt in     out     source               destination         
> 
> Chain FWDO_public_deny (1 references)
>  pkts bytes target     prot opt in     out     source               destination         
> 
> Chain FWDO_public_log (1 references)
>  pkts bytes target     prot opt in     out     source               destination         
> 
> Chain FWDO_trusted (1 references)
>  pkts bytes target     prot opt in     out     source               destination         
>     0     0 FWDO_trusted_log  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
>     0     0 FWDO_trusted_deny  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
>     0     0 FWDO_trusted_allow  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
>     0     0 ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0           
> 
> Chain FWDO_trusted_allow (1 references)
>  pkts bytes target     prot opt in     out     source               destination         
> 
> Chain FWDO_trusted_deny (1 references)
>  pkts bytes target     prot opt in     out     source               destination         
> 
> Chain FWDO_trusted_log (1 references)
>  pkts bytes target     prot opt in     out     source               destination         
> 
> Chain INPUT_ZONES (1 references)
>  pkts bytes target     prot opt in     out     source               destination         
> 64157 5162K IN_public  all  --  +      *       0.0.0.0/0            0.0.0.0/0           [goto] 
> 
> Chain INPUT_ZONES_SOURCE (1 references)
>  pkts bytes target     prot opt in     out     source               destination         
>    18  2025 IN_trusted  all  --  *      *       10.8.0.0/24          0.0.0.0/0           
> 
> Chain INPUT_direct (1 references)
>  pkts bytes target     prot opt in     out     source               destination         
> 
> Chain IN_public (1 references)
>  pkts bytes target     prot opt in     out     source               destination         
> 64157 5162K IN_public_log  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
> 64157 5162K IN_public_deny  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
> 64157 5162K IN_public_allow  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
>  3688  368K ACCEPT     icmp --  *      *       0.0.0.0/0            0.0.0.0/0           
> 
> Chain IN_public_allow (1 references)
>  pkts bytes target     prot opt in     out     source               destination         
>  3485  216K ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:22 ctstate NEW
>  5966  829K ACCEPT     udp  --  *      *       0.0.0.0/0            0.0.0.0/0            udp dpt:1194 ctstate NEW
> 
> Chain IN_public_deny (1 references)
>  pkts bytes target     prot opt in     out     source               destination         
> 
> Chain IN_public_log (1 references)
>  pkts bytes target     prot opt in     out     source               destination         
> 
> Chain IN_trusted (1 references)
>  pkts bytes target     prot opt in     out     source               destination         
>    18  2025 IN_trusted_log  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
>    18  2025 IN_trusted_deny  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
>    18  2025 IN_trusted_allow  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
>    18  2025 ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0           
> 
> Chain IN_trusted_allow (1 references)
>  pkts bytes target     prot opt in     out     source               destination         
> 
> Chain IN_trusted_deny (1 references)
>  pkts bytes target     prot opt in     out     source               destination         
> 
> Chain IN_trusted_log (1 references)
>  pkts bytes target     prot opt in     out     source               destination         
> 
> Chain OUTPUT_direct (1 references)
>  pkts bytes target     prot opt in     out     source               destination    

     
> [root@vultr ~]# iptables -nvL -t nat
> Chain PREROUTING (policy ACCEPT 178K packets, 14M bytes)
>  pkts bytes target     prot opt in     out     source               destination         
>  178K   14M PREROUTING_direct  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
>  178K   14M PREROUTING_ZONES_SOURCE  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
>  178K   14M PREROUTING_ZONES  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
> 
> Chain INPUT (policy ACCEPT 9828 packets, 860K bytes)
>  pkts bytes target     prot opt in     out     source               destination         
> 
> Chain OUTPUT (policy ACCEPT 5029 packets, 367K bytes)
>  pkts bytes target     prot opt in     out     source               destination         
>  5286  383K OUTPUT_direct  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
> 
> Chain POSTROUTING (policy ACCEPT 5029 packets, 367K bytes)
>  pkts bytes target     prot opt in     out     source               destination         
>  127K   10M POSTROUTING_direct  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
>  5286  383K POSTROUTING_ZONES_SOURCE  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
>  5286  383K POSTROUTING_ZONES  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
> 
> Chain OUTPUT_direct (1 references)
>  pkts bytes target     prot opt in     out     source               destination         
> 
> Chain POSTROUTING_ZONES (1 references)
>  pkts bytes target     prot opt in     out     source               destination         
>  5286  383K POST_public  all  --  *      +       0.0.0.0/0            0.0.0.0/0           [goto] 
> 
> Chain POSTROUTING_ZONES_SOURCE (1 references)
>  pkts bytes target     prot opt in     out     source               destination         
>     0     0 POST_trusted  all  --  *      *       0.0.0.0/0            10.8.0.0/24         
> 
> Chain POSTROUTING_direct (1 references)
>  pkts bytes target     prot opt in     out     source               destination         
>  121K 9984K SNAT       all  --  *      *       10.8.0.0/24         !10.8.0.0/24          to:140.82.32.201
> 
> Chain POST_public (1 references)
>  pkts bytes target     prot opt in     out     source               destination         
>  5286  383K POST_public_log  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
>  5286  383K POST_public_deny  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
>  5286  383K POST_public_allow  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
> 
> Chain POST_public_allow (1 references)
>  pkts bytes target     prot opt in     out     source               destination         
> 
> Chain POST_public_deny (1 references)
>  pkts bytes target     prot opt in     out     source               destination         
> 
> Chain POST_public_log (1 references)
>  pkts bytes target     prot opt in     out     source               destination         
> 
> Chain POST_trusted (1 references)
>  pkts bytes target     prot opt in     out     source               destination         
>     0     0 POST_trusted_log  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
>     0     0 POST_trusted_deny  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
>     0     0 POST_trusted_allow  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
> 
> Chain POST_trusted_allow (1 references)
>  pkts bytes target     prot opt in     out     source               destination         
> 
> Chain POST_trusted_deny (1 references)
>  pkts bytes target     prot opt in     out     source               destination         
> 
> Chain POST_trusted_log (1 references)
>  pkts bytes target     prot opt in     out     source               destination         
> 
> Chain PREROUTING_ZONES (1 references)
>  pkts bytes target     prot opt in     out     source               destination         
>  178K   14M PRE_public  all  --  +      *       0.0.0.0/0            0.0.0.0/0           [goto] 
> 
> Chain PREROUTING_ZONES_SOURCE (1 references)
>  pkts bytes target     prot opt in     out     source               destination         
>  121K   10M PRE_trusted  all  --  *      *       10.8.0.0/24          0.0.0.0/0           
> 
> Chain PREROUTING_direct (1 references)
>  pkts bytes target     prot opt in     out     source               destination         
> 
> Chain PRE_public (1 references)
>  pkts bytes target     prot opt in     out     source               destination         
>  178K   14M PRE_public_log  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
>  178K   14M PRE_public_deny  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
>  178K   14M PRE_public_allow  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
> 
> Chain PRE_public_allow (1 references)
>  pkts bytes target     prot opt in     out     source               destination         
> 
> Chain PRE_public_deny (1 references)
>  pkts bytes target     prot opt in     out     source               destination         
> 
> Chain PRE_public_log (1 references)
>  pkts bytes target     prot opt in     out     source               destination         
> 
> Chain PRE_trusted (1 references)
>  pkts bytes target     prot opt in     out     source               destination         
>  121K   10M PRE_trusted_log  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
>  121K   10M PRE_trusted_deny  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
>  121K   10M PRE_trusted_allow  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
> 
> Chain PRE_trusted_allow (1 references)
>  pkts bytes target     prot opt in     out     source               destination         
> 
> Chain PRE_trusted_deny (1 references)
>  pkts bytes target     prot opt in     out     source               destination         
> 
> Chain PRE_trusted_log (1 references)
>  pkts bytes target     prot opt in     out     source               destination         
>

**Comment by kuntsman** [comment]
its working very well on android client @ics-openvpn

**Comment by angristan** [comment]
Can you do

```sh
iptables -F
iptables -X
iptables -t nat -F
systemctl restart iptables-openvpn
```

**Comment by asdonetheone** [comment]
Hi there, just wanted to say that I had some issues to run the script on a freshly installed CentOS 7.
I kept getting TLS key negotiation failed to occur within 60 seconds when trying to connect.
So after disabling the firewalld on the server and trying again the client would be able to connect but no internet access, so unable to open anything.

While the script worked completely fine on the same VPS till yesterday when I was running Ubuntu 18.04, it had issues to work on CentOS7, then once again after running a fresh copy of CentOS on the VPS I tried Nyr's script and worked correctly with firewalld enabled and not having to change anything.

I then tried the solution below:

stopping firewalld and running

> Can you do
> 
> ```shell
> iptables -F
> iptables -X
> iptables -t nat -F
> systemctl restart iptables-openvpn
> ```

this did allow me to connect and have Internet, then after re-enabling firewalld I added these rules:

sudo firewall-cmd --zone=trusted --add-service openvpn
sudo firewall-cmd --zone=trusted --add-service openvpn --permanent

sudo firewall-cmd --add-masquerade
sudo firewall-cmd --permanent --add-masquerade

sudo firewall-cmd --reload

and allowed me to connect while firewalld enabled.

Is there anything I were doing wrong? if so please address me. (Thanks again for your work.)
