### ISSUE TITLE
Routing Traffic

### ISSUE THREAD

**Issue by mxnavid** [angristan/openvpn-install#351]
Hi,
First of all thanks for this amazing repo. I have two Networks (Network A: 192.169.0.0/24 and Network B: 192.168.0.0/24). Webserver running in Network A in 192.169.0.4:3000. I am trying to access the webserver from Network B. 
A VPN Server (VM) with 2 network adapters (Connected to both Network A and B) and the client (Network B) is connected to VPN Server. When trying to access the Webserver from Network B, I am not able to access it. When doing TCPDump in VPN Server, I can see that the Client from network B is requesting the Webserver 192.169.0.4:3000, but the Webserver is not able to send it back to 10.0.0.8 (Tunnel)  (No clue where this IP range came from)

**Comment by randshell** [comment]
Hello,
I'm not sure, but does adding `push "route 192.169.0.0 255.255.255.0"` in `server.conf` work for you?

`10.0.0.8` is the internal IP the VPN assigned to the client. `10.0.0.1/24` is the VPN subnet.

**Comment by mxnavid** [comment]
Hi, 
thanks for the reply. I added it on the config file, but nothing changed. When pinging from Network B computer (Connected to VPN Server) to Network A computer , we can see it in wireshark at Network A. But in Network A there is 100% packet loss. I am just trying to establish communication from Network B to Network A using the VPN Server. 
![ping](https://user-images.githubusercontent.com/23007314/48438763-aec0b700-e752-11e8-9697-db694c3cf4a3.JPG)
