### ISSUE TITLE
No connection to server

### ISSUE THREAD

**Issue by datatrasher** [angristan/openvpn-install#353]
I recently used this script to replace a previous raspberry pi based home VPN solution. As far as I can tell the script has completed correctly however no clients can establish a VPN connection. Port forwarding is configured on my home router and logs on clients show that connection attempts are being established to my external IP on the standard port number 1194. "sudo netstat -lptu" does not appear to be showing port 1194 listening for connections, has some step failed in the script or are further actions necessary on my part to enable this on my part?

**Comment by angristan** [comment]
Where is the OpenVPN server installed? Is it one the Raspberry Pi?
