### ISSUE TITLE
Waiting for server response!

### ISSUE THREAD

**Issue by sadra** [angristan/openvpn-install#355]
Unfortunately, I can't connect to server!

The TunnelBlink always stock on "Waiting for server response"!
What should I do? Is there any needed configuration on my server?

My server from Hetzner.cloud:
Linux my-server 4.15.0-39-generic #42-Ubuntu SMP Tue Oct 23 15:48:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by x0r2d2** [comment]
Please, provide client log.

**Comment by angristan** [comment]
Is OpenVPN running on the server?

```sh
netstat -ulnp
netstat -tlnp
ps faux | grep openvpn
```
