### ISSUE TITLE
Connecting via dd-wrt

### ISSUE THREAD

**Issue by hacketaler** [angristan/openvpn-install#357]
Hi
I switched from the nyr-script. But now I have problems in my dd-wrt settings on my router.

I know how to paste the certs/keys to dd-wrt, but not sure about the differences in other settings.

from the client-ovpn-file:
client
proto udp
remote [IP] 1194
dev tun
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
verify-x509-name server_FKn6NInjol7A6usB name
auth SHA256
auth-nocache
cipher AES-128-GCM
tls-client
tls-version-min 1.2
tls-cipher TLS-ECDHE-ECDSA-WITH-AES-128-GCM-SHA256
setenv opt block-outside-dns # Prevent Windows 10 DNS leak
verb 3

for example: I could use AES-128 CBC encryption. But the client file shows AES-128-GCM?!
the settings in the config-field of dd-wrt are based on my settings with nyr-script.

Could you help me, what to use?

![dd-wrt](https://user-images.githubusercontent.com/45298900/48961517-86686200-ef75-11e8-9a25-ce8019971999.jpg)

**Comment by angristan** [comment]
If `AES-128-GCM` is not available on your router then choose AES-CBC during the install process.

Anything else?
