### ISSUE TITLE
Can i use the second IP-Adress for the Internet?

### ISSUE THREAD

**Issue by ghost** [angristan/openvpn-install#358]
Hello, i use on my Server two IP addresses, the first main IP is for the connecting to my OpenVPN Server and the second IP address will i use as a public ip address, can i config the OpenVPN Server that use my second IP address for the public web?
Must i change something in Iptables or server.conf? 
I used a different installer earlier, had the same problem, but after a change in Iptables it worked.

**Comment by angristan** [comment]
> I used a different installer earlier, had the same problem, but after a change in Iptables it worked.

Can you post what iptables change you did?

**Comment by ghost** [comment]
I don't know, the installer does not exist anymore.
All I know is Iptables had an IP address. And I had to change this IP address to make it work.
It's not like that in your installer, it's different!
