### ISSUE TITLE
Server poll timeout, trying next remote entry...

### ISSUE THREAD

**Issue by hampuskraft** [angristan/openvpn-install#359]
[Deleted for privacy reasons]

**Comment by angristan** [comment]
> my client firewall does not allow other connections than HTTP and HTTPS

HTTP(S) is working over TCP. I see you are using UDP. Did you try TCP?

**Comment by reckr** [comment]
You're a life saver! Thanks 👍

**Comment by nirupama123** [comment]
Can you please let us know the exact change made to make it work.Thanks
