### ISSUE TITLE
ARM not supported

### ISSUE THREAD

**Issue by clickwir** [angristan/openvpn-install#36]
Trying to run on an Odroid C1+ running Ubuntu 14.04. During install I see this message: 

W: Failed to fetch http://swupdate.openvpn.net/apt/dists/trusty/Release  Unable to find expected entry 'main/binary-armhf/Packages' in Release file (Wrong sources.list entry or malformed file)

Which seems to say that there isn't an ARM version available, thus the current repo only has version 2.3.2 and thus doesn't support tls-version-min. 

Here's what syslog reported when trying to start the openvpn service.

Feb 18 17:29:11 odroid ovpn-server[5160]: Options error: Unrecognized option or missing parameter(s) in /etc/openvpn/server.conf:23: tls-version-min (2.3.2)
Feb 18 17:29:11 odroid ovpn-server[5160]: Use --help for more information.
Feb 18 17:37:06 odroid ovpn-server[5284]: Options error: Unrecognized option or missing parameter(s) in /etc/openvpn/server.conf:23: tls-version-min (2.3.2)
Feb 18 17:37:06 odroid ovpn-server[5284]: Use --help for more information.

**Comment by angristan** [comment]
Yep, sadly. Until there an OpenVPN 2.4 ARM package for Ubuntu, Debian and CentOS, I can't do anything. Sorry !

**Comment by ghost** [comment]
Hi there, 
I recently spawned an arm64 instance @ scaleway, so after crying a little when I had to deal with missing packages and whatnot, here comes "OpenVPN and the chamber of secrets".  

As of now, debian jessie have OpenVPN 2.3.4-5+deb8u1 (arm64) :  
OpenVPN 2.3.4 aarch64-unknown-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [MH] [IPv6] built on Nov 20 2015

And this version supports "tls-version-min" and the newest algos just fine.

Sad quirk tho, the systemd service is retarded, so :  
cd /lib/systemd/system/
mv openvpn.service openvpn@.service

This will fix starting the server using "service openvpn start", service xyz start uses the openvpn@.service which is not properly starting openvpn.
"openvpn /etc/openvpn/server.conf" manually worked, but I just want to make sure if my server reboots / whatever, it will auto-start openvpn as well as the other softwares....

Anyway: TLDR: arm64 works again ;)

**Comment by angristan** [comment]
FYI I added the archs (https://github.com/Angristan/OpenVPN-install/commit/f4f8d0806730874c582bade84c5295cf2950dcf1).
