### ISSUE TITLE
No outgoing internet access within the server

### ISSUE THREAD

**Issue by 0xNeffarion** [angristan/openvpn-install#361]
Server OS: Ubuntu 16.04 (VPS)
Client OS: Ubuntu 18.10

The VPN works really well, except for the fact that the server itself has issues. Its DNS is failing.

I can ping IP's without issue:

> PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=123 time=1.13 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=123 time=1.47 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=123 time=1.15 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=123 time=1.34 ms
64 bytes from 8.8.8.8: icmp_seq=5 ttl=123 time=1.24 ms
64 bytes from 8.8.8.8: icmp_seq=6 ttl=123 time=1.41 ms
64 bytes from 8.8.8.8: icmp_seq=7 ttl=123 time=1.61 ms
^C
--- 8.8.8.8 ping statistics ---
7 packets transmitted, 7 received, 0% packet loss, time 6005ms
rtt min/avg/max/mdev = 1.130/1.337/1.611/0.166 ms

But if I ping a domain it doesn't even ping it once

> ping google.com
ping: unknown host google.com

Also, I am using UFW if that makes any difference

It cripples the whole server as I cant even update ubuntu lol

**Comment by 0xNeffarion** [comment]
Fixed it!  
I checked /etc/resolv.conf and found just this

> \# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
>\#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

It was empty, not a single DNS server. Once I added one, the DNS started working

Since it removes itself after reboot I installed dnsmasq

>sudo apt-get install dnsmasq

Then I edited its config file 

>sudo nano /etc/dnsmasq.conf

I added the servers at the end of the file like so

>server=1.1.1.1
server=1.0.0.1

saved and restarted, now it works well :)

**Comment by angristan** [comment]
Thanks for posting your solution :)
