### ISSUE TITLE
netflix doesn't work

### ISSUE THREAD

**Issue by tabi** [angristan/openvpn-install#362]
I got fresh install (VPS seted up 10 minutes ago, your script 5 minutes ago). New VPS.

And netflix still doesn't work and talking about Netflix.com/proxy

Is it only IP fault or OpenVPN?

**Comment by nxtreaming** [comment]
it's your VPS issue, 

The IP of your VPS is banned by Netflix.

**Comment by angristan** [comment]
Netflix bans all IP ranges of cloud providers ans hosting companies. (sadly)

**Comment by Leopere** [comment]
@nxtreaming  Best to stop supporting providers that ban VPN's.
