### ISSUE TITLE
Connecting to DB over VPN

### ISSUE THREAD

**Issue by vuckookv3** [angristan/openvpn-install#364]
So I have successfuly installed this VPN with the script on my server where also I am hosting mongoDB. (NOTICE: VPN and mongo on the same machine)
On the client side, I am connected to VPN (my IP address changes to the server)

Now, I want to connect to that db with simple **_mongo --host IP_**, but I am getting blocked by firewall (when I turn it off, I successfuly connect to it)

How can I enable UFW rules so it can forward or accept connections over VPN?

**Comment by randshell** [comment]
Hi!

```
sudo ufw allow from 10.8.0.1/24
```
Change with your VPN subnet if different.
