### ISSUE TITLE
Support lz4-v2

### ISSUE THREAD

**Issue by angristan** [angristan/openvpn-install#366]
Since OpenVPN 2.4, there is support for `lz4` compression. Apparently OpenVPN supports a faster version, `lz4-v2`, though it is currently undocumented.

https://community.openvpn.net/openvpn/ticket/820

**Comment by ookangzheng** [comment]
tried for days, it working pretty good on Mac, Android 9, Debian9

**Comment by angristan** [comment]
Thanks for the feedback 👍

**Comment by Firerouge** [comment]
You probably shouldn't be using compression at all. It tends to provide minimal gains with an increased security risk. See:
https://community.openvpn.net/openvpn/wiki/VORACLE
https://openvpn.net/security-advisory/the-voracle-attack-vulnerability/

Takaway, "the general consensus in the crypto community is that compression should be avoided. On top of that, a lot of the traffic that the VPN carry today is either already compressed or encrypted and cannot be compressed any more. So benefits are diminishing."
https://www.mail-archive.com/openvpn-devel@lists.sourceforge.net/msg17417.html

**Comment by angristan** [comment]
Yes, see https://github.com/angristan/openvpn-install#compression.
