### ISSUE TITLE
How to Add New Clients?

### ISSUE THREAD

**Issue by ekianjo** [angristan/openvpn-install#367]
HI, thanks for Openvpn-install this has been super useful so far.
I was wondering if there a way to add new clients that would not use the same certificate to connect? (or use the same certificate but use a different key?)

**Comment by randshell** [comment]
Hi, run again the script and select the option.

**Comment by angristan** [comment]
From the README:

> When OpenVPN is installed, you can run the script again, and you will get the choice to :
> 
> - Add a client
> - Remove a client
> - Uninstall OpenVPN

Let us know if you need more help.
