### ISSUE TITLE
TCP Packet length from client is out of range

### ISSUE THREAD

**Issue by jcouton** [angristan/openvpn-install#37]
Hi, 
I got this error when setting up openvpn using TCP configuration. 
> WARNING: Bad encapsulated packet length from peer (18516), which must be > 0 and <= 1574 -- please ensure that --tun-mtu or --link-mtu is equal on both peers -- this condition could also indicate a possible active attack on the TCP link -- [Attempting restart...]

No error using UDP, I tried several TCP configurations from the install script.

**Comment by nathan-fiscaletti** [comment]
Check your client's MTU. This is an issue primarily with the client, not the server. However, I'd also verify that `tun-mtu` in `server.conf` matches that of your client.
