### ISSUE TITLE
Error:  ./openvpn-install.sh: line 958

### ISSUE THREAD

**Issue by gituser0000** [angristan/openvpn-install#370]
New install of Debian 9.6.0 (4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux)

DL'd and ran script.  Used all defaults.

Right after setting "passwordless client" to default of 1 the script broke with this error:

> ./openvpn-install.sh: line 958: cd: /etc/openvpn/easy-rsa/: No such file or directory
> If you want to add more clients, you simply need to run this script another time!

I checked /etc/openvpn/eas* and this exists:

root@www1:/etc/openvpn# ls -l ea*
-rwxrwxr-x 1 1001 1001 38858 Sep 14 23:21 easyrsa
-rwxrwxr-x 1 1001 1001 38856 Sep 14 23:17 easyrsa-e

Not sure how to proceed!

Thanks!

**Comment by fuddel18** [comment]
I have just installed a VM with Debian 9.6 Clean Install and had no errors.

Debian 9.6 64bit Netinstall
- no desktop
- no webserver
- only standard tools
- SSH server only

The script I left everything on standard without password.

**Comment by gituser0000** [comment]
Debian 9.6 64bit DVD install
Normal install (non graphical)
Selected SSH
Set IP to Manual
Logged in
Configured networking
SSH'd in, switch to root
Modified apt-get sources to remove DVD and use standard debian servers
Set /etc/resolv.conf to use nameserver 8.8.8.8
wget the openvpn-install.sh into ~
chmod +x 
./openvpn-install.sh
default for all
error line 958


Just did it again in a VM environment and got the same error.

Brand new install, nothing done for any tun module or anything. 

The script is looking for /etc/openvpn/easy-rsa   yet the file directory doesn't exist.  This is confirmed.

**Comment by gituser0000** [comment]
I haven't touched anything with regards to openvpn, tun, nothing.  Brand spanking new Debian install from DVD on ESXi.

**Comment by fuddel18** [comment]
I also just downloaded and installed Debian Netinstall. My VM is running VMware Workstation Pro 14.1.3

**Comment by angristan** [comment]
Could you execute these lines manually ?

https://github.com/angristan/openvpn-install/blob/master/openvpn-install.sh#L612

**Comment by angristan** [comment]
@gituser0000 Can you do `ls -l /etc/openvpn/easy-rsa`? This is weird

**Comment by ogulec** [comment]
> @gituser0000 Can you do `ls -l /etc/openvpn/easy-rsa`? This is weird

`ls: cannot access '/etc/openvpn/easy-rsa': No such file or directory`

**Comment by angristan** [comment]
@ogulec is openvpn installed? (dpkg -l | grep openvpn)

**Comment by ogulec** [comment]
> @ogulec is openvpn installed? (dpkg -l | grep openvpn)

yes, it gives this error during the user creation with password step.

**Comment by angristan** [comment]
Can you open another issue will full details?

**Comment by ogulec** [comment]
today the script works like a charm, issue solved for me thanks for the help.

**Comment by gituser0000** [comment]
Was something updated?

**Comment by angristan** [comment]
No.

**Comment by sqerk** [comment]
Same error on Ubuntu 18, no easy-rsa folder.

**Comment by luk4s** [comment]
I had same problem on my CentOS 7. It was caused by "unfinished transactions" (`There are unfinished transactions remaining. You might consider running yum-complete-transaction, or "yum-complete-transaction --cleanup-only"`) - after that script working fine.
Maybe it helps 🙂

**Comment by zhyonc** [comment]
Same error on Centos7, no easy-rsa folder.

**Comment by angristan** [comment]
@luk4s Does it mean OpenVPN was not completely installed in your case ?

**Comment by ghost** [comment]
I had the same problem in a fresh Ubuntu 16.04.6 LTS install and fixed it doing a sudo apt-get upgrade, uninstalling the script and installing again. To uninstall the script run it and select the third option.

**Comment by angristan** [comment]
Maybe fixed with https://github.com/angristan/openvpn-install/commit/a0685af1a32f7a5729abcd9dbda1e08dfa4e75ab

**Comment by angristan** [comment]
If anyone has this problem again: please run the script with `bash -x openvpn-install.sh` on a clean server and post the output. It will help to debug the issue.
