### ISSUE TITLE
Upgrade to Ubuntu 18.04 from 16.04

### ISSUE THREAD

**Issue by redeuxx** [angristan/openvpn-install#372]
This isn't an issue since, but a quick question since it hasn't been address in the FAQ.

I am currently running Ubuntu Server 16.04.5. Is there a safe way to do an upgrade to 18.04 LTS while keeping my current certs for my users?

Thanks!

**Comment by angristan** [comment]
Hello,

Doing this upgrade should not affect your OpenVPN setup.

**Comment by redeuxx** [comment]
@angristan 

Thank you for the super-fast reply!
