### ISSUE TITLE
Not connecting on mobile

### ISSUE THREAD

**Issue by emad90sh** [angristan/openvpn-install#376]
Hello there,
Thank you for your perfect script
Actually the configuration file not working on IOS and Android , it just work on linux and windows platform
The OpenVpn mobile log file
![ovpn0log](https://user-images.githubusercontent.com/46196306/50484504-09158e80-0a06-11e9-8be2-20b7a7437ed6.jpg)

Server OS:Ubuntu 16.04 LTS
Official app (IOS & Android)

Thank you

**Comment by trochdewei** [comment]
@emad90sh can you try [OpenVPN for Android](https://play.google.com/store/apps/details?id=de.blinkt.openvpn)?

**Comment by angristan** [comment]
Please try with "OpenVPN for Android" and report back if it does not work.
