### ISSUE TITLE
Add client without menu

### ISSUE THREAD

**Issue by iambenmitchell** [angristan/openvpn-install#377]
Hello, I am trying to create a new user from a script. 

I want to do something like

./openvpn --newuser --name Ben --nopassword

**Comment by iambenmitchell** [comment]
Never mind I made my own just to do this. was easier than I thought. https://pastebin.com/NiEhrMjd

**Comment by angristan** [comment]
I'm reopening this because this is a nice to have feature.

**Comment by angristan** [comment]
See #422
