### ISSUE TITLE
Please Re-Open "Problem running on OpenVZ #129"

### ISSUE THREAD

**Issue by StuckUpCreations** [angristan/openvpn-install#378]
https://github.com/Angristan/OpenVPN-install/issues/129

im still having this problen on debian 9 minimal install and this solution propposed here solves my problem...after commenting out what is suggested here my service started and everything works as expected..

Debian 9 minimal install on OpenVZ

**Comment by angristan** [comment]
Hello, what line are you talking about? It's commented here: https://github.com/angristan/openvpn-install/blob/6e402289bd780efc535beba8cb9d85f766b291bf/openvpn-install.sh#L842

**Comment by angristan** [comment]
Let me know if you find the issue.

**Comment by parasquid** [comment]
Heya, sorry I just got here while debugging my own installation.

```
tristan@quadhost-nc:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial
```
It would seem like the OS detection is detecting that I have Ubuntu (which I do) but I am running on an OpenVZ host.

Copying and pasting the lines after the `else` in that if branch you linked got everything working.

**Comment by HenryNe** [comment]
The issure again.
```
daemon() failed or unsupported: Resource temporarily unavailable (errno=11)
```
The modifired file `/etc/systemd/system/openvpn@.service` seams not used by Debian 9.
I need to fix the file `/lib/systemd/system/openvpn@.service`, and comment out the **LimitNPROC**, to get it working.

```
# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.9 (stretch)
Release:        9.9
Codename:       stretch

```
