### ISSUE TITLE
Add feature that disable user after days.

### ISSUE THREAD

**Issue by n0b0dyvn** [angristan/openvpn-install#38]
Hi Angristan,

Can easyrsa auto expire user cert after n days? 

Thanks.

**Comment by angristan** [comment]
Yes : https://github.com/OpenVPN/easy-rsa/blob/master/easyrsa3/vars.example#L117
You can modify the script like here : https://github.com/Angristan/OpenVPN-install/blob/master/openvpn-install.sh#L402
