### ISSUE TITLE
Split tunneling ? 

### ISSUE THREAD

**Issue by Yfksw65** [angristan/openvpn-install#385]
Est-il prévu de faire une version du script proposant du split tunneling ? 

Je ne souhaite par exemple que mon VPN ne me permette uniquement d'acceder a mon LAN mais pas de me router tout le traffic a travers le VPN.

Il existe peut etre une autre façon de faire cela ? un truc simple ? J'ai peut être pas tout compris

Merci

**Comment by Yfksw65** [comment]
The correct configuration for OpenVpn is:

route-nopull 
route 192.168.0.0 255.255.255.0

These entries belong in your .ovpn file and will direct all 192.168.0.* subnet traffic through the VPN.

**Comment by Yfksw65** [comment]
It will work only for access on the server where openvpn is install not for other lan ressources..

i made a mistake ?

**Comment by randshell** [comment]
I found it documented [here](https://community.openvpn.net/openvpn/wiki/BridgingAndRouting). It's the first iptables rule in the "Using routing" section, the rest of the configuration is the same as yours.

**Comment by Yfksw65** [comment]
Thank you 

It work :+1:
