### ISSUE TITLE
Can connect after rebooting server (CentOS 6.5), but no internet. Any way to restart the service?

### ISSUE THREAD

**Issue by ghost** [angristan/openvpn-install#386]

**Comment by randshell** [comment]
See #356.

**Comment by ghost** [comment]
Thanks. 
I tried to run the mentioned commands, but `systemctl` is only on CentOS 7 and later. And `service restart ipatables-openvpn` gives me "unrecognized service".

**Comment by randshell** [comment]
I think you only have to use the firewalld-cmd commands: this was the final solution and confirmed by https://github.com/angristan/openvpn-install/issues/356#issuecomment-448141450 too.
Hope it helps.

**Comment by ghost** [comment]
Well, I don't think the firewall is the problem. Because even when it's disabled, I still have no internet.

I also checked with the firewall enabled and trusting openvpn... no success. Even restarting openvpn service with `service openvpn restart` didn't help.

The comment on [#365](https://github.com/angristan/openvpn-install/issues/356#issuecomment-448141450) mentions manually adding masquerade with `firewall-cmd --add-masquerade`, but how is it done on CentOS 6.5? There's no `firewall-cmd` in 6.5 and the only similar command I could find was this:

`iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE`

Is it the same thing? (I run this command, too! no luck)

**Comment by angristan** [comment]
If `eth0` is your interface, yes, this will enable NAT.

CentOS 6 is not supported, so I'm closing this.
