### ISSUE TITLE
OpenVPN Connect on Windows does not support tls-crypt

### ISSUE THREAD

**Issue by henstercoza** [angristan/openvpn-install#391]
Hi Hi 

The Installation went smooth and thank you for that  :) 

But wen i connect i keep on getting connection timed out 

**ip a**

```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: ens18: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 76:4a:83:73:5c:b5 brd ff:ff:ff:ff:ff:ff
    inet x.x.x.x/21 brd x.x.x.x scope global ens18
       valid_lft forever preferred_lft forever
    inet6 fe80::744a:83ff:fe73:5cb5/64 scope link
       valid_lft forever preferred_lft forever
4: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN group default qlen 100
    link/none
    inet 10.8.0.1/24 brd 10.8.0.255 scope global tun0
       valid_lft forever preferred_lft forever
    inet6 fe80::62ce:b8d5:b9a7:44e0/64 scope link stable-privacy
       valid_lft forever preferred_lft forever
```

**uname -a lsb_release -a**

`root@iscore:~# uname -a
Linux @@@@ 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
root@iscore:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic
`
_I also uncommented_

 # Uncomment the next line to enable packet forwarding for IPv4
net.ipv4.ip_forward=1

* I dont have ipv6 enabled on my server

**Comment by henstercoza** [comment]
I dont know if this midnight be the issue 

**sudo systemctl status openvpn@server**


`● openvpn@server.service - OpenVPN connection to server
   Loaded: loaded (/etc/systemd/system/openvpn@.service; indirect; vendor preset: enabled)
   Active: active (running) since Fri 2019-02-08 07:20:54 UTC; 4 days ago
     Docs: man:openvpn(8)
           https://community.openvpn.net/openvpn/wiki/Openvpn24ManPage
           https://community.openvpn.net/openvpn/wiki/HOWTO
 Main PID: 14016 (openvpn)
   Status: "Initialization Sequence Completed"
    Tasks: 1 (limit: 505)
   CGroup: /system.slice/system-openvpn.slice/openvpn@server.service
           └─14016 /usr/sbin/openvpn --daemon ovpn-server --status /run/openvpn/server.status 10 --cd /etc/openv

Feb 12 11:49:29 iscore ovpn-server[14016]: tls-crypt unwrap error: packet too short
Feb 12 11:49:29 iscore ovpn-server[14016]: TLS Error: tls-crypt unwrapping failed from [AF_INET]41.1xx5957
Feb 12 11:49:30 iscore ovpn-server[14016]: tls-crypt unwrap error: packet too short
Feb 12 11:49:30 iscore ovpn-server[14016]: TLS Error: tls-crypt unwrapping failed from [AF_INET]41.146xx:5957
Feb 12 11:49:31 iscore ovpn-server[14016]: tls-crypt unwrap error: packet too short
Feb 12 11:49:31 iscore ovpn-server[14016]: TLS Error: tls-crypt unwrapping failed from [AF_INET]41.1xx6:5957
Feb 12 11:49:32 iscore ovpn-server[14016]: tls-crypt unwrap error: packet too short
Feb 12 11:49:32 iscore ovpn-server[14016]: TLS Error: tls-crypt unwrapping failed from [AF_INET]41.146.xx:5957
Feb 12 11:49:33 iscore ovpn-server[14016]: tls-crypt unwrap error: packet too short
Feb 12 11:49:33 iscore ovpn-server[14016]: TLS Error: tls-crypt unwrapping failed from [AF_INETxx5957
lines 1-22/22 (END)
`

**Comment by angristan** [comment]
From what client are you connecting?

**Comment by henstercoza** [comment]
> From what client are you connecting?
windows 10 .. using openvpn connect 2.6.0.100

**Comment by angristan** [comment]
Can you show us the server.conf and client.ovpn files?

**Comment by henstercoza** [comment]
the err on log files of the client
Options error: Unrecognized option or missing parameter(s) in hennie.ovpn:22: tls-crypt (2.3.18)
Use --help for more information.
 
henster.ovpn below 

```
proto udp
remote 41.76.215.224 1194
dev tun
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
verify-x509-name server_YBKmERYXewxKn2Ot name
auth SHA256
auth-nocache
cipher AES-128-GCM
tls-client
tls-version-min 1.2
tls-cipher TLS-ECDHE-ECDSA-WITH-AES-128-GCM-SHA256
setenv opt block-outside-dns # Prevent Windows 10 DNS leak
verb 3
<ca>
-----BEGIN CERTIFICATE-----
xxxxxxxxxxxxx
-----END CERTIFICATE-----
</ca>
<cert>
-----BEGIN CERTIFICATE-----
xxxxxxxxxxxxxx
-----END CERTIFICATE-----
</cert>
<key>
-----BEGIN PRIVATE KEY-----
xxxxxxxxxxx
-----END PRIVATE KEY-----
</key>
<tls-crypt>
#
# 2048 bit OpenVPN static key
#
-----BEGIN OpenVPN Static key V1-----
xxxxxxxx
-----END OpenVPN Static key V1-----
</tls-crypt>

```

**Comment by henstercoza** [comment]
port 1194
proto udp
dev tun
user nobody
group nogroup
persist-key
persist-tun
keepalive 10 120
topology subnet
server 10.8.0.0 255.255.255.0
ifconfig-pool-persist ipp.txt
push "dhcp-option DNS 1.0.0.1"
push "dhcp-option DNS 1.1.1.1"
push "redirect-gateway def1 bypass-dhcp"
dh none
ecdh-curve prime256v1
tls-crypt tls-crypt.key 0
crl-verify crl.pem
ca ca.crt
cert server_YBKmERYXewxKn2Ot.crt
key server_YBKmERYXewxKn2Ot.key
auth SHA256
cipher AES-128-GCM
ncp-ciphers AES-128-GCM
tls-server
tls-version-min 1.2
tls-cipher TLS-ECDHE-ECDSA-WITH-AES-128-GCM-SHA256
status /var/log/openvpn/status.log
verb 3

**Comment by henstercoza** [comment]
this is my installed version 

  Installed: 2.4.4-2ubuntu1.1
  Candidate: 2.4.4-2ubuntu1.1
  Version table:
 *** 2.4.4-2ubuntu1.1 500
        500 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     2.4.4-2ubuntu1 500

**Comment by angristan** [comment]
Can you try to remove the `tls-crypt` parts?

**Comment by henstercoza** [comment]
id did this and still the same issue 
#tls-crypt tls-crypt.key 0

let me just delete it comply

**Comment by henstercoza** [comment]
nope same issue

**Comment by angristan** [comment]
Post logs?

**Comment by henstercoza** [comment]
OpenVPN CLIENT LIST
Updated,Tue Feb 26 17:22:55 2019
Common Name,Real Address,Bytes Received,Bytes Sent,Connected Since
ROUTING TABLE
Virtual Address,Common Name,Real Address,Last Ref
GLOBAL STATS
Max bcast/mcast queue length,0
END

oly thing i could find in the  /var/log/openvpn/status.l.og


and still in the client log file


status.log
root@iscore:/var/log/openvpn# sudo nano status.log
root@iscore:/var/log/openvpn# ls
status.log
root@iscore:/var/log/openvpn# cd ..
root@iscore:/var/log# cd syslog
bash: cd: syslog: Not a directory
root@iscore:/var/log# sudo nano syslog
  GNU nano 2.9.3

**Comment by henstercoza** [comment]
set the verb to 6 on client and server but not getting any new log's

**Comment by randshell** [comment]
Hi! The openvpn connect app doesn't seem to work with some latest openvpn features used in this script, in this case tls-crypt.
You can try installing again using tls-auth instead or use another client app, for example https://github.com/OpenVPN/openvpn-gui/.

**Comment by angristan** [comment]
Oops! I did not realise you were using this client, even though I asked, sorry. As @randomshell said, please use the official client: https://openvpn.net/community-downloads/

**Comment by henstercoza** [comment]
I got it to work , thank you so much :)

**Comment by earlelnar** [comment]
> Oops! I did not realise you were using this client, even though I asked, sorry. As @randomshell said, please use the official client: https://openvpn.net/community-downloads/

Thanks working from my end!
