### ISSUE TITLE
Script don't recognizes an existing prior created openvpn installation or users with the script

### ISSUE THREAD

**Issue by Zuendapp** [angristan/openvpn-install#394]
Hi :),

it's a very nice script, thank you very much!
I have one little problem. I want to add a new user but the script doesn't recognize that there is already an installation respectively existing users. How can I tell the script that there is already a config etc. ?

Thank you very much!

BR

**Comment by angristan** [comment]
Did you install OpenVPN with the script?

**Comment by Zuendapp** [comment]
Hi,

yes I installed it with the Script!
Creating a second and third user worked also.

BR

**Comment by angristan** [comment]
Does `/etc/openvpn/server.conf` exist on the server?

**Comment by Zuendapp** [comment]
I renamed it because I created a second config with tcp.

BR

**Comment by Zuendapp** [comment]
I tried it to rename my server.conf, now it works :)! Thank you very much!

Another question... is it possible to change a user pem password afterwards?

Thank you!

BR

**Comment by randshell** [comment]
The script looks for `/etc/openvpn/server.conf` to know if openvpn it's installed. You might `touch` it to get it working.

@Angristan can we check for `*.conf` instead of the hardcoded `server.conf` because of these use cases?

**Comment by randshell** [comment]
You can't change the password, but you can revoke and add it again, not sure if it allows the same name though.

**Comment by angristan** [comment]
@randomshell It's not a bad idea, but I don't want to support anything that is not 100% managed by the script, so I won't add this.

**Comment by Zuendapp** [comment]
Thank you very much! In case of adding a new user for example, I will rename the config temporary.

BR
