### ISSUE TITLE
Revert commit removing OpenNIC

### ISSUE THREAD

**Issue by Kcchouette** [angristan/openvpn-install#4]
Hello,

I don't understand why you remove  OpenNIC servers on the commit https://github.com/Angristan/OpenVPN-install/commit/903270be4ba25c169843fee3a55428ff98060f82.
I think that openDNS is less trustable than openNIC (because of Cisco and more). Moreover, some openNIC server have dnscrypt activated.

So why do you remove it?

**Comment by angristan** [comment]
> I think that openDNS is less trustable than openNIC (because of Cisco and more).

Well, yes and no. I don't recommend using OpenDNS, I don't use it, and I don't like it. (same for Google)
I let Google DNS and OpenDNS as a choice because they're the only Anycast DNS public resolvers I know, and thus providing a quick latency all around the world.

There is 2 other DNS options, but if you're not in western Europe, they're not a great choice in term of latency.

As for OpenNIC, everyone can setup a server and do whatever he wants about the queries, the logs, etc. I don't have much trust in this kind of 3rd-party individuals. Moreover, the uptime of the OpenNIC servers is really bad.

>Moreover, some openNIC server have dnscrypt activated.

That's a great feature, but it doesn't change anything to the problem (the script does not use it).

If you have any worldwide trustable alternative, I'll take it :)

**Comment by Kcchouette** [comment]
At first I used 
- 185.121.177.177
- 185.121.177.53

It's worldwide DNS resolver on openNIC. (https://servers.opennicproject.org/edit.php?srv=ns1.any.dns.opennic.glue)

Now I'm planning on searching how to build a DNS resolver for my VPN.

**Comment by angristan** [comment]
Indeed OpenNIC have some Anycast servers, but they can be down at any time, like ns2.any.dns.opennic.glue which was up a few months ago.

Using a local DNS resolver is possible, simply install unbound (https://github.com/Angristan/Local-DNS-resolver) and allow your private network, then set 10.8.0.1 as your resolver. I'm considering to add this as an option.

**Comment by Kcchouette** [comment]
It would be great. What about adding dnscrypt/no log option?

**Comment by angristan** [comment]
DNSCrypt is just a way of making the DNS request, we have to find the appropriate DNS resolvers too.

What do you mean by no log ?

**Comment by Kcchouette** [comment]
I mean, that:

>whatever he wants about the queries, the logs, etc.

Avoid to do that.

**Comment by angristan** [comment]
You can't do anything about that unless you're running you own DNS server, which is the best option for speed, neutrality, privacy, etc.

**Comment by Kcchouette** [comment]
Yes, I speak about doing that on your own local dns resolver script.

**Comment by angristan** [comment]
If you don't specify the logging options in the conf, it won't log anything

**Comment by m0r0n** [comment]
Hey @Angristan,

There is a danish organisation offering Anycast DNS
https://blog.censurfridns.dk/

Also there are more good ones:
https://www.privacyfoundation.ch/de/service/server.html
https://digitalcourage.de/support/zensurfreier-dns-server
or 213.73.91.35 from the CCC, which is probably known in Europe.

By the way, in #5 you suggested to have local resolvers. Can communication to the DNS root servers somehow be encrypted as well? Or will everybody on the way (all hops) from my VPN server to the next root server know what I just query?

**Comment by angristan** [comment]
Thanks I'll take a look.

> By the way, in #5 you suggested to have local resolvers. Can communication to the root server somehow be encrypted as well? Or will everybody on the way from my VPN server to the next root server know what I just query?

DNS queries are not encrypted, that inherent to the DNS protocol as for now. :/

**Comment by m0r0n** [comment]
> DNS queries are not encrypted, that inherent to the DNS protocol as for now. :/

It's a shame, that even with DNSSEC there is no way of encrypting the actual queries :(

**Comment by Kcchouette** [comment]
imo DNScrypt encrypt the request. More info on: https://dnscrypt.org/

**Comment by m0r0n** [comment]
Still you need to get DNS data from somewhere and the IANA root servers don't seem to support it.

**Comment by angristan** [comment]
DNScrypt only solves one part of the problem : 
- Yes, client <=> DNSCrypt server request are encrypted.
But : 
- Third party server with all the problems linked
- DNSCrypt server <=> root servers request are not encrypted

**Comment by Kcchouette** [comment]
I think having `client <-(dnscrypt)-> our server <-(dnscrypt)->other DNSCrypt server <-(normal)-> root server` is better than `client <-(normal)-> DNS <-(normal)-> root server`
