### ISSUE TITLE
Port forward to clien OpenVPN

### ISSUE THREAD

**Issue by error105** [angristan/openvpn-install#400]
Hello, i have big problem with port forwad to my OpenVPN clients :(
My WAN and network with open IP is enp1s0, and OpenVPN have tun0.
Clients in OpenVPN have static IP, but anyway i cant push e.g port 80 to my client 10.8.0.10.
Anybody can helps me ?

**Comment by Digital1012** [comment]
use iptables to port forward the port(s) you need.
 iptables -t nat -A PREROUTING -p tcp --dport porthere -j DNAT --to 10.8.0.10

**Comment by error105** [comment]
I try it but it doesn't work, and I don't have connection from outside to my PC :(

**Comment by angristan** [comment]
What about from your server to the client?

**Comment by cellulosa** [comment]
I have the same question! I found [this](https://github.com/angristan/openvpn-install/issues/224#issuecomment-392328780) but the Open Port Check Tool keeps saying the port is not open...

**Comment by Digital1012** [comment]
When you issue the iptables command be sure to save iptables rules and make sure your using the correct ip address i listed 10.8.0.10 but it should be your ip given by openvpn. Also make sure to change porthere to the port you want open. Also make sure you have the service or program running so it will be open.
