### ISSUE TITLE
One click script for wireguard

### ISSUE THREAD

**Issue by rvpn** [angristan/openvpn-install#406]
Hi Sir, will you make a script for wireguard too?

**Comment by MightyDouro** [comment]
That would be TOP!!  :)

**Comment by angristan** [comment]
See #331

Also since I am using Wireguard myself, I made a tutorial: https://angristan.xyz/how-to-setup-vpn-server-wireguard-nat-ipv6/

I'll think about the design of the script when I have the time

**Comment by angristan** [comment]
See https://github.com/angristan/wireguard-install for a WIP 😬
