### ISSUE TITLE
Just for all wondering, this script does not mysteriously work on Google Compute Engine. 

### ISSUE THREAD

**Issue by ishmumx** [angristan/openvpn-install#407]
Hi all, don't try this script on Google Compute Engine. I tried installing this on different distros, different networks, etc and nothing worked. I used the nyr version and weirdly enough that worked. No idea why, but just thought I'd let you know so you don't pull your hair out haha.

**Comment by BelleNottelling** [comment]
Did you open the port in the compute instance ?

**Comment by ishmumx** [comment]
> Did you open the port in the compute instance ?

I did. In fact, the firewall was entirely disabled.

Pic:

![image](https://user-images.githubusercontent.com/37858032/54331162-e000a500-45d5-11e9-8ca2-3e1a427a9b54.png)

**Comment by angristan** [comment]
Hello,

What do you mean by "nothing worked"?

**Comment by ishmumx** [comment]
Couldn't ping anything besides the IP itself.

**Comment by angristan** [comment]
Which IP?

**Comment by ishmumx** [comment]
> Which IP?

The External IP of the VM Instance. I can make a VM and provide you the ssh if you'd like?

**Comment by Dan-Wood** [comment]
#409 

Could be similar.

**Comment by angristan** [comment]
Just tried this on a Debian 9 Compute Engine and everything went fine.

**Comment by deval** [comment]
i can confirm that this work on compute engine. either with tcp or udp. just dont forget to open ports. 

the script will ask two ip, i just enter the internal (default), and external ip when asked if its using nat.

im using google dns.

**Comment by dollabi11z** [comment]
I have actually never tried Google Cloud Engines now is a good time 2 start hhaha. First thing I will do is try out my fav script here ive used for years but has let me down past few months. I only run Bionic right now. Before bionic i used trusty, yes, trusty up until last year : and this script worked flawlessly on it
