### ISSUE TITLE
Reinstall the script doesnt make a network interface???

### ISSUE THREAD

**Issue by ItsMennyo** [angristan/openvpn-install#408]
Ok so, I uninstalled the script to change the ip and port (even while I could change that manually but I did not thinked about that at that time) but now when I install the script again on the same Ubuntu 18.04 install, it doesn't create a network interface called tun0 while it did that before. I checked the iptables files and they are still there but I guess something goes wrong here and I don't know what 😉

**Comment by angristan** [comment]
Hello,

Is OpenVPN running? The tun interface only exist when it is.

**Comment by ItsMennyo** [comment]
It was running...

**Comment by angristan** [comment]
Did OpenVPN work then?

**Comment by ItsMennyo** [comment]
It was in a loaded/active state. I only could not connect to it with the error message:
`TCP: connect to [AF_INET]***.**.**.**:443 failed: Unknown error`
I selected a 2nd IP that is available on the machine to use port 443 there so.

**Comment by ItsMennyo** [comment]
But I guess something is messed up in the script or on my os install because if I try to reinstall it again, I see a lot of `No such file or directory` messages... I prob have to reinstall the OS this time.
