### ISSUE TITLE
iOS cannot connect: Connection timeout

### ISSUE THREAD

**Issue by ajthemacboy** [angristan/openvpn-install#41]
Using an .ovpn file generated with the script in the `master` branch, the OpenVPN app on iOS fails to connect.

Here is the log: https://gist.githubusercontent.com/ajthemacboy/657d7a4e3aa94db351f2ce3940fbc1ec/raw/451667b20a7dc2f3e747147afcdea2ef6dcbf1dc/gistfile1.txt

I can connect using this same .ovpn file with my desktop, which is on the same LAN/network as iOS.

**Comment by ghost** [comment]
You are running multiple OpenVPN clients with the same profile (.ovpn file)
Run the script again and choose 1 (add a cert for new user)

p.s. hide your server ip address from the text file

**Comment by ajthemacboy** [comment]
Thanks, creating a new cert fixed it... It's my LAN IP so I don't care about it.
