### ISSUE TITLE
MikroTik

### ISSUE THREAD

**Issue by ADMiNZ** [angristan/openvpn-install#410]
Hello. Hardware MikroTik currently only supports md5 | sha1. Add sha1 & md5 support to the script.

Thank you very much in advance.

**Comment by ADMiNZ** [comment]
Hello.

Why? Is it very difficult to do?

**Comment by randshell** [comment]
Hi,
this script is security focused, so no sha1 or worse md5. Anyway there are other scripts that should support your use case.

**Comment by angristan** [comment]
Hello,

md5 and sha1 are deprecated protocols that should not be used in 2019. The goal of this script is to use state-of-the-art encryption.

**Comment by cyberbob61** [comment]
FYI: Stable routeros version 7.8 supports SHA256, SHA512
