### ISSUE TITLE
How to change the default OpenVPN subnet?

### ISSUE THREAD

**Issue by nxtreaming** [angristan/openvpn-install#414]
Thanks for the great script!

The default openvpn subnet is 10.8.0.1/24 in this script.

I try to replace all the 10.8.0.1 to 10.123.0.1 in the script before installation, but the OpenVPN instance still uses the default 10.8.0.1/24

So how to use another subnet, such as 10.123.0.1/24? 

Thanks.

**Comment by angristan** [comment]
Make sure to replace all `10.8.0.1` **and** `10.8.0.0`

**Comment by nxtreaming** [comment]
Thanks, I forget 10.8.0.0
