### ISSUE TITLE
Google GCP MTU 1500 cause Ovpn TCP download speed slow.

### ISSUE THREAD

**Issue by ookangzheng** [angristan/openvpn-install#424]
Im using  TCP on google cloud GCP Debian9 with Openvpn TCP.
cuz Google eth0 default MTU is 1500, the download speed on Openvpn very slow, around 2xx kbps, When I change MTU from 1500 to 1460, then download speed works perfectly.
Any suggestion on Google GCP MTU tweak?

**Comment by ookangzheng** [comment]
Sorry, is Google GCP eth0 default MTU is 1460, everyting works fine. 
When I also installed iKEV2 strongswan on the same VPS, I have to modified eth0 MTU to 1500, other wise iKEV2 will got UDP fragmentation. then cause Openvpn download speed dropped to 2xx kbps.

So far this problem has been fixed, I set some thing like this on iptables with MTU I tested which working fine with iKEV2 and Openvpn without changing eth0 MTU to 1500
```
*mangle
-A FORWARD -o eth0 -p tcp -m policy --dir in --pol ipsec -m tcp --tcp-flags SYN,RST SYN -s 10.10.10.0/24  -m tcpmss --mss 1280:1500 -j TCPMSS --set-mss 1310
-A FORWARD -o eth0 -p tcp -m policy --dir out --pol ipsec -m tcp --tcp-flags SYN,RST SYN -s 10.10.10.0/24 -m tcpmss --mss 1280:1500 -j TCPMSS --set-mss 1310
```

**Comment by angristan** [comment]
Thanks for the feedback!
