### ISSUE TITLE
Unable to start unbound

### ISSUE THREAD

**Issue by Galac512** [angristan/openvpn-install#427]
OS: `Debian GNU/Linux 9 (stretch/stable)`
Linux: `4.9.0-9-amd64`
Unbound: `1.6.0`
OpenVPN: ` 2.4.0 x86_64-pc-linux-gnu (build with openssl)`

Hello, I am unable to start unbound after installing it with the script.

`systemctl status unbound` returns
```
● unbound.service - Unbound DNS server
   Loaded: loaded (/lib/systemd/system/unbound.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2019-06-05 21:15:16 CEST; 32min ago
     Docs: man:unbound(8)
  Process: 1199 ExecStart=/usr/sbin/unbound -d $DAEMON_OPTS (code=exited, status=1/FAILURE)
  Process: 1195 ExecStartPre=/usr/lib/unbound/package-helper root_trust_anchor_update (code=exited, status=1/FAILURE)
  Process: 1190 ExecStartPre=/usr/lib/unbound/package-helper chroot_setup (code=exited, status=1/FAILURE)
 Main PID: 1199 (code=exited, status=1/FAILURE)

Jun 05 21:15:16 balthazar systemd[1]: unbound.service: Unit entered failed state.
Jun 05 21:15:16 balthazar systemd[1]: unbound.service: Failed with result 'exit-code'.
Jun 05 21:15:16 balthazar systemd[1]: unbound.service: Service hold-off time over, scheduling restart.
Jun 05 21:15:16 balthazar systemd[1]: Stopped Unbound DNS server.
Jun 05 21:15:16 balthazar systemd[1]: unbound.service: Start request repeated too quickly.
Jun 05 21:15:16 balthazar systemd[1]: Failed to start Unbound DNS server.
Jun 05 21:15:16 balthazar systemd[1]: unbound.service: Unit entered failed state.
Jun 05 21:15:16 balthazar systemd[1]: unbound.service: Failed with result 'exit-code'.
```

When I run `unbound` manually, I get:
```
[1559764033] unbound[4700:0] error: can't bind socket: Address already in use for 10.8.0.1
[1559764033] unbound[4700:0] fatal error: could not open ports
```

By running `lsof -Pni | egrep "(UDP|LISTEN)"`, I found that `named` was already using the DNS port (53). So I killed named to see if unbound would work, but I still get the same error.

**Comment by angristan** [comment]
> By running lsof -Pni | egrep "(UDP|LISTEN)", I found that named was already using the DNS port (53). So I killed named to see if unbound would work, but I still get the same error.

Are you sure nothing is binding on port 53 even after killing bind?

**Comment by Galac512** [comment]
I tried to change the port to 9595 but I got the same error. By the way I'm using `ufw` as a firewall, it may be what's blocking the ports.

**Comment by angristan** [comment]
You changed the port to 9595 for unbound or openvpn?
