### ISSUE TITLE
Can I manage the VPN with this Web Panel?

### ISSUE THREAD

**Issue by draft1** [angristan/openvpn-install#428]
Instead of doing it on CLI, I would like to do it on web panel using this:
https://github.com/Chocobozzz/OpenVPN-Admin

Thanks!

**Comment by angristan** [comment]
Hello,

No, these are too separate projects. You can manage the whole OpenVPN server using OpenVPN-Admin only, you can't mix the two

**Comment by x0r2d2** [comment]
@angristan 
Maybe it will be better just do it with simple Web UI with httpd? 
Just for creating, downloading and revoking clients.
If somebody will need something more from it, they can use Openvpn Monitor - https://github.com/furlongm/openvpn-monitor
http://openvpn-monitor.openbytes.ie/
