### ISSUE TITLE
Feature: Listen on multiple ports

### ISSUE THREAD

**Issue by ghost** [angristan/openvpn-install#43]
Hi. 

As of now I'm using my VPN server both at home and other networks. I've experienced that custom ports might be blocked on public networks. Would it be possible to implement setup on both default port and a custom defined port (ex. 443/TCP)?

**Comment by atulsian89** [comment]
An alternative method is to use <connection> on the server configuration file. We can setup a  combined' client profile that cycles through UDP port 8757, TCP port 636, and TCP port 443. Refer to the below link for more details
Credit : https://github.com/jlund/streisand/pull/504
https://community.openvpn.net/openvpn/wiki/Openvpn24ManPage

**Comment by ghost** [comment]
Hello,

could you please give some more info how to do that? I'm pretty new to this (this is why I use the script provided here instead to do all manually) and feel a bit lost. Indeed it seems that, e.g., Telekom blocks VPN traffic so a tunnel over port 80 or 443 would be great.

**Comment by angristan** [comment]
@antares2001 Just choose any port you want during the setup :)

**Comment by ghost** [comment]
@Angristan does the setup provide the ability for multiple ports?

**Comment by angristan** [comment]
@antares2001 No, just one port, either TCP od UDP

**Comment by ghost** [comment]
@Angristan So it would mean principally that I have to run multiple servers? Could you be so kind to provide a hint how to get it running on 443/tcp and 1194/udp? I must say I have not managed to get any further, which might be due to the fact that I'm fairly new to OpenVPN and that's the reason I use your script instead of setting it up myself.

You did a great job with this script and it would be so great if it provided the ability to run on 2 ports, as for my experience 1194/udp delivers much faster service, while some hotels and open WiFi only allow "standard ports" like 443 and tcp, so there I'd have to use that "downgraded" connection.

Thanks a lot!

**Comment by angristan** [comment]
Closing this, see #28
