### ISSUE TITLE
Don't route internet traffic through the VPN

### ISSUE THREAD

**Issue by razvanstr** [angristan/openvpn-install#431]
The openvpn works just fine with the default options from the script, but I don`t want all traffic to be routed through vpn so I removed 

push "redirect-gateway def1 bypass-dhcp"
push "dhcp-option DNS 192.168.1.1"

after restarting the openvpn service and reconnecting to vpn, the browser says " No internet connection"

I can ping 8.8.8.8 and 10.8.0.1, but if I try to ping 192.168.1.120 (openvpn server) or 192.168.1.1 (network gw) it fails.

The server is on Ubuntu 18.04 and the client is Windows 10 with Openvpn community client.
Is there anything I need to add or remove from server/client config?

@angristan maybe this should be an option in the script, if you want or not that Internet traffic to be routed through vpn.

**Comment by avxkim** [comment]
Agree, would be nice if it will be implemented in this script.

This line in server.conf disabled default gateway for VPN connection:

```
push "redirect-gateway def1 bypass-dhcp"
```

But then, i can't access anything from VPN, using Shimo VPN client.

**Comment by angristan** [comment]
#443
