### ISSUE TITLE
Add to wiki: openVPN in a LXC-Container (f.e. Proxmox)

### ISSUE THREAD

**Issue by Norrodar** [angristan/openvpn-install#436]
Hey,
I looked for a solution for my proxmox, lxc-container problem for many days. Now I found a solution and shared it in the wiki from nyx:
https://github.com/Nyr/openvpn-install/wiki/How-to-setup-openVPN-in-a-LXC-container-(f.e.-Proxmox)

You may add it to your wiki/FAQ? (:

**Comment by angristan** [comment]
Thanks! I added it.
