### ISSUE TITLE
what ports shall I keep open in firewall to let this openvpn with cloudflare anycast DNS works?

### ISSUE THREAD

**Issue by perfectpeach** [angristan/openvpn-install#437]
Hi,

what ports shall I keep open in firewall to let this openvpn with Cloudflare anycast DNS works? I' unable to connect after 'firewalld' in centos7 is enabled. I added the 1194/UDP port, but I think this is not enough, maybe a port for DNS should be opened too? Could you list me all the ports that need to e open to this works? I'm using option<3> in DNS selection, as Cloudflare Anycast. ?

Best regards

**Comment by angristan** [comment]
DNS is UDP 53

**Comment by perfectpeach** [comment]
Tnx @angristan
