### ISSUE TITLE
Not working on Android

### ISSUE THREAD

**Issue by ghost** [angristan/openvpn-install#44]
I have used your script on my server and with Windows 10 and the official OpenVPN GUI app everything works like a charm.

But it's not working on my Android 7.1 phone. I have imported the same .ovpn file which I used on my Desktop and I cannot ping anything (or connect to anything). And no, I'm not connected on my PC and the phone at the same time.

The connection is established without issues, I cannot see anything in the logs. 

Do I have to use some special connection settings to make this work with the official Android App from OpenVPN?

**Comment by Kcchouette** [comment]
What app do you use from android? I personnaly use [OpenVPN for Android](https://play.google.com/store/apps/details?id=de.blinkt.openvpn)

**Comment by ghost** [comment]
Yes me too. But I have found out another issue: Now it's not even working on my Windows Client. 

It was working without any issue and now it just connects and I cannot ping anything, not even the server itself. Do you have any suggestions?

**Comment by Kcchouette** [comment]
is the process openvpn working on your server? (use `top`/`htop` to check that)

**Comment by ghost** [comment]
Yes the process is still running, via systemctl status openvpn@server.service

**Comment by angristan** [comment]
If you restart the server, does it work ?

**Comment by ghost** [comment]
I've tried that too and I've disabled all of my iptables rules just to be sure.

**Comment by Kcchouette** [comment]
@bodkov did you check your log? (I've no idea why it's not working in your case)

**Comment by ghost** [comment]
Yes. 

Server.log (Y.Y.Y.Y is my external ip from my network)

Y.Y.Y.Y:54356 TLS: Initial packet from [AF_INET]Y.Y.Y.Y:54356, sid=692cbb53 82df8468
Y.Y.Y.Y:54356 CRL CHECK OK: CN=ChangeMe
Y.Y.Y.Y:54356 VERIFY OK: depth=1, CN=ChangeMe
Y.Y.Y.Y:54356 CRL CHECK OK: CN=bodkov
Y.Y.Y.Y:54356 VERIFY OK: depth=0, CN=bodkov
Y.Y.Y.Y:54356 Data Channel Encrypt: Cipher 'AES-128-CBC' initialized with 128 bit key
Y.Y.Y.Y:54356 Data Channel Encrypt: Using 256 bit message hash 'SHA256' for HMAC authentication
Y.Y.Y.Y:54356 Data Channel Decrypt: Cipher 'AES-128-CBC' initialized with 128 bit key
Y.Y.Y.Y:54356 Data Channel Decrypt: Using 256 bit message hash 'SHA256' for HMAC authentication
Y.Y.Y.Y:54356 Control Channel: TLSv1.2, cipher TLSv1/SSLv3 DHE-RSA-AES128-GCM-SHA256, 2048 bit RSA
Y.Y.Y.Y:54356 [bodkov] Peer Connection Initiated with [AF_INET]Y.Y.Y.Y:54356
bodkov/Y.Y.Y.Y:54356 MULTI_sva: pool returned IPv4=10.8.0.2, IPv6=(Not enabled)
bodkov/Y.Y.Y.Y:54356 MULTI: Learn: 10.8.0.2 -> bodkov/Y.Y.Y.Y:54356
bodkov/Y.Y.Y.Y:54356 MULTI: primary virtual IP for bodkov/Y.Y.Y.Y:54356: 10.8.0.2
 bodkov/Y.Y.Y.Y:54356 PUSH: Received control message: 'PUSH_REQUEST'
bodkov/Y.Y.Y.Y:54356 send_push_reply(): safe_cap=940
 bodkov/Y.Y.Y.Y:54356 SENT CONTROL [bodkov]: 'PUSH_REPLY,dhcp-option DNS 84.200.69.80,dhcp-option DNS 84.200.70.40,redirect-gateway def1 bypass-dhcp,route-gateway 10.8.0.1,topology subnet,ping 10,ping-restart 120,ifconfig 10.8.0.2 255.255.255.0' (status=1)


Client Log (Where X.X.X.X is the remote server where your script is installed)

Thu Mar 23 21:17:35 2017 OpenVPN 2.4.0 x86_64-w64-mingw32 [SSL (OpenSSL)] [LZO] [LZ4] [PKCS11] [AEAD] built on Dec 27 2016
Thu Mar 23 21:17:35 2017 Windows version 6.2 (Windows 8 or greater) 64bit
Thu Mar 23 21:17:35 2017 library versions: OpenSSL 1.0.2i  22 Sep 2016, LZO 2.09
Enter Management Password:
Thu Mar 23 21:17:35 2017 MANAGEMENT: TCP Socket listening on [AF_INET]127.0.0.1:25340
Thu Mar 23 21:17:35 2017 Need hold release from management interface, waiting...
Thu Mar 23 21:17:35 2017 MANAGEMENT: Client connected from [AF_INET]127.0.0.1:25340
Thu Mar 23 21:17:36 2017 MANAGEMENT: CMD 'state on'
Thu Mar 23 21:17:36 2017 MANAGEMENT: CMD 'log all on'
Thu Mar 23 21:17:36 2017 MANAGEMENT: CMD 'hold off'
Thu Mar 23 21:17:36 2017 MANAGEMENT: CMD 'hold release'
Thu Mar 23 21:17:36 2017 Outgoing Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC authentication
Thu Mar 23 21:17:36 2017 Incoming Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC authentication
Thu Mar 23 21:17:36 2017 TCP/UDP: Preserving recently used remote address: [AF_INET]X.X.X.X:1194
Thu Mar 23 21:17:36 2017 Socket Buffers: R=[65536->65536] S=[65536->65536]
Thu Mar 23 21:17:36 2017 UDP link local: (not bound)
Thu Mar 23 21:17:36 2017 UDP link remote: [AF_INET]X.X.X.X:1194
Thu Mar 23 21:17:36 2017 MANAGEMENT: >STATE:1490300256,WAIT,,,,,,
Thu Mar 23 21:17:36 2017 MANAGEMENT: >STATE:1490300256,AUTH,,,,,,
Thu Mar 23 21:17:36 2017 TLS: Initial packet from [AF_INET]X.X.X.X:1194, sid=0ca45941 8cceb6ec
Thu Mar 23 21:17:36 2017 VERIFY OK: depth=1, CN=ChangeMe
Thu Mar 23 21:17:36 2017 Validating certificate key usage
Thu Mar 23 21:17:36 2017 ++ Certificate has key usage  00a0, expects 00a0
Thu Mar 23 21:17:36 2017 VERIFY KU OK
Thu Mar 23 21:17:36 2017 Validating certificate extended key usage
Thu Mar 23 21:17:36 2017 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Thu Mar 23 21:17:36 2017 VERIFY EKU OK
Thu Mar 23 21:17:36 2017 VERIFY OK: depth=0, CN=server
Thu Mar 23 21:17:36 2017 Control Channel: TLSv1.2, cipher TLSv1/SSLv3 DHE-RSA-AES128-GCM-SHA256, 2048 bit RSA
Thu Mar 23 21:17:36 2017 [server] Peer Connection Initiated with [AF_INET]X.X.X.X:1194
Thu Mar 23 21:17:37 2017 MANAGEMENT: >STATE:1490300257,GET_CONFIG,,,,,,
Thu Mar 23 21:17:37 2017 SENT CONTROL [server]: 'PUSH_REQUEST' (status=1)
Thu Mar 23 21:17:37 2017 PUSH: Received control message: 'PUSH_REPLY,dhcp-option DNS 84.200.69.80,dhcp-option DNS 84.200.70.40,redirect-gateway def1 bypass-dhcp,route-gateway 10.8.0.1,topology subnet,ping 10,ping-restart 120,ifconfig 10.8.0.2 255.255.255.0'
Thu Mar 23 21:17:37 2017 OPTIONS IMPORT: timers and/or timeouts modified
Thu Mar 23 21:17:37 2017 OPTIONS IMPORT: --ifconfig/up options modified
Thu Mar 23 21:17:37 2017 OPTIONS IMPORT: route options modified
Thu Mar 23 21:17:37 2017 OPTIONS IMPORT: route-related options modified
Thu Mar 23 21:17:37 2017 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
Thu Mar 23 21:17:37 2017 Data Channel Encrypt: Cipher 'AES-128-CBC' initialized with 128 bit key
Thu Mar 23 21:17:37 2017 Data Channel Encrypt: Using 256 bit message hash 'SHA256' for HMAC authentication
Thu Mar 23 21:17:37 2017 Data Channel Decrypt: Cipher 'AES-128-CBC' initialized with 128 bit key
Thu Mar 23 21:17:37 2017 Data Channel Decrypt: Using 256 bit message hash 'SHA256' for HMAC authentication
Thu Mar 23 21:17:37 2017 interactive service msg_channel=624
Thu Mar 23 21:17:37 2017 ROUTE_GATEWAY 192.168.10.1/255.255.255.0 I=7 HWADDR=1c:1b:0d:96:fe:fe
Thu Mar 23 21:17:37 2017 open_tun
Thu Mar 23 21:17:37 2017 TAP-WIN32 device [Ethernet 2] opened: \\.\Global\{7571AF95-A5E1-4ACD-BA79-52EECD6FE0A2}.tap
Thu Mar 23 21:17:37 2017 TAP-Windows Driver Version 9.21 
Thu Mar 23 21:17:37 2017 Set TAP-Windows TUN subnet mode network/local/netmask = 10.8.0.0/10.8.0.2/255.255.255.0 [SUCCEEDED]
Thu Mar 23 21:17:37 2017 Notified TAP-Windows driver to set a DHCP IP/netmask of 10.8.0.2/255.255.255.0 on interface {7571AF95-A5E1-4ACD-BA79-52EECD6FE0A2} [DHCP-serv: 10.8.0.254, lease-time: 31536000]
Thu Mar 23 21:17:37 2017 Successful ARP Flush on interface [4] {7571AF95-A5E1-4ACD-BA79-52EECD6FE0A2}
Thu Mar 23 21:17:37 2017 do_ifconfig, tt->did_ifconfig_ipv6_setup=0
Thu Mar 23 21:17:37 2017 MANAGEMENT: >STATE:1490300257,ASSIGN_IP,,10.8.0.2,,,,
Thu Mar 23 21:17:37 2017 Blocking outside dns using service succeeded.
Thu Mar 23 21:17:42 2017 TEST ROUTES: 1/1 succeeded len=0 ret=1 a=0 u/d=up
Thu Mar 23 21:17:42 2017 C:\Windows\system32\route.exe ADD X.X.X.X MASK 255.255.255.255 192.168.10.1
Thu Mar 23 21:17:42 2017 Route addition via service succeeded
Thu Mar 23 21:17:42 2017 C:\Windows\system32\route.exe ADD 0.0.0.0 MASK 128.0.0.0 10.8.0.1
Thu Mar 23 21:17:42 2017 Route addition via service succeeded
Thu Mar 23 21:17:42 2017 C:\Windows\system32\route.exe ADD 128.0.0.0 MASK 128.0.0.0 10.8.0.1
Thu Mar 23 21:17:42 2017 Route addition via service succeeded
Thu Mar 23 21:17:42 2017 Initialization Sequence Completed
Thu Mar 23 21:17:42 2017 MANAGEMENT: >STATE:1490300262,CONNECTED,SUCCESS,10.8.0.2,X.X.X.X,1194,,

**Comment by Kcchouette** [comment]
Can you check using OpenVPN 2.4.1 (just to be sure it's not an OpenVPN 2.4.0 issue)?

**Comment by ghost** [comment]
Here's my Log output with 2.41


Mon Mar 27 18:24:07 2017 OpenVPN 2.4.1 x86_64-w64-mingw32 [SSL (OpenSSL)] [LZO] [LZ4] [PKCS11] [AEAD] built on Mar 22 2017
Mon Mar 27 18:24:07 2017 Windows version 6.2 (Windows 8 or greater) 64bit
Mon Mar 27 18:24:07 2017 library versions: OpenSSL 1.0.2k  26 Jan 2017, LZO 2.09
Mon Mar 27 18:24:07 2017 MANAGEMENT: TCP Socket listening on [AF_INET]127.0.0.1:25340
Mon Mar 27 18:24:07 2017 Need hold release from management interface, waiting...
Mon Mar 27 18:24:07 2017 MANAGEMENT: Client connected from [AF_INET]127.0.0.1:25340
Mon Mar 27 18:24:07 2017 MANAGEMENT: CMD 'state on'
Mon Mar 27 18:24:07 2017 MANAGEMENT: CMD 'log all on'
Mon Mar 27 18:24:07 2017 MANAGEMENT: CMD 'echo all on'
Mon Mar 27 18:24:07 2017 MANAGEMENT: CMD 'hold off'
Mon Mar 27 18:24:07 2017 MANAGEMENT: CMD 'hold release'
Mon Mar 27 18:24:07 2017 Outgoing Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC authentication
Mon Mar 27 18:24:07 2017 Incoming Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC authentication
Mon Mar 27 18:24:07 2017 TCP/UDP: Preserving recently used remote address: [AF_INET]Z.Z.Z.Z:1194
Mon Mar 27 18:24:07 2017 Socket Buffers: R=[65536->65536] S=[65536->65536]
Mon Mar 27 18:24:07 2017 UDP link local: (not bound)
Mon Mar 27 18:24:07 2017 UDP link remote: [AF_INET]Z.Z.Z.Z:1194
Mon Mar 27 18:24:07 2017 MANAGEMENT: >STATE:1490631847,WAIT,,,,,,
Mon Mar 27 18:24:07 2017 MANAGEMENT: >STATE:1490631847,AUTH,,,,,,
Mon Mar 27 18:24:07 2017 TLS: Initial packet from [AF_INET]Z.Z.Z.Z:1194, sid=0cad284f 12705a1a
Mon Mar 27 18:24:07 2017 VERIFY OK: depth=1, CN=ChangeMe
Mon Mar 27 18:24:07 2017 VERIFY KU OK
Mon Mar 27 18:24:07 2017 Validating certificate extended key usage
Mon Mar 27 18:24:07 2017 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Mon Mar 27 18:24:07 2017 VERIFY EKU OK
Mon Mar 27 18:24:07 2017 VERIFY OK: depth=0, CN=server
Mon Mar 27 18:24:08 2017 Control Channel: TLSv1.2, cipher TLSv1/SSLv3 DHE-RSA-AES128-GCM-SHA256, 2048 bit RSA
Mon Mar 27 18:24:08 2017 [server] Peer Connection Initiated with [AF_INET]Z.Z.Z.Z:1194
Mon Mar 27 18:24:09 2017 MANAGEMENT: >STATE:1490631849,GET_CONFIG,,,,,,
Mon Mar 27 18:24:09 2017 SENT CONTROL [server]: 'PUSH_REQUEST' (status=1)
Mon Mar 27 18:24:09 2017 PUSH: Received control message: 'PUSH_REPLY,dhcp-option DNS 84.200.69.80,dhcp-option DNS 84.200.70.40,redirect-gateway def1 bypass-dhcp,route-gateway 10.8.0.1,topology subnet,ping 10,ping-restart 120,ifconfig 10.8.0.2 255.255.255.0'
Mon Mar 27 18:24:09 2017 OPTIONS IMPORT: timers and/or timeouts modified
Mon Mar 27 18:24:09 2017 OPTIONS IMPORT: --ifconfig/up options modified
Mon Mar 27 18:24:09 2017 OPTIONS IMPORT: route options modified
Mon Mar 27 18:24:09 2017 OPTIONS IMPORT: route-related options modified
Mon Mar 27 18:24:09 2017 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
Mon Mar 27 18:24:09 2017 Data Channel Encrypt: Cipher 'AES-128-CBC' initialized with 128 bit key
Mon Mar 27 18:24:09 2017 Data Channel Encrypt: Using 256 bit message hash 'SHA256' for HMAC authentication
Mon Mar 27 18:24:09 2017 Data Channel Decrypt: Cipher 'AES-128-CBC' initialized with 128 bit key
Mon Mar 27 18:24:09 2017 Data Channel Decrypt: Using 256 bit message hash 'SHA256' for HMAC authentication
Mon Mar 27 18:24:09 2017 interactive service msg_channel=552
Mon Mar 27 18:24:09 2017 ROUTE_GATEWAY Y.Y.Y.Y/255.255.255.0 I=7 HWADDR=1c:1b:0d:96:fe:fe
Mon Mar 27 18:24:09 2017 open_tun
Mon Mar 27 18:24:09 2017 TAP-WIN32 device [Ethernet 2] opened: \\.\Global\{7571AF95-A5E1-4ACD-BA79-52EECD6FE0A2}.tap
Mon Mar 27 18:24:09 2017 TAP-Windows Driver Version 9.21 
Mon Mar 27 18:24:09 2017 Set TAP-Windows TUN subnet mode network/local/netmask = 10.8.0.0/10.8.0.2/255.255.255.0 [SUCCEEDED]
Mon Mar 27 18:24:09 2017 Notified TAP-Windows driver to set a DHCP IP/netmask of 10.8.0.2/255.255.255.0 on interface {7571AF95-A5E1-4ACD-BA79-52EECD6FE0A2} [DHCP-serv: 10.8.0.254, lease-time: 31536000]
Mon Mar 27 18:24:09 2017 Successful ARP Flush on interface [4] {7571AF95-A5E1-4ACD-BA79-52EECD6FE0A2}
Mon Mar 27 18:24:09 2017 do_ifconfig, tt->did_ifconfig_ipv6_setup=0
Mon Mar 27 18:24:09 2017 MANAGEMENT: >STATE:1490631849,ASSIGN_IP,,10.8.0.2,,,,
Mon Mar 27 18:24:09 2017 Blocking outside dns using service succeeded.
Mon Mar 27 18:24:14 2017 TEST ROUTES: 1/1 succeeded len=0 ret=1 a=0 u/d=up
Mon Mar 27 18:24:14 2017 C:\Windows\system32\route.exe ADD Z.Z.Z.Z MASK 255.255.255.255 Y.Y.Y.Y
Mon Mar 27 18:24:14 2017 Route addition via service succeeded
Mon Mar 27 18:24:14 2017 C:\Windows\system32\route.exe ADD 0.0.0.0 MASK 128.0.0.0 10.8.0.1
Mon Mar 27 18:24:14 2017 Route addition via service succeeded
Mon Mar 27 18:24:14 2017 C:\Windows\system32\route.exe ADD 128.0.0.0 MASK 128.0.0.0 10.8.0.1
Mon Mar 27 18:24:14 2017 Route addition via service succeeded
Mon Mar 27 18:24:14 2017 Initialization Sequence Completed
Mon Mar 27 18:24:14 2017 MANAGEMENT: >STATE:1490631854,CONNECTED,SUCCESS,10.8.0.2,Z.Z.Z.Z,1194,,

**Comment by Kcchouette** [comment]
How do you know it's not working? Your browser showed you a blank page instead of the website you want to go?

**Comment by ghost** [comment]
I cannot ping either the server itself or static ip addresses like Google DNS (8.8.8.8) or anything else, DNS is not working too... I have checked the firewall port UDP 1194 is open. 

net.ipv4.ip_forward=1 is also set in the sysctl.conf....

So do you have any suggestions? What else could it be?

**Comment by Kcchouette** [comment]
>I cannot ping either the server itself

It seems that this one is normal behavior.

Edit: I don't know what can be the problem, but if one day I would have this kind of problem, I would test if the """original""" version is working (https://github.com/Nyr/openvpn-install), and see what's the difference between these two to check the error.

**Comment by Kcchouette** [comment]
any news @bodkov ?

**Comment by ghost** [comment]
Okay I've tried the one from Nyr and installed it with the standard settings. Now I can ping 8.8.8.8 at least but DNS is not working.

**Comment by Kcchouette** [comment]
Can you report at https://github.com/Nyr/openvpn-install/issues please @bodkov your problem?

I think it's a host problem, but let's try that!

**Comment by lutostag** [comment]
This was happening to me to, with an 'unsupported' (zesty lxd image), the iptables command was not restored for me.
which I could tell by running
```
root@openvpn:~# iptables -t nat -L
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination

Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination
```

Was fixed by running (with IP set appropriately):
```
iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -j SNAT --to $IP
```
and adding that to my startup.

Maybe your same issue?

**Comment by ruslanguns** [comment]
@lutostag  buddy, 

regarding the IP that you have set 10.8.0..0/24 is that the Public Network or the Local Network?

iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -j SNAT --to $IP

**Comment by ghost** [comment]
Oh I'm so sorry I totally forgot about this. I ended up using your script on Debian 9 and it works just fine.
