### ISSUE TITLE
Ability to change the subnet of the OpenVPN network

### ISSUE THREAD

**Issue by heutger** [angristan/openvpn-install#441]
Allow changing the OpenVPN network via the script (so on multiple installations be able to use connection on both without conflict)

**Comment by angristan** [comment]
Can you clarify what you mean?

**Comment by heutger** [comment]
Per default server and client use 10.8.0.0/24 via your script but I wanted to install your script on different servers and want to be able to connect to this servers parallel, so I need different networks for each installation.

**Comment by angristan** [comment]
See #153
