### ISSUE TITLE
Add the possibility to not enforce DNS resolvers

### ISSUE THREAD

**Issue by heutger** [angristan/openvpn-install#442]
Allow disabling DNS been sent

**Comment by angristan** [comment]
Can you clarify this?

**Comment by heutger** [comment]
Your setup expects to send any DNS server (local unbound, server settings, any public DNS) to the client, but if I want the client to keep his own DNS server and no need to send new DNS server via VPN, I would like to disable this option. I don't use your script for a road warrior setup but just for privileged access to a server system.

**Comment by angristan** [comment]
This would with #443
