### ISSUE TITLE
Client connects on Windows 10 but no internet

### ISSUE THREAD

**Issue by emgee-909** [angristan/openvpn-install#445]
Hi,

Strangely I can connect to internet on Android and Linux clients but not on Windows 10 Home.
OpenVPN connects to server just fine (no errors in the log) but I can't access internet. 
I tried restoring Windows Firewall to default settings and even turning it off to no avail.

What am I missing here?

**Comment by angristan** [comment]
Can you ping the server's private IP on Windows?

**Comment by emgee-909** [comment]
Ha! I have forgotten to do it in first place before posting here.

I re-run your script again and everything is working just fine. Before second attempt at installing your script I reseted Windows firewall and my router to default settings.
