### ISSUE TITLE
enable traffic control

### ISSUE THREAD

**Issue by agentmishra** [angristan/openvpn-install#452]
hi

say i wish to control traffic, how to implement it

https://github.com/rda0/tc-openvpn

if possible kindly update me here

thanks

**Comment by techroy23** [comment]
> hi
> 
> say i wish to control traffic, how to implement it
> 
> https://github.com/rda0/tc-openvpn
> 
> if possible kindly update me here
> 
> thanks

I'm really looking forward to this feature
