### ISSUE TITLE
easy-rsa .rnd issue

### ISSUE THREAD

**Issue by techroy23** [angristan/openvpn-install#454]
- [x] You installed OpenVPN with the lastest version of the script
- [x] Ubuntu 18.04
- [x] Installation date July 28 2019 using last commit https://github.com/angristan/openvpn-install/commit/b095c2349619bab4a6433aec21aaeb59c71387b9

```javascript

... some text here ...
Do you want to protect the configuration file with a password?
(e.g. encrypt the private key with a password)
   1) Add a passwordless client
   2) Use a password for the client
Select an option [1-2]: 1

Note: using Easy-RSA configuration from: ./vars

Using SSL: openssl OpenSSL 1.1.1  11 Sep 2018
Can't load /etc/openvpn/easy-rsa/pki/.rnd into RNG
140291402555840:error:2406F079:random number generator:RAND_load_file:Cannot open file:../crypto/rand/randfile.c:88:Filename=/etc/openvpn/easy-rsa/pki/.rnd
Generating an EC private key
writing new private key to '/etc/openvpn/easy-rsa/pki/private/client.key.esbg8QqRO7'
-----
Using configuration from /etc/openvpn/easy-rsa/pki/safessl-easyrsa.cnf
Can't load /etc/openvpn/easy-rsa/pki/.rnd into RNG
140392562667968:error:2406F079:random number generator:RAND_load_file:Cannot open file:../crypto/rand/randfile.c:88:Filename=/etc/openvpn/easy-rsa/pki/.rnd
Check that the request matches the signature
Signature ok
The Subject's Distinguished Name is as follows
commonName            :ASN.1 12:'client'
Certificate is to be certified until Jul 12 23:02:56 2022 GMT (1080 days)

Write out database with 1 new entries
Data Base Updated
... some text here ...

```

**FIX :**
To prevent gettint error
please comment line 3 on both of these files
* /etc/openvpn/easy-rsa/pki/openssl-easyrsa.cnf
* /etc/openvpn/easy-rsa/pki/safessl-easyrsa.cnf

```javascript
# RANDFILE		= /etc/openvpn/easy-rsa/pki/.rnd
```

this error may not have impact on how openvpn works but its better not to see any errors.

**Comment by zib92130** [comment]
Got also this error on **debian 10** (Proxmox 6), with loaded [EasyRSA 3.0.6](https://github.com/OpenVPN/easy-rsa/releases/download/v3.0.6/EasyRSA-unix-v3.0.6.tgz) . 
Looks to be a [known issue](https://github.com/OpenVPN/easy-rsa/issues/261) that will be "corrected" (by removing the line like you mentioned), in the upcoming 3.0.7 version...
