### ISSUE TITLE
About the web interface 

### ISSUE THREAD

**Issue by yasirow** [angristan/openvpn-install#455]
Hello,
https://openvpn.net/vpn-server-resources/troubleshooting-access-to-the-web-interface/
Is it possible to add web interface as in this address? 
How can we do it if possible?

Or a panel like this can be added in the future?
https://github.com/Chocobozzz/OpenVPN-Admin

**Comment by angristan** [comment]
Hello, this is not possible https://github.com/angristan/openvpn-install/issues/428

**Comment by randshell** [comment]
A web interface for monitoring should be possible https://github.com/angristan/openvpn-install/issues/665#issuecomment-673050329. An interface for managing the server like creating another user, revoking it's not because it would need to be programmed for this script specifically.
