### ISSUE TITLE
Google Compute Engine - Additional iptables config

### ISSUE THREAD

**Issue by gpchelkin** [angristan/openvpn-install#46]
According to [this answer](http://serverfault.com/a/827763/342772) and to my attempts on **Google Compute Engine g1-small Instance with Ubuntu 16.04**, you need this after installing with this script to get out to the internet through OpenVPN on Debian/Ubuntu GCE instances:
```
sudo iptables -t nat -I POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE
```
`eth0` is instance's WAN connection, in my case it was `ens4`.

Would be nice if this is included in script somehow.

**Comment by DrXala** [comment]
@Angristan ;)
```
# Get network interface
NIC=$(ip -o -4 a | grep $IP | awk '{print $2}')
# or
NIC=$(ip -4 route ls | grep default | grep -Po '(?<=dev )(\S+)')
```
