### ISSUE TITLE
Unable to configure it on Port 53

### ISSUE THREAD

**Issue by saugatadatta** [angristan/openvpn-install#467]
I am unable to configure it on port 53 (TCP or UDP), connection getting reset  and I am getting Fatal TLS Error
I am on Amazon Lightsail

**Comment by angristan** [comment]
Does it work for other ports?

**Comment by saugatadatta** [comment]
Yes, works for every other port I select. Only having issue with port 53 for both TCP and UDP. 
Very strange, service is running and port is listing to server, but while connecting, getting error.

**Comment by iAmSaugata** [comment]
Tue Aug 20 19:24:41 2019 TLS Error: client->client or server->server connection attempted from [AF_INET]107.23.229.202:53
Tue Aug 20 19:24:43 2019 TLS Error: client->client or server->server connection attempted from [AF_INET]107.23.229.202:53
Tue Aug 20 19:24:47 2019 TLS Error: client->client or server->server connection attempted from [AF_INET]107.23.229.202:53
Tue Aug 20 19:24:55 2019 TLS Error: client->client or server->server connection attempted from [AF_INET]107.23.229.202:53

**Comment by saugatadatta** [comment]
Successful on port 110
===============
Tue Aug 20 19:30:23 2019 OpenVPN 2.4.6 x86_64-w64-mingw32 [SSL (OpenSSL)] [LZO] [LZ4] [PKCS11] [AEAD] built on Apr 26 2018
Tue Aug 20 19:30:23 2019 Windows version 6.2 (Windows 8 or greater) 64bit
Tue Aug 20 19:30:23 2019 library versions: OpenSSL 1.1.0h  27 Mar 2018, LZO 2.10
Tue Aug 20 19:30:23 2019 MANAGEMENT: TCP Socket listening on [AF_INET]127.0.0.1:25340
Tue Aug 20 19:30:23 2019 Need hold release from management interface, waiting...
Tue Aug 20 19:30:23 2019 MANAGEMENT: Client connected from [AF_INET]127.0.0.1:25340
Tue Aug 20 19:30:23 2019 MANAGEMENT: CMD 'state on'
Tue Aug 20 19:30:23 2019 MANAGEMENT: CMD 'log all on'
Tue Aug 20 19:30:24 2019 MANAGEMENT: CMD 'echo all on'
Tue Aug 20 19:30:24 2019 MANAGEMENT: CMD 'bytecount 5'
Tue Aug 20 19:30:24 2019 MANAGEMENT: CMD 'hold off'
Tue Aug 20 19:30:24 2019 MANAGEMENT: CMD 'hold release'
Tue Aug 20 19:30:24 2019 Outgoing Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Tue Aug 20 19:30:24 2019 Outgoing Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Tue Aug 20 19:30:24 2019 Incoming Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Tue Aug 20 19:30:24 2019 Incoming Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Tue Aug 20 19:30:24 2019 MANAGEMENT: >STATE:1566309624,RESOLVE,,,,,,
Tue Aug 20 19:30:24 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]XX.XX.XX.XX:110
Tue Aug 20 19:30:24 2019 Socket Buffers: R=[65536->65536] S=[64512->64512]
Tue Aug 20 19:30:24 2019 Attempting to establish TCP connection with [AF_INET]XX.XX.XX.XX:110 [nonblock]
Tue Aug 20 19:30:24 2019 MANAGEMENT: >STATE:1566309624,TCP_CONNECT,,,,,,
Tue Aug 20 19:30:25 2019 TCP connection established with [AF_INET]XX.XX.XX.XX:110
Tue Aug 20 19:30:25 2019 TCP_CLIENT link local: (not bound)
Tue Aug 20 19:30:25 2019 TCP_CLIENT link remote: [AF_INET]XX.XX.XX.XX:110
Tue Aug 20 19:30:25 2019 MANAGEMENT: >STATE:1566309625,WAIT,,,,,,
Tue Aug 20 19:30:25 2019 MANAGEMENT: >STATE:1566309625,AUTH,,,,,,
Tue Aug 20 19:30:25 2019 TLS: Initial packet from [AF_INET]XX.XX.XX.XX:110, sid=af666e50 e32f93db
Tue Aug 20 19:30:25 2019 VERIFY OK: depth=1, CN=cn_oDJeikXs8Gj5r8MZ
Tue Aug 20 19:30:25 2019 VERIFY KU OK
Tue Aug 20 19:30:25 2019 Validating certificate extended key usage
Tue Aug 20 19:30:25 2019 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Tue Aug 20 19:30:25 2019 VERIFY EKU OK
Tue Aug 20 19:30:25 2019 VERIFY X509NAME OK: CN=server_TZn2piBXHTCUIwAJ
Tue Aug 20 19:30:25 2019 VERIFY OK: depth=0, CN=server_TZn2piBXHTCUIwAJ
Tue Aug 20 19:30:26 2019 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-ECDSA-AES128-GCM-SHA256, 256 bit EC, curve: prime256v1
Tue Aug 20 19:30:26 2019 [server_TZn2piBXHTCUIwAJ] Peer Connection Initiated with [AF_INET]XX.XX.XX.XX:110
Tue Aug 20 19:30:27 2019 MANAGEMENT: >STATE:1566309627,GET_CONFIG,,,,,,
Tue Aug 20 19:30:27 2019 SENT CONTROL [server_TZn2piBXHTCUIwAJ]: 'PUSH_REQUEST' (status=1)
Tue Aug 20 19:30:29 2019 PUSH: Received control message: 'PUSH_REPLY,dhcp-option DNS 1.0.0.1,dhcp-option DNS 1.1.1.1,redirect-gateway def1 bypass-dhcp,route-gateway 10.8.0.1,topology subnet,ping 10,ping-restart 120,ifconfig 10.8.0.3 255.255.255.0,peer-id 0,cipher AES-128-GCM'
Tue Aug 20 19:30:29 2019 OPTIONS IMPORT: timers and/or timeouts modified
Tue Aug 20 19:30:29 2019 OPTIONS IMPORT: --ifconfig/up options modified
Tue Aug 20 19:30:29 2019 OPTIONS IMPORT: route options modified
Tue Aug 20 19:30:29 2019 OPTIONS IMPORT: route-related options modified
Tue Aug 20 19:30:29 2019 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
Tue Aug 20 19:30:29 2019 OPTIONS IMPORT: peer-id set
Tue Aug 20 19:30:29 2019 OPTIONS IMPORT: adjusting link_mtu to 1626
Tue Aug 20 19:30:29 2019 OPTIONS IMPORT: data channel crypto options modified
Tue Aug 20 19:30:29 2019 Outgoing Data Channel: Cipher 'AES-128-GCM' initialized with 128 bit key
Tue Aug 20 19:30:29 2019 Incoming Data Channel: Cipher 'AES-128-GCM' initialized with 128 bit key
Tue Aug 20 19:30:29 2019 interactive service msg_channel=0
Tue Aug 20 19:30:29 2019 ROUTE_GATEWAY 192.168.31.1/255.255.255.0 I=10 HWADDR=d4:25:8b:f6:0d:79
Tue Aug 20 19:30:29 2019 open_tun
Tue Aug 20 19:30:29 2019 TAP-WIN32 device [Ethernet 2] opened: \\.\Global\{C935EA68-F332-4977-9DAC-CE30BDB3C701}.tap
Tue Aug 20 19:30:29 2019 TAP-Windows Driver Version 9.21 
Tue Aug 20 19:30:29 2019 Set TAP-Windows TUN subnet mode network/local/netmask = 10.8.0.0/10.8.0.3/255.255.255.0 [SUCCEEDED]
Tue Aug 20 19:30:29 2019 Notified TAP-Windows driver to set a DHCP IP/netmask of 10.8.0.3/255.255.255.0 on interface {C935EA68-F332-4977-9DAC-CE30BDB3C701} [DHCP-serv: 10.8.0.254, lease-time: 31536000]
Tue Aug 20 19:30:29 2019 Successful ARP Flush on interface [17] {C935EA68-F332-4977-9DAC-CE30BDB3C701}
Tue Aug 20 19:30:29 2019 do_ifconfig, tt->did_ifconfig_ipv6_setup=0
Tue Aug 20 19:30:29 2019 MANAGEMENT: >STATE:1566309629,ASSIGN_IP,,10.8.0.3,,,,
Tue Aug 20 19:30:29 2019 Block_DNS: WFP engine opened
Tue Aug 20 19:30:29 2019 Block_DNS: Using existing sublayer
Tue Aug 20 19:30:29 2019 Block_DNS: Added permit filters for exe_path
Tue Aug 20 19:30:29 2019 Block_DNS: Added block filters for all interfaces
Tue Aug 20 19:30:29 2019 Block_DNS: Added permit filters for TAP interface
Tue Aug 20 19:30:34 2019 TEST ROUTES: 1/1 succeeded len=0 ret=1 a=0 u/d=up
Tue Aug 20 19:30:34 2019 C:\WINDOWS\system32\route.exe ADD XX.XX.XX.XX MASK 255.255.255.255 192.168.31.1
Tue Aug 20 19:30:34 2019 ROUTE: CreateIpForwardEntry succeeded with dwForwardMetric1=50 and dwForwardType=4
Tue Aug 20 19:30:34 2019 Route addition via IPAPI succeeded [adaptive]
Tue Aug 20 19:30:34 2019 C:\WINDOWS\system32\route.exe ADD 0.0.0.0 MASK 128.0.0.0 10.8.0.1
Tue Aug 20 19:30:34 2019 ROUTE: CreateIpForwardEntry succeeded with dwForwardMetric1=3 and dwForwardType=4
Tue Aug 20 19:30:34 2019 Route addition via IPAPI succeeded [adaptive]
Tue Aug 20 19:30:34 2019 C:\WINDOWS\system32\route.exe ADD 128.0.0.0 MASK 128.0.0.0 10.8.0.1
Tue Aug 20 19:30:34 2019 ROUTE: CreateIpForwardEntry succeeded with dwForwardMetric1=3 and dwForwardType=4
Tue Aug 20 19:30:34 2019 Route addition via IPAPI succeeded [adaptive]
Tue Aug 20 19:30:34 2019 Initialization Sequence Completed
Tue Aug 20 19:30:34 2019 MANAGEMENT: >STATE:1566309634,CONNECTED,SUCCESS,10.8.0.3,XX.XX.XX.XX,110,192.168.31.74,53400

**Comment by iAmSaugata** [comment]
With Port 53
==============
Tue Aug 20 19:34:23 2019 OpenVPN 2.4.6 x86_64-w64-mingw32 [SSL (OpenSSL)] [LZO] [LZ4] [PKCS11] [AEAD] built on Apr 26 2018
Tue Aug 20 19:34:23 2019 Windows version 6.2 (Windows 8 or greater) 64bit
Tue Aug 20 19:34:23 2019 library versions: OpenSSL 1.1.0h  27 Mar 2018, LZO 2.10
Tue Aug 20 19:34:23 2019 MANAGEMENT: TCP Socket listening on [AF_INET]127.0.0.1:25340
Tue Aug 20 19:34:23 2019 Need hold release from management interface, waiting...
Tue Aug 20 19:34:23 2019 MANAGEMENT: Client connected from [AF_INET]127.0.0.1:25340
Tue Aug 20 19:34:24 2019 MANAGEMENT: CMD 'state on'
Tue Aug 20 19:34:24 2019 MANAGEMENT: CMD 'log all on'
Tue Aug 20 19:34:24 2019 MANAGEMENT: CMD 'echo all on'
Tue Aug 20 19:34:24 2019 MANAGEMENT: CMD 'bytecount 5'
Tue Aug 20 19:34:24 2019 MANAGEMENT: CMD 'hold off'
Tue Aug 20 19:34:24 2019 MANAGEMENT: CMD 'hold release'
Tue Aug 20 19:34:24 2019 Outgoing Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Tue Aug 20 19:34:24 2019 Outgoing Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Tue Aug 20 19:34:24 2019 Incoming Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Tue Aug 20 19:34:24 2019 Incoming Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Tue Aug 20 19:34:24 2019 MANAGEMENT: >STATE:1566309864,RESOLVE,,,,,,
Tue Aug 20 19:34:24 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]54.89.72.43:53
Tue Aug 20 19:34:24 2019 Socket Buffers: R=[65536->65536] S=[64512->64512]
Tue Aug 20 19:34:24 2019 Attempting to establish TCP connection with [AF_INET]54.89.72.43:53 [nonblock]
Tue Aug 20 19:34:24 2019 MANAGEMENT: >STATE:1566309864,TCP_CONNECT,,,,,,
Tue Aug 20 19:34:25 2019 TCP connection established with [AF_INET]54.89.72.43:53
Tue Aug 20 19:34:25 2019 TCP_CLIENT link local: (not bound)
Tue Aug 20 19:34:25 2019 TCP_CLIENT link remote: [AF_INET]54.89.72.43:53
Tue Aug 20 19:34:25 2019 MANAGEMENT: >STATE:1566309865,WAIT,,,,,,
Tue Aug 20 19:34:25 2019 Connection reset, restarting [0]
Tue Aug 20 19:34:25 2019 SIGUSR1[soft,connection-reset] received, process restarting
Tue Aug 20 19:34:25 2019 MANAGEMENT: >STATE:1566309865,RECONNECTING,connection-reset,,,,,
Tue Aug 20 19:34:25 2019 Restart pause, 5 second(s)
Tue Aug 20 19:34:30 2019 MANAGEMENT: >STATE:1566309870,RESOLVE,,,,,,
Tue Aug 20 19:34:30 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]54.89.72.43:53
Tue Aug 20 19:34:30 2019 Socket Buffers: R=[65536->65536] S=[64512->64512]
Tue Aug 20 19:34:30 2019 Attempting to establish TCP connection with [AF_INET]54.89.72.43:53 [nonblock]
Tue Aug 20 19:34:30 2019 MANAGEMENT: >STATE:1566309870,TCP_CONNECT,,,,,,
Tue Aug 20 19:34:31 2019 TCP connection established with [AF_INET]54.89.72.43:53
Tue Aug 20 19:34:31 2019 TCP_CLIENT link local: (not bound)
Tue Aug 20 19:34:31 2019 TCP_CLIENT link remote: [AF_INET]54.89.72.43:53
Tue Aug 20 19:34:31 2019 MANAGEMENT: >STATE:1566309871,WAIT,,,,,,
Tue Aug 20 19:34:31 2019 TLS Error: client->client or server->server connection attempted from [AF_INET]54.89.72.43:53
Tue Aug 20 19:34:31 2019 Fatal TLS error (check_tls_errors_co), restarting
Tue Aug 20 19:34:31 2019 SIGUSR1[soft,tls-error] received, process restarting
Tue Aug 20 19:34:31 2019 MANAGEMENT: >STATE:1566309871,RECONNECTING,tls-error,,,,,
Tue Aug 20 19:34:31 2019 Restart pause, 5 second(s)
Tue Aug 20 19:34:36 2019 MANAGEMENT: >STATE:1566309876,RESOLVE,,,,,,
Tue Aug 20 19:34:36 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]54.89.72.43:53
Tue Aug 20 19:34:36 2019 Socket Buffers: R=[65536->65536] S=[64512->64512]
Tue Aug 20 19:34:36 2019 Attempting to establish TCP connection with [AF_INET]54.89.72.43:53 [nonblock]
Tue Aug 20 19:34:36 2019 MANAGEMENT: >STATE:1566309876,TCP_CONNECT,,,,,,
Tue Aug 20 19:34:37 2019 TCP connection established with [AF_INET]54.89.72.43:53
Tue Aug 20 19:34:37 2019 TCP_CLIENT link local: (not bound)
Tue Aug 20 19:34:37 2019 TCP_CLIENT link remote: [AF_INET]54.89.72.43:53
Tue Aug 20 19:34:37 2019 MANAGEMENT: >STATE:1566309877,WAIT,,,,,,
Tue Aug 20 19:34:37 2019 Connection reset, restarting [0]
Tue Aug 20 19:34:37 2019 SIGUSR1[soft,connection-reset] received, process restarting
Tue Aug 20 19:34:37 2019 MANAGEMENT: >STATE:1566309877,RECONNECTING,connection-reset,,,,,
Tue Aug 20 19:34:37 2019 Restart pause, 5 second(s)

**Comment by saugatadatta** [comment]
With Port 53
============
Tue Aug 20 19:34:23 2019 OpenVPN 2.4.6 x86_64-w64-mingw32 [SSL (OpenSSL)] [LZO] [LZ4] [PKCS11] [AEAD] built on Apr 26 2018
Tue Aug 20 19:34:23 2019 Windows version 6.2 (Windows 8 or greater) 64bit
Tue Aug 20 19:34:23 2019 library versions: OpenSSL 1.1.0h  27 Mar 2018, LZO 2.10
Tue Aug 20 19:34:23 2019 MANAGEMENT: TCP Socket listening on [AF_INET]127.0.0.1:25340
Tue Aug 20 19:34:23 2019 Need hold release from management interface, waiting...
Tue Aug 20 19:34:23 2019 MANAGEMENT: Client connected from [AF_INET]127.0.0.1:25340
Tue Aug 20 19:34:24 2019 MANAGEMENT: CMD 'state on'
Tue Aug 20 19:34:24 2019 MANAGEMENT: CMD 'log all on'
Tue Aug 20 19:34:24 2019 MANAGEMENT: CMD 'echo all on'
Tue Aug 20 19:34:24 2019 MANAGEMENT: CMD 'bytecount 5'
Tue Aug 20 19:34:24 2019 MANAGEMENT: CMD 'hold off'
Tue Aug 20 19:34:24 2019 MANAGEMENT: CMD 'hold release'
Tue Aug 20 19:34:24 2019 Outgoing Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Tue Aug 20 19:34:24 2019 Outgoing Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Tue Aug 20 19:34:24 2019 Incoming Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Tue Aug 20 19:34:24 2019 Incoming Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Tue Aug 20 19:34:24 2019 MANAGEMENT: >STATE:1566309864,RESOLVE,,,,,,
Tue Aug 20 19:34:24 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]XX.XX.XX.XX:53
Tue Aug 20 19:34:24 2019 Socket Buffers: R=[65536->65536] S=[64512->64512]
Tue Aug 20 19:34:24 2019 Attempting to establish TCP connection with [AF_INET]XX.XX.XX.XX:53 [nonblock]
Tue Aug 20 19:34:24 2019 MANAGEMENT: >STATE:1566309864,TCP_CONNECT,,,,,,
Tue Aug 20 19:34:25 2019 TCP connection established with [AF_INET]XX.XX.XX.XX:53
Tue Aug 20 19:34:25 2019 TCP_CLIENT link local: (not bound)
Tue Aug 20 19:34:25 2019 TCP_CLIENT link remote: [AF_INET]XX.XX.XX.XX:53
Tue Aug 20 19:34:25 2019 MANAGEMENT: >STATE:1566309865,WAIT,,,,,,
Tue Aug 20 19:34:25 2019 Connection reset, restarting [0]
Tue Aug 20 19:34:25 2019 SIGUSR1[soft,connection-reset] received, process restarting
Tue Aug 20 19:34:25 2019 MANAGEMENT: >STATE:1566309865,RECONNECTING,connection-reset,,,,,
Tue Aug 20 19:34:25 2019 Restart pause, 5 second(s)
Tue Aug 20 19:34:30 2019 MANAGEMENT: >STATE:1566309870,RESOLVE,,,,,,
Tue Aug 20 19:34:30 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]XX.XX.XX.XX:53
Tue Aug 20 19:34:30 2019 Socket Buffers: R=[65536->65536] S=[64512->64512]
Tue Aug 20 19:34:30 2019 Attempting to establish TCP connection with [AF_INET]XX.XX.XX.XX:53 [nonblock]
Tue Aug 20 19:34:30 2019 MANAGEMENT: >STATE:1566309870,TCP_CONNECT,,,,,,
Tue Aug 20 19:34:31 2019 TCP connection established with [AF_INET]XX.XX.XX.XX:53
Tue Aug 20 19:34:31 2019 TCP_CLIENT link local: (not bound)
Tue Aug 20 19:34:31 2019 TCP_CLIENT link remote: [AF_INET]XX.XX.XX.XX:53
Tue Aug 20 19:34:31 2019 MANAGEMENT: >STATE:1566309871,WAIT,,,,,,
**Tue Aug 20 19:34:31 2019 TLS Error: client->client or server->server connection attempted from [AF_INET]XX.XX.XX.XX:53
Tue Aug 20 19:34:31 2019 Fatal TLS error (check_tls_errors_co), restarting**
Tue Aug 20 19:34:31 2019 SIGUSR1[soft,tls-error] received, process restarting
Tue Aug 20 19:34:31 2019 MANAGEMENT: >STATE:1566309871,RECONNECTING,tls-error,,,,,
Tue Aug 20 19:34:31 2019 Restart pause, 5 second(s)
Tue Aug 20 19:34:36 2019 MANAGEMENT: >STATE:1566309876,RESOLVE,,,,,,
Tue Aug 20 19:34:36 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]XX.XX.XX.XX:53
Tue Aug 20 19:34:36 2019 Socket Buffers: R=[65536->65536] S=[64512->64512]
Tue Aug 20 19:34:36 2019 Attempting to establish TCP connection with [AF_INET]XX.XX.XX.XX:53 [nonblock]
Tue Aug 20 19:34:36 2019 MANAGEMENT: >STATE:1566309876,TCP_CONNECT,,,,,,
Tue Aug 20 19:34:37 2019 TCP connection established with [AF_INET]XX.XX.XX.XX:53
Tue Aug 20 19:34:37 2019 TCP_CLIENT link local: (not bound)
Tue Aug 20 19:34:37 2019 TCP_CLIENT link remote: [AF_INET]XX.XX.XX.XX:53
Tue Aug 20 19:34:37 2019 MANAGEMENT: >STATE:1566309877,WAIT,,,,,,
**Tue Aug 20 19:34:37 2019 Connection reset, restarting [0]**
Tue Aug 20 19:34:37 2019 SIGUSR1[soft,connection-reset] received, process restarting
Tue Aug 20 19:34:37 2019 MANAGEMENT: >STATE:1566309877,RECONNECTING,connection-reset,,,,,
Tue Aug 20 19:34:37 2019 Restart pause, 5 second(s)

**Comment by angristan** [comment]
Did you check your instance's firewall?

**Comment by angristan** [comment]
It works for me on Lightsail with Debian 9, and with the correct ports open on the firewall. (I mean the Lightsail firewall, via the web console)

**Comment by saugatadatta** [comment]
Hi,
I have all the ports opened, I am using this for my Lightsail 
WordPress Certified by Bitnami and Automattic 5.1.1-2.

Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial

Ports: https://imgur.com/yroWaAf

Could you please give it a try with same image i am using.

**Comment by angristan** [comment]
It works for me. Are you sure OpenVPN is running?

**Comment by saugatadatta** [comment]
I just deployed a new instances in Lightsail in Oregon, with both TCP/UDP DNS port opened. Installation went fine, even I can telnet to port 53 on the server, but failed to establish connectivity, getting same error in TLS.

========
Tue Aug 20 22:09:25 2019 OpenVPN 2.4.6 x86_64-w64-mingw32 [SSL (OpenSSL)] [LZO] [LZ4] [PKCS11] [AEAD] built on Apr 26 2018
Tue Aug 20 22:09:25 2019 Windows version 6.2 (Windows 8 or greater) 64bit
Tue Aug 20 22:09:25 2019 library versions: OpenSSL 1.1.0h  27 Mar 2018, LZO 2.10
Enter Management Password:
Tue Aug 20 22:09:25 2019 MANAGEMENT: TCP Socket listening on [AF_INET]127.0.0.1:25341
Tue Aug 20 22:09:25 2019 Need hold release from management interface, waiting...
Tue Aug 20 22:09:25 2019 MANAGEMENT: Client connected from [AF_INET]127.0.0.1:25341
Tue Aug 20 22:09:25 2019 MANAGEMENT: CMD 'state on'
Tue Aug 20 22:09:25 2019 MANAGEMENT: CMD 'log all on'
Tue Aug 20 22:09:25 2019 MANAGEMENT: CMD 'echo all on'
Tue Aug 20 22:09:25 2019 MANAGEMENT: CMD 'bytecount 5'
Tue Aug 20 22:09:25 2019 MANAGEMENT: CMD 'hold off'
Tue Aug 20 22:09:25 2019 MANAGEMENT: CMD 'hold release'
Tue Aug 20 22:09:25 2019 Outgoing Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Tue Aug 20 22:09:25 2019 Outgoing Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Tue Aug 20 22:09:25 2019 Incoming Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Tue Aug 20 22:09:25 2019 Incoming Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Tue Aug 20 22:09:25 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]54.190.160.15:53
Tue Aug 20 22:09:25 2019 Socket Buffers: R=[65536->65536] S=[64512->64512]
Tue Aug 20 22:09:25 2019 Attempting to establish TCP connection with [AF_INET]54.190.160.15:53 [nonblock]
Tue Aug 20 22:09:25 2019 MANAGEMENT: >STATE:1566319165,TCP_CONNECT,,,,,,
Tue Aug 20 22:09:26 2019 TCP connection established with [AF_INET]54.190.160.15:53
Tue Aug 20 22:09:26 2019 TCP_CLIENT link local: (not bound)
Tue Aug 20 22:09:26 2019 TCP_CLIENT link remote: [AF_INET]54.190.160.15:53
Tue Aug 20 22:09:26 2019 MANAGEMENT: >STATE:1566319166,WAIT,,,,,,
Tue Aug 20 22:09:26 2019 TLS Error: client->client or server->server connection attempted from [AF_INET]54.190.160.15:53
Tue Aug 20 22:09:26 2019 Fatal TLS error (check_tls_errors_co), restarting
Tue Aug 20 22:09:26 2019 SIGUSR1[soft,tls-error] received, process restarting
Tue Aug 20 22:09:26 2019 MANAGEMENT: >STATE:1566319166,RECONNECTING,tls-error,,,,,
Tue Aug 20 22:09:26 2019 Restart pause, 5 second(s)
Tue Aug 20 22:09:31 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]54.190.160.15:53
Tue Aug 20 22:09:31 2019 Socket Buffers: R=[65536->65536] S=[64512->64512]
Tue Aug 20 22:09:31 2019 Attempting to establish TCP connection with [AF_INET]54.190.160.15:53 [nonblock]
Tue Aug 20 22:09:31 2019 MANAGEMENT: >STATE:1566319171,TCP_CONNECT,,,,,,
Tue Aug 20 22:09:32 2019 TCP connection established with [AF_INET]54.190.160.15:53
Tue Aug 20 22:09:32 2019 TCP_CLIENT link local: (not bound)
Tue Aug 20 22:09:32 2019 TCP_CLIENT link remote: [AF_INET]54.190.160.15:53
Tue Aug 20 22:09:32 2019 MANAGEMENT: >STATE:1566319172,WAIT,,,,,,
Tue Aug 20 22:09:32 2019 Connection reset, restarting [0]
Tue Aug 20 22:09:32 2019 SIGUSR1[soft,connection-reset] received, process restarting
Tue Aug 20 22:09:32 2019 MANAGEMENT: >STATE:1566319172,RECONNECTING,connection-reset,,,,,
Tue Aug 20 22:09:32 2019 Restart pause, 5 second(s)
Tue Aug 20 22:09:37 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]54.190.160.15:53
Tue Aug 20 22:09:37 2019 Socket Buffers: R=[65536->65536] S=[64512->64512]
Tue Aug 20 22:09:37 2019 Attempting to establish TCP connection with [AF_INET]54.190.160.15:53 [nonblock]
Tue Aug 20 22:09:37 2019 MANAGEMENT: >STATE:1566319177,TCP_CONNECT,,,,,,
Tue Aug 20 22:09:38 2019 TCP connection established with [AF_INET]54.190.160.15:53
Tue Aug 20 22:09:38 2019 TCP_CLIENT link local: (not bound)
Tue Aug 20 22:09:38 2019 TCP_CLIENT link remote: [AF_INET]54.190.160.15:53
Tue Aug 20 22:09:38 2019 MANAGEMENT: >STATE:1566319178,WAIT,,,,,,
Tue Aug 20 22:09:38 2019 Connection reset, restarting [0]
Tue Aug 20 22:09:38 2019 SIGUSR1[soft,connection-reset] received, process restarting
Tue Aug 20 22:09:38 2019 MANAGEMENT: >STATE:1566319178,RECONNECTING,connection-reset,,,,,
Tue Aug 20 22:09:38 2019 Restart pause, 5 second(s)
Tue Aug 20 22:09:41 2019 SIGTERM[hard,init_instance] received, process exiting
Tue Aug 20 22:09:41 2019 MANAGEMENT: >STATE:1566319181,EXITING,init_instance,,,,,

**Comment by angristan** [comment]
The client can access the server, but the issue is `Connection reset, restarting`

**Comment by angristan** [comment]
Can you check the openvpn logs on the server?

**Comment by saugatadatta** [comment]
This is very strange, nothing wrong OpenVPN, as today I discovered that something blocking the client while initiating the connectivity over home WiFi, it is actually dropping the request, and I really don't know why or what actually the root cause.

I am able to established the connectivity while using my mobile data.

Thanks for your help.

**Comment by angristan** [comment]
Interesting! Maybe some QoS on your router or something :man_shrugging:
