### ISSUE TITLE
Need "#security-and-encryption" section in README.md

### ISSUE THREAD

**Issue by BaseMax** [angristan/openvpn-install#471]
Hello,

```
Do you want to customize encryption settings?
Unless you know what you're doing, you should stick with the default parameters provided by the script.
Note that whatever you choose, all the choices presented in the script are safe. (Unlike OpenVPN's defaults)
See https://github.com/angristan/openvpn-install#security-and-encryption to learn more.
```

Link: https://github.com/angristan/openvpn-install#security-and-encryption
At: https://github.com/angristan/openvpn-install/blob/master/README.md

Best,
Max Base

**Comment by angristan** [comment]
The anchor does exist, though?

**Comment by BaseMax** [comment]
> The anchor does exist, though?

Yes, Let's me to check.

Best,
Max

**Comment by angristan** [comment]
I'm confused :slightly_smiling_face: If https://github.com/angristan/openvpn-install#security-and-encryption is valid, what is the issue about?

**Comment by BaseMax** [comment]
> I'm confused 🙂 If https://github.com/angristan/openvpn-install#security-and-encryption is valid...

Sorry, Thank you, Solved. 👍
