### ISSUE TITLE
Increase certificate issue time and some infos

### ISSUE THREAD

**Issue by rtu-dataframe** [angristan/openvpn-install#474]
Hi, many thanks for the script, it's very useful for me.

I have two question about the certificate issue time, and how i can modify these infos:

- How it's generated the CA server certificate? what is the CA server issue days? 
- How it's generated the client certificate? i've seen that the issue days are set to 1080, if i want, for example increase the expiry date of the server CA and certificates, where i need to go to modify those settings? it's possible to manage them using the script itself?

Thanks.

**Comment by rtu-dataframe** [comment]
Ok, i've solved the problem echoing into the var file in this section of the script:

```
        SERVER_CN="cn_$(head /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 16 | head -n 1)"
	SERVER_NAME="server_$(head /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 16 | head -n 1)"
	echo "set_var EASYRSA_REQ_CN $SERVER_CN" >> vars

        echo 'set_var EASYRSA_CA_EXPIRE	    36500'                      >> vars
        echo 'set_var EASYRSA_CERT_EXPIRE	36500'                      >> vars
        echo 'set_var EASYRSA_CRL_DAYS	    36500'                      >> vars

	# Workaround to remove unharmful error until easy-rsa 3.0.7
	# https://github.com/OpenVPN/easy-rsa/issues/261
	sed -i 's/^RANDFILE/#RANDFILE/g' pki/openssl-easyrsa.cnf
```

**Comment by randshell** [comment]
#109
