### ISSUE TITLE
How do I change DNS without reinstalling everything?

### ISSUE THREAD

**Issue by LordPicard** [angristan/openvpn-install#475]
Hello,

This might be a simple question, but here it goes.
When I installed the VPN using the script I setup a DNS provider. However, I want to change it.

I'm not sure if I just need to modify /etc/resolv.conf (CentOS) to take effect because I don't know what option / where does the script save the information I add about the DNS server I want to use.

Thank you for letting me know.

Regards.

**Comment by angristan** [comment]
You can modify `/etc/openvpn/server.conf` and then restart the openvpn server with `systemctl restart openvpn@server`
