### ISSUE TITLE
Suggestion: Enable 2 DNS Servers in the server.conf

### ISSUE THREAD

**Issue by johndave9296** [angristan/openvpn-install#476]
As stated in the title, hopefully this would be implemented in the next update using this in the custom dns server input not by 2 but making jit 4. This is my sample DNS lines in my server.conf

![image](https://user-images.githubusercontent.com/8472952/64309315-c2355b00-cfce-11e9-9a49-98ea43fe68f7.png)

**Comment by angristan** [comment]
Well that doesn't seem very useful. You will end up using the first server 99.99999999999% of the time anyways. That seems overkill.

**Comment by johndave9296** [comment]
Not likely so sir because it only helps it apply 2 DNS Servers at the same time but depends.
