### ISSUE TITLE
Change time sending tls key session

### ISSUE THREAD

**Issue by malikshi** [angristan/openvpn-install#478]
How to change time to send tls key session? Default is every 1hour right? I want change it to every 6 hour. Or disable it if possible

**Comment by randshell** [comment]
For 6 hours add `reneg-sec 21600` to `/etc/openvpn/server.conf`. You can disable it with `reneg-sec 0` but for security it's not recommended.

**Comment by malikshi** [comment]
Solved

**Comment by randshell** [comment]
Can I ask why you need to change the `reneg-sec` option? If it's because credentials aren't cached and so you need to login again every hour, #662 should prevent this.

**Comment by malikshi** [comment]
It's tls renegotiate key, now I'm set 0 to disable reconnect every one hour default value. My clients are complaining bcs every one hour are asking reconnect. Well my clients are complaining about reconnect every 1 hour

**Comment by randshell** [comment]
> Well my clients are complaining about reconnect every 1 hour

It's just logging not a complain. For security reasons the renegotiation should happen every hour
