### ISSUE TITLE
DNS Leaks

### ISSUE THREAD

**Issue by ghost** [angristan/openvpn-install#479]
How does one avoid DNS leaks? 

Are they absent in the default config?

Thanks in advance.

**Comment by angristan** [comment]
They should be blocked yes. In the [FAQ](https://github.com/angristan/openvpn-install/wiki/FAQ), I wrote:

> **Q:** How do I check for DNS leaks?
> 
> **A:** Go to [dnsleaktest.com](https://dnsleaktest.com/) or [ipleak.net](https://ipleak.net/) with your browser. Only your server's IP should show up.

If you notice DNS leaks, please let us know!

**Comment by ghost** [comment]
According to dnsleaktest.com i'm fine, on ipleak.net it shows my home dns and geo location though.

**Comment by ghost** [comment]
Actually, I just ran the extended test on ipleak.net and that shows my ISP too.

**Comment by angristan** [comment]
Which client OS are you using?

**Comment by ghost** [comment]
OpenVPN 2.4.7 [git:makepkg/2b8aec62d5db2c17+] x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 19 2019 / Arch Linux

**Comment by angristan** [comment]
How are you connecting? Using NetworkManager?

**Comment by ghost** [comment]
```
systemctl enable openvpn-client@openvpn.service
systemctl start openvpn-client@openvpn.service
```

**Comment by ghost** [comment]
Yes I do use NetworkManager to connect my system to the dhcp server on my router.

**Comment by bayars** [comment]
@gregf You resolv.conf system may use local dns address. I give a sample in /etc/resolv.conf: 

```
nameserver 192.168.1.1
search <yourdomain>
```

so your system first look at local DNS address. You should change yours DNS address also it might be same in openvpn DNS configuration. (You can look at /etc/openvpn/server.conf)

**Comment by ghost** [comment]
Sorry I meant to come back to this issue, yeah my local resolver wasn't right. Maybe this should get documented, because I was under the impression that the client did this automatically.

**Comment by bayars** [comment]
Okay, I will open PR for this problem. I think, we can close this issue.

**Comment by angristan** [comment]
#597

**Comment by randshell** [comment]
@angristan an older issue is duplicate of a newer one?

> #597

Including the comment would be faster https://github.com/angristan/openvpn-install/issues/597#issuecomment-607452478

**Comment by angristan** [comment]
The age does not matter. #597 is the one with the most helpful information so, yes, the others are duplicates to me.
