### ISSUE TITLE
Feature request: Change (or randomize) the CN on the CA

### ISSUE THREAD

**Issue by DavidCWGA** [angristan/openvpn-install#48]
I wanted to use this script to setup two VPNs on pfSense, but because both certs are signed by a CA with the same name "ChangeMe", it confuses the two and you can only use one at a time.

**Comment by DavidCWGA** [comment]
I kludged a fix by adding this line:
````
echo "set_var EASYRSA_REQ_CN $(date +'%Y-%m-%d-%H-%M')" >> vars
````
after this line:
````
echo "set_var EASYRSA_KEY_SIZE $RSA_KEY_SIZE" > vars
````

This sets the CN to be the date and time you ran the script, which isn't super pretty, but it is unique.

(Sorry I don't know how to make a pull request.)

**Comment by DavidCWGA** [comment]
Changing the CA name was not enough. Both VPNs had the same gateway network "10.8.0.0". I had to search-and-replace every mention of 10.8. with 10.somethingelse. on one of the VPNs to finally generate two that did not clash. Perhaps this network could also be randomized.

**Comment by tenten8401** [comment]
Just gonna nudge this issue a bit as having "ChangeMe" as the CA is kinda strange.

**Comment by angristan** [comment]
@tenten8401 this is set by easy-rsa, not the script https://github.com/OpenVPN/easy-rsa/blob/master/easyrsa3/vars.example#L193

**Comment by tenten8401** [comment]
However, that doesn't mean we can't change it in the script.

**Comment by angristan** [comment]
@tenten8401 sure

**Comment by ttait-vantim** [comment]
Is it possible to let the user give meaningful names there instead? 

Also can the user enter the desired subnet?

Thanks
Tim
