### ISSUE TITLE
Not an issue, but a question, please...

### ISSUE THREAD

**Issue by 7starsone** [angristan/openvpn-install#484]
Hello,
could you technically explain why you need to install `unbound`?

That's it, reading a lot about openvpn, no one suggests to do it...or the need of it...
hence the question 😄 
thank you, it works very well at the moment

**Comment by r7l** [comment]
You don't need to install it. It's an option next to many others. You can select one of the others and decide against unbound if you don't see a need for it.

**Comment by 7starsone** [comment]
ok, thanks...just another, please:
I noticed that there's not `client-to-client` option but routing works anyway...
and at the same time I don't find `route add..`, `push route` or something like this into the script...

so, how it works? Before I had issues to let clients ping each others and use the internet access from the virtual machine....now, instead, all is working like a charm...so I would like to better understand
and also, why `bypass-dhcp` is important here?
