### ISSUE TITLE
CentOS 7: something wrong with iptables

### ISSUE THREAD

**Issue by 7starsone** [angristan/openvpn-install#485]
Hello,
sorry, don't know the origin of the issue...

1) yesterday I saved the iptables into `/etc/sysconfig/iptables`

2) today removed the old openvpn and installed by your script
so, the 1st time it worked and the clients connected as usual

3) then on purpose I rebooted the virtual machine and unfortunately I had `no route to host` on the client log and `TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)... TLS Error: TLS handshake failed` 

4) I went back to check `/etc/sysconfig/iptables` and
`Generated by iptables-save v1.4.21 on Mon Sep 16 01:48:51 2019`
that means the yesterday edits are there...

I had to stop the iptables service to let it run good

So, does it mean that your script doesn't permanently save firewall rules? Or better, I see that you autostart some rules by service...so What Do i need to do now? I think I need to reset those old bad iptables to default...wait for confirmation
Thanks

**Comment by 7starsone** [comment]
I removed iptables, then openvpn..., reinstalled iproute/iptables and reinstall by your script

maybe I didn't notice it before but on your install log there is...
`sysctl: cannot open "/etc/sysctl.conf": No such file or directory`

why this, please?

**Comment by angristan** [comment]
The script adds `/etc/iptables/add-openvpn-rules.sh` and `/etc/iptables/rm-openvpn-rules.sh` and executes them with `/etc/systemd/system/iptables-openvpn.service`. That's all there is to it. All these files are deleted when you uninstall OpenVPN with the script

**Comment by angristan** [comment]
I don't know why you have `sysctl: cannot open "/etc/sysctl.conf": No such file or directory`. This doesn't seem related. The script only adds/removes `/etc/sysctl.d/20-openvpn.conf`.

**Comment by pchaos** [comment]
centos 7 using firewalld,not iptalbes.
try edit /etc/systemd/system/iptables-openvpn.service, add "After=firewalld.service"
good luck!

**Comment by manickamk** [comment]
Description=iptables rules for OpenVPN
Before=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
ExecStart=/etc/iptables/add-openvpn-rules.sh
ExecStop=/etc/iptables/rm-openvpn-rules.sh
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
~


Where i have add please let me know

**Comment by angristan** [comment]
@manickamk Below `Wants=`

**Comment by randshell** [comment]
> centos 7 using firewalld,not iptalbes.

Indeed, this issue is likely the same as #356

**Comment by angristan** [comment]
Closing as duplicate of https://github.com/angristan/openvpn-install/issues/356
