### ISSUE TITLE
not able to connect after revoke of one of the users

### ISSUE THREAD

**Issue by estimadarocha** [angristan/openvpn-install#49]
This is the second time this happens... after i revoke a user i cannot connect again with any of the remain users... any help will be appreciated!

**Comment by estimadarocha** [comment]
it looks like a issue with crl.pem permissions after the revoke

**Comment by Kcchouette** [comment]
duplicate issue: See #47

**Comment by chocolateshirt** [comment]
go to /etc/openvpn

then make **chown nobody crl.pem**

**Comment by estimadarocha** [comment]
@chocolateshirt 

still getting 
CRL: cannot read: crl.pem

**Comment by chocolateshirt** [comment]
Just goto openvpn directory, every distro have their own directory..
