### ISSUE TITLE
customer suspension

### ISSUE THREAD

**Issue by ultraandreyy** [angristan/openvpn-install#493]
Hello! Please help with advice.
How can I stop a client profile without deleting it from the server?

To just run this profile in the future.

Thank.

**Comment by nerull13** [comment]
i follow !

this would be  perfect !!

**Comment by AMDBartek** [comment]
This would be a good idea.

**Comment by randshell** [comment]
```
echo "disable" > /etc/openvpn/ccd/user1
echo "disable" > /etc/openvpn/ccd/user2
```
To re enable `user1` you remove `disable` from `/etc/openvpn/ccd/user1` or remove the file:
```
rm /etc/openvpn/ccd/user1
```

@angristan Can we add it to the FAQ?

**Comment by ghost** [comment]
> Enable client specific configuration:
> 
> ```
> echo "client-config-dir ccd" >> /etc/openvpn/server.conf
> mkdir /etc/openvpn/ccd
> service openvpn restart
> ```
> 
> To disable users
> 
> ```
> echo "disable" > /etc/openvpn/ccd/user1
> echo "disable" > /etc/openvpn/ccd/user2
> ```
> 
> To re enable `user1` you remove `disable` from `/etc/openvpn/ccd/user1` or remove the file:
> 
> ```
> rm /etc/openvpn/ccd/user1
> ```
> 
> @angristan Can we add it to the FAQ?

no work for me

**Comment by randshell** [comment]
@ortiga88  What OS and OpenVPN server version are you using? I tested on updated Debian 10 server and it works.

To test if it's working you need to disconnect the client you want to disable, disable it on the server with the command above (replace `user1` with the client name) and then try to connect.
I'm not sure but I think if you disable a client when he is connected you need to wait 1 hour for the vpn renegotiation to happen and then the user will be disconnected and disabled.

**Comment by ghost** [comment]
> @ortiga88 What OS and OpenVPN server version are you using? I tested on updated Debian 10 server and it works.
> 
> To test if it's working you need to disconnect the client you want to disable, disable it on the server with the command above (replace `user1` with the client name) and then try to connect.
> I'm not sure but I think if you disable a client when he is connected you need to wait 1 hour for the vpn renegotiation to happen and then the user will be disconnected and disabled.

ok it already works for me, but is it safe to implement this configuration ???

**Comment by randshell** [comment]
Yes it's safe. From the OpenVPN manual:

> Disable a particular client (based on the common name) from connecting. Don't use this option to disable a client due to key or password compromise. Use a CRL (certificate revocation list) instead (see the --crl-verify option).

**Comment by HenryNe** [comment]
As I known, needs to put the option whith `--`
```
echo '--disable' > /etc/openvpn/ccd/user1
echo '--disable' > /etc/openvpn/ccd/user2

```

**Comment by randshell** [comment]
I think `--` are for command line arguments. In configurations you can write only the option.

**Comment by HenryNe** [comment]
> 
> 
> I think `--` are for command line arguments. In configurations you can write only the option.

Ok, You are right. Just tested. Both works.

**Comment by ultraandreyy** [comment]
Thank you very much, you helped me a lot.
