### ISSUE TITLE
Server cloning

### ISSUE THREAD

**Issue by ultraandreyy** [angristan/openvpn-install#494]
Hello!
Suppose I bound my domain to an OpenVPN server.
In the future, the server became unavailable. How can I restore OpenVPN on a new server by binding my domain to it?

How can I run my OpenVPN server on another server without replacing the server keys.

Thank.

**Comment by pchaos** [comment]
backup pre vps /etc/openvpn 
after setup new vpn in new vps,restore /etc/openvpn

**Comment by angristan** [comment]
^this + update the IP in your client config file, unless you use a domain

**Comment by ultraandreyy** [comment]
> backup pre vps /etc/openvpn
> after setup new vpn in new vps,restore /etc/openvpn

Thank you very much for your reply.

I tried to do so. I launched Openvpn on the VDS server, created a test user profile for openvpn, launched this profile on my phone - it works.

Next, I copied the entire openvpn folder from the / etc folder, and deleted Openvpn from the server.

On the same VDS server, I installed openvpn again, and via FTP I copied the "openvpn" folder to the server folder on the server etc.

On the server, and for a minute my profile appears in the Openvpn user list, but then disappears. The old profile in the phone does not start. The list of OpenVPN users is empty.

The server is bound to a domain. The domain is registered in the profile.

Please help with advice, what am I doing wrong?

Thank you so much.

**Comment by ultraandreyy** [comment]
Thanks a lot. That helped
