### ISSUE TITLE
Fedora 30 requires change

### ISSUE THREAD

**Issue by pswilde** [angristan/openvpn-install#495]
Configuring on Fedora Server 30, haven't tried earlier versions, all works fine once configured but a minor change is needed in the script.
Because Fedora Server 30 has both /etc/system-release and /etc/fedora-release files, and /etc/system-release gets checked first in the script, the $OS variable in checkOS() returns an empty value. Moving the `elif [[ -e /etc/fedora-release ]]; then
                OS=fedora` line before the `elif [[ -e /etc/system-release ]]; then` line resolves the issue for now.

**Comment by angristan** [comment]
Seems to have been fixed in the meantime
