### ISSUE TITLE
Tried removing other Linux systems except ubuntu

### ISSUE THREAD

**Issue by johndave9296** [angristan/openvpn-install#496]
After editing it, it gave me numerous errors mostly on if statements. Can you atleast give me a proper script that only supports ubuntu system?

**Comment by angristan** [comment]
Can you clarify your issue?

**Comment by johndave9296** [comment]
I want to run the script by which it is supported only to ubuntu Sir but when I tried removing other linux systems in the code, it gave me bunch of errors running them.

**Comment by angristan** [comment]
Sorry I don't understand...

**Comment by johndave9296** [comment]
What I am trying to sir is that your openvpn-install.sh can be run in any linux systems right depends on its compatibility? Now I want to edit it and only run on Ubuntu Linux system. Now it only gives me errors when I tried removing the other linux based systems. Is there any way to run your script only for Ubuntu?

**Comment by angristan** [comment]
> Is there any way to run your script only for Ubuntu?

Run it on Ubuntu then...

**Comment by angristan** [comment]
I don't support edits...
