### ISSUE TITLE
Self-hosted DNS Resolver (Unbound)

### ISSUE THREAD

**Issue by angristan** [angristan/openvpn-install#5]
As discussed in https://github.com/Angristan/OpenVPN-install/issues/4, having the option to use a local DNS server would be great for the following reasons : 

- It will be fast all aroung the world, as it will allow a local cache and will communicate directly with the root servers
- It's neutral
- Logs will be disabled by default, and if they are enabled, they'll be only accessible on the server
- It does not depend on any third-party server, thus ensuring 100% availability and neutrality

I already made a script to install a local DNS server on a Linux machine : https://github.com/Angristan/Local-DNS-resolver

I will use unbound, and adapt the configuration to allow queries from the private network (10.8.0.0/24), and then use 10.8.0.1 as the DNS resolver in the OpenVPN configuration.

~If unbound is already installed on the server where the script is ran, I think I'll ask for a confirmation to overwrite `/etc/ubound.conf`, and if the answer is no, ask the user to select other DNS servers.~

Any suggestion is welcomed until I implement the feature.

**Comment by Kcchouette** [comment]
>Any suggestion is welcomed until I implement the feature.

As I say at https://github.com/Angristan/OpenVPN-install/issues/4#issuecomment-268005288, use dnscrypt and dns-scrypt-proxy to make a request to others servers.

**Comment by yolateng0** [comment]
Pourquoi ne pas installer directement Unbound lors de l’installe du script?
Cela fonctionne, j'ai testé sur un fork de l'ancienne version.
https://github.com/yolateng0/OpenVPN-install

Why not install Unbound directly when installing the script?
This works, I tested on a fork of the old version.
Https://github.com/yolateng0/OpenVPN-install

thanks for your work 0/ <3

**Comment by angristan** [comment]
That's what I'm going to do :)

**Comment by chpasswd** [comment]
Adblocking? like [this](https://github.com/pi-hole/pi-hole) but without the web interface, etc.

**Comment by angristan** [comment]
@chpasswd 
>Adblocking? like this but without the web interface, etc.

No.

**Comment by Leopere** [comment]
You could try to use [Pi-Hole](https://pi-hole.net/) which also happens to have a fancy UI.  It does blocking and things as well.  I wonder if it'd work to do IP blocklists as well.

**Comment by angristan** [comment]
The goal is only to install a neutral DNS resolver. You can install Pi-Hole on your server if you want and use it with OpenVPN :)

**Comment by cezar97** [comment]
@Angristan 
Any updates about integration with Local-DNS-resolver? I just created a pull request for this [here](https://github.com/Angristan/Local-DNS-resolver/pull/10).

@chpasswd 
Integration with a local dns resolver can also be set-up to block ads domains, but ad-blocking will not be included in the repo as it's out of scope for this project. Despite this, [Pi-Hole](https://pi-hole.net/) it's the best solution for ad-blocking.

**Comment by angristan** [comment]
Yep, the update to Local-DNS-resolver will help.

I guess we should add a check like if `netstat -tuln | grep :53` is not empty then we don't install unbound or something

**Comment by Leopere** [comment]
@Angristan you could look into how the PiHole does it's stuff and maybe omit anything in their script that installs the web panel or something.  OR include it as an option.  It wouldn't work in my usage case as I'm hosting my own authoritative nameservers on my OpenVPN instance but some people might like the DNS blackholing capability.

**Comment by cezar97** [comment]
@chamunks Maybe this can help:
https://gist.github.com/iamGavinJ/e05831979b247a24068e88a6b02eedc1

**Comment by Leopere** [comment]
Oops, my apologies I didn't realize how many times in this thread people had mentioned PiHole and slammed the idea down.  I think that PiHole has other benefits outside of simple adblocking it also helps thwart malicious attempts to call home to command and control nodes given that they are known threats.  

At the end of the day I think that a great home VPN solution if we're taking this way further than we initially intended should probably help the user gain full control over their traffic.  

There is too much [background radiation](https://dl.acm.org/citation.cfm?id=1028794) in modern tech if we could help people get to a point where the background radiation is a bit more under control I think that's a pretty positive benefit to the internet as a whole.  

I wonder how much of the internet is just background radiation now that I think of it.

**Comment by Leopere** [comment]
I was just reading @cezar97's response in #189 about a web panel and the security implications and it had me thinking.

What sort of collision would there be between this script and PiHole would it be reasonable to just add a test to see if PiHole is installed?  Then if it is just to use that.

**Comment by cezar97** [comment]
@Angristan I know others asked for it and you already answered, but if unbound gets selected for install, why not include ( with another option that can be chosen by user ) the pi-hole default blacklists and integrate them with unbound, so no need for installing other things?
Why I'm asking it again, then? Because we are not talking just about ads but also trackers all around the web ( not to forget that ads often if not always are trackers too ). So at least while using VPN, trackers and other stuff like malware domains get blocked.
That said, it remains up to you to decide: I'm sorry for re-asking if you're not fine with this.
PS: I'm talking about pi-hole blacklists just because they don't block more than basic and necessary things and so sites don't get broken.
@chamunks @chpasswd

**Comment by Leopere** [comment]
The biggest value-add from a PiHole is the ability to whitelist domains it
has the whole functionality already stitched in.  Even if the script just
offers you a suggestion/endorsement to go and install PiHole yourself it
might be cool.  I mostly just want to know if there are conflicts between
the two scripts which is kind of hard to tell at first.

**Comment by angristan** [comment]
Installing Pi-Hole or any web interface is clearly no, but adding an option for a blacklist to the unbound option may be ok.

**Comment by cezar97** [comment]
@Angristan Thank you for your response.
@chamunks Well, there aren't any kind of conflicts. I can tell you that because this was my setup for a while: I had a machine running openvpn and pihole was listening on the VPN interface 10.8.0.1 and another machine running an unbound caching resolver, just because both of them requires listening on port 53. The upstream for pihole was the ip of unbound.
Later on I thought that it can be done on a single machine, too. Pihole can listen on 10.8.0.1:53/tcp-udp and unbound on 127.0.0.1:53/tcp-udp: it's possible because it is the same port but on different interfaces. So here as the upstream you just have to use 127.0.0.1.

**Comment by Leopere** [comment]
Spectacular idea

**Comment by cezar97** [comment]
@chamunks I'm glad it helped. BTW may I have a response on your # 179's and # 195's so maybe I can update the answer in case, too?

**Comment by Leopere** [comment]
Always nice to be good netizens and leave good records for future Googlers.

**Comment by cezar97** [comment]
@Angristan For this integration isn't enough the local dns option in the menu and :
```
wget -O /tmp/unbound-install.sh https://raw.githubusercontent.com/Angristan/Local-DNS-resolver/master/unbound-install.sh
bash /tmp/unbound-install.sh
sed -i 's|interface: 127.0.0.1|interface: 10.8.0.1|' /etc/unbound/unbound.conf
sed -i 's|access-control: 127.0.0.1 allow|access-control: 10.8.0.0/24 allow|' /etc/unbound/unbound.conf
```
? Or it needs tweaks somewhere else like don't modify `/etc/resolv.conf` to set unbound as the machine's default resolver, etc.?

**Comment by angristan** [comment]
Yes I think we shouldn't touch `/etc/resolv.conf`

**Comment by cezar97** [comment]
@Angristan and what about `resolvconf` and `ubuntu-minimal`? I think it's a bad idea automatically uninstall them in production. BTW on Debian I tried installing unbound with `resolvconf` still installed and didn't notice any problem, didn't tested on Ubuntu though.

**Comment by angristan** [comment]
It's been a long time since I decided to remove these, but if we use `chattr` to lock `resolv.conf`, it may not be needed...

**Comment by Leopere** [comment]
I personally have to also be careful as I'm using OpenVPN on the same
machine as a mail server and authoritative DNS. Via MailInABox.

**Comment by angristan** [comment]
Enjoy :)
