### ISSUE TITLE
static_key_parse_error on Android

### ISSUE THREAD

**Issue by CatalinSoare** [angristan/openvpn-install#500]
Hello,

The openvpn-install script ran successfully, on a Debian 10 server.
However when I tried to import it into an Android 7.0 device, running the official OpenVPN client, I got a "Failed to parse profile: static_key_parse_error".
After inspecting the .ovpn client file, I noticed that the tls-crypt section in it is empty:

```
<tls-crypt>
</tls-crypt>

```

Since this is the first time I've ran the openvpn-install script (with no other options passed to it), I have no idea if this is something that the script should have taken care of it, or I should do something

Thanks for any suggestions

**Comment by angristan** [comment]
Have you tried generating another client? Is the `tls-crypt` section empty too?

**Comment by CatalinSoare** [comment]
Yes, apparently a new client will also have the tls-crypt section empty

**Comment by CatalinSoare** [comment]
OK, honestly, I have no idea what happened.
I've been able to install it in a VM, and then on a physical server without issues -- basically I wasn't able to duplicate the issue myself.

**Comment by angristan** [comment]
Oh ok :) I will close this then
