### ISSUE TITLE
FAQ clarification for TLS Crypt

### ISSUE THREAD

**Issue by marchelo2000** [angristan/openvpn-install#508]
This is not an issue but a problem of ASUS routers which I spent a lot of time to understand and nice to be reflected in FAQ. 

Asus Routers do not support Tls-crypt. 
In such case they throw error:
Options error: No closing quotation (") in config.ovpn:46

To fix it is need to go to custom encryption setting during setup and choose TLS Auth.

**Comment by dmitrybabich** [comment]
@marchelo2000 thank you for this comment. You cannot imagine how much time you saved me! The configuration from FAQ doesn't work for me, but when I enable only TLS Auth - everything works perfectly.

**Comment by angristan** [comment]
Thanks @marchelo2000 :)

**Comment by randshell** [comment]
Related #162 #387 #540
