### ISSUE TITLE
Feature request: support for IPv6 inside the tunnel

### ISSUE THREAD

**Issue by DavidCWGA** [angristan/openvpn-install#51]
The current configuration is set up for IPv4 only. It would be nice to be able to support IPv6.

**Comment by thxo** [comment]
#24 might be worth a look.

**Comment by DrXala** [comment]
Check this merge request [#45](https://github.com/Angristan/OpenVPN-install/pull/45).

**Comment by angristan** [comment]
See #238 for IPv6 support **with NAT**
