### ISSUE TITLE
I have these errors on Ubuntu 18

### ISSUE THREAD

**Issue by fa1rid** [angristan/openvpn-install#511]
read EC key
writing EC key
Can't load /etc/openvpn/easy-rsa/pki/.rnd into RNG
140254160486848:error:2406F079:random number generator:RAND_load_file:Cannot open file:../crypto/rand/randfile.c:88:Filename=/etc/openvpn/easy-rsa/pki/.rnd

Note: using Easy-RSA configuration from: ./vars

Using SSL: openssl OpenSSL 1.1.1  11 Sep 2018
Can't load /etc/openvpn/easy-rsa/pki/.rnd into RNG
140303726440896:error:2406F079:random number generator:RAND_load_file:Cannot open file:../crypto/rand/randfile.c:88:Filename=/etc/openvpn/easy-rsa/pki/.rnd
Generating an EC private key
writing new private key to '/etc/openvpn/easy-rsa/pki/private/server_Atv2pbib8chXQmmU.key.V6V4UboucE'

Using configuration from /etc/openvpn/easy-rsa/pki/safessl-easyrsa.cnf
Can't load /etc/openvpn/easy-rsa/pki/.rnd into RNG
140107950825920:error:2406F079:random number generator:RAND_load_file:Cannot open file:../crypto/rand/randfile.c:88:Filename=/etc/openvpn/easy-rsa/pki/.rnd
Can't open /etc/openvpn/easy-rsa/pki/index.txt.attr for reading, No such file or directory
140107950825920:error:02001002:system library:fopen:No such file or directory:../crypto/bio/bss_file.c:72:fopen('/etc/openvpn/easy-rsa/pki/index.txt.attr','r')
140107950825920:error:2006D080:BIO routines:BIO_new_file:no such file:../crypto/bio/bss_file.c:79:
Check that the request matches the signature
Signature ok
The Subject's Distinguished Name is as follows
commonName            :ASN.1 12:'server_Atv2pbib8chXQmmU'
Certificate is to be certified until Oct  8 21:18:27 2022 GMT (1080 days)

Write out database with 1 new entries
Data Base Updated

Note: using Easy-RSA configuration from: ./vars

Using SSL: openssl OpenSSL 1.1.1  11 Sep 2018
Using configuration from /etc/openvpn/easy-rsa/pki/safessl-easyrsa.cnf
Can't load /etc/openvpn/easy-rsa/pki/.rnd into RNG
140159892517312:error:2406F079:random number generator:RAND_load_file:Cannot open file:../crypto/rand/randfile.c:88:Filename=/etc/openvpn/easy-rsa/pki/.rnd

An updated CRL has been created.
CRL file: /etc/openvpn/easy-rsa/pki/crl.pem

* Applying /etc/sysctl.d/10-console-messages.conf ...
kernel.printk = 4 4 1 7
* Applying /etc/sysctl.d/10-ipv6-privacy.conf ...

Using SSL: openssl OpenSSL 1.1.1  11 Sep 2018
Can't load /etc/openvpn/easy-rsa/pki/.rnd into RNG
139866303836608:error:2406F079:random number generator:RAND_load_file:Cannot open file:../crypto/rand/randfile.c:88:Filename=/etc/openvpn/easy-rsa/pki/.rnd
Generating an EC private key
writing new private key to '/etc/openvpn/easy-rsa/pki/private/farid.key.JWDhQp5gef'
Using configuration from /etc/openvpn/easy-rsa/pki/safessl-easyrsa.cnf
Can't load /etc/openvpn/easy-rsa/pki/.rnd into RNG
140047423467968:error:2406F079:random number generator:RAND_load_file:Cannot open file:../crypto/rand/randfile.c:88:Filename=/etc/openvpn/easy-rsa/pki/.rnd
Check that the request matches the signature
Signature ok
The Subject's Distinguished Name is as follows
commonName            :ASN.1 12:'farid'
Certificate is to be certified until Oct  8 21:19:13 2022 GMT (1080 days)

Write out database with 1 new entries
Data Base Updated

Client farid added, the configuration file is available at /root/farid.ovpn.
Download the .ovpn file and import it in your OpenVPN client.

**Comment by fa1rid** [comment]
The problem is your sed command to fix easyrsa 3.0.6 is not working:

sed: can't read pki/openssl-easyrsa.cnf: No such file or directory

**Comment by fa1rid** [comment]
You need to put sed command after this line:
./easyrsa init-pki
and before
./easyrsa --batch build-ca nopass

**Comment by melalj** [comment]
I have the same issue here...
@fa1rid Where do I font the file `pki/openssl-easyrsa.cnf` ?

**Comment by fa1rid** [comment]
@melalj just edit the script as I said above.
Search for ./easyrsa init-pki 
Then before it you will find 'sed ....' command.Take this command and put it after ./easyrsa init-pk

**Comment by bayars** [comment]
@fa1rid We had take this error on centos 8 support issue. I wrote this [comment:](https://github.com/angristan/openvpn-install/pull/506/files/b8f0eed80cad0dac849cea9b65ac099ecf10bed9#r338290469)
