### ISSUE TITLE
Allow option to pass more variables

### ISSUE THREAD

**Issue by Akshay-Hegde** [angristan/openvpn-install#516]
https://github.com/angristan/openvpn-install/blob/caa571f7688eb1ffd2df8c9d908ee787a4503b51/openvpn-install.sh#L672

Example

```
echo "set_var EASYRSA_REQ_CN $SERVER_CN" >> vars

 # pass more vars from file, can be used to override also
        [ ! -z "$MORE_VARS" ] && [ -f "$MORE_VARS" ] && cat "$MORE_VARS" >>vars
```

and then run installation

```
export MORE_VARS="/home/akshay/server-setup/more_vars.txt"
./openvpn-install.sh
```
I see in feature list `Randomised server certificate name`, what is the use of it, I didn't understand how this helps.

**Comment by angristan** [comment]
Randomised server certificate name is because when doing packet inspection you can get the certificate name during the handshake. If you see "openvpn" it's obvious the packet is an openpvn packet.
