### ISSUE TITLE
How to fill «gateway» parameter ?

### ISSUE THREAD

**Issue by stemy2** [angristan/openvpn-install#518]
Hello,

I have generated a vpn config file with headless install but it is unusable. The gateway parameter is empty and i have no idea of how to fill it, so i can't apply the config.

**Comment by angristan** [comment]
If this happen again please run the script with `bash -x openvpn-install.sh`. Otherwise we can't guess what went wrong.

**Comment by randshell** [comment]
Did you set the `ENDPOINT` variable?
```
If the server is behind NAT, you can specify its endpoint with the ENDPOINT variable. If the endpoint is the public IP address which it is behind, you can use ENDPOINT=$(curl -4 ifconfig.co) (the script will default to this). The endpoint can be an IPv4 or a domain.
```
