### ISSUE TITLE
Centos7 installs OpenVPN configuration log without time mark

### ISSUE THREAD

**Issue by Sirius2016** [angristan/openvpn-install#519]
Centos7 installs OpenVPN configuration log without time mark
There is no time mark in the log file.
Please help with it.

add server.conf:
log  /var/log/openvpn/openvpn.log

**Comment by TinCanTech** [comment]
This is configured in the **systemd** unit file with `--suppress-timestamps`
Read the log with `journalctl -u openvpn-{server/client}@your-config` and do **not** include `--log your-logfile.log` in the config file.
