### ISSUE TITLE
Cannot connect from iOS/Android when on local LAN

### ISSUE THREAD

**Issue by ghost** [angristan/openvpn-install#52]
Hello,

thanks a lot for your great script. There's just one little issue on my (Debian 8) installation that I hope can be resolved:

When I connect from my Android or iOS device via my mobile / LTE connection, all is fine and I get to my VPN. However, if my device is in my home WiFi (same network as OpenVPN server), I cannot connect to OpenVPN. The client says "waiting for server" until a timeout occurs, and on the server I see a lot of these lines:

```
Fri Apr 14 22:39:58 2017 172.16.0.42:64061 TLS: Initial packet from [AF_INET]172.16.0.42:64061, sid=7837bf5f 957ffa19
Fri Apr 14 22:39:59 2017 172.16.0.42:64061 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #1 / time = (1492202398) Fri Apr 14 22:39:58 2017 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Fri Apr 14 22:39:59 2017 172.16.0.42:64061 TLS Error: incoming packet authentication failed from [AF_INET]172.16.0.42:64061
Fri Apr 14 22:40:00 2017 172.16.0.42:64061 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #1 / time = (1492202398) Fri Apr 14 22:39:58 2017 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Fri Apr 14 22:40:00 2017 172.16.0.42:64061 TLS Error: incoming packet authentication failed from [AF_INET]172.16.0.42:64061
Fri Apr 14 22:40:01 2017 172.16.0.42:64061 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #1 / time = (1492202398) Fri Apr 14 22:39:58 2017 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
```

As soon as I switch to 3G/LTE, I can connect and all works.

Since the connection over WiFI works with the OpenVPN installation on my Synology Diskstation I would think that the problem is not on my WiFi. Do you have any suggestion, what might be causing this issue and how to resolve it? Unfortunately Google didn't help me (this issue is seen a lot, but I never saw a post about it only happen when on local Wifi but not on other network).

EDIT: Just to add that the Synology DS works on UDP/1194. Now, when I switch on the OpenVPN installation from your script the port to TCP it works from mobile AND local network. So it seems a UDP related issue with your installation.

**Comment by angristan** [comment]
Sorry for the very late reply. It's weird indeed, but we made a lot of changes to the script so if someone still encouters this issue they may open a new issue.
