### ISSUE TITLE
Active Connection log

### ISSUE THREAD

**Issue by Hagrid78** [angristan/openvpn-install#520]
Hello,

i was wondering is there a command that shows the active connections ?

**Comment by angristan** [comment]
Does this help you? https://serverfault.com/a/571602/405096

**Comment by x0r2d2** [comment]
@jjackson524 http://openvpn-monitor.openbytes.ie/#apache

@angristan it will be a great addition to the script.

**Comment by randshell** [comment]
> Does this help you? https://serverfault.com/a/571602/405096

@angristan We use a different path and filename. The command should be `cat /var/log/openvpn/status.log`
