### ISSUE TITLE
Option for Gigabit Networks mode?

### ISSUE THREAD

**Issue by ruicruzpt** [angristan/openvpn-install#525]
Hello,

This might not be an "issue" but I did not found any other place to ask for it. Might just be a feature request. 

Can Gigabit Network mode as seen in https://community.openvpn.net/openvpn/wiki/Gigabit_Networks_Linux be enabled as an option while installing the OpenVPN with your script?

Thank you for your attention.

R.

**Comment by TinCanTech** [comment]
There is no such option as `Gigabit Network mode`

The link you reference documents a simple **static key** VPN.

There are also some tweaks which **may** help but the doc is quite old and has not been edited in over a year.
