### ISSUE TITLE
Slow speed on Debian 10 and Ubuntu 18.04

### ISSUE THREAD

**Issue by ofit** [angristan/openvpn-install#528]
Hello. I have problem with Debian 10 and Ubuntu 18.04. After installation on clean debian 10 or Ubuntu 18.04 network speed over openvpn is slow, looks like it cutting to  max 50Mbis/s, but if install it on Debian 9 or ubuntu 16.04 speed is ok more than 100Mbit/s. I used different port and different vps(KVM) or dedi but speed is not ok on debian 10. Even if install on debian 9 and upgrade to debian 10 bug exist.

Test network speed with iperf3 over VPN
`iperf3 -c 10.8.0.1 -t40 -R -p5331`

Bug can be seen on
netcup VPS 200 G8 (on debian 9 100Mbits/s, on debian 10 30-50Mbit/s)
online.net Start-2-S-SATA (Paris and Amsterdam) (on debian 9 100Mbits/s, on debian 10 30-50Mbit/s)
online.net Start-2-S-SSD (test only Amsterdam) (on debian 9 100Mbits/s, on debian 10 30-50Mbit/s)
Virmach (USA, NY / DE) (on debian 9 100Mbits/s, on debian 10 30-50Mbit/s)

Please, take a look at it. I think not only this providers have that bug.

**Comment by randshell** [comment]
See https://github.com/angristan/openvpn-install/issues/31#issuecomment-293959606
