### ISSUE TITLE
 OPENVPN and http/https

### ISSUE THREAD

**Issue by ultraandreyy** [angristan/openvpn-install#533]
Hello.
Our provider seems to be analyzing domain names through an http \ https request for 443 and 80 ports.

Is it possible to somehow configure the OpenVPN server so that with an http / https request on port 443 and 80 it will issue a website or redirect to some popular website.

Please tell me what to read on this topic, what to study in order to implement this.

Or is there an option for someone to perform this work remotely.

Thanks.

**Comment by randshell** [comment]
If you want to use port 443 for both a vpn and a webserver, ~~take a look at https://github.com/yrutschle/sslh~~ use openvpn's port-share.
Let me know if this works with your provider.

**Comment by angristan** [comment]
You mean your provider is inspecting packets to make sure requests on TCP:80/443 are HTTP(S) requests?

**Comment by ultraandreyy** [comment]
I don’t know this for sure, trying to try various options.
At the moment, I am deploying OpenVPN on a server without additional software.

Can you tell me how to disguise OpenVPN for HTTP/s traffic?

**Comment by ultraandreyy** [comment]
I thought so.
Direct all traffic to port 443/80 (I don’t know how yet), then distinguish traffic from http/s and openvpn.

Openvpn traffic should be directed to open, and http/s traffic should be directed to any page of the site (for this I think to hang any site on the server for the view).

Is it possible to do this? And Will it help disguise the OpenVPN server as regular http/s?

**Comment by randshell** [comment]
They are two different things. It depends on how your provider works.

1)From what I understand only port 80/443 is allowed and it's checked to see if a valid webserver responds. In this case you want both a webserver and openvpn running on 443 and you do this with openvpn's `port-share` and nginx or apache.

2)If they are looking at the protocol and not if the website loads in the browser, then you can use stunnel to disguise your openvpn traffic as https.

You can combine both if necessary, but try 2) first because it's the most common.

**Comment by ultraandreyy** [comment]
> They are two different things. It depends on how your provider works.
> 
> 1)From what I understand only port 80/443 is allowed and it's checked to see if a valid webserver responds. In this case you want both a webserver and openvpn running on 443 and you do this with openvpn's `port-share` and nginx or apache.
> 
> 2)If they are looking at the protocol and not if the website loads in the browser, then you can use stunnel to disguise your openvpn traffic as https.
> 
> You can combine both if necessary, but try 2) first because it's the most common.


Thanks. Is it possible to configure stunnel together with OpenVPN from angristan?

Or do you need to install a clean OpenVPN on the server?

**Comment by Prajwal-Koirala** [comment]
+1

**Comment by x0r2d2** [comment]
@ultraandreyy Best option for you is v2ray over websocket with LetsEncrypt certificate and fake site.
Shadowsocksr also can be used with obfs parameters.

**Comment by randshell** [comment]
> Thanks. Is it possible to configure stunnel together with OpenVPN from angristan?

Yes, it's possible. Follow any stunnel server guide.

There is a issue open to support this too #464.
