### ISSUE TITLE
How can disable TLS authentication?

### ISSUE THREAD

**Issue by brightways021** [angristan/openvpn-install#536]
Hello,
As my Client OS mikrotik does not support  TLS authentication. I want to disable this in Debian 10.
How can disable this features?
Please teach how to configure Open VPN for mikrotik?
Thanks in advance.

**Comment by randshell** [comment]
Hello,
I don't think it doesn't support tls authentication. It's more possible it has an older and insecure version.

Posting the connection logs help identify the exact issue, without them I can recommend you issue #162.

**Comment by brightways021** [comment]
Unfortunately, I read, but #162. didn't solve my problem.In mikrotiks, only the Error gives no connection.

**Comment by angristan** [comment]
Please tell us what specific error you get

**Comment by brightways021** [comment]
Hi. I was able to solve the problem for microtics. The appropriate settings for mikrotik are as follows:
for config for server:
port 443
proto tcp
dev tun
user nobody
group nogroup
persist-key
persist-tun
keepalive 10 120
topology subnet
server 10.8.0.0 255.255.255.0
ifconfig-pool-persist ipp.txt
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.4.4"
push "redirect-gateway def1 bypass-dhcp"
dh none
ecdh-curve prime256v1
#tls-crypt tls-crypt.key 0
crl-verify crl.pem
cert server_xxxxxxxxx.crt
key server_xxxxxxxxxx.key
#auth SHA256
cipher AES-128-CBC
ncp-ciphers AES-128-CBC
tls-server
tls-version-min 1.2
tls-cipher TLS-ECDHE-RSA-WITH-AES-128-GCM-SHA256
status /var/log/openvpn/status.log
verb 3

-------------
config for client:
client
proto tcp-client
remote xxxxxxxxx 443
dev tun
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
verify-x509-name server_xxxxxxxxxxx name
#auth SHA256
auth-nocache
cipher AES-128-CBC
tls-client
tls-version-min 1.2
tls-cipher TLS-ECDHE-RSA-WITH-AES-128-GCM-SHA256
setenv opt block-outside-dns # Prevent Windows 10 DNS leak
verb 3

**Comment by dolbykoray** [comment]
Hello, when I use OpenVPN my speed drops to 20Mbit. There is a public to local speed of nearly 300Mbit between the server and the client, but when OpenVPN is activated it slows down tremendously.
