### ISSUE TITLE
 I can connect to OpenVPN, but I cannot access the Internet unless I add these codes

### ISSUE THREAD

**Issue by slicol** [angristan/openvpn-install#537]
sysctl -w net.ipv4.ip_forward=1
sysctl -w net.ipv4.conf.tun0.forwarding=1
sysctl -w net.ipv4.conf.eth0.forwarding=1
sysctl -w net.ipv4.conf.lo.forwarding=1
sysctl -w net.ipv4.conf.default.forwarding=1
sysctl -w net.ipv4.conf.all.forwarding=1

**Comment by randshell** [comment]
It is already managed by the script and should work on the supported platforms. 
https://github.com/angristan/openvpn-install/blob/006167b3c7aef6a0c9a265cbd6bb17120c51c012/openvpn-install.sh#L838-L843
