### ISSUE TITLE
Change of parameters

### ISSUE THREAD

**Issue by ultraandreyy** [angristan/openvpn-install#539]
Hello.
After creating the server, the profile contains the following lines:
auth SHA256
cipher AES-128-GCM

Please tell me how to change these settings on auth SHA384 and cipher AES-256-GCM?

thanks

**Comment by frank3427** [comment]
Looking at the install script, it has all the options your looking for. It
seems you just accepted the defaults

**Comment by frank3427** [comment]
the changes you are looking for are in the customize section of the install script
```
		# The "auth" options behaves differently with AEAD ciphers
		if [[ "$CIPHER" =~ CBC$ ]]; then
			echo "The digest algorithm authenticates data channel packets and tls-auth packets from the control channel."
		elif [[ "$CIPHER" =~ GCM$ ]]; then
			echo "The digest algorithm authenticates tls-auth packets from the control channel."
		fi
		echo "Which digest algorithm do you want to use for HMAC?"
		echo "   1) SHA-256 (recommended)"
		echo "   2) SHA-384"
		echo "   3) SHA-512"
		until [[ $HMAC_ALG_CHOICE =~ ^[1-3]$ ]]; do
			read -rp "Digest algorithm [1-3]: " -e -i 1 HMAC_ALG_CHOICE
		done
		case $HMAC_ALG_CHOICE in
			1)
				HMAC_ALG="SHA256"
			;;
			2)
				HMAC_ALG="SHA384"
			;;
			3)
				HMAC_ALG="SHA512"
			;;
		esac
		echo ""
```

**Comment by angristan** [comment]
Yes, this is included in the script. During the install process it asks `Do you want to customize encryption settings?`

You could also edit these in your server.conf and client files yourself.

**Comment by ultraandreyy** [comment]
Thank you all very much. You helped me a lot. I managed to configure the settings as I needed it.

I did everything according to the script, before that I was not attentive and did not see this scenario.

**Comment by angristan** [comment]
Great!
