### ISSUE TITLE
No internet connection

### ISSUE THREAD

**Issue by kezern** [angristan/openvpn-install#54]
I have no internet connection when connected to the openvpn server.
What I'm doing wrong?

**Comment by DrXala** [comment]
What's OS of your openvpn server? By default, I imagine it's Debian.

Check if IPv4 forward is enable.
```
# grep net.ipv4.ip_forward /etc/sysctl.conf
net.ipv4.ip_forward=1
# cat /proc/sys/net/ipv4/ip_forward
1
# sysctl -a | grep "net.ipv4.ip_forward "
net.ipv4.ip_forward = 1
```
If it's ok, check your iptables rules.
```
iptables -t nat -L -vn --line
iptables -L FORWARD -vn --line
```
If it's ok, check the route table in your client.

**Comment by kezern** [comment]
I'm using ubuntu as server and windows 10 as client.
I have checked ipv4 forward rules and its ok.

Here is the result of iptables.
sudo iptables -t nat -L -vn --line
Chain PREROUTING (policy ACCEPT 0 packets, 0 bytes)
num   pkts bytes target     prot opt in     out     source               destination         

Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
num   pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
num   pkts bytes target     prot opt in     out     source               destination         

Chain POSTROUTING (policy ACCEPT 0 packets, 0 bytes)
num   pkts bytes target     prot opt in     out     source               destination


sudo iptables -L FORWARD -vn --line 
Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
num   pkts bytes target     prot opt in     out     source               destination

Must I change something in the client?

**Comment by DrXala** [comment]
You have no NAT rule in your nat table.
Try to add this rule where `$IP` is your public server IP:
```
iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -j SNAT --to $IP
```
You have not check if ipv4 forward is enable, cf. my last post.

**Comment by adworacz** [comment]
Actually, I have run into this same issue. I think I found the root problem. 

I rebooted the server. 

After running the script, downloading and using the ovpn profile, having it work just fine in my Ubuntu 17.04 client OS, I rebooted the server, and everything broke. 

I can connect just fine, but looking at the script, I think all of my iptable rules that were setup by this script weren't persisted at all. 

Also: I use UFW to manage by server rules normally as well, in case that might be effecting things. 

In short, I can connect, but DNS completely fails on my client side, and the custom iptable rules set by the script appear to be gone. 

**Edit: Confirmed.**

Running the following lines as root totally fixed my problems (substitute $MY_IP_ADDRESS with your server's IP address).
```
iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -j SNAT --to $MY_IP_ADDRESS
iptables -I FORWARD -s 10.8.0.0/24 -j ACCEPT
iptables -I FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
```

So, the question becomes, why wasn't this saved? Keep in mind, I'm running an Ubuntu 17.04 server, and I don't believe there is an ```/etc/rc.local``` file, which could be why nothing got saved.

**Comment by adworacz** [comment]
Actually, this article might help in the UFW case:
https://www.digitalocean.com/community/tutorials/how-to-set-up-an-openvpn-server-on-ubuntu-16-04

**Comment by DrXala** [comment]
Hmm I think, rc.local was removed with cover of sysv by systemd on Ubuntu... 

You can add this service in your systemd.

1. Create service
```
sudo vi /etc/systemd/system/rc-local.service
```
```
[Unit]
Description=/etc/rc.local Compatibility
ConditionPathExists=/etc/rc.local

[Service]
Type=forking
ExecStart=/etc/rc.local start
TimeoutSec=0
StandardOutput=tty
RemainAfterExit=yes
SysVStartPriority=99

[Install]
WantedBy=multi-user.target
```
2. Create `/etc/rc.local`
```
sudo vi /etc/rc.local
```
```
#!/bin/sh -e
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# By default this script does nothing.

exit 0
```
```
sudo chmod +x /etc/rc.local
```
3. Enable the service
```
sudo systemctl enable rc-local
```
4. Start service and check status
```
sudo systemctl start rc-local.service
sudo systemctl status rc-local.service
```

> Note :
> On my Debian8 with systemd, this service is in `/lib/systemd/system/`.

**Comment by adworacz** [comment]
Might I suggest following the pattern of Algo, and using iptables-persistent, which simply requires adding necessary rules to the ```/etc/iptables/rules.v4``` (IPv4) or ```/etc/iptables/rules.v6``` (IPv6).

iptables-persistent is available on many OS's (Ubuntu, Arch, Debian, etc), and it can massively simplify persisting firewall rules for the systems we setup.

Reference:
https://github.com/trailofbits/algo/blob/07ddb5863b265ce15ebf74ce7638c2ef981a9181/roles/vpn/tasks/iptables.yml
https://github.com/trailofbits/algo/blob/07ddb5863b265ce15ebf74ce7638c2ef981a9181/roles/vpn/templates/rules.v4.j2

Another option is to use UFW's methods for persisting these rules:
https://wiki.archlinux.org/index.php/OpenVPN#ufw

**Comment by Kcchouette** [comment]
@kezern Can you confirm us that after adding:
```
	# Needed to use rc.local with some systemd distros
	if [[ "$OS" = 'debian' && ! -e $RCLOCAL ]]; then
		echo '#!/bin/sh -e
exit 0' > $RCLOCAL
	fi
	chmod +x $RCLOCAL
```
 [here](https://github.com/Angristan/OpenVPN-install/blob/823ff21fccb3823fcb0f0fc16faf3fdaeb859f2b/openvpn-install.sh#L484) on your script, it works?

Thank you very much.
(PS, this solution come from https://github.com/Nyr/openvpn-install/commit/a31aaf82f3664e5854c617752a5493011ede731f)

**Comment by angristan** [comment]
Should be fixed with https://github.com/Angristan/OpenVPN-install/commit/ac203dd5eef586fb4a1c5db2fb0ca602d91edd32

**Comment by amgadfahmi** [comment]
Am also not getting internet on windows 10 client + dd-wrt router 
The only client is working is Iphone which is weird 
Server config 
```
port 1194
proto udp
dev tun
user nobody
group nogroup
persist-key
persist-tun
keepalive 10 120
topology subnet
server 10.8.0.0 255.255.255.0
ifconfig-pool-persist ipp.txt
push "dhcp-option DNS 8.8.4.4"
push "dhcp-option DNS 8.8.8.8"
push "redirect-gateway def1 bypass-dhcp" 
crl-verify crl.pem
ca ca.crt
cert server.crt
key server.key
tls-auth tls-auth.key 0
dh dh.pem
auth SHA256
cipher AES-128-CBC
tls-server
tls-version-min 1.2
tls-cipher TLS-DHE-RSA-WITH-AES-128-GCM-SHA256
status openvpn.log
log-append openvpndebug.log
verb 6 
```
iptables -t nat -L -vn --line output (xx is my public ip)

```
Chain PREROUTING (policy ACCEPT 5979 packets, 794K bytes)
num   pkts bytes target     prot opt in     out     source               destination

Chain INPUT (policy ACCEPT 544 packets, 72116 bytes)
num   pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy ACCEPT 209 packets, 16698 bytes)
num   pkts bytes target     prot opt in     out     source               destination

Chain POSTROUTING (policy ACCEPT 209 packets, 16698 bytes)
num   pkts bytes target     prot opt in     out     source               destination
1      141  7838 SNAT       all  --  *      *       10.8.0.0/24          0.0.0.0/0            to:xx.xx.xx.xx
```
iptables -L FORWARD -vn --line output 

```
Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
num   pkts bytes target     prot opt in     out     source               destination
1     4473 2642K ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            state RELATED,ESTABLISHED
2      162  9610 ACCEPT     all  --  *      *       10.8.0.0/24          0.0.0.0/0
3        0     0 ACCEPT     all  --  eth0   *       0.0.0.0/0            10.8.0.0/24          ctstate RELATED,ESTABLISHED
4      192 12288 ACCEPT     all  --  *      eth0    10.8.0.0/24          0.0.0.0/0
```
i have enabled ip4 forwarding
windows client is latest version, getting correct ip dns but gateway is empty

**Comment by Kcchouette** [comment]
@amgadfahmi Is your client for windows this one: https://swupdate.openvpn.org/community/releases/openvpn-install-2.4.4-I601.exe
Or is it another one?

**Comment by amgadfahmi** [comment]
yes that's my client openvpn-install-2.4.4-I601.exe
 And dd-wrt also latest version was release 2 days back 
it worth mentioning that logs on server + both clients shows 0 warnings/errors
