### ISSUE TITLE
no closing quotation (") in config.ovpn

### ISSUE THREAD

**Issue by tinysun** [angristan/openvpn-install#540]
I have debian9 server and asus router openvpn client , want to use this.
but there is *no closing quotation (") in config.ovpn* error for asus router.
i saw the router's log and config.ovpn. the error line is *tls-crypt [[INLINE]] "*.
i donot know how i can do.
By the way ,these is one more issues by *tls-version-min 1.2*line, but when i delete it,the error is Disappeared.

**Comment by angristan** [comment]
Try to delete the whole `tls-crypt` block, your router is probably too old to support it.

**Comment by tinysun** [comment]
client
proto udp
remote xxx.xxx.xxx.xxx 1194
dev tun
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
verify-x509-name server_UMvvaI6NJIEGBdPi name
auth SHA256
auth-nocache
cipher AES-128-GCM
tls-client
;tls-version-min 1.2
tls-cipher TLS-ECDHE-ECDSA-WITH-AES-128-GCM-SHA256
setenv opt block-outside-dns # Prevent Windows 10 DNS leak
verb 3

my client script is not include the tls-crypt,which line I need to delete?

**Comment by angristan** [comment]
It is below that, under the certifcate.
