### ISSUE TITLE
Add another OpenVPN Port

### ISSUE THREAD

**Issue by johndave9296** [angristan/openvpn-install#542]
Suggestion if it's possible if we'll add an additional feature that not only one port is open into a VPS but another port to be opened. For example, if we set a port 1194 then we're hoping to add another port which is 80. Hopefully there's a feature to the script.

**Comment by angristan** [comment]
Sorry, I'm not sure to understand your request.

**Comment by johndave9296** [comment]
What I mean is for a possibility of establishing multiple OpenVPN Ports instead of only one.

**Comment by x0r2d2** [comment]
> What I mean is for a possibility of establishing multiple OpenVPN Ports instead of only one.

@johndave9296
For now you can add it manualy. Copy existing server.conf, change port and subnet to desired one e.g. 64000 and 10.9.0.1, rename it to server2.conf, add iptables rules and then start and enable it:

```
systemctl start openvpn@server2.service
systemctl enable openvpn@server2.service
```

I also wanted to ask @angristan regarding this feature request.

Dear @angristan is there any possibility to add this feature to script? 
Options: keep same config or with different options (cipher, HMAC, tls-cipher), ability to choose port or use random one and ability to choose subnet.

**Comment by johndave9296** [comment]
I think this would be possible. How about doing a custom line script such as 

port 443
port 8080
port 80

**Comment by johndave9296** [comment]
@hybtoy 

Update: It's not working even though I added these two commands

`systemctl start openvpn@server2.service
systemctl enable openvpn@server2.service`

It turns out that the tun device driver was somehow disabled in my server.

**Comment by johndave9296** [comment]
Hello I would like to ask if my iptables are correctly executed.

> #!/bin/sh
> iptables -t nat -I POSTROUTING 1 -s 9.2.96.0/24 -o eth0 -j MASQUERADE
> iptables -t nat -I POSTROUTING 1 -s 9.2.97.0/24 -o eth0 -j MASQUERADE
> iptables -I INPUT 1 -i tun0 -j ACCEPT
> iptables -I INPUT 1 -i tun1 -j ACCEPT
> iptables -I FORWARD 1 -i eth0 -o tun0 -j ACCEPT
> iptables -I FORWARD 1 -i eth0 -o tun1 -j ACCEPT
> iptables -I FORWARD 1 -i tun0 -o eth0 -j ACCEPT
> iptables -I FORWARD 1 -i tun1 -o eth0 -j ACCEPT
> iptables -I INPUT 1 -i eth0 -p tcp --dport 1194 -j ACCEPT
> iptables -I INPUT 1 -i eth0 -p udp --dport 53 -j ACCEPT

**Comment by randshell** [comment]
The iptables should be fine. If you followed @hybtoy comment and it doesn't work I think the problem is with port 53 udp, some program might be using it. You can try changing it to confirm this.
