### ISSUE TITLE
[Patch attached] Make the script idempotent for automated provisioning

### ISSUE THREAD

**Issue by jmeubank** [angristan/openvpn-install#545]
Hi! This script has been super-useful to me with a bit of patching to make it more idempotent in headless mode. Maybe others will find it useful as well?

This allows it to plug straight into state-enforcers like Terraform/Ansible/Salt/Puppet/Chef, because it simply works to enforce the desired state of OpenVPN being up and running and a client configuration file being generated.

I didn't change a whole lot actually! Just added a couple checks to make sure random things got saved and OpenVPN and Easy-RSA only got pull down from upstream on the first run.

Gist: [idempotent.patch](https://gist.github.com/jmeubank/9f6a0ffa5d559c5c45b8e00c3d705ed0)
`curl https://gist.githubusercontent.com/jmeubank/9f6a0ffa5d559c5c45b8e00c3d705ed0/raw/8221d8fced9a8e4d0727edebfdef4e1a7e994987/idempotent.patch | git am`
(Review)
`git push origin/master`

**Comment by randshell** [comment]
Can you open a pull request for it?

**Comment by jmeubank** [comment]
Sure, done. #592

**Comment by angristan** [comment]
Thanks 🙂
