### ISSUE TITLE
Possible run OpenVPN with two protocols at the same time

### ISSUE THREAD

**Issue by johndave9296** [angristan/openvpn-install#546]
I'm seeing many VPN Services that runs both UDP and TCP at the same time. Is it possible to be implemented here in this script?

**Comment by DGxInfinitY** [comment]
I second this!

**Comment by x0r2d2** [comment]
@johndave9296 
Do not duplicate your questions, please. I have already provided you with solution. 
https://github.com/angristan/openvpn-install/issues/542#issuecomment-588070210

**Comment by johndave9296** [comment]
Will try it. Gonna close this one out.
