### ISSUE TITLE
installing openvpn server on another port

### ISSUE THREAD

**Issue by A2116** [angristan/openvpn-install#553]
when I installed OpenVPN server with default port 1194 it works properly
but when I want to install it on another port the connection does not connect
I think it is something about open ports or... but I have not any knowledge to solve it
what should I do?

also if I want users to have user and password, what should I do?

I am using centos 7 and latest version of the script, also I updated all modules in Linux

**Comment by randshell** [comment]
Try this and replace with your protocol and port.
```
# yum install policycoreutils-python

# semanage port -a -t openvpn_port_t -p udp 1194
```
I am going to open a PR to fix this because `semanage` isn't preinstalled in CentOS and the script needs it to change selinux policy.


> also if I want users to have user and password, what should I do?

For security reasons this script doesn't support password authentication. You login automatically with the key inside the ovpn file.

**Comment by A2116** [comment]
thank you for your answers
if I use these commands after installation, no other change needed to done
on firewall or iptables? only modifying clients .ovpn files?
for username and password I mean using them alongside with cert and key,
because, for example, MikroTik does not support OpenVPN without password

**Comment by randshell** [comment]
> if I use these commands after installation, no other change needed to done on firewall or iptables?

No. The script does everything but on CentOS it runs `semanage` without installing it.

Thanks for reporting.

>only modifying clients .ovpn files?

MikroTik isn't supported even if you login with username and password, it needs other changes #410 .

**Comment by A2116** [comment]
i ran it and it prompt
ERROR: could not find datum for type vpn
ValueError: Type vpn is invalid, must be a port type

**Comment by randshell** [comment]
It's `-t openvpn_port_t` not `-t vpn`. Sorry for this.

**Comment by A2116** [comment]
thanks

**Comment by angristan** [comment]
FYI you can choose to protect your client key with a password when you add a client.

**Comment by randshell** [comment]
@angristan for the record is a bug report not a support issue.

**Comment by angristan** [comment]
Fixed by #554, right?

**Comment by randshell** [comment]
@angristan yes

**Comment by mavanlong868-crypto** [comment]
// Free Fire aim assist — Android NDK native library
// Target: com.dts.freefireth / com.dts.freefiremax (ARM64)
// Build: ndk-build or CMake, minSdk 24, targetSdk 33
// Inject: via Magisk module / LSPosed / patched libil2cpp.so

#include <jni.h>
#include <android/log.h>
#include <cstring>
#include <cmath>
#include <unistd.h>
#include <fcntl.h>
#include <sys/mman.h>

#define LOG_TAG "FFAIM"
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO,  LOG_TAG, __VA_ARGS__)
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, LOG_TAG, __VA_ARGS__)

// ==== CONFIG ====
static float  FOV_RADIUS   = 200.0f;
static float  SMOOTH        = 6.0f;
static float  MAX_DIST      = 400.0f;
static float  HEAD_OFFSET_Z = 0.85f;
static bool   AIM_ENABLED   = true;
static bool   ESP_ENABLED   = true;

// ==== SIGNATURES (replace per build) ====
static uintptr_t g_base          = 0;
static uintptr_t g_localPlayer   = 0;
static uintptr_t g_entityList    = 0;
static uintptr_t g_entityCount   = 0;
static uintptr_t g_viewMatrix    = 0;

// ============================================================
// 1. MODULE BASE RESOLUTION
// ============================================================
static uintptr_t getModuleBase(const char* name) {
    FILE* fp = fopen("/proc/self/maps", "r");
    if (!fp) return 0;
    char line[512];
    uintptr_t base = 0;
    while (fgets(line, sizeof(line), fp)) {
        if (strstr(line, name)) {
            base = strtoul(line, nullptr, 16);
            break;
        }
    }
    fclose(fp);
    return base;
}

// ============================================================
// 2. PATTERN SCAN
// ============================================================
static uintptr_t patternScan(uintptr_t start, size_t size,
                             const uint8_t* pat, const char* mask) {
    size_t plen = strlen(mask);
    uint8_t* p = (uint8_t*)start;
    for (size_t i = 0; i < size - plen; ++i) {
        bool hit = true;
        for (size_t j = 0; j < plen; ++j) {
            if (mask[j] == 'x' && p[i+j] != pat[j]) { hit = false; break; }
        }
        if (hit) return start + i;
    }
    return 0;
}

// ============================================================
// 3. INIT OFFSETS
// ============================================================
extern "C" void initOffsets() {
    g_base = getModuleBase("libil2cpp.so");
    if (!g_base) g_base = getModuleBase("libunity.so");
    if (!g_base) { LOGE("module not found"); return; }

    const uint8_t sigLocal[]  = {0x48,0x8B,0x05,0,0,0,0,0x48,0x85,0xC0};
    const char    mskLocal[]  = "xxx????xxx";
    g_localPlayer = patternScan(g_base, 0x800000, sigLocal, mskLocal);

    const uint8_t sigList[]   = {0x48,0x8B,0x0D,0,0,0,0,0x48,0x8B,0x04,0xC1};
    const char    mskList[]   = "xxx????xxxx";
    g_entityList  = patternScan(g_base, 0x800000, sigList, mskList);

    const uint8_t sigMtx[]    = {0xF3,0x0F,0x10,0x05,0,0,0,0,0xF3,0x0F,0x11};
    const char    mskMtx[]    = "xxxx????xxx";
    g_viewMatrix  = patternScan(g_base, 0x800000, sigMtx, mskMtx);

    LOGI("base=%p lp=%p list=%p mtx=%p", (void*)g_base,
         (void*)g_localPlayer, (void*)g_entityList, (void*)g_viewMatrix);
}

// ============================================================
// 4. SAFE MEMORY READ
// ============================================================
template<typename T>
static T safeRead(uintptr_t addr) {
    if (!addr) return T{};
    return *(T*)addr;
}

// ============================================================
// 5. ENTITY HELPERS
// ============================================================
struct Vec3 { float x, y, z; };

static uintptr_t localPlayer() {
    return safeRead<uintptr_t>(g_localPlayer);
}

static uintptr_t entityAt(int i) {
    uintptr_t list = safeRead<uintptr_t>(g_entityList);
    if (!list) return 0;
    return safeRead<uintptr_t>(list + i * 0x8);
}

static Vec3 getPos(uintptr_t e) {
    return { safeRead<float>(e+0x134),
             safeRead<float>(e+0x138),
             safeRead<float>(e+0x13C) };
}

// ============================================================
// 6. WORLD TO SCREEN
// ============================================================
static bool w2s(Vec3 p, float* m, int w, int h, float& sx, float& sy) {
    float cx = p.x*m[0]+p.y*m[4]+p.z*m[8] +m[12];
    float cy = p.x*m[1]+p.y*m[5]+p.z*m[9] +m[13];
    float cw = p.x*m[3]+p.y*m[7]+p.z*m[11]+m[15];
    if (cw < 0.01f) return false;
    sx = (w*0.5f)*(1.0f+cx/cw);
    sy = (h*0.5f)*(1.0f-cy/cw);
    return true;
}

// ============================================================
// 7. AIM STEP (via input injection)
// ============================================================
extern "C" void injectTouch(float dx, float dy);
static void aimStep(float sx, float sy, int w, int h) {
    float dx = (sx - w*0.5f) / SMOOTH;
    float dy = (sy - h*0.5f) / SMOOTH;
    injectTouch(dx, dy);
}

// ============================================================
// 8. MAIN LOOP
// ============================================================
extern "C" void onFrame(int w, int h) {
    if (!AIM_ENABLED) return;
    uintptr_t lp = localPlayer();
    if (!lp) return;
    Vec3 lpPos = getPos(lp);
    int lpTeam = safeRead<int>(lp + 0x210);

    float m[16];
    memcpy(m, (void*)g_viewMatrix, sizeof(m));

    int count = safeRead<int>(g_entityCount);
    float bestFov = FOV_RADIUS;
    float bsx = 0, bsy = 0; bool found = false;

    for (int i = 0; i < count; ++i) {
        uintptr_t e = entityAt(i);
        if (!e || e == lp) continue;
        int hp   = safeRead<int>(e + 0x214);
        int team = safeRead<int>(e + 0x210);
        if (hp <= 0 || team == lpTeam) continue;

        Vec3 p = getPos(e);
        float dx = p.x-lpPos.x, dy = p.y-lpPos.y, dz = p.z-lpPos.z;
        float dist = sqrtf(dx*dx+dy*dy+dz*dz);
        if (dist > MAX_DIST) continue;

        Vec3 aim = { p.x, p.y, p.z + HEAD_OFFSET_Z };
        float sx, sy;
        if (!w2s(aim, m, w, h, sx, sy)) continue;
        float fdx = sx - w*0.5f, fdy = sy - h*0.5f;
        float fov = sqrtf(fdx*fdx+fdy*fdy);
        if (fov < bestFov) { bestFov = fov; bsx = sx; bsy = sy; found = true; }
    }
    if (found) aimStep(bsx, bsy, w, h);
}

// ============================================================
// JNI ENTRY
// ============================================================
extern "C" JNIEXPORT void JNICALL
Java_com_ffaim_Main_init(JNIEnv*, jobject) { initOffsets(); }

extern "C" JNIEXPORT void JNICALL
Java_com_ffaim_Main_tick(JNIEnv*, jobject, jint w, jint h) { onFrame(w, h); }
