### ISSUE TITLE
Remove revoked clients from ipp.txt

### ISSUE THREAD

**Issue by estimadarocha** [angristan/openvpn-install#56]
Revoked clients still appear on ipp.txt is it normal?

Is there anyway to reorder ipaddressing on it?

**Comment by x0r2d2** [comment]
Did you delete them from the list after removal?

**Comment by cezar97** [comment]
Yes, revoked clients still appear on ipp.txt, each one having it's static ip.

Seems that the file is just for reference: editing a client's ip there doesn't change it's actual assigned static ip to that one.

**Comment by angristan** [comment]
Fixed in https://github.com/angristan/openvpn-install/commit/e4a9851b4fe3ceca6fdc3a33f2322f84d5c1ef3c
