### ISSUE TITLE
How to access Admin UI for OpenVPN activation/license

### ISSUE THREAD

**Issue by mozo78** [angristan/openvpn-install#560]
Hello,
Is there any way to activate already installed OpenVPN? The installation was made via your script but I can't find a way to access the Admin UI as the help page at OpenVPN's site says it's needed for the activation process. There's no /usr/local/openvpn_as/bin/ovpn-init and I can't configure the UI, hence I can't activate OpenVPN.
I already tried https://myIP:943/admin to no avail.
I use Arch Linux and openvpn is v.2.4.8-4
Thank you.

**Comment by angristan** [comment]
Hello, you're confusing OpenVPN access (the open source software) and OpenVPN Access (the commercial product by OpenVPN with a web UI)

**Comment by mozo78** [comment]
But there is no OpenVPN Access (the commercial product) for Arch I think or I'm wrong? Is there a way to install it or any way to activate the existing installation or I'll have to reinstall with another distribution?

And can I ask you - is there a limititation for simultaneous connections for installations with your script? If there isn't a limitation, that would be great!

Thank you for your help :)

**Comment by angristan** [comment]
Either way, you can't use both this script and OpenVPN Access, sorry.

There is no limitation with this script :)

**Comment by mozo78** [comment]
Oh, that's perfect! Limitation is what bothers me. Thank you very much!!!
