### ISSUE TITLE
OpenVPN on Centos 8 does not access to internet

### ISSUE THREAD

**Issue by kaori14112** [angristan/openvpn-install#561]
I installed openvpn as instruction on centos 8 (newest), but seem like something goes wrong, first, firewalld does not automatically open 1194 udp (i have to manually open with firewall-cmd command), then client computer cannot access to internet (on server still ping 8.8.8.8 normally), still able to ping TUN gateway (10.8.0.1).
I tried to remove openvpn *(with script of course) then reinstall with Nyr scripts then seem like everything work normally (his script does not provide some feature like you are). 
After a while reading his script and your i realize that your script dont do firewalld setting, here is few command i typed so problem solved:
$firewall-cmd --add-port=1194/udp

$firewall-cmd --zone=trusted --add-source=10.8.0.0/24

$firewall-cmd --permanent --add-port=1194/udp

$firewall-cmd --permanent --zone=trusted --add-source=10.8.0.0/24

$ip=ip=$(ip addr | grep inet | grep -v inet6 | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | cut -d '/' -f 1 | grep -oE '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')

$firewall-cmd --direct --add-rule ipv4 nat POSTROUTING 0 -s 10.8.0.0/24 ! -d 10.8.0.0/24 -j SNAT --to $ip

$firewall-cmd --permanent --direct --add-rule ipv4 nat POSTROUTING 0 -s 10.8.0.0/24 ! -d 10.8.0.0/24 -j SNAT --to $ip

$firewall-cmd --reload

Can you update firewalld config on the future? Thank you.

**Comment by randshell** [comment]
There is #417 but unfortunately it is open for a while now.

**Comment by angristan** [comment]
Closing as duplicate of https://github.com/angristan/openvpn-install/issues/356
