### ISSUE TITLE
OpenVPN handshake failed

### ISSUE THREAD

**Issue by JorisH1992** [angristan/openvpn-install#562]
Hello

I tried to install openVPN with the script and it seems to work fine, however a little bit slow. 
Now I wanted to try it on a different network and I hoped this would maybe improve the speed instead ofusing the same network but I can't connect as you can see in the log. 

Sat Mar 14 17:52:21 2020 library versions: OpenSSL 1.1.0l  10 Sep 2019, LZO 2.10
Enter Management Password:
Sat Mar 14 17:52:21 2020 MANAGEMENT: TCP Socket listening on [AF_INET]127.0.0.1:25340
Sat Mar 14 17:52:21 2020 Need hold release from management interface, waiting...
Sat Mar 14 17:52:21 2020 MANAGEMENT: Client connected from [AF_INET]127.0.0.1:25340
Sat Mar 14 17:52:21 2020 MANAGEMENT: CMD 'state on'
Sat Mar 14 17:52:21 2020 MANAGEMENT: CMD 'log all on'
Sat Mar 14 17:52:21 2020 MANAGEMENT: CMD 'echo all on'
Sat Mar 14 17:52:21 2020 MANAGEMENT: CMD 'bytecount 5'
Sat Mar 14 17:52:21 2020 MANAGEMENT: CMD 'hold off'
Sat Mar 14 17:52:21 2020 MANAGEMENT: CMD 'hold release'
Sat Mar 14 17:52:21 2020 MANAGEMENT: CMD 'password [...]'
Sat Mar 14 17:52:21 2020 Outgoing Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Sat Mar 14 17:52:21 2020 Outgoing Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Sat Mar 14 17:52:21 2020 Incoming Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Sat Mar 14 17:52:21 2020 Incoming Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Sat Mar 14 17:52:21 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]192.168.0.250:1194
Sat Mar 14 17:52:21 2020 Socket Buffers: R=[65536->65536] S=[65536->65536]
Sat Mar 14 17:52:21 2020 UDP link local: (not bound)
Sat Mar 14 17:52:21 2020 UDP link remote: [AF_INET]192.168.0.250:1194
Sat Mar 14 17:52:21 2020 MANAGEMENT: >STATE:1584204741,WAIT,,,,,,
Sat Mar 14 17:53:22 2020 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Sat Mar 14 17:53:22 2020 TLS Error: TLS handshake failed
Sat Mar 14 17:53:22 2020 SIGUSR1[soft,tls-error] received, process restarting
Sat Mar 14 17:53:22 2020 MANAGEMENT: >STATE:1584204802,RECONNECTING,tls-error,,,,,
Sat Mar 14 17:53:22 2020 Restart pause, 5 second(s)
Sat Mar 14 17:53:27 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]192.168.0.250:1194
Sat Mar 14 17:53:27 2020 Socket Buffers: R=[65536->65536] S=[65536->65536]
Sat Mar 14 17:53:27 2020 UDP link local: (not bound)
Sat Mar 14 17:53:27 2020 UDP link remote: [AF_INET]192.168.0.250:1194
Sat Mar 14 17:53:27 2020 MANAGEMENT: >STATE:1584204807,WAIT,,,,,,
Sat Mar 14 17:54:27 2020 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Sat Mar 14 17:54:27 2020 TLS Error: TLS handshake failed
Sat Mar 14 17:54:27 2020 SIGUSR1[soft,tls-error] received, process restarting
Sat Mar 14 17:54:27 2020 MANAGEMENT: >STATE:1584204867,RECONNECTING,tls-error,,,,,
Sat Mar 14 17:54:27 2020 Restart pause, 5 second(s)
Sat Mar 14 17:54:32 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]192.168.0.250:1194
Sat Mar 14 17:54:32 2020 Socket Buffers: R=[65536->65536] S=[65536->65536]
Sat Mar 14 17:54:32 2020 UDP link local: (not bound)
Sat Mar 14 17:54:32 2020 UDP link remote: [AF_INET]192.168.0.250:1194
Sat Mar 14 17:54:32 2020 MANAGEMENT: >STATE:1584204872,WAIT,,,,,,

I found issue #383 and the solution presented was to port forward to the raspberry pi, however I have already done that on my home network where the pi is on, but is it also necessary to do this for all the other networks I connect with, because I guess I won't be able to access all these routersettings? My idea was to connect to the network where I am at the moment and that it would then be forwarded so that all my traffic goes through my home network or is that not possible?

**Comment by angristan** [comment]
If you're trying to connect from a different network, then you have to use your router's public IP address and configure port-forward.

**Comment by JorisH1992** [comment]
> If you're trying to connect from a different network, then you have to use your router's public IP address and configure port-forward.

I'm gonna try that, thank you
