### ISSUE TITLE
Port forwarding

### ISSUE THREAD

**Issue by ghost** [angristan/openvpn-install#564]
Hello,

I install OpenVPN with script with no problem.
I connect a client to the OpenVPN server installed on a VPS Server.

I try to foward port 8080 from public IP VPS to a local 8080 IP with iptables :

iptables -t nat -A PREROUTING -d 51.XX.XX.X -p tcp --dport 8080 -j DNAT --to-dest 10.8.0.2:8080
iptables -t filter -A INPUT -p tcp -d 10.8.0.2 --dport 8080 -j ACCEPT

Nothing works !

Could you help me ?

Thanks

**Comment by randshell** [comment]
See https://github.com/angristan/openvpn-install/issues/224#issuecomment-392328780

@angristan perhaps we can add this to the FAQ?

**Comment by ghost** [comment]
Hello 

Adding : 

iptables -A PREROUTING -t nat -i ens3 -p tcp --dport 8080 -j DNAT --to 10.8.0.2:8080
iptables -A FORWARD -p tcp -d 51.xx.xxx.xx --dport 8080 -j ACCEPT

Redirection failed, i change net.ipv4.ip_forward = 0 to 1

**Comment by randshell** [comment]
Did you change `-i ens3` to your Internet interface? It can be `eth0` for example. See the correct one with `ifconfig`.

**Comment by ghost** [comment]
My interface is ens3, i share you my ifconfig :

ens3: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet vpsip  netmask 255.255.255.255  broadcast vpsip  
        inet6 fe80::f816:3eff:fef4:ee30  prefixlen 64  scopeid 0x20<link>
        ether fa:16:3e:f4:ee:30  txqueuelen 1000  (Ethernet)
        RX packets 110348  bytes 18531120 (17.6 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 110922  bytes 23054654 (21.9 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1  (Local Loopback)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

tun0: flags=4305<UP,POINTOPOINT,RUNNING,NOARP,MULTICAST>  mtu 1500
        inet 10.8.0.1  netmask 255.255.255.0  destination 10.8.0.1
        inet6 fe80::c99d:b94:8ef7:6c94  prefixlen 64  scopeid 0x20<link>
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 100  (UNSPEC)
        RX packets 4130  bytes 835748 (816.1 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 5577  bytes 4711132 (4.4 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

and my iptable : 

:PREROUTING ACCEPT [1:60]
:INPUT ACCEPT [1:60]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
-A PREROUTING -i ens3 -p tcp -m tcp --dport 8080 -j DNAT --to-destination 10.8.$
-A PREROUTING -i ens3 -p tcp -m tcp --dport 80 -j DNAT --to-destination 67.227.$
-A POSTROUTING -s 10.8.0.0/24 -o ens3 -j MASQUERADE
-A POSTROUTING -s 10.8.0.0/24 -o ens3 -j MASQUERADE
COMMIT
filter
:INPUT ACCEPT [16:2131]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [37:5305]
-A INPUT -i ens3 -p udp -m udp --dport 1194 -j ACCEPT
-A INPUT -i tun0 -j ACCEPT
-A INPUT -i ens3 -p udp -m udp --dport 1194 -j ACCEPT
-A INPUT -i tun0 -j ACCEPT
-A FORWARD -i tun0 -o ens3 -j ACCEPT
-A FORWARD -i ens3 -o tun0 -j ACCEPT
-A FORWARD -i tun0 -o ens3 -j ACCEPT
-A FORWARD -i ens3 -o tun0 -j ACCEPT
-A FORWARD -d vpsip/32 -p tcp -m tcp --dport 8080 -j ACCEPT
-A FORWARD -d vpsip/32 -p tcp -m tcp --dport 80 -j ACCEPT
COMMIT

I use a OVH VPS. 

When i use https://www.yougetsignal.com/tools/open-ports/ to check open port, website returns closed for 80 and 8080

Thanks

**Comment by ghost** [comment]
Hi,

Today i try these rules : 

iptables -t nat -I PREROUTING 1 -d PUBLIC_IP_VPS -p tcp --dport 8080 -j DNAT --to-dest 10.8.0.2:8080
iptables -t nat -I POSTROUTING 1 -d 10.8.0.2 -p tcp --dport 8080 -j SNAT --to-source 10.8.0.1
iptables -I FORWARD 1 -d 10.8.0.2 -p tcp --dport 8080 -j ACCEPT

OR 

iptables -t nat -I PREROUTING 1 -d PUBLIC_IP_VPS  -p tcp --dport 8080 -j DNAT --to-dest 192.168.1.100:8080
iptables -t nat -I POSTROUTING 1 -d 192.168.1.100 -p tcp --dport 8080 -j SNAT --to-source 10.8.0.1
iptables -I FORWARD 1 -d 192.168.1.100 -p tcp --dport 8080 -j ACCEPT

**Comment by randshell** [comment]
Maybe #498 helps?
