### ISSUE TITLE
[Request] Have an option to delete AND revoke users' keys/cetrts (index.txt).

### ISSUE THREAD

**Issue by AMDBartek** [angristan/openvpn-install#566]
When you revoke access to the VPN for a user (client) the key remains in some places like the index.txt file in the Easy-RSA PKI folder. It would be convenient for the script to have an option to delete the key listing in the index.txt file (Easy-RSA) while revoking users (clients).

**Comment by randshell** [comment]
Why do you want to delete all information related to revoked users? They should remain there to provide a log of the revocation for security reasons.

Even if you delete listings in index.txt, the CRL file still contains the list of revoked users so it doesn't makes much sense.

**Comment by AMDBartek** [comment]
I am going to close this issue because @randomshell provided a good point on why the revoked users should stay in the index.txt and CRL files. I looked over it again and it didn’t make much sense to remove revoked users from index.txt and CRL files.
