### ISSUE TITLE
Posibility to exclude certain IPs/ CIDR from VPN routing.

### ISSUE THREAD

**Issue by Vudubond** [angristan/openvpn-install#574]
Hello,

The possibility to exclude certain IPs, CIDRs from routing through VPN, using the install GUI.

**Comment by x0r2d2** [comment]
@Vudubond
https://github.com/angristan/openvpn-install/issues/575#issuecomment-603431835

**Comment by randshell** [comment]
@angristan does it need a FAQ entry?
