### ISSUE TITLE
Adding internal network

### ISSUE THREAD

**Issue by ruicruzpt** [angristan/openvpn-install#575]
Hello,

I'm using Ubuntu 18 LTS as server and I've added both public and private network in the Proxmox configuration. Also, I see the networks in the server.

However, the OpenVPN only allow me to surf public networks, not private network. Is there any config I need to add after using your script to allow me to add the 192.168.*.* range?

**Comment by x0r2d2** [comment]
> Hello,
> 
> I'm using Ubuntu 18 LTS as server and I've added both public and private network in the Proxmox configuration. Also, I see the networks in the server.
> 
> However, the OpenVPN only allow me to surf public networks, not private network. Is there any config I need to add after using your script to allow me to add the 192.168._._ range?

`push "route 10.0.0.0 255.255.0.0 net_gateway"`
`push "redirect-gateway def1"`
 
You have to add range or specific network (or ip) to your server config

https://forums.openvpn.net/viewtopic.php?t=7065

**Comment by randshell** [comment]
@angristan does it need a FAQ entry?

**Comment by angristan** [comment]
yep!
