### ISSUE TITLE
Feature Request: Script with New Cipher Options supported by OpenVPN 2.4.1

### ISSUE THREAD

**Issue by newsera** [angristan/openvpn-install#58]
Can we have a newer script containing New Cipher Options supported by OpenVPN 2.4.1 such as GCM?

**Comment by newsera** [comment]
Also another feature request: Ability to choose your own /24 subnet as an option than the default 10.8.0.0/24?

**Comment by angristan** [comment]
I'll be working on that in the next weeks : https://github.com/Angristan/OpenVPN-install/pull/33

For the subnet, that's not planned but feel free to add a PR
