### ISSUE TITLE
Complains if /usr/sbin isn't in root's PATH

### ISSUE THREAD

**Issue by martinwguy** [angristan/openvpn-install#593]
Hi! Nice script! :D

Just one minor problem: if /usr/sbin isn't in root's PATH, launching "openvpn" and "systemctl" fail ("Command not found"), but it seems to work the same.

Thanks!

    M

**Comment by randshell** [comment]
What distro are you using?
We had some similar issues and someone suggested a PATH problem too. https://github.com/angristan/openvpn-install/issues/523#issuecomment-596022859

**Comment by ananthu-sk** [comment]
i had the same problem, to fix use
`sudo cp /usr/sbin/openvpn /usr/local/bin`

**Comment by martinwguy** [comment]
On 30/03/2020, randomshell <notifications@github.com> wrote:
> What distro are you using?

Debian 10. It happens when you go "su" from a user account.
One solution: /root/.bashrc, but you might think of automating that in
the script

Blessings

   M

**Comment by HenryNe** [comment]
> 
> Debian 10. It happens when you go "su" from a user account. One solution: /root/.bashrc, but you might think of automating that in the script Blessings M

This is not a bug in this script.
You should use `su -` to get the envoronment from root. Or use `sudo -i`.

**Comment by randshell** [comment]
> you might think of automating that in the script

@ask1234560 @martinwguy In the linked PR I added the necessary `/usr/sbin` to the `$PATH`. Now the script will complete without errors but using `su` instead of `su -` can cause some other issues like @HenryNe said.

**Comment by HenryNe** [comment]
An other difference between `su` and `su -` is the current working directory. A `su -` goes into the directory `/root` and executes the `.profile` there, `su` does it not not.

**Comment by angristan** [comment]
Yes, this isn't a bug in the script.
