### ISSUE TITLE
Change Cloudflare from default DNS option

### ISSUE THREAD

**Issue by randshell** [angristan/openvpn-install#595]
Instead of promoting Cloudflare as default option can we use the system resolvers as the default installer option?

I think a better default alternative can be Adguard because claims to not log at all (Cloudflare keeps some logs) and it blocks some trackers too. https://adguard.com/en/adguard-dns/overview.html

@angristan We should remember this script should be secure and private by default and I'm not sure Cloudflare meets this requirement.

EDIT: in the wireguard-install repo you use Adguard as default.

**Comment by x0r2d2** [comment]
NextDNS is better option for that, IMHO.

**Comment by randshell** [comment]
Not when it comes out of beta https://nextdns.io/pricing

**Comment by x0r2d2** [comment]
> Not when it comes out of beta https://nextdns.io/pricing

`If you decide to stay on the free plan, NextDNS will simply behave like a classic public resolver after reaching the 300,000 queries limit.`

Still not bad :)

**Comment by angristan** [comment]
We'll go with AdGuard for now #688
