### ISSUE TITLE
Resolver not being updated on Linux CLI clients (DNS leaking)

### ISSUE THREAD

**Issue by ananthu-sk** [angristan/openvpn-install#597]
Openvpn version 2.4, latest openvpn-install, OS arch linux & kali linux

`sudo openvpn --config client.ovpn`
The dns aka resolv.conf is not updated when connection established like above, so dns leak happens.

But when executed in network manager by adding vpn connection resolv.conf is updated and dns leaks is not there.

The above scenario is confirmed in both of my os. Do i have to manually edit resolv.conf when used in command line mode?

**Comment by HenryNe** [comment]
I can confirm your issue. You need to add the script `update-resolv-conf` to your config or to your command line. The script needs a helper `/sbin/resolvconf`.

This should help you (for Debian 9):
```
$ sudo apt-get install resolvconf
$ sudo openvpn --config client.ovpn \
  --up /etc/openvpn/update-resolv-conf \
  --down /etc/openvpn/update-resolv-conf \
  --script-security 2
```

**Comment by randshell** [comment]
Add this to your `.ovpn` profile
```
script-security 2
up /etc/openvpn/update-resolv-conf
down /etc/openvpn/update-resolv-conf
```
~I will write a PR.~

**Comment by ananthu-sk** [comment]
> I can confirm your issue. You need to add the script `update-resolv-conf` to your config or to your command line. The script needs a helper `/sbin/resolvconf`.
> 
> This should help you:
> 
> ```
> $ sudo apt-get install resolvconf
> $ sudo openvpn --config client.ovpn \
>   --up /etc/openvpn/update-resolv-conf \
>   --down /etc/openvpn/update-resolv-conf \
>   --script-security 2
> ```

thanks for replying, this new error shows how to resolve it


Unrecognized option or missing or extra parameter(s) in /home/ananthu/.config/vpnclients/arch.ovpn:18: block-outside-dns (2.4.8)
Options error: --up script fails with '/etc/openvpn/update-resolv-conf': No such file or directory (errno=2)
Options error: Please correct this error.
Use --help for more information.

**Comment by randomshell** [comment]
Did you test on arch or on Kali?

**Comment by randshell** [comment]
~If you are on Arch try installing `openvpn-update-resolv-conf-git` first.~ See https://github.com/angristan/openvpn-install/issues/597#issuecomment-607452478

**Comment by randshell** [comment]
> I will write a PR.

Including `up /etc/openvpn/update-resolv-conf` in generated `.ovpn` exits with error if the script doesn't exists and I haven't found a solution to check if it exists first. The best is to update the wiki with instructions @angristan 

Related #479

**Comment by angristan** [comment]
So, sorry, what's the solution to this?

**Comment by randshell** [comment]
@angristan the solution is adding to the `.ovpn` file the lines for the corresponding OS. The scripts come with the `openvpn` package.

Debian 9, 10 and Ubuntu 16.04, 18.04
```
script-security 2
up /etc/openvpn/update-resolv-conf
down /etc/openvpn/update-resolv-conf
```

Centos 6, 7
```
script-security 2
up /usr/share/doc/openvpn-2.4.8/contrib/pull-resolv-conf/client.up
down /usr/share/doc/openvpn-2.4.8/contrib/pull-resolv-conf/client.down
```

Centos 8, Fedora 30, 31
```
script-security 2
up /usr/share/doc/openvpn/contrib/pull-resolv-conf/client.up
down /usr/share/doc/openvpn/contrib/pull-resolv-conf/client.down
```

Arch Linux
```
script-security 2
up /usr/share/openvpn/contrib/pull-resolv-conf/client.up
down /usr/share/openvpn/contrib/pull-resolv-conf/client.down
```

**Comment by randshell** [comment]
@ask1234560 after some more research is not necessary to install `openvpn-update-resolv-conf-git` on Arch. See my previous comment (https://github.com/angristan/openvpn-install/issues/597#issuecomment-607452478)

**Comment by ananthu-sk** [comment]
@randomshell yup that fixed it
