### ISSUE TITLE
rc.local not present on Ubuntu 16.10, 17.04 and Debian 9

### ISSUE THREAD

**Issue by angristan** [angristan/openvpn-install#6]
`/etc/rc.local` is not present on Ubuntu 16.10.

Instead, there is multiple folders : 
```
rc0.d
rc1.d
rc2.d
rc3.d
rc4.d
rc5.d
rc6.d
rcS.d
```

As a result, the iptables NAT rule to forward traffic is not applied at reboot.

I'll take a look asap.

**Comment by kfl** [comment]
It seems that the package `iptables-persistent` is the right thing to use in this case, for both Debian and Ubuntu.

I was able to save the iptables NAT rule by installing the `iptables-persistent` package after running the `openvpn-install.sh` script.

**Comment by Kcchouette** [comment]
You can fix that by doing theses changes: https://github.com/Nyr/openvpn-install/commit/a31aaf82f3664e5854c617752a5493011ede731f
