### ISSUE TITLE
UDP MODE NOT WORK

### ISSUE THREAD

**Issue by CorePack** [angristan/openvpn-install#616]
any https connection not work when i use UDP mode and it works well with TCP
Ubuntu 18.04 Amazon

**Comment by angristan** [comment]
Verify your security group...

**Comment by CorePack** [comment]
http://prntscr.com/rxk9x7
here is my security group inbound and outbound too
http://prntscr.com/rxka7c
Connection to google.com 1194 port [udp/openvpn] succeeded!

and here i tested the udp connection to google and it works serverside

**Comment by angristan** [comment]
Are you able to ping something while connected to OpenVPN in UDP mode?

**Comment by CorePack** [comment]
Yes i can ping everysingle ip
I got the problem 

EGYPT HOME ISP blocking ssl over udp connection when using openvpn, 
But when i used mobile data it works fine. 

So i tried  wireguard and everything is working perfect and smoothly (Home and mobile ISP'S) .

**Comment by x0r2d2** [comment]
> Yes i can ping everysingle ip
> I got the problem 
> 
> EGYPT HOME ISP blocking ssl over udp connection when using openvpn, 
> But when i used mobile data it works fine. 
> 
> So i tried  wireguard and everything is working perfect and smoothly (Home and mobile ISP'S) . 

What you mean by "ssl over UDP"?
Clean openvpn on 443 port over UDP or openvpn+stunnel on 443 port over UDP?

**Comment by CorePack** [comment]
> 
> 
> > Yes i can ping everysingle ip
> > I got the problem
> > EGYPT HOME ISP blocking ssl over udp connection when using openvpn,
> > But when i used mobile data it works fine.
> > So i tried  wireguard and everything is working perfect and smoothly (Home and mobile ISP'S) .
> 
> What you mean by "ssl over UDP"?
> Clean openvpn on 443 port over UDP or openvpn+stunnel on 443 port over UDP?

Clean openvpn on 443 port over UDP

**Comment by x0r2d2** [comment]
> EGYPT HOME ISP blocking ssl over udp connection when using openvpn,

even with tls-crypt?
