### ISSUE TITLE
Why cp /usr/lib/systemd/system/openvpn-server@.service /etc/systemd/system/openvpn-server@.service?

### ISSUE THREAD

**Issue by laichiaheng** [angristan/openvpn-install#617]
Why do you add `cp /usr/lib/systemd/system/openvpn-server@.service /etc/systemd/system/openvpn-server@.service in the script`?
If I don't add this command, openvpn-server@.service is not going to be started by systemd. How do you know that you need it? ArchWiki didn't mention it.

**Comment by angristan** [comment]
Because we need to overwrite some lines:

https://github.com/angristan/openvpn-install/blob/6989b0d326f22439afc66b03011a0afd1bf9e2fa/openvpn-install.sh#L879-L912

**Comment by angristan** [comment]
Do you have an issue with this?

**Comment by laichiaheng** [comment]
I don't know why we should do this here, I'm still learning how to setup a OpenVPN server.
