### ISSUE TITLE
common names from certyficate

### ISSUE THREAD

**Issue by joksik** [angristan/openvpn-install#619]
maybe stupid question but after you add support for client-configuration-dir i want for few clients 
make individual configuration. i read openvpn instructions and i know that i must create files in ccd with certyficate common name but the question is where i found that common names? maybe there is hidden file with all common names? or certyficate common name is the same as client name when i launch script and create new client ?

**Comment by randshell** [comment]
> certyficate common name is the same as client name when i launch script and create new client

Yes

**Comment by randshell** [comment]
@angristan this can be closed
