### ISSUE TITLE
Another IP output and URL filter

### ISSUE THREAD

**Issue by ultraandreyy** [angristan/openvpn-install#622]
#### Hello everyone.
Please tell me how to implement this idea:
you need to create two _OpenVPN-servers_ using the script from @angristan. Next, do you need to combine these two _OpenVPN-servers_ so that the user connects to one _IP-address_ and leaves the Internet with a different _IP-address_?

How to implement this please tell me.

**Comment by ultraandreyy** [comment]
Is it mandatory to use two _OpenVPN-servers_, or can you just use another server to access the Internet? 
All that matters to me is that the user accesses the Internet with a different _IP-address_, not the same as the _OpenVPN-server_. Are there any other options to do this?

**Comment by ultraandreyy** [comment]
Can I put several _OpenVPN-servers_ on the Internet through one server with a different _IP-address_?
And how can you prevent users from visiting certain sites? Please tell me what kind of utility for this or can it be implemented in _OpenVPN_?

**Comment by angristan** [comment]
Hello, this is unrelated to this script, please find appropriate OpenVPN forums or similar to ask for help. We already overflowing with issues, so no hard feelings but I will close this.

**Comment by randshell** [comment]
> the user connects to one IP-address and leaves the Internet with a different IP-address?

Install a proxy server on the entry IP and OpenVPN on the exit IP and use the `http-proxy` option in the ovpn file. See https://openvpn.net/community-resources/connecting-to-an-openvpn-server-via-an-http-proxy/

> And how can you prevent users from visiting certain sites?

Install Pihole and set the OpenVPN server to use it as DNS server so that connected clients use it. It's the easiest solution but with some knowledge it can be bypassed.

**Comment by ultraandreyy** [comment]
> 
> 
> Hello, this is unrelated to this script, please find appropriate OpenVPN forums or similar to ask for help. We already overflowing with issues, so no hard feelings but I will close this.

OK well. It's okay, I understand

**Comment by ultraandreyy** [comment]
> 
> 
> > the user connects to one IP-address and leaves the Internet with a different IP-address?
> 
> Install a proxy server on the entry IP and OpenVPN on the exit IP and use the `http-proxy` option in the ovpn file. See https://openvpn.net/community-resources/connecting-to-an-openvpn-server-via-an-http-proxy/
> 
> > And how can you prevent users from visiting certain sites?
> 
> Install Pihole and set the OpenVPN server to use it as DNS server so that connected clients use it. It's the easiest solution but with some knowledge it can be bypassed.

Thank you, I will read the information about the proxy.

Yes, PiHole, this is what I needed.
