### ISSUE TITLE
what to choose? Gui or script? help!

### ISSUE THREAD

**Issue by Itay1787** [angristan/openvpn-install#623]
Hi,
I really liked the script
I have only two problems
1. Unable to create username and password for login
2. I can't change the tunnel IP
No matter what, the IP just would be nice if it were possible to change
But not being able to login with a username and password is really a huge security risk!
My question is whether to use the script even though the username and password cannot be used mainly in the security part of this thing.
Or just install the openVPN sever's gui and that's it?

I really don't know what to choose!!
Would appreciate help
Thanks
Itay

**Comment by randshell** [comment]
You can password protect the ovpn file and when it's compromised revoke the client and generate another. A password pretected ovpn file is secure and you don't need username and passwords for login.

**Comment by Itay1787** [comment]
Ok I know it's secure but more secure or equivalent to having a username and password?
And I'm also going to connect as a client in pfsense. Will password protection that already exists still work? Or would I have to without?

**Comment by Itay1787** [comment]
??

**Comment by randshell** [comment]
> more secure or equivalent to having a username and password

If you can keep your .ovpn file secure then it's secure. And if it's password protected then even better.

Username and passwords can be remotely bruteforced but the configuration of OpenVPN installed by this script requires a certificate that you can find in the ovpn file. You can't bruteforce this remotely.

> Will password protection that already exists still work? Or would I have to without?

What do you mean?

**Comment by Itay1787** [comment]
> Username and passwords can be remotely bruteforced but the configuration of OpenVPN installed by this script requires a certificate that you can find in the ovpn file. You can't bruteforce this remotely.

Ok, so I choose the script and not the Gui! As long as there is no username and password does not compromise security, and even by what you said it is the opposite it increases security it is better!!

> What do you mean?

I mean if I use a connection to pfsense as a client. I can't use a .ovpn file there.
So I asked if I add the script protected password, can I use it in pfsense as well (just add the password there)? Or will it just not work? And the password is actually meant for clients who use the .ovpn file?

**Comment by randshell** [comment]
> what you said it is the opposite it increases security it is better

Another option is to use username and password with a TOTP code if you think it's the most secure for your use case but it's not supported by this script.

> I can't use a .ovpn file there.

> And the password is actually meant for clients who use the .ovpn file?

Then you need to input the options manually. The password is to protect the ovpn file but if you need to input the options in pfsense then you generate a client without password protected ovpn so you can read the certificate parts and copy to pfsense.

**Comment by Itay1787** [comment]
Ok, as long as this script creates a secure OpenVPN server, then it's fine. I was just scared to use it because I saw that it didn't have the option to create a username and password so I didn't know if the way it was doing it was as secure.

Yes in pfsense I have to enter everything manually.
And I believe that even if I create a client without a password to protect the ovpn file and encrypt the certificate it is still secure. Right?

I've probably repeated myself several times, I just have to make sure that what I do is really secure.

**Comment by randshell** [comment]
> Ok, as long as this script creates a secure OpenVPN server, then it's fine. I was just scared to use it because I saw that it didn't have the option to create a username and password so I didn't know if the way it was doing it was as secure.

Yes. We use certificates instead of username and password.

> Yes in pfsense I have to enter everything manually.
And I believe that even if I create a client without a password to protect the ovpn file and encrypt the certificate it is still secure. Right?

The password to protect the ovpn file prevents others from reading it and connecting without the password. It is useful on portable devices that can be stolen. For desktop or router use it is not necessary.

> I just have to make sure that what I do is really secure.

I think it is. Read https://github.com/angristan/openvpn-install#security-and-encryption and the NSA FAQ https://github.com/angristan/openvpn-install#faq

If you think Wireguard is better for you @angristan has a wireguard repo too at https://github.com/angristan/wireguard-install but I don't know if pfsense supports it.

**Comment by Itay1787** [comment]
Ok!! thanks so much for the help!
> Yes. We use certificates instead of username and password.
>
> The password to protect the ovpn file prevents others from reading it and connecting without the password. It is useful on portable devices that can be stolen. For desktop or router use it is not necessary.

You answered me exactly what I wanted! And just what I wanted to hear - which is secure and I just worry about nothing :) 

> If you think Wireguard is better for you @angristan has a wireguard repo too at https://github.com/angristan/wireguard-install but I don't know if pfsense supports it.

I thought about Wireguard but unfortunately in many places it still does not support nor is pfsense officially supportive. Probably in a later version.
So thank you so much!

**Comment by angristan** [comment]
Thanks @randomshell

**Comment by randshell** [comment]
@Itay1787 looks like someone managed to install Wireguard on PFsense https://www.reddit.com/r/PFSENSE/comments/eakwmt/pfsense_wireguard_tutorial_as_found_on_torguard/

Have you tried OPNsense? They support Wireguard and someone migrated for this reason https://blog.linuxserver.io/2019/11/16/setting-up-wireguard-on-opnsense-android/
