### ISSUE TITLE
connection problem

### ISSUE THREAD

**Issue by Janasek** [angristan/openvpn-install#625]
Hi.
I have big problems getting a connection
I use openvz7 vps, and I had no problems until yesterday
I decided to reinstall the system and openvpn not working
Has something changed?

I tried with changes TUN / TAP, PPP
I tried with adding ports, ufw allow nothing too
There is a connection but I can't open any website and so on

Where can I find versions from 4 months ago?

**Comment by randshell** [comment]
Try with this link from Jan 27 https://raw.githubusercontent.com/angristan/openvpn-install/4b0f47b534f374deebdd0e5430f2caf908b3e79f/openvpn-install.sh

What OS are you using?

**Comment by Janasek** [comment]
thanks, I'll check it as soon as possible
I see that I can use shh via vpn but nothing else works.

System: Ubuntu 18.04 x64 OVZ7

**Comment by Janasek** [comment]
Uff, iptables is horrible but necessary.
probably the supplier has changed something
because everything worked until reinstallation, and I don't remember setting it up

**It helped me,** 

iptables -F

iptables -A INPUT -i lo -j ACCEPT
iptables -A FORWARD -o lo -j ACCEPT
iptables -A OUTPUT -o lo -j ACCEPT
iptables -A INPUT -i venet0 -p udp -m udp --dport MY-VPN-PORT -j ACCEPT
iptables -A INPUT -i tun0 -j ACCEPT
iptables -A FORWARD -i tun0 -o venet0 -j ACCEPT
iptables -A FORWARD -i venet0 -o tun0 -j ACCEPT

**#EXTRA**
iptables -A INPUT -s **MY-HOME-IP/26** -p udp -j ACCEPT
iptables -A INPUT -s **MY-HOME-IP/26** -p tcp -j ACCEPT
iptables -A OUTPUT -d **MY-HOME-IP/26** -p udp -j ACCEPT
iptables -A OUTPUT -d **MY-HOME-IP/26** -p tcp -j ACCEPT
iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A OUTPUT -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT
iptables -P INPUT DROP
iptables -P FORWARD DROP
iptables -P OUTPUT DROP
