### ISSUE TITLE
Not working on Arch Linux

### ISSUE THREAD

**Issue by mattwelke** [angristan/openvpn-install#63]
I'm using Arch (Antergos) and for me this install script didn't work. I followed the script and noticed near the end it had an error message saying it couldn't start the service. I also get this when I try to manually start it (I found the service name from reading other issues on this repo):

```
[mwelke@mdesk ~]$ systemctl status openvpn@server.service
Unit openvpn@server.service could not be found.
[mwelke@mdesk ~]$ sudo systemctl status openvpn@server.service
Unit openvpn@server.service could not be found.
```

Was wondering if anyone could give me a hand with this.

**Comment by DrXala** [comment]
@welkie Check [#61](https://github.com/Angristan/OpenVPN-install/issues/61) ;)
