### ISSUE TITLE
Suggest browserleaks.com for dns leak tests

### ISSUE THREAD

**Issue by randshell** [angristan/openvpn-install#633]
The FAQ suggests https://dnsleaktest.com/ and https://ipleak.net/ to test dns leaks. Do they support IPv6 leaks? I don't have an IPv6 connection to test.

An alternative is https://browserleaks.com/dns that explicitly tests IPv6:
> This test attempts to resolve 100 randomly generated domain names asynchronously, 50 with A record (IPv4-only) and 50 with both A and AAAA records (IPv4+IPv6).

**Comment by angristan** [comment]
https://ipleak.net/ does support IPv6, but https://browserleaks.com/dns seems like a good alternative too
