### ISSUE TITLE
Connection restart

### ISSUE THREAD

**Issue by retro-desert** [angristan/openvpn-install#635]
The connection is reconnected every hour. It does not depend on the device.
I was looking for information, but did not find anything. Could there be a problem in the config?

**Comment by randshell** [comment]
> Could there be a problem in the config?

No, this is the default behavior of OpenVPN. For security reasons every hour the key used to encrypt vpn traffic is changed and the client automatically reconnects.

> The connection is reconnected every hour.

The reconnection happens automatically without your input, where is the problem?

Anyway if you need to change this behavior see #478.

**Comment by retro-desert** [comment]
@randomshell Internet connection every times broke(
