### ISSUE TITLE
UDP

### ISSUE THREAD

**Issue by tonweak** [angristan/openvpn-install#648]
Please add this feature in your next update. Running multiple OpenVPN instances (multi port). Thanks for your work bro!

**Comment by randshell** [comment]
UDP is supported, please download the script again if you don't have the latest version
 Use `curl -O https://raw.githubusercontent.com/angristan/openvpn-install/master/openvpn-install.sh`

**Comment by randshell** [comment]
@angristan can you include in the issue template to reinstall openvpn using the latest `openvpn-install.sh` version before opening an issue?

**Comment by tonweak** [comment]
@randomshell  Here is what I mean ---> https://www.hugeserver.com/kb/openvpn-multiple-ports/

**Comment by randshell** [comment]
> @randomshell Here is what I mean ---> https://www.hugeserver.com/kb/openvpn-multiple-ports/

See https://github.com/angristan/openvpn-install/issues/28#issuecomment-421851122
