### ISSUE TITLE
Can't open webpages, but can ping.

### ISSUE THREAD

**Issue by faust21** [angristan/openvpn-install#649]
I installed openvpn listening on ``` tcp/1194 ```, and redirect port ``` 443 ``` to ``` 1194 ```
 with the scripts ``` iptables -t nat -A PREROUTING -p tcp --dport 443 -j REDIRECT --to-ports 1194 ```.
I have tried every DNS but it still not working.

**Comment by angristan** [comment]
So, is it a DNS problem?

**Comment by faust21** [comment]
@angristan I don't know if it's a DNS problem. But I guessed so. I tried ping the domain on server, that's no problem. And on my phone, the app use network works perfectly, but I can't open the webpages on browser.

**Comment by angristan** [comment]
Please use issue templates when opening issues.

**Comment by faust21** [comment]
Solved. When use port 443, the web site use http can visit, but https not. So I use 53 instead 443, then it works.
