### ISSUE TITLE
the openvpn service doesn't show up with systemctl disable.

### ISSUE THREAD

**Issue by laichiaheng** [angristan/openvpn-install#651]
**Checklist**

- [x] I read the [README](https://github.com/angristan/openvpn-install/blob/master/README.md)
- [x] I read the [FAQ](https://github.com/angristan/openvpn-install/blob/master/FAQ.md)
- [x] I searched the [issues](https://github.com/angristan/openvpn-install/issues?q=is%3Aissue+)
- [x] My issue is about the script, and not OpenVPN itself

**Describe the issue**
When I tried to disable the openvpn service with `systemctl disable`, I couldn't find the option.

**To Reproduce**

1. Type `sudo systemctl disable openvpn`
2. Press TAB button.
3. It doesn't autocomplete the command.

**Expected behavior**
It should show the full name like `sudo systemctl disable openvpn-server@server.service` 

**Logs**

**Server if applicable): My PC

- OS: Manjaro
- Hosting provider (if applicable): My PC

**Client (if applicable):My android phone

- Device: Android phone.
- OS: Android 9
- Client: OpenVPN Connect

**Additional context**

**Comment by angristan** [comment]
That doesn't seem to be related to the script, but if it does I... don't really mind. Please open a PR if you have a fix.

**Comment by randshell** [comment]
Do you have the package `bash-completion` installed? You should have a script at `/usr/share/bash-completion/completions/systemctl` that does this job.

**Comment by laichiaheng** [comment]
> Do you have the package `bash-completion` installed? You should have a script at `/usr/share/bash-completion/completions/systemctl` that does this job.

Yes, it is installed. I can disable it if I follow the ArchWiki way, but it doesn't work with this script.
