### ISSUE TITLE
On the same server with Telegram Proxy

### ISSUE THREAD

**Issue by x0r2d2** [angristan/openvpn-install#656]
Good day!
I have an issue and I don't know how to solve it. Tried Googling but I didn't find any solution (may be I am blind).

Info:
Telegram Proxy and Openvpn server are living on the same server (same ip).
I am using Openvpn on my router. Default route - everything through VPN.
Issue:
When I am connected to my router (VPN), I am not able to reach my Telegram proxy through global ip address, I can reach it only through Openvpn's internal network (e.g. 10.3.0.1).

Question:
What iptables rule I have to input on my server, so I will be able to communicate with telegram proxy when I am in my home network (VPN)?

**Comment by randshell** [comment]
Can you try advertising the route with `push "route <subnet> 255.255.255.0"` in `server.conf` and restart openvpn? It's the remote LAN question in the FAQ

**Comment by x0r2d2** [comment]
> Can you try advertising the route with `push "route <subnet> 255.255.255.0"` in `server.conf` and restart openvpn? It's the remote LAN question in the FAQ

Which route? Openvpn subnet?

**Comment by randshell** [comment]
The server's IP you wanted to reach.

**Comment by x0r2d2** [comment]
> The server's IP you wanted to reach.

It didn't help.

**Comment by randshell** [comment]
As a side note when you connect to a VPN it's like you are physically there, like using ssh. So I don't see why to connect to a PC in the same network you would use its public IP.

Personally I always set services to listen on `10.8.0.1` and use that.

**Comment by x0r2d2** [comment]
> As a side note when you connect to a VPN it's like you are physically there, like using ssh. So I don't see why to connect to a PC in the same network you would use its public IP.
> 
> Personally I always set services to listen on `10.8.0.1` and use that.

I am using the proxy in different networks. I don't want to switch proxies when I am on my VPN network.

**Comment by randshell** [comment]
You are right, it seems easier with iptables. The command I found is `iptables -t nat -A PREROUTING -s $VPNclientIP -p $protocol --dport $destPort -j DNAT --to-destination 10.8.0.1:$destPort`.

Source https://www.debuntu.org/how-to-redirecting-network-traffic-to-a-new-ip-using-iptables/

**Comment by x0r2d2** [comment]
> You are right, it seems easier with iptables. The command I found is `iptables -t nat -A PREROUTING -s $VPNclientIP -p $protocol --dport $destPort -j DNAT --to-destination 10.8.0.1:$destPort`.

Still didn't help. I think it is almost impossible. The only way for now is to install MTProxy on different server.

**Comment by x0r2d2** [comment]
@randomshell 
It is not only with Telegram Proxy. I can not ssh to server via public interface if I am in Openvpn network, only through the Openvpn subnet (10.X.0.1).

**Comment by randshell** [comment]
@hybtoy  I'm sorry I can't help much with iptables. I should get a vps and test these things.
