### ISSUE TITLE
failed to import ovpn profile static_key_parse 

### ISSUE THREAD

**Issue by BoniWPy** [angristan/openvpn-install#657]
**Checklist**

- [x] I read the [README](https://github.com/angristan/openvpn-install/blob/master/README.md)
- [x] I read the [FAQ](https://github.com/angristan/openvpn-install/blob/master/FAQ.md)
- [x] I searched the [issues](https://github.com/angristan/openvpn-install/issues?q=is%3Aissue+)
- [ ] My issue is about the script, and not OpenVPN itself

**Describe the issue**

**To Reproduce**

1. ...

**Expected behavior**

**Logs**
If applicable, add logs or screenshots to help explain your problem.

If you can reproduce the issue, please run the script in debug mode and post the output: `bash -x openvpn-install.sh`

**Server if applicable):**

- OS: [e.g. Debian 10]
- Hosting provider (if applicable): [e.g. Vultr, AWS]

**Client (if applicable):**

- Client: [e.g. OpenVPN Connect]

**Additional context**

**Comment by randshell** [comment]
I think the problem is in the comments of the `.ovpn` file. Can you remove the following lines and import the profile again?
```
# 
# 2048 bit OpenVPN static key
# 
```

**Comment by angristan** [comment]
Not enough details, closing...
