### ISSUE TITLE
Does Openvpn need dns-crypt?

### ISSUE THREAD

**Issue by x0r2d2** [angristan/openvpn-install#658]
Just curios if openvpn needs dns-crypt with established connection. 

I am testing it out now and this is my browserleaks test:

<img src="https://i.ibb.co/rbtYk54/browserleaks-dns-2020-05-04-16-05-27.png" alt=""><br/>&nbsp;<br/>

**Comment by angristan** [comment]
This is classic DNS leak, something is wrong with your config :)
