### ISSUE TITLE
Internet is not working after connecting to Open VPN server.

### ISSUE THREAD

**Issue by chdharm** [angristan/openvpn-install#659]
I am using Digital ocean droplet Ubuntu-18.0 1GB/25GB for VPN server. My VPN server connection is working with internet on my laptop but when I am trying the same on friends laptop , Internet is not working.
My laptop is Ubuntu. They are using Ubuntu and Mac-book Pro. I have tried lot of things but it didn't work in their system.

Their IP's are changing but Internet connection is not working, they are not able to surf. We are at different places they are using different Wifi.

**Comment by x0r2d2** [comment]
@chdharm 
Good day! 
First I thought it is an iptables (firewall rules) issue but you say that VPN is working for you. 
Did you install openvpn with script default parameters?
Please check if compression is turned off on friends laptop.

**Comment by chdharm** [comment]
**Steps I followed while installing:**
1. Installed open VPN using.
`curl -O https://raw.githubusercontent.com/angristan/openvpn-install/master/openvpn-install.sh
chmod +x openvpn-install.sh` 
./openvpn-install.sh   [I went ahead with default settings]
2. After that ran script again to add few more password less users.
3. After that I added duplicate-cn in server.config.
4. After that I saw DEFAULT_FORWARD_POLICY in /etc/default/ufw is DROP. I changes it to "ACCEPT".
5. In file /etc/sysctl.conf , net.ipv4.ip_forward=1 was commented so I uncommented it.
6. Checked cat /proc/sys/net/ipv4/ip_forward which is 1. Leaving it as it is.
7. sysctl -a | grep "net.ipv4.ip_forward " and this net.ipv4.ip_forward=1. Leaving it as it is.
8.  Next comment.

**Comment by chdharm** [comment]
8. sudo iptables -t nat -L -vn --line
Chain PREROUTING (policy ACCEPT 486 packets, 26479 bytes)
num pkts bytes target prot opt in out source destination

Chain INPUT (policy ACCEPT 486 packets, 26479 bytes)
num pkts bytes target prot opt in out source destination

Chain OUTPUT (policy ACCEPT 2 packets, 152 bytes)
num pkts bytes target prot opt in out source destination

Chain POSTROUTING (policy ACCEPT 2 packets, 152 bytes)
num pkts bytes target prot opt in out source destination

1  0   0  MASQUERADE all --  * eth0  10.8.0.0/24  0.0.0.0


9. sudo iptables -L FORWARD -vn --line
             1   0  0  ACCEPT   all   --  tun0   0.0.0.0/0    0.0.0.0/0 
             2   0  0  ACCEPT   all   --  tun0   0.0.0.0/0    0.0.0.0/0

**Comment by chdharm** [comment]
Did no change in step 8 and 9 too.

**Comment by chdharm** [comment]
Still, It's not working in friends laptops.
What should I do.
Should I use:
               iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -j SNAT --to $IP(Replacing it by server IP)
And then restating server.

@hybtoy Good day , Please help me with this.

**Comment by chdharm** [comment]
@hybtoy @angristan 
Did you install openvpn with script default parameters?
Please check if compression is turned off on friends laptop.

Yes I have installed it using script default option.
How can I check compression setting is turned off in friends laptop.

**Comment by chdharm** [comment]
**VPN Client Logs from friends computer who is using different WiFi:**

Tue May  5 19:51:22 2020 Unrecognized option or missing or extra parameter(s) in subhhu.ovpn:19: block-outside-dns (2.4.4)
Tue May  5 19:51:22 2020 OpenVPN 2.4.4 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on May 14 2019
Tue May  5 19:51:22 2020 library versions: OpenSSL 1.1.1  11 Sep 2018, LZO 2.08
Tue May  5 19:51:22 2020 Outgoing Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Tue May  5 19:51:22 2020 Outgoing Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Tue May  5 19:51:22 2020 Incoming Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Tue May  5 19:51:22 2020 Incoming Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Tue May  5 19:51:22 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]167.71.237.84:1194
Tue May  5 19:51:22 2020 Socket Buffers: R=[212992->212992] S=[212992->212992]
Tue May  5 19:51:22 2020 UDP link local: (not bound)
Tue May  5 19:51:22 2020 UDP link remote: [AF_INET]167.71.237.84:1194
Tue May  5 19:51:22 2020 TLS: Initial packet from [AF_INET]167.71.237.84:1194, sid=589e6b62 400bc7e1
Tue May  5 19:51:22 2020 VERIFY OK: depth=1, CN=cn_KmyMW0BlYWxzza0R
Tue May  5 19:51:22 2020 VERIFY KU OK
Tue May  5 19:51:22 2020 Validating certificate extended key usage
Tue May  5 19:51:22 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Tue May  5 19:51:22 2020 VERIFY EKU OK
Tue May  5 19:51:22 2020 VERIFY X509NAME OK: CN=server_qkHf6lQbGNGUktQa
Tue May  5 19:51:22 2020 VERIFY OK: depth=0, CN=server_qkHf6lQbGNGUktQa
Tue May  5 19:51:22 2020 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_AES_256_GCM_SHA384, 256 bit EC, curve: prime256v1
Tue May  5 19:51:22 2020 [server_qkHf6lQbGNGUktQa] Peer Connection Initiated with [AF_INET]167.71.237.84:1194
Tue May  5 19:51:24 2020 SENT CONTROL [server_qkHf6lQbGNGUktQa]: 'PUSH_REQUEST' (status=1)
Tue May  5 19:51:24 2020 PUSH: Received control message: 'PUSH_REPLY,dhcp-option DNS 1.0.0.1,dhcp-option DNS 1.1.1.1,redirect-gateway def1 bypass-dhcp,route-gateway 10.8.0.1,topology subnet,ping 10,ping-restart 120,ifconfig 10.8.0.2 255.255.255.0,peer-id 0,cipher AES-128-GCM'
Tue May  5 19:51:24 2020 OPTIONS IMPORT: timers and/or timeouts modified
Tue May  5 19:51:24 2020 OPTIONS IMPORT: --ifconfig/up options modified
Tue May  5 19:51:24 2020 OPTIONS IMPORT: route options modified
Tue May  5 19:51:24 2020 OPTIONS IMPORT: route-related options modified
Tue May  5 19:51:24 2020 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
Tue May  5 19:51:24 2020 OPTIONS IMPORT: peer-id set
Tue May  5 19:51:24 2020 OPTIONS IMPORT: adjusting link_mtu to 1624
Tue May  5 19:51:24 2020 OPTIONS IMPORT: data channel crypto options modified
Tue May  5 19:51:24 2020 Outgoing Data Channel: Cipher 'AES-128-GCM' initialized with 128 bit key
Tue May  5 19:51:24 2020 Incoming Data Channel: Cipher 'AES-128-GCM' initialized with 128 bit key
Tue May  5 19:51:24 2020 ROUTE_GATEWAY 192.168.0.1/255.255.255.0 IFACE=wlo1 HWADDR=dc:f5:05:dc:d5:b5
Tue May  5 19:51:24 2020 TUN/TAP device tun0 opened
Tue May  5 19:51:24 2020 TUN/TAP TX queue length set to 100
Tue May  5 19:51:24 2020 do_ifconfig, tt->did_ifconfig_ipv6_setup=0
Tue May  5 19:51:24 2020 /sbin/ip link set dev tun0 up mtu 1500
Tue May  5 19:51:24 2020 /sbin/ip addr add dev tun0 10.8.0.2/24 broadcast 10.8.0.255
Tue May  5 19:51:24 2020 /sbin/ip route add 167.71.237.84/32 via 192.168.0.1
Tue May  5 19:51:24 2020 /sbin/ip route add 0.0.0.0/1 via 10.8.0.1
Tue May  5 19:51:24 2020 /sbin/ip route add 128.0.0.0/1 via 10.8.0.1
Tue May  5 19:51:24 2020 Initialization Sequence Completed

**Comment by HenryNe** [comment]
> How can I check compression setting is turned off in friends laptop.

If the compression would be differ on server and client, then openvpn would give you a warning about different configs in client syslog.

Your client log seems correctly.

There must be something with the firewall.
Because you say, your laptop is working: May be the firewall on your freends latpot is blocking outgoing over the new "tun" device?

Can you ping the server 10.8.0.1 from your friens laptop?

**Comment by chdharm** [comment]
@HenryNe  
Actually in my laptop it's working(I am able to ping and browse) but in friend laptop who is using different laptop and different WiFi , he is able to ping  10.8.0.1 IP but internet is not working. He is not able to open any page in browser.

Should I do this too:
iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -j SNAT --to $IP(Replacing it by server IP)
And then restating server.

**Comment by randshell** [comment]
`duplicate-cn` might be in conflict with `ifconfig-pool-persist ipp.txt`. Your friend uses the same `.ovpn` file as you?

[Source](https://forums.openvpn.net/viewtopic.php?t=7273#p8444)
> After that I saw DEFAULT_FORWARD_POLICY in /etc/default/ufw is DROP. I changes it to "ACCEPT".

Does it work without manually editing UFW? This issue should be fixed https://github.com/angristan/openvpn-install/issues/233

> In file /etc/sysctl.conf , net.ipv4.ip_forward=1 was commented so I uncommented it.

We use `/etc/sysctl.d/20-openvpn.conf` to enable IP forwarding.

**Comment by chdharm** [comment]
Duplicate-cn might be in conflict with ifconfig-pool-persist ipp.txt. Your friend uses the same .ovpn file as you?

              - I have got separate files for each and every user while the time I add users.

Does it work without manually editing UFW? This issue should be fixed #233
              - It was not fixed

In file /etc/sysctl.conf , net.ipv4.ip_forward=1 was commented so I uncommented it.
We use /etc/sysctl.d/20-openvpn.conf to enable IP forwarding.
     
           - Should I again do this using your way.

@randomshell

**Comment by randshell** [comment]
> Should I do this too:
iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -j SNAT --to $IP(Replacing it by server IP)
And then restating server.

If you say it's working for you I don't think iptables on the server are a problem.

Another thing I can suggest it's an issue with the DNS. Can he ping 8.8.8.8 or visit https://1.1.1.1?

> Tue May 5 19:51:24 2020 PUSH: Received control message: 'PUSH_REPLY,dhcp-option DNS 1.0.0.1,dhcp-option DNS 1.1.1.1,redirect-gateway def1 bypass-dhcp,route-gateway 10.8.0.1,topology subnet,ping 10,ping-restart 120,**ifconfig 10.8.0.2 255.255.255.0**,peer-id 0,cipher AES-128-GCM'

BTW It's strange if you connected first that he has the IP 10.8.0.2. What are your client logs?

**Comment by chdharm** [comment]
@randomshell 

He is neither able to ping 8.8.8.8 nor able to visit https://1.1.1.1.
I have posted the logs in this thread.

When he is connecting to server , internet is not working but I am able to see it in openvpn server's status log that he is connected.

The only problem we have is the internet. The firewall in his system is also disabled.

**Comment by chdharm** [comment]
It worked after I reinstalled VPN client from official website and disabled firewall in their systems.

Thank you so much @randomshell @HenryNe @hybtoy :) Closing this issue :)

**Comment by angristan** [comment]
Thanks for the help everyone!
