### ISSUE TITLE
User Limit

### ISSUE THREAD

**Issue by J0113** [angristan/openvpn-install#66]
Hello!

I'am running in to a problem that users can't connect to the VPN although they get an OK respond.
I think it has to do with the 2 user limit of OpenVPN. The community edition has this by my knowledge not, any change I could change the 2 user limit to (idk) 100 user limit? (I am expecting a maximum of 20 users the most at all time so 25 would be enough).

Greetings
- J0113

**Comment by J0113** [comment]
Any possibility??

**Comment by adworacz** [comment]
Are you generating a new profile for each user? You can't use the same profile for every user with this setup, you need a profile per user.

**Comment by J0113** [comment]
@adworacz I'm creating for every user a new .ovpn file with option _1)_ from the menu

**Comment by Kcchouette** [comment]
@J0113 I don't uderstand your issue.
Have you put: user limit to 2, ad now do you want to change it to 50?

**Comment by J0113** [comment]
@Kcchouette Every user get's a profile (custom generated). The problem is that only two users can connect to the server. I want to let all my all my users (20) be able to connect to the VPN server at the same time!

**Comment by Kcchouette** [comment]
Can you try adding `max-clients 20` on server.conf?

Did adding that change something?

**Comment by angristan** [comment]
OpenVPN Access Server has a user limit. OpenVPN Community does not have any. 

Plus I can't reproduce this on my side.
