### ISSUE TITLE
Config expired and user pass auth

### ISSUE THREAD

**Issue by xwarior2017** [angristan/openvpn-install#663]
how to make config CA expired after 30 days? and please add user and pass auth option thanks

**Comment by randshell** [comment]
> how to make config CA expired after 30 days?

CA are in a secure location so they don't expire this often. You would have to reinstall everything again every month. You are better if you expire user certs after this time. You can do it with a cron job and #486 when it gets merged.

> and please add user and pass auth option thanks

See #623
