### ISSUE TITLE
Webmin module settings

### ISSUE THREAD

**Issue by sinankizar** [angristan/openvpn-install#665]
Hello,
First of all I want to thank you for the incredibly easy to use script. For a long time I tried to install openvpn without success. Your script made me do that literally in seconds. 

My issue is not so important but anyway I want to ask here. Hope you don't mind. 
I am administering my server with webmin and after installing openvpn I wanted to admin the openvpn server with webmin too. I have installed Openvpn admin 3.2 webmin module but I couldn't set it up to see in webmin. I am attaching a screenshot. Can you please point me out what is missing in my settings or is it even possible to see the openvpn server with the openvpn admin module. Thanks in advance.

https://imgur.com/6Sgq05K

**Comment by senkron24** [comment]
yes i am auchso very interst on a admin interface :))

**Comment by sinankizar** [comment]
Found the OpenVPN Access Server but afraid to install it for I can bust my openvpn setup 😆Is there any possibility to install OpenVPN AS? Because that can be a solution too

**Comment by senkron24** [comment]
> Found the OpenVPN Access Server but afraid to install it for I can bust my openvpn setup 😆Is there any possibility to install OpenVPN AS? Because that can be a solution too

good question
???

**Comment by randshell** [comment]
>  Can you please point me out what is missing in my settings or is it even possible to see the openvpn server with the openvpn admin module. Thanks in advance.

What OS are you using? Before #653 is merged we have different paths depending on the distro.

> Found the OpenVPN Access Server but afraid to install it for I can bust my openvpn setup laughingIs there any possibility to install OpenVPN AS? Because that can be a solution too

OpenVPN AS is not open source. This script and OpenVPN are.

I think you need to uninstall the current openvpn if you choose to install AS.

**Comment by sinankizar** [comment]
> > Can you please point me out what is missing in my settings or is it even possible to see the openvpn server with the openvpn admin module. Thanks in advance.
> 
> What OS are you using? Before #653 is merged we have different paths depending on the distro.
> 
> > Found the OpenVPN Access Server but afraid to install it for I can bust my openvpn setup laughingIs there any possibility to install OpenVPN AS? Because that can be a solution too
> 
> OpenVPN AS is not open source. This script and OpenVPN are.
> 
> I think you need to uninstall the current openvpn if you choose to install AS.

I am using:
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial

according to `lsb_release -a`  command.

I am searching a visual monitor for openvpn server so I can keep track of my created users.

**Comment by randshell** [comment]
> I am searching a visual monitor for openvpn server so I can keep track of my created users.

Some options are
- `tail -F /var/log/openvpn/status.log` and #669 (recommended, doesn't require installation of other apps or scripts)
- https://github.com/adamwalach/openvpn-web-ui
- https://github.com/furlongm/openvpn-monitor
- https://github.com/Chocobozzz/OpenVPN-Admin

Tell me if you still want to use the webmin module.

**Comment by sinankizar** [comment]
Sorry to open a closed issue but I have installed https://github.com/adamwalach/openvpn-web-ui as per suggestion but that didn't work unfortunately. Do I have to add any line to my server conf file?

**Comment by randshell** [comment]
> as per suggestion

My suggestions are untested from GitHub search results, you can use whatever you like.

> I have installed https://github.com/adamwalach/openvpn-web-ui but that didn't work unfortunately.

I looked a bit at it and it's possible that the app is expecting different paths from what we are using. I think a more compatible one is https://github.com/furlongm/openvpn-monitor because it uses the management interface of openvpn but please read the docs on how to secure it.

**Comment by senkron24** [comment]
i hope thare its a posibility or any how to get installet 
https://github.com/furlongm/openvpn-monitor

kind regarts
