### ISSUE TITLE
help with nat configuration

### ISSUE THREAD

**Issue by wgalafassijr** [angristan/openvpn-install#667]
In my setup i have this openvpn server (centos8):
etho (public) 10.1.1.230
tun0 (trusted) 10.8.0.1

clients connected to openvpn with 10.8.0.X can connect to public network 10.1.1.X normally, but clients connected to 10.1.1.X can’t.

How to enable this nat/forwarding?

firewall-cmd –get-active-zones
public
interfaces: eth0
trusted
sources: 10.8.0.0/24

iptables -nL
Chain INPUT (policy ACCEPT)
target prot opt source destination
ACCEPT all — 0.0.0.0/0 0.0.0.0/0 ctstate RELATED,ESTABLISHED
ACCEPT all — 0.0.0.0/0 0.0.0.0/0
INPUT_direct all — 0.0.0.0/0 0.0.0.0/0
INPUT_ZONES_SOURCE all — 0.0.0.0/0 0.0.0.0/0
INPUT_ZONES all — 0.0.0.0/0 0.0.0.0/0
DROP all — 0.0.0.0/0 0.0.0.0/0 ctstate INVALID
REJECT all — 0.0.0.0/0 0.0.0.0/0 reject-with icmp-host-prohibited

Chain FORWARD (policy ACCEPT)
target prot opt source destination
ACCEPT all — 0.0.0.0/0 0.0.0.0/0 ctstate RELATED,ESTABLISHED
ACCEPT all — 0.0.0.0/0 0.0.0.0/0
FORWARD_direct all — 0.0.0.0/0 0.0.0.0/0
FORWARD_IN_ZONES_SOURCE all — 0.0.0.0/0 0.0.0.0/0
FORWARD_IN_ZONES all — 0.0.0.0/0 0.0.0.0/0
FORWARD_OUT_ZONES_SOURCE all — 0.0.0.0/0 0.0.0.0/0
FORWARD_OUT_ZONES all — 0.0.0.0/0 0.0.0.0/0
DROP all — 0.0.0.0/0 0.0.0.0/0 ctstate INVALID
REJECT all — 0.0.0.0/0 0.0.0.0/0 reject-with icmp-host-prohibited

Chain OUTPUT (policy ACCEPT)
target prot opt source destination
ACCEPT all — 0.0.0.0/0 0.0.0.0/0
OUTPUT_direct all — 0.0.0.0/0 0.0.0.0/0

Chain FORWARD_IN_ZONES (1 references)
target prot opt source destination
FWDI_public all — 0.0.0.0/0 0.0.0.0/0 [goto]
FWDI_public all — 0.0.0.0/0 0.0.0.0/0 [goto]

Chain FORWARD_IN_ZONES_SOURCE (1 references)
target prot opt source destination
FWDI_trusted all — 10.8.0.0/24 0.0.0.0/0

Chain FORWARD_OUT_ZONES (1 references)
target prot opt source destination
FWDO_public all — 0.0.0.0/0 0.0.0.0/0 [goto]
FWDO_public all — 0.0.0.0/0 0.0.0.0/0 [goto]

Chain FORWARD_OUT_ZONES_SOURCE (1 references)
target prot opt source destination
FWDO_trusted all — 0.0.0.0/0 10.8.0.0/24

Chain FORWARD_direct (1 references)
target prot opt source destination

Chain FWDI_public (2 references)
target prot opt source destination
FWDI_public_log all — 0.0.0.0/0 0.0.0.0/0
FWDI_public_deny all — 0.0.0.0/0 0.0.0.0/0
FWDI_public_allow all — 0.0.0.0/0 0.0.0.0/0
ACCEPT icmp — 0.0.0.0/0 0.0.0.0/0

Chain FWDI_public_allow (1 references)
target prot opt source destination

Chain FWDI_public_deny (1 references)
target prot opt source destination

Chain FWDI_public_log (1 references)
target prot opt source destination

Chain FWDI_trusted (1 references)
target prot opt source destination
FWDI_trusted_log all — 0.0.0.0/0 0.0.0.0/0
FWDI_trusted_deny all — 0.0.0.0/0 0.0.0.0/0
FWDI_trusted_allow all — 0.0.0.0/0 0.0.0.0/0
ACCEPT all — 0.0.0.0/0 0.0.0.0/0

Chain FWDI_trusted_allow (1 references)
target prot opt source destination

Chain FWDI_trusted_deny (1 references)
target prot opt source destination

Chain FWDI_trusted_log (1 references)
target prot opt source destination

Chain FWDO_public (2 references)
target prot opt source destination
FWDO_public_log all — 0.0.0.0/0 0.0.0.0/0
FWDO_public_deny all — 0.0.0.0/0 0.0.0.0/0
FWDO_public_allow all — 0.0.0.0/0 0.0.0.0/0

Chain FWDO_public_allow (1 references)
target prot opt source destination

Chain FWDO_public_deny (1 references)
target prot opt source destination

Chain FWDO_public_log (1 references)
target prot opt source destination

Chain FWDO_trusted (1 references)
target prot opt source destination
FWDO_trusted_log all — 0.0.0.0/0 0.0.0.0/0
FWDO_trusted_deny all — 0.0.0.0/0 0.0.0.0/0
FWDO_trusted_allow all — 0.0.0.0/0 0.0.0.0/0
ACCEPT all — 0.0.0.0/0 0.0.0.0/0

Chain FWDO_trusted_allow (1 references)
target prot opt source destination

Chain FWDO_trusted_deny (1 references)
target prot opt source destination

Chain FWDO_trusted_log (1 references)
target prot opt source destination

Chain INPUT_ZONES (1 references)
target prot opt source destination
IN_public all — 0.0.0.0/0 0.0.0.0/0 [goto]
IN_public all — 0.0.0.0/0 0.0.0.0/0 [goto]

Chain INPUT_ZONES_SOURCE (1 references)
target prot opt source destination
IN_trusted all — 10.8.0.0/24 0.0.0.0/0

Chain INPUT_direct (1 references)
target prot opt source destination

Chain IN_public (2 references)
target prot opt source destination
IN_public_log all — 0.0.0.0/0 0.0.0.0/0
IN_public_deny all — 0.0.0.0/0 0.0.0.0/0
IN_public_allow all — 0.0.0.0/0 0.0.0.0/0
ACCEPT icmp — 0.0.0.0/0 0.0.0.0/0

Chain IN_public_allow (1 references)
target prot opt source destination
ACCEPT tcp — 0.0.0.0/0 0.0.0.0/0 tcp dpt:22 ctstate NEW,UNTRACKED
ACCEPT udp — 0.0.0.0/0 0.0.0.0/0 udp dpt:1150 ctstate NEW,UNTRACKED

Chain IN_public_deny (1 references)
target prot opt source destination

Chain IN_public_log (1 references)
target prot opt source destination

Chain IN_trusted (1 references)
target prot opt source destination
IN_trusted_log all — 0.0.0.0/0 0.0.0.0/0
IN_trusted_deny all — 0.0.0.0/0 0.0.0.0/0
IN_trusted_allow all — 0.0.0.0/0 0.0.0.0/0
ACCEPT all — 0.0.0.0/0 0.0.0.0/0

Chain IN_trusted_allow (1 references)
target prot opt source destination

Chain IN_trusted_deny (1 references)
target prot opt source destination

Chain IN_trusted_log (1 references)
target prot opt source destination

Chain OUTPUT_direct (1 references)
target prot opt source destination

Thank you,
Wilson

**Comment by randshell** [comment]
> clients connected to 10.1.1.X can’t.

Do you want to connect from this subnet to local openvpn clients on 10.8.0.X?

**Comment by wgalafassijr** [comment]
> 
> 
> > clients connected to 10.1.1.X can’t.
> 
> Do you want to connect from this subnet to local openvpn clients on 10.8.0.X?

Correct. I need connected clients on subnet 10.1.1.X  (that is my LAN) where i have others pcs and servers be able to connect to clients connected to openvpn on 10.8.0.X subnet.

**Comment by wgalafassijr** [comment]
It's working. My fault: forget to check windows firewall from client inside 10.8.0.X subnet.
