### ISSUE TITLE
server got hang after 1K user

### ISSUE THREAD

**Issue by naziur604** [angristan/openvpn-install#668]
after 1K user connect to the server its show this error
accept(5) failed: Too many open files (errno=24)
then server need to openvpn restart

server have 8core dedicate server
64G  ram
512SSD
1GBPS dedicate BW

on openvpn config
/16 ip pool
duplicate-cn
max-clients 500000

root@ns566624:~# uname -a
Linux ns566624 4.19-ovh-xxxx-std-ipv6-64 #1240349 SMP Mon May 11 08:31:47 UTC 2020 x86_64 GNU/Linux

root@ns566624:~# ulimit -n
900000

if you have any solutions please let me know

**Comment by randshell** [comment]
Can you try with `systemctl edit openvpn-server@.service` or `systemctl edit openvpn@.service` to edit the limits specifically for the openvpn service and add
```
[Service]
LimitNOFILE=1617596
LimitNOFILESoft=1617596
```
Run `sudo systemctl daemon-reload` before restarting the openvpn service again.

Source https://linuxx.info/error-too-many-open-files-in-linux/

**Comment by mercadeoshop** [comment]
I had the same issue before and the issue corrects adding: max-clients 4096 to the server.conf
