### ISSUE TITLE
Entropy

### ISSUE THREAD

**Issue by stormtrooper42** [angristan/openvpn-install#67]
Peut etre pourrais-tu inclure haveged au script histoire de booster l'entropy et donc generer les clefs plus vite ;)

**Comment by angristan** [comment]
C'est pas une mauvaise idée en soit, mais c'est un sujet sensible et un utilisateur peut utiliser autre chose pour générer de l'entropie. De plus on peut remettre en question la qualité de l'entropie générée par havaged (je l'utilise moi même mais bon). Je préfère garder le script relativement light
