### ISSUE TITLE
Fix github workflows

### ISSUE THREAD

**Issue by randshell** [angristan/openvpn-install#673]
@angristan Since last week there is an unnamed workflow on github actions that runs on [`on: watch`](https://github.com/angristan/openvpn-install/actions/runs/119979384), [`on:fork`](https://github.com/angristan/openvpn-install/actions/runs/120082137), [`on: issue_comment`](https://github.com/angristan/openvpn-install/actions/runs/122994721) and [`on: issues`](https://github.com/angristan/openvpn-install/actions/runs/123001340).

**Comment by angristan** [comment]
Thanks, I didn't notice. I don't understand if this is a configuration error on the repo or a github bug though

**Comment by robiiinos** [comment]
I think this issue can be closed as it has been resolved by https://github.com/angristan/openvpn-install/pull/647

**Comment by randshell** [comment]
The Linting actions stopped working too #680

**Comment by robiiinos** [comment]
> The Linting actions stopped working too #680

We managed to solve this issue (repository misconfiguration for remote actions); can you try force pushing your branch or wait for angristan to manually trigger actions ? Thanks

This should also solve the (Unknown Event) actions trigger; looks promising so far.
