### ISSUE TITLE
How to copy a user to another server?

### ISSUE THREAD

**Issue by dausruddin** [angristan/openvpn-install#678]
**Checklist**

- [ / ] I read the [README](https://github.com/angristan/openvpn-install/blob/master/README.md)
- [ / ] I read the [FAQ](https://github.com/angristan/openvpn-install/blob/master/FAQ.md)
- [ / ] I searched the [issues](https://github.com/angristan/openvpn-install/issues?q=is%3Aissue+)
- [ / ] My issue is about the script, and not OpenVPN itself

Hi. I have a question. Currently I maintain 2 servers due to bandwidth limitation. How do I generate a user on server A, then copy the user to server B so I can use 1 **.ovpn** for 2 servers?
I searched and read some files in `/etc/openvpn/` just in case I would just need to copy specific files, but I had no luck. Is there any way to do this without backing up the whole `/etc/openvpn` and restore on server B?

Thanks.

**Comment by dausruddin** [comment]
I took a look into the code and seems that there is multiple files in `easy-rsa` related to clients. Do I need to backup `easy-rsa` folder and restore it on server B every time I generated a new user on server A?

**Comment by randshell** [comment]
You can use rsync and it does this job for you. Read the post at https://www.tecmint.com/sync-new-changed-modified-files-rsync-linux/ and use the path `/etc/openvpn/`.

In the ovpn file you need to change the IP of the server if you want to connect to the second one.

**Comment by dausruddin** [comment]
Hi @randomshell. Thanks for the reply. Actually, I have been using rsync and scp to transfer files between servers. But since I disabled root user (I always have) and use new user with sudo access, I'm wondering if there is an easy way like "copy these 3 files" or something like that.

Also yes I know I can do sudo with rsync on remote server, but I would prefer these hacky stuff as my last resort.
Thanks

**Comment by randshell** [comment]
https://unix.stackexchange.com/questions/92123/rsync-all-files-of-remote-machine-over-ssh-without-root-user

**Comment by dausruddin** [comment]
Thanks. But please, read my reply above you. What you shared is basically what I said, although my English explanation might be bad.

Anyway, I think I'll just go with rsync since I don't think anyone will reply me with the list of files. Even there is someone, it would not be convenience to do.

Thanks for your help😁

**Comment by randshell** [comment]
> Thanks. But please, read my reply above you. What you shared is basically what I said, although my English explanation might be bad.

Do you mean that using rsync is hacky? For me it was the easiest and complete solution that automatically copies only modified files.

> Anyway, I think I'll just go with rsync since I don't think anyone will reply me with the list of files. Even there is someone, it would not be convenience to do.

I don't know why you avoid rsync but if you want the list of files I think the only one you need to copy to server 2, after adding or revoking a client on server 1, is `/etc/openvpn/crl.pem`.

You have to copy `/etc/openvpn/easy-rsa/pki` only if you want to have relevant information when you run the script on the second server, for example if you want the list of the issued clients. If you use the menu of the script only on server 1 and on server 2 you just need to connect and you don't run the script for information then you are fine without this folder.

Let me know if this works for you.

**Comment by dausruddin** [comment]
> Do you mean that using rsync is hacky? For me it was the easiest and complete solution that automatically copies only modified files.

Well, you need to edit sudoer file, type long command and stuff, of course I can set it up in advanced, but I don't feel like doing that on my mobile phone. I rarely have access to PC. That being said, I have them set up since I gave up after trackinf files created in the source and follow your advice.

> You have to copy /etc/openvpn/easy-rsa/pki only if you want to have relevant information when you run the script on the second 

Yeah, seems like using rsync would be much easier like you said

Thanks😁

**Comment by randshell** [comment]
> Well, you need to edit sudoer file, type long command and stuff, of course I can set it up in advanced, but I don't feel like doing that on my mobile phone.

Perhaps you can use rsync with crontab or copy the command you need in a bash script to make it easier to run?

**Comment by dausruddin** [comment]
Yeah, I'll figure it out later. Thanks a lot😁
