### ISSUE TITLE
Yandex DNS Resolver

### ISSUE THREAD

**Issue by ghost** [angristan/openvpn-install#68]
Please add  Yandex DNS resolvers as option. It fast for Russia and near to it countries 
`77.88.8.8`
`77.88.8.1`

**Comment by stormtrooper42** [comment]
Yes but for privacy is not the best option :/

**Comment by ghost** [comment]
¯ \ _ (ツ) _ / ¯

**Comment by stormtrooper42** [comment]
anyway i think is a great options for who leave near russia and who don't care about privacy :)

**Comment by Kcchouette** [comment]
There's 2 solutions:
1. if @Angristan is ok, adding it to the main script
2. create your own fork to enter your own DNS (something like that: https://github.com/Kcchouette/OpenVPN-VPS/commit/3dbb6d38f95048476a5049930d842a7046b12444)

**Comment by ghost** [comment]
You can add any DNS to your server.conf, after @Angristan 's script has completed.

**Comment by angristan** [comment]
>You can add any DNS to your server.conf, after @Angristan 's script has completed.

Indeed, your are free to add whatever DNS server you want !

**Comment by angristan** [comment]
Added https://github.com/Angristan/OpenVPN-install/commit/a2a3bfc605d104e363bdd1b2fde4cf94a6636fa3
