### ISSUE TITLE
How can I enable client-to-client talk?

### ISSUE THREAD

**Issue by diyaa59** [angristan/openvpn-install#696]
**Checklist**

- [ ] I read the [README](https://github.com/angristan/openvpn-install/blob/master/README.md)
- [ ] I read the [FAQ](https://github.com/angristan/openvpn-install/blob/master/FAQ.md)
- [ ] I searched the [issues](https://github.com/angristan/openvpn-install/issues?q=is%3Aissue+)
- [x] My issue is about the script, and not OpenVPN itself

**Is your feature request related to a problem? Please describe.**
clients on the OpenVPN server cant talk to each other like for example if 10.8.0.2 is trying to ping 10.8.0.3 all the packets would be lost. therefore it is important to enable client-to-client support in the server configuration!

**Describe the solution you'd like**
an option in the script that would allow a user to enable client to client talk.

**Additional context**

![image](https://user-images.githubusercontent.com/26883110/87237236-f9c02100-c3b0-11ea-8646-1c6b84c05cee.png)

**Comment by diyaa59** [comment]
It worked for me in this way:

I opened the `sudo  nano /etc/openvpn/server.conf` file and added the following line to it `client-to-client` and restarted the server `sudo service openvpn restart`now it is working no problem.

![image](https://user-images.githubusercontent.com/26883110/87237684-a8b32b80-c3b6-11ea-917e-34a469820e13.png)

**Comment by randshell** [comment]
> It worked for me in this way:

Take the time to read the FAQ next time please.

@angristan might know why it isn't enabled by default.

**Comment by angristan** [comment]
Well, client-to-client communication is simply not the main goal of the script. If I give a client config to a friend I don't want them to access my device through the VPN. IMO this is just a sane default! Good thing we address this in the FAQ, which apparently people don't bother reading :)

**Comment by randshell** [comment]
> If I give a client config to a friend I don't want them to access my device through the VPN.

This means the iptables rules used shouldn't allow access to the private LAN. From the FAQ, to access the LAN you only need to push its routing, so it doesn't really match the friend use case. What did I miss?

> client-to-client communication is simply not the main goal of the script

I agree.
