### ISSUE TITLE
How to change the connection to a different Public IP address 

### ISSUE THREAD

**Issue by Seeder101** [angristan/openvpn-install#7]
hi, i have a question regarding the public ip address, lets say I have the main IP address of the vps or dedi and set it up with the installer, then rents a new IPv4 address set it up and everything and want the user for example to use it instead of the main IPv4 address ? 
I came to simple idea and is to change the "remote IP" in the ovpn certificate ? does that helps? 
because I didn't purchase a new ipv4 yet 

thank you

**Comment by angristan** [comment]
You can't change the IP adress remotely but you can use a domain or subdomain instead :)

**Comment by Seeder101** [comment]
Angristan, thank you for your response...I think you didn't get my point...
now, lets say I have 2 IP addresses active on my vps and I wants to run for example one IP for a user and the other one for another user...if you opened the ovpn cert you will find remote argument...with the main IP address of your server, if I change that remote argument to the other sec IP and connect, is it gonna shows the sec IP or as you modify the remote argument?

NOTICE: the IP is failover

**Comment by angristan** [comment]
I think you'll have to use 2 different ports and 2 different private network, but I'm not sure. Anyway, this is not related to this script, so I'm closing the issue.

**Comment by Seeder101** [comment]
the port can run the same for every unique IP, anyway there is not private network I'm talking about Public IPs 
I will try that and give feedback about it...Thanks ;)
