### ISSUE TITLE
Adblock

### ISSUE THREAD

**Issue by hodorisking** [angristan/openvpn-install#70]
Is it possible to implement dnsmasq to filter ads when client uses the VPN? Would you guide me in that direction? Thank you!

**Comment by technicalpyro** [comment]
https://github.com/pi-hole/pi-hole/wiki/OpenVPN-server:-Installation 

use whatever VPN installation you choose and run pihole alongside it

**Comment by hodorisking** [comment]
Thank you @technicalpyro  Wouldn't that make the ip address of the server to be a public DNS that blocks ads? I want to avoid that.

**Comment by technicalpyro** [comment]
no.  there are a few features that prevent this.  the first being firewall rules i myself have a droplet running pihole and openVPN it is not a public resolver.  dnsmasq allows three settings within this project 
Listen on all interface and respond to all queries
listen only on the designated interface
listen on all interfaces but only respond if the device requesting is one hop away or less

The only thing i have that is public facing is the web interface but that can be easily disabled as well and is still password protected regardless

also worth noting it can be a little tricky to set up in terms of the VPN server options and a couple other things but if following the wiki i pasted above has you struggling i am willing to help as much as i can
