### ISSUE TITLE
how do I automatically install with Vultr Startup Scripts

### ISSUE THREAD

**Issue by Nasterman** [angristan/openvpn-install#704]
Hello

I want to ask, is there an automatic script without selecting options 1, 2, 3, 4? because I want to install the vultr startup script, so after I tried to make vps after waiting for OpenVPN running itself. because after I try the script I have to press enter until the process is complete. so I want the default script without pressing my keyboard?

**Comment by randshell** [comment]
I don't know about the Vultur Startup Scripts specifically but you can install OpenVPN without pressing enter by exporting the required variables https://github.com/angristan/openvpn-install#headless-install. You only have to run it with enter once so you know what options you want and what values to export.
