### ISSUE TITLE
Data encryption with cipher AES-512-CBC

### ISSUE THREAD

**Issue by perfectpeach** [angristan/openvpn-install#705]
Hiya @angristan and @randomshell and all security enthusiasts,

There is a possibility to implement **_data encryption cipher AES-512-CBC_** as its described [here](http://www.ijircce.com/upload/2014/march/22_AES.pdf) And it needs possibly a slightly modified version of OpenVPN+OpenSSL. Could you please implement this in your amazing auto-installer and provide me instructions on how shall I proceed to use the AES-512-CBC data encryption cipher?

Update 10/8/2020: It would be nice if we can implement this data encryption cipher alongside TLS 1.3?

Tnx and best of luck

**Comment by randshell** [comment]
Using TLS 1.3 and the related recommended ciphers should be secure without using 512 bits ciphers.

If you don't agree you can use WireGuard with a pre-shared key for post quantum security :smile:

**Comment by perfectpeach** [comment]
Hiya @randomshell 


Thanks. May please confirm as I installed the OpenVPN by this auto-installer and I set the security and data encryption cipher and data control channel cipher to maximum, then for being sure that only TLS 1.3 is used and not TLS 1.2, setting code below only in client config file will be enough?
**_tls-version-min 1.3_**

I mean shall I set anything related to TLS 1.3 at a minimum in the Server-side config file too?

Tnx and best of luck

**Comment by perfectpeach** [comment]
Update:

I confirm that while I updated the min TLS 1.2 to 1.3, as below:
**_tls-version-min 1.3_**
I couldn't connect to my VPS on the OpenWRT router. Does this something OpenWRT relate or even if I use this OpenVPN profile in Windows 10 or Linux Tails, I will encounter this unable to connect issue as well? I mean there is something wrong on where, and where its the error coming that I can't connect on OpenWRT? 
Do you think on DDWRT or Windows 10 or Linux Tails the same unable to connect issues occurs as well?

Tnx and best of luck

**Comment by perfectpeach** [comment]
**Update I**:

I get this error on Windows 10 x64 pro:
 **_TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
TLS Error: TLS handshake failed_**
Where is the issue? Is there something that I shall configure on install in CentOS 7.5 x64 VPS?

Tnx and bets of luck

**Comment by perfectpeach** [comment]
**Update II**:

I got this error on another Windows 10 x64 pro machine, on OpenVPN error log:
_**Options error: unknown tls-version-min parameter: 1.3
Use --help for more information.**_

But based on [here](https://forums.openvpn.net/viewtopic.php?f=23&t=26776#p80131) the code of **_tls-version-min 1.3_** is correct?
How shall I fix this please?

Tnx and best of luck

**Comment by randshell** [comment]
> tls-version-min 1.3

This script doesn't support TLS 1.3 settings yet, but because we use `tls-version-min 1.2` in the server configuration then OpenVPN can negotiate TLS 1.3 automatically if available https://github.com/angristan/openvpn-install/issues/637#issuecomment-619457889.

If you want to use TLS 1.3 only connections then yes, you write `tls-version-min 1.3` in the client config or if you want to apply it to all clients write it in the server config. The best available cipher will be auto negotiated, so you don't have to do anything else. You can verify the client logs to see what cipher are you using exactly.

> I couldn't connect to my VPS on the OpenWRT router.

OpenWRT may be slow to update its OpenVPN/OpenSSL package, you're better connecting from an OS other than a router.

> Options error: unknown tls-version-min parameter: 1.3
Use --help for more information.

Try with OpenVPN Community from this link https://openvpn.net/community-downloads/

**Comment by perfectpeach** [comment]
**Update III**:

I tested two approaches below:

1) I tested android client official 'OpenVPN connect' and I modified the config file of .ovpn content to 'tls-version-min 1.3', the results were, I will be able to connect to the VPS server, but the server or OpenVPN-Connect official app, either of these refused to accept the client config file request for 'tls-version-min 1.3' as I verified this on Android OpenVPN-Connect logs.

2) I set the settings for official OpenVPN-Connect Android app to TLS minimum>1.3, and with or without the line of 'tls-version-min 1.3' in the .ovpn config file, I couldn't connect either.

> tls-version-min 1.3
> This script doesn't support TLS 1.3 settings yet, but because we use tls-version-min 1.2 in the server configuration then OpenVPN can negotiate TLS 1.3 automatically if available #637 (comment).

Unfortunately, this failed as I have tested this in the two approaches above and it didn't work? What shall I do now?

> Try with OpenVPN Community from this link https://openvpn.net/community-downloads/

In my previous comment I mentioned as 'Update II' and error log associated for the test, I used the same OpenVPN windows client from the official community version, it failed to connect as I mentioned in 'Update II' comment. ?


I'm confused as I don't get if I need to update OpenSSL on my CentOS 7.5 x64 to get TLS 1.3 works for me or what? As I just recently updated the CentOS 7.5 x64, and I updated the OpenVPN separately and updated the CSF+LFD separately as well. Thus I believe I shall be on the latest OpenSSL version now? 
The thing is, I don't get if my server is on a lower version of OpenSSL that this may cause that I can't use the TLS 1.3 or else what is the reason for these errors in three clients, official Android OpenVPN-connect and official windows community edition alongside the OpenWRT all giving me similar errors as I mentioned. 
As you mentioned if I use the official OpenVPN community version on Windows 10 x64 pro, it should work with setting the 'tls-version-min 1.3'  in .ovpn client config file, but it didn't work for me?

May please advise me on what step shall I take to make TLS 1.3 work for me now? Is the OpenSSL is the only thing that can potentially be associated with causing this error or there are other steps that I shall check them as well? Please do advise me and I test them and provide the error logs. My CentOS 7.5 x64 is configured to don't keep logs, but f there is a way to produce the log on terminal commands, please advise and I will post them here?


Tnx and best of luck

**Comment by randshell** [comment]
I didn't play at all with TLS 1.3 so I don't really know what to say.

@TinCanTech clarified that is not 100% possible yet https://github.com/angristan/openvpn-install/issues/637#issuecomment-665352652

**Comment by perfectpeach** [comment]
Hiya @randomshell 


Thanks for your reply. I see there are alpha releases and beyond of OpenSSL that supporting TLS1.3. Also, the OpenVPN community content shows that 'tls-version-min 1.3' is an option, thus I believe there is a possibility to implement this at this stage as link [here ](https://community.openvpn.net/openvpn/ticket/1118?__cf_chl_jschl_tk__=e9595314d7e262cb0fe6487e847d5f42cffcf2d1-1596066358-0-AXNhKUOXWaVcGmnaPVXgK6G_s62nIY28WZMYBnncu5dkAJoBH4zHU8MYZaG_KhWQIE3mJE1nxTVAycssViMUcxd-H6Ry_sozZhtunJ6ptlFcde07mcbw6UOrFSi3ASUF-CLiYN4K5GaN3-r1erkyhAMfrqRy9WCdtSnIZHHfja_E5lPzItihPTrYV4bYP8ukT4Uss5KvZQuuUHUsKBqAyj3alL5anUANzcyRgfi12yRW12efhOvo8kmBUxG7wNq8UYytOBAttVqL_ZhWJLeYTGturXO3Jr-w8qSigfyFgz0Y#ticket)confirms the OpenVPN 2.4 can use TLS 1.3. If I search in the net and find some solutions, you may able to advise me which approach shall I take if I want to apply/implement them on my CentOS 7.5 x64, please?

I tested today with the latest OpenVPN official community version of OpenVPN windows 10 x64 client and the error below was in the logs:

**_TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
TLS Error: TLS handshake failed_**

I see the OpenSSL that is implemented in the OpenVPN official community edition is 'library versions: OpenSSL 1.1.1f' from connection logs that confirm both OpenVPN and OpenSSL can implement TLS1.3 in my opinion? I respect your professional opinion and I understand you mentioned above that in the end, it's not possible to 100% implement this TLS 1,.3, but considering my statement above with facts I mentioned about OpenVPN+OpenSSL may you please confirm this if it's correct?

If you may advise me, I search the net and find implementation solutions, like the one [here](https://dev.to/bidhanahdib/how-to-enable-tls-1-3-in-nginx-with-openssl-centos-7-4f4b) confirms the CentOS7 can use the TLS1.3, and while OpenSSL at least alpha releases can support TLS 1.3, and this 'library versions: OpenSSL 1.1.1f' is implemented in OpenVPN official community Windows 10 x64 client, then I personally think this is possible and if you may kindly advise me on the approaches I find on the internet, I can implement this with your help?

Do you think if I post a request on OpenVPN official community forum, they may able to advise me better? Or I can get advice from the and inform you of implementation idea, and you may able to kindly advise on the final implementation approach, if you may please?


Tnx and best of luck

**Comment by perfectpeach** [comment]
**_Update IV:_**

I checked my CentOS 7.5 x64, and I have the low installed:
**_SSLv3
TLS 1.2_**
Thus I'm going to install the OpenSSL newest version that supports the TLS 1.3 now. I'll report for duty when I installed and tested it :) lol

Tnx and best of luck

**Comment by perfectpeach** [comment]
**_Update V:_** 


I'm updating/Upgrading CentOS 7.5 x64 and CSF and OpenVPN and Wireguard before installing OpenSSL. Could you please confirm if 'yum upgrade'  will fully update/upgrade the Wireguard and all it packages and components or it needs a different command to update/upgrade in CentOS 7.5 x64? 

Tnx and bets of luck

**Comment by TinCanTech** [comment]
I know what I would do ..

**Comment by perfectpeach** [comment]
**_Update VI:_** 

I updated the OpenSSL to the latest version through a complex process and didn't encounter any error in the installation nor test process. In the end, I tested the OpenSSL installed TLS version as I did before while it was on OpenSSL/TLS 1.2, but the system does not give me the latest OpenSSL installed version. The error I got while requesting the OpenSSL/TLS version is:
**_-bash OpenSSL: command not found_**

I'm not sure if I have done anything wrong in the installation of OpenSSL/TLS1.3 or after installing the OpenSSL/TLS1.3 the old commands do not work to check the version? Is there any way to troubleshoot this as seems system des did not recognize OpenSSL as a command? Could you please kindly provide me some troubleshooting notes that I can test and report here, thus you may able to advise me where am I wrong?

Also, I shall confirm that OpenVPN-connect on the Android is successfully connecting and giving me the TLS version of TLS1.2 in the logs. While the CentOS 7.5 x64 server, while I requested the OpenSSL version, it does not recognize the OpenSSL as a command as the error above occurred? Could you please kindly advise me on this, how shall I proceed and troubleshoot?

Does the OpenVPN need to be reinstalled to be able to support the OpenSSL/TLS1.3 or just adding the 'tls-version-min 1.3' in client profile shall make everything work without the need for the reinstallation of OpenVPN or changing anything on the server config file? What procedure shall I take for this?

I DM you by blondepeach@... the series of code I used for the installation of OpenSSL/TLS1.3. I send you some info about the output I see in the terminal. I can't find out where is the problem? Do you mind reading the code there and reply to me there or here, please?

Tnx and best of luck

**Comment by perfectpeach** [comment]
Update VII:


I fixed the OpenSSL issue now and proceeding to the next step to utilize whether OpenVPN can be used without recompile or it nee reinstallation or recompilation for OpenSSL/TLS1.3. I can see there is the list blow under OpenSSL versions on my CentOS 7.5 x64:
**_SSLv3
TLSv1
TLSv1.2
TLSv1.3_**

I'm going to test and will report here accordingly. Please do advise me on the need for the reinstallation of OpenVPN/Wireguard is required or not?

Tnx and best of luck

**Comment by randshell** [comment]
- Yes, OpenVPN would need a recompilation with the new build OpenSSL
- If you get openssl command not found you didn't symlink the binary to a location in the `$PATH`. `/usr/local/bin` should be good to use.
- You can avoid compiling OpenSSL manually and recompiling it on updates by upgrading to Centos 8 where TLS 1.3 is supported in the repositories.
- To use TLS 1.3 with all clients add `tls-version-min 1.3` in the server configuration.
- I don't know if TLS 1.3 is supported on Windows. Anyway if you care about using the latest encryption but you're still using this privacy invasive OS I believe you're doing it wrong, no offense :smiley:

If I missed to answer to something you can quote the question again and I will try to answer.

**Comment by perfectpeach** [comment]
Hiya @randomshell 



Thanks for your reply. About below,
>Yes, OpenVPN would need a recompilation with the new build OpenSSL

How shall I recompile OpenVPN 2.4? [Here](https://openvpn.net/community-resources/reference-manual-for-openvpn-2-4/) in the manual, there is no instruction for 'recompile', also I installed the script by @angristan 's installer. How shall I do this, may please advise me on how shall I recompile the OpenVPN 2.4 for this purpose, whether by auto-installer or manually? 
Maybe 
`emerge -av openvpn`
or
`emerge -v openvpn`
?
Or shall I use the auto-installer script options if there is the exit? 

I remember I used a code to nullify the logs and many similar tweaks for hardening and privacy(no logs). If the OpenVPN is recompiled, shall I reapply/reconfigure all the privacy and security tweaks from scratch or there is a way to save them? Assuming the server side's .conf file will be updated after recompile, I can't just replace the server.conf after recompile or can I? Could you please send me the code that nullifies all OpenVPN server-side logs and make it privacy-minded? In case my settings get erased after recompile? I'd prefer a list of all applicable settings that can make this server-side privacy-minded without any logs and is there are any settings for hardening beyond what @angristan did, I'd happy to have it, please?

> If you get openssl command not found you didn't symlink the binary to a location in the $PATH. /usr/local/bin should be good to use.
You can avoid compiling OpenSSL manually and recompiling it on updates by upgrading to Centos 8 where TLS 1.3 is supported in the repositories.

Thanks. It's fixed now. I have all below listed while I made an inquiry about this from CentOS 7.5 x74, as below:
**_SSLv3
TLSv1
TLSv1.2
TLSv1.3_**


>To use TLS 1.3 with all clients add tls-version-min 1.3 in the server configuration.

Shall I replace the exact line here  **_/etc/openvpn/server.conf_** in the server.conf from TLS 1.2 to TLS 1.3, just by replacing character '2' to '3' in the relevant line, please?

>I don't know if TLS 1.3 is supported on Windows. Anyway if you care about using the latest encryption but you're still using this privacy invasive OS I believe you're doing it wrong, no offense 😃

Thanks for your concerns. I really appreciate it. But while I'm a Journalist and need privacy, I'm a sketch artist and model and more as well, thus I need my graphic software packages like most of Adobe, Corel, and many sound recording and editing and mixing and creative software installed on OS. Most of these companies' software does not have Linux installable versions as per my knowledge? Also, these software packages that I bought for Windows 10 OS, the license is under Windows 10 OS, thus I don't know if it's possible to transfer my licenses for this software's from Windows 10 OS to Linux? My laptop support USB 3, USB3 3.1, USB C thus if it's possible to run Tails on VM over installed Tails OS, on a separate external SSD hard-disk, this will solve my issue. But I'm not sure if it's possible to access both Windows 10 pro x64 workstation OS alongside the Tails running on VM over installed Tails on an external SSD hard-disk at the same time without the need for restarting the laptop or not? e.g. the idea like while we connect two PC case to one monitor and we can use a switch on the monitor to select the source, but this time booting two OS, one Tails from external SSD hard-disk, one Windows 10 OS from Laptops hard-disk at the same time on a laptop, is it possible or a reliable solution exists or not? If its any help, I shall mention that I have two NVMe SSD M2 WD-Black as RAID and one SSD as the third storage of my laptop. But I have lots of data and downloads and I don't like to use either of these three internal storage for Tails. I'd prefer an external SSD on USB-C/USB-3.1/USB-3 if it's possible, please?
At the moment I'm using the OpenVPN/Wireguard on OpenWRT/DDWRT and running Windows 10 OS firewall-protected and VM on Windows OS to run the Tails ISO. I'm happy if you advise me on improvement suggestions on this, for privacy and security-minded aspects?

Also, I'm using the VM on Windows 10 Pro x64 Workstation, Virtualbox one, display settings as 'VMSVGA' 128/128MB, and 3D acceleration enabled, but my Tails screen is not as sharp as I want. I have Nvidia Quadro on the laptop and Intel UHD as secondary GPU and Windows on Nvidia GPU is very sharp and fast and applications as well. But this Tails on VM is very blurred and I noticed my eyes getting red and painful while I web-browsing on Tails on its low-end graphic display with the blurred screen. This is a comparison of the web-page in Windows OS on VM-Virtualbox installed on Windows 10 OS x64 Workstation and other one Tails on VM over Windows OS as below. Neither of these is my actual Windows 10 installed OS, both are running on VM-Virtualbox as below:
https://prnt.sc/twyklr
https://prnt.sc/twykqu
Below is how  I see the Github code in Windows 10 OS:
https://prnt.sc/twzai2
I want my text and graphic and web-pages to be as clear as this one in both Tails and even if I use the Windows OS on VM-Virtualbox? Do you know how may I do this in Tails at least, please?

I tried to install the NVidia display drivers for Tails ISO running on the VM-Virtualbox, but I believe the VM-Virtualbox does not support transferring my NVidia graphic card to the virtual OS, and the virtual OS only get a virtual graphic card as{ 'VMSVGA' 128/128MB, and 3D acceleration enabled} at maximum. Any suggestions on how shall I have a better graphic in the Tails running on VM-Virtualbox? Also, I shall mention that I'm running Tails as the root user to be able to apply a better routing for TOR file 'torrc', otherwise the normal user can't access this file. Thus I thought I can install the NVidia graphic card driver over the RAM as I'm running Tails as ISO without any hard-disk(even 256 encryption for hard-disk is not over the using only Tails ISO over VM-Virtualbox)?

May please advise me on these?


Tnx and best of luck

**Comment by randshell** [comment]
> How shall I recompile OpenVPN 2.4? Here in the manual, there is no instruction for 'recompile', also I installed the script by @angristan 's installer. How shall I do this, may please advise me on how shall I recompile the OpenVPN 2.4 for this purpose, whether by auto-installer or manually?

Just build again openvpn like you did with openssl but link it with the new openssl version that supports TLS 1.3. Something like this https://stackoverflow.com/questions/38985889/build-openvpn-with-specific-openssl-version. Again, I'd suggest to upgrade to Centos 8 so you don't have to worry about keeping these manually built packages up to date. Centos 8 repository has a newer openssl that should be with TLS 1.3 support already.

>  just by replacing character '2' to '3' in the relevant line, please?

Yes and verify all your devices support TLS 1.3.

---

- First you really need to assess your situation and decide what to do for yourself https://ssd.eff.org/en/module/your-security-plan
- It's not possible to run multiple OS on the same PC without a virtualization software like VirtualBox or virtualization OS like Xen Server https://phoenixnap.com/kb/what-is-hypervisor-type-1-2
- If you're using a Tails VM on Windows it's better than a VPN or Tor Browser on Windows because you learn to compartmentalize. Still if Windows is compromised or just sends sensitive diagnostics to Microsoft a Tails VM can't do much. You would need to have a Tails installation on another disk to boot from to completely separate the 2 OS. See "Security considerations" at https://tails.boum.org/doc/advanced_topics/virtualization/index.en.html
- Windows has hidden settings so even if you disable everything from the Settings app there might be sensitive stuff it does.
- You use graphics/sound software so I don't recommend virtualizing Windows for performance reasons.
- I don't know about the sharpness.
- You can pass a graphic card to a virtualized OS if you have another graphic card for your OS.
- It's not recommended to change some settings of torrc: "You get the best security that Tor can provide when you leave the route selection to Tor; overriding the entry / exit nodes can mess up your anonymity in ways we don't understand. "
- Inform yourself more about how TOR or Tails protect you https://2019.www.torproject.org/docs/faq.html.en#anonsec

I don't know what else to say, ultimately you should assess your situation and research for yourself. Making a plan (the link I pasted in the first entry https://ssd.eff.org/en/module/your-security-plan) it's essential because otherwise you would fall down a rabbit hole.

Keep in mind that I'm not an expert so please do your own research :smiley:

**Comment by angristan** [comment]
Closing as this went a bit off topic 😄
