### ISSUE TITLE
Add support for DUO Security

### ISSUE THREAD

**Issue by dudefoxlive** [angristan/openvpn-install#707]
Recently I have been wanting to add 2FA to my OpenVPN. I used this script to install it and since I use DUO Security for RDP 2FA protection on my windows systems I thought I would add it to OpenVPN since there is an option. I went through all the steps and it keeps failing to auth correctly since it pulls the username from the common name of the certificate. Is there anyway that maybe we could fix this so that it works? I am sorry if this is not the correct place to post this but since I use this script I though it might be the first place to start.

**Comment by randshell** [comment]
> I used this script to install it 

Their guide at https://duo.com/docs/openvpn says to install their customized OpenVPN package.

**Comment by dudefoxlive** [comment]
> Their guide at https://duo.com/docs/openvpn says to install their customized OpenVPN package.

I installed it but the problem I have is that it pulls the username from the common name of the certificate. Basically what ever I put for the username is ignored. Since the script is creating the certificates I don't have the ability to specify a username.

**Comment by randshell** [comment]
> Since the script is creating the certificates I don't have the ability to specify a username.

> I went through all the steps and it keeps failing to auth correctly since it pulls the username from the common name of the certificate

The Common Name of the client is the same as the client name you write when you add a new user. Is this of any help? I didn't set up my OpenVPN with 2FA so I wouldn't know the details.

**Comment by dudefoxlive** [comment]
>The Common Name of the client is the same as the client name you write when you add a new user

I figured this was the case. Now one question i have is how would this play if i wanted to say connect my iphone and my ipad or laptop at once? since one profile and only be used on one device at a time this could be a problem.

**Comment by randshell** [comment]
> since one profile and only be used on one device at a time this could be a problem.

I thought that would be the case... If you don't have too many devices, you could enroll new users from DUO's panel. For the email use yours but write dots in it to make it appear like a new one https://support.google.com/mail/answer/7436150?hl=en.

**Comment by dudefoxlive** [comment]
>If you don't have too many devices, you could enroll new users from DUO's panel

That would require multiple email addresses. I think DUO allows setting alias's so I might try that and hope that it works. 

EDIT: Setting up alias's worked and after creating specific names things are working fine.

**Comment by Shootify** [comment]
> > If you don't have too many devices, you could enroll new users from DUO's panel
> 
> That would require multiple email addresses. I think DUO allows setting alias's so I might try that and hope that it works.
> 
> EDIT: Setting up alias's worked and after creating specific names things are working fine.

can you help me setting this up?
