### ISSUE TITLE
Change the static server IP to a variable provided by the user during install

### ISSUE THREAD

**Issue by grizzy255** [angristan/openvpn-install#718]
***Feature Request***

**Checklist**

- [ ] I read the [README](https://github.com/angristan/openvpn-install/blob/master/README.md)
- [ ] I read the [FAQ](https://github.com/angristan/openvpn-install/blob/master/FAQ.md)
- [ ] I searched the [issues](https://github.com/angristan/openvpn-install/issues?q=is%3Aissue+)
- [ ] My issue is about the script, and not OpenVPN itself

**Is your feature request related to a problem? Please describe.**
Trying to install OpenVPN server on multiple machines. Realised each server has a hardcoded IP 10.8.0.0/24 causing conflicts when a client connects.

**Describe the solution you'd like**
Users to be able to specify the IP address of the server during installation.

**Describe alternatives you've considered**
In my case first I tries changing the IP address in the server.conf file after a default install and realised that traffic wouldn't pass through. It is because the script used the hardcoded IP to create NAT and FORWARDING rules.
I ended up manually changing the IP address of the the server in the script everywhere and then reinstalling again. 
It would be great it the server IP converted to a client provided input.

Thanks for the great work!

**Comment by randshell** [comment]
Yes, it would be great. PR #550 addresses this issue.

**Comment by angristan** [comment]
Yes, there is already an open issue for that: https://github.com/angristan/openvpn-install/issues/153
