### ISSUE TITLE
Update to script required for CentOS 8.2 - no longer works

### ISSUE THREAD

**Issue by zebcarnell** [angristan/openvpn-install#719]
The script doesn't place config files in the correct directory for CentOS 8.2 or RHEL 8.2 (when using the OpenVPN package in EPEL).

Ideally it would automatically place config into /etc/openvpn/server/

Workaround: manually cp files from /etc/openvpn/ into /etc/openvpn/server/

**Comment by zebcarnell** [comment]
Edit: Confirmed effects CentOS 8.2 as well

**Comment by randshell** [comment]
Duplicate of #605.

Please search the issue tracker before opening new ones.

**Comment by zebcarnell** [comment]
Apologies, was originally focused on RHEL only before confirming CentOS also had the issue.
Closing
