### ISSUE TITLE
NAT type Strict and slow speeds

### ISSUE THREAD

**Issue by Ammar7347** [angristan/openvpn-install#72]
Hi,
I use the Vpn mostly to play online games to hide my IP so that I don't get DDoSed. Everything works fine except for 2 problems. One being the speeds i get are very low as my VPS has 1Gbit connection and iperf and speedtest-cli shows above 1gbps up and down speed and I usually get 15-20 Mbps max. Lastly, most annoying and important problem I get is the NAT issue. All online games requires Open(NAT type 1)  which I do get without VPN but the instant I turn on my VPN, NAT becomes Strict which basically means I can't host matches/lobbies whatsoever and most importantly, can't play games without issues.

P.S. I get Open NAT type on all paid VPN's and few free VPN's running OpenVPN.

Any help would be highly appreciated.

**Comment by DrXala** [comment]
@Ammar7347,
What's the bandwidth between your battlestation and your VPS when your VPN is down? 15-20Mbps?

For your NAT problem, I think you need to open the incoming stream to your VPS for your battlestation. What's the game where you would like to host matches/lobbies ?

**Comment by Ammar7347** [comment]
@DrXala thanks for the reply. I think I don't completely understand what you were trying to convey. My VPN never goes down and I get constant speeds every time of about 15-20 Mbps and my home connection is of 60 Mbps whereas VPS has a connection of 1 Gbps. So, I think I should be getting above 50 Mbps as I have 60 Mbps bandwidth at my end. Secondly, how can I open the incoming stream to my VPS for my battle station? I usually play Rainbow Six Siege, COD's and Battlefield games.

**Comment by DrXala** [comment]
Ok! You have not indicated the bandwidth of your internet, then I thought it was 15-20Mbps ;) I have no idea for this problem... Maybe, you can fix this with faster encryption degree.

You can open the incoming stream with iptables. In Rainbow Six Siege exemple, you need UDP/6015 ([source](https://support.ubi.com/en-GB/Faqs/000023138/Connectivity-issues-in-Rainbow-6-Siege)).
You can add this port forwarding rule on your VPS:
```
iptables -t NAT -I PREROUTING -i $WAN -p udp --dport 6015 -j DNAT --to $CLIENT
iptables -I FORWARD -p upd -d $CLIENT --dport 6015 -j ACCEPT
```
$WAN = name of internet interface of your VPS (ie: eth0)
$CLIENT =  VPN IP address of your battlestation (ie: 10.8.0.10)

See [this paper](https://support.ubi.com/en-GB/Faqs/000023138/Connectivity-issues-in-Rainbow-6-Siege) for more informations on port forwarding with iptables.

You have many tools for diagnose this problem: netcat, tcpdump etc
```
nc -z -w 5 -u $IPVPS -v
```

**Comment by Ammar7347** [comment]
I am getting this error while trying to follow the steps you mentioned earlier with iptables. 
```
iptables v1.4.21: can't initialize iptables table `NAT': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.

```
P.S. Will disabling the iptables completely help me in this situation? I don't need iptables as I own VPS from anti-DDoS hoster who have their own firewall. If so then any easy way to disable the iptables which should remain disabled forever even on VPS restart.

Thanks

**Comment by DrXala** [comment]
No, if you disabling completely iptables, your battlestation will no longer have internet. Iptables translate the plublic IP of your VPS for your battlestation connected in VPN ([NAT](https://en.wikipedia.org/wiki/Network_address_translation)). The router of your ISP use this same method. And the port forwarding is an application of NAT that redirects a communication request from one address and port number combination (VPS) to another (Battlestation). So this is not a firewalling problem but NAT yes.

If I want to connect at your battlestation via UDP/6015, I can't because my request will not be redirected to your battlestation. She will come on your VPS and it will not answer.

Also, do not confuse anti-ddos and firewalling. Your Anti-DDOS hoster does not protect you from other attacks.

Can you paste your iptables config?
```
iptables -L -vn --line
# and
iptables -t nat -L -vn --line
```
You can replace IP addresses by `xx.xx.xx.xx` and `yy.yy.yy.yy`. It's not important.
And the result of:
```
lsmod | grep nat
```

**Comment by Ammar7347** [comment]
```
Chain INPUT (policy ACCEPT 4238K packets, 4105M bytes)
num   pkts bytes target     prot opt in     out     source               destination
1      428 35417 ACCEPT     tcp  --  *      *       127.0.0.1            0.0.0.0/0            tcp dpt:2008
2        1    40 DROP       tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:2008

Chain FORWARD (policy ACCEPT 39106 packets, 12M bytes)
num   pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy ACCEPT 19M packets, 4109M bytes)
num   pkts bytes target     prot opt in     out     source               destination

```
and

```
Chain PREROUTING (policy ACCEPT 27695 packets, 1591K bytes)
num   pkts bytes target     prot opt in     out     source               destination

Chain INPUT (policy ACCEPT 26884 packets, 1505K bytes)
num   pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy ACCEPT 36377 packets, 2550K bytes)
num   pkts bytes target     prot opt in     out     source               destination

Chain POSTROUTING (policy ACCEPT 36377 packets, 2550K bytes)
num   pkts bytes target     prot opt in     out     source               destination
1      809 86159 SNAT       all  --  *      *       10.8.0.0/24          0.0.0.0/0            to:XX.XX.XX.XX
```
and 

```
xt_nat                 12681  1
iptable_nat            13011  1
nf_nat_ipv4            13263  1 iptable_nat
nf_nat                 21841  3 nf_nat_ipv4,xt_nat,iptable_nat
nf_conntrack           97201  4 nf_nat,nf_nat_ipv4,iptable_nat,nf_conntrack_ipv4
ip_tables              27116  2 iptable_filter,iptable_nat
x_tables               34802  4 ip_tables,xt_tcpudp,xt_nat,iptable_filter
```

**Comment by DrXala** [comment]
Why you have no forward rule for your VPN?
You need to add this rule:
```
iptables -A FORWARD -s 10.8.0.0/24 -j ACCEPT
# and
iptables -A FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
```

The error from adding port forwarding rule, it's probably because your VPS is an OpenVZ virtual machine. OpenVZ support basic iptables rules but not those who use the nat table.

**Comment by Ammar7347** [comment]
I've added the rules. I've 2 KVM VPS's and 2 OpenVZ VPS's and I get the same NAT type problem using OpenVPN. 
I've tried the NAT table on KVM servers as well but I get the same error mentioned in one of my aforementioned reply.

**Comment by DrXala** [comment]
Ok, for your kvm servers, check if nat kernel module is loaded with `lsmod | grep nat`.

**Comment by Ammar7347** [comment]
The previous results were from a KVM machine running ubuntu but my second KVM machine is on Debian and I am getting no result (see attached screen shot).

Here's the same result for your reference from a KVM machine:
```
xt_nat                 12681  1
iptable_nat            13011  1
nf_nat_ipv4            13263  1 iptable_nat
nf_nat                 21841  3 nf_nat_ipv4,xt_nat,iptable_nat
nf_conntrack           97201  5 nf_nat,nf_nat_ipv4,xt_conntrack,iptable_nat,nf_conntrack_ipv4
ip_tables              27116  2 iptable_filter,iptable_nat
x_tables               34802  5 ip_tables,xt_tcpudp,xt_conntrack,xt_nat,iptable_filter

```
![screenshot_5](https://cloud.githubusercontent.com/assets/19525838/26765463/d045bcd8-4995-11e7-8c90-d3d4cd51b50b.png)

**Comment by DrXala** [comment]
omg! I have miss in my iptables command...
Try this `iptables -t nat -I PREROUTING -i $WAN -p udp --dport 6015 -j DNAT --to $CLIENT`

Sorry...

**Comment by DrXala** [comment]
For load nat module : `modprobe iptable_nat`

**Comment by Ammar7347** [comment]
Yeah, now your commands work but unfortunately it doesn't fix my issue. IDK why I get NAT open or on some servers moderate when using paid VPN's but on my own VPS, I get Strict everytime plus limited speed even though both are OpenVPN setups.

**Comment by Ammar7347** [comment]
The problem is definitely with the firewall because I ran some tests and received different results. For my direct connection and paid VPN's which gives me Open/moderate NAT type i was getting this result : 
![image](https://cloud.githubusercontent.com/assets/19525838/26768151/29db3f24-49bf-11e7-995b-1e0015571bf5.png)

and with my personal VPN's running on my VPS was giving me this:
![image](https://cloud.githubusercontent.com/assets/19525838/26768172/54bec8b4-49bf-11e7-89be-334e8b5087ce.png)

Online source I used to check my ports/NAT: www.grc.com

**Comment by DrXala** [comment]
Ok. Have you add this 3 rules in your iptables?
Can you paste the result of `iptables -t nat -L -vn --line` and `iptables -L -vn --line`

On your VPS with VPN, can you paste the result of `nc -z -w 5 -u IP-VPN-BS -v` where `IP-VPN-BS` is VPN IP address (ie: 10.8.0.20) of your BattleStation?

**Comment by Ammar7347** [comment]
No i've just added rules for 6015 udp. The other's are tcp and are used for uplay.
Results:

```
Chain PREROUTING (policy ACCEPT 11141 packets, 728K bytes)
num   pkts bytes target     prot opt in     out     source               destination
1        0     0 DNAT       udp  --  eth0   *       0.0.0.0/0            0.0.0.0/0            udp dpt:6015 to:10.8.0.2
2        0     0 DNAT       udp  --  eth0   *       0.0.0.0/0            0.0.0.0/0            udp dpt:6015 to:10.8.0.1
3        0     0 DNAT       udp  --  eth0   *       0.0.0.0/0            0.0.0.0/0            udp dpt:6015 to:10.8.0.10

Chain INPUT (policy ACCEPT 9169 packets, 549K bytes)
num   pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy ACCEPT 14635 packets, 1035K bytes)
num   pkts bytes target     prot opt in     out     source               destination

Chain POSTROUTING (policy ACCEPT 14635 packets, 1035K bytes)
num   pkts bytes target     prot opt in     out     source               destination
1     3093  318K SNAT       all  --  *      *       10.8.0.0/24          0.0.0.0/0            to:XX.XX.XX.XX
```
```
Chain INPUT (policy ACCEPT 1299K packets, 1074M bytes)
num   pkts bytes target     prot opt in     out     source               destination
1      616 51312 ACCEPT     tcp  --  *      *       127.0.0.1            0.0.0.0/0            tcp dpt:2008
2        1    40 DROP       tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:2008

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
num   pkts bytes target     prot opt in     out     source               destination
1        0     0 ACCEPT     udp  --  *      *       0.0.0.0/0            10.8.0.2             udp dpt:6015
2        0     0 ACCEPT     udp  --  *      *       0.0.0.0/0            10.8.0.1             udp dpt:6015
3        0     0 ACCEPT     udp  --  *      *       0.0.0.0/0            10.8.0.10            udp dpt:6015
4    71848 5688K ACCEPT     all  --  *      *       10.8.0.0/24          0.0.0.0/0
5     119K  107M ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            state RELATED,ESTABLISHED

Chain OUTPUT (policy ACCEPT 5293K packets, 1214M bytes)
num   pkts bytes target     prot opt in     out     source               destination

```
For the last one I am getting this error:

```
This is nc from the netcat-openbsd package. An alternative nc is available
in the netcat-traditional package.
usage: nc [-46bCDdhjklnrStUuvZz] [-I length] [-i interval] [-O length]
          [-P proxy_username] [-p source_port] [-q seconds] [-s source]
          [-T toskeyword] [-V rtable] [-w timeout] [-X proxy_protocol]
          [-x proxy_address[:port]] [destination] [port]
```

**Comment by DrXala** [comment]
You have 0 packet for your port forwarding rules, so it doesn't match.

For netcat, try `nc -zuv -w 5 IP-VPN-BS 6015`, I have forget port... You can use this tool with other machine for test your port forwarding. Replace IP-VPN-BS by the public IP of your vps.

**Comment by Ammar7347** [comment]
Thanks for your help and prompt replies. I am still unable to solve the problem unfortunately and I think I should leave it be. 
I just want to ask one last thing, so basically, people who have OpenVZ can't use NAT and will have no way to forward ports? I am asking this because I just recently shifted to another host and i bought OpenVZ instead of KVM and i am just waiting for my both KVM VPS's to expire.
