### ISSUE TITLE
services stop and won't restart automatically

### ISSUE THREAD

**Issue by A2116** [angristan/openvpn-install#722]
I have the same problem with iptables-openvpn.service
and both of them will stop on the different error and because of this problem I should care of service on the server
it's good that services restart on failure and this leads a server to be maintenance-free or less maintenance

service output:

● openvpn-iptables.service
   Loaded: loaded (/etc/systemd/system/openvpn-iptables.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Sun 2020-08-30 10:06:45 EDT; 25s ago
  Process: 489 ExecStart=/sbin/iptables -t nat -A POSTROUTING -s 10.8.0.0/24 ! -d 10.8.0.0/24 -j SNAT --to 198.143.178.85 (code=exited, status=4)
 Main PID: 489 (code=exited, status=4)

Aug 30 10:06:45 aaserver systemd[1]: Starting openvpn-iptables.service...
Aug 30 10:06:45 aaserver iptables[489]: Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
Aug 30 10:06:45 aaserver systemd[1]: openvpn-iptables.service: main process exited, code=exited, status=4/NOPERMISSION
Aug 30 10:06:45 aaserver systemd[1]: Failed to start openvpn-iptables.service.
Aug 30 10:06:45 aaserver systemd[1]: Unit openvpn-iptables.service entered failed state.
Aug 30 10:06:45 aaserver systemd[1]: openvpn-iptables.service failed.

**Comment by angristan** [comment]
Hi, what OS are you using?

**Comment by A2116** [comment]
> Hi, what OS are you using?

centos 7.4
kernel 5.8.4-1

**Comment by w84night** [comment]
same problem happend for me after restarting the server.
it was perfect and i could connect from outside till the unwanted restart happened.
im using centos 7 and the kernel information is this:
Linux 3.10.0-1160.2.2.el7.x86_64

ive got this error when i try to get the service status:

> [root@localhost /]# systemctl status openvpn@server
> ● openvpn@server.service - OpenVPN Robust And Highly Flexible Tunneling Application On server
>    Loaded: loaded (/usr/lib/systemd/system/openvpn@.service; disabled; vendor preset: disabled)
>    Active: failed (Result: exit-code) since Thu 2020-11-19 13:48:00 +03; 16min ago
>   Process: 1726 ExecStart=/usr/sbin/openvpn --cd /etc/openvpn/ --config %i.conf (code=exited, status=1/FAILURE)
>  Main PID: 1726 (code=exited, status=1/FAILURE)
>    Status: "Pre-connection initialization successful"
> 
> Nov 19 13:48:00 localhost.localdomain openvpn[1726]: Thu Nov 19 13:48:00 2020 us=652652 Data Channel MTU parms [ L:1621 D:1450 EF:121 EB:406 ET:0 EL:3 ]
> Nov 19 13:48:00 localhost.localdomain openvpn[1726]: Thu Nov 19 13:48:00 2020 us=653113 Could not determine IPv4/IPv6 protocol. Using AF_INET
> Nov 19 13:48:00 localhost.localdomain openvpn[1726]: Thu Nov 19 13:48:00 2020 us=653144 Socket Buffers: R=[212992->212992] S=[212992->212992]
> Nov 19 13:48:00 localhost.localdomain openvpn[1726]: Thu Nov 19 13:48:00 2020 us=653238 TCP/UDP: Socket bind failed on local address [AF_INET][undef]:1194: Address already in use (errno=98)
> Nov 19 13:48:00 localhost.localdomain openvpn[1726]: Thu Nov 19 13:48:00 2020 us=653247 Exiting due to fatal error
> Nov 19 13:48:00 localhost.localdomain openvpn[1726]: Thu Nov 19 13:48:00 2020 us=653261 Closing TUN/TAP interface
> Nov 19 13:48:00 localhost.localdomain openvpn[1726]: Thu Nov 19 13:48:00 2020 us=653271 /sbin/ip addr del dev tun1 10.8.1.1/24
> Nov 19 13:48:00 localhost.localdomain systemd[1]: openvpn@server.service: main process exited, code=exited, status=1/FAILURE
> Nov 19 13:48:00 localhost.localdomain systemd[1]: Unit openvpn@server.service entered failed state.
> Nov 19 13:48:00 localhost.localdomain systemd[1]: openvpn@server.service failed.


this is my server.conf which is located in /etc/openvpn :

> port 1194
> proto udp
> dev tun
> user nobody
> group nobody
> persist-key
> persist-tun
> keepalive 10 120
> topology subnet
> server 10.8.1.0 255.255.255.0
> ifconfig-pool-persist ipp.txt
> push "dhcp-option DNS 8.8.8.8"
> push "dhcp-option DNS 8.8.4.4"
> push "redirect-gateway def1 bypass-dhcp"
> dh none
> ecdh-curve prime256v1
> tls-crypt tls-crypt.key
> crl-verify crl.pem
> ca ca.crt
> cert server_U1IykeyFSDkmZiHD.crt
> key server_U1IykeyFSDkmZiHD.key
> auth SHA256
> cipher AES-128-GCM
> ncp-ciphers AES-128-GCM
> tls-server
> tls-version-min 1.2
> tls-cipher TLS-ECDHE-ECDSA-WITH-AES-128-GCM-SHA256
> client-config-dir /etc/openvpn/ccd
> status /var/log/openvpn/status.log
> verb 3

**Comment by hellresistor** [comment]
xtables ? or iptables ?

**Comment by randshell** [comment]
We could make `openvpn-server.service` more reliable by making it depend on the successful run of `iptables-openvpn.service`.

More important, the script configures a service called `iptables-openvpn.service`, why do you have one named `openvpn-iptables.service`?

**Comment by y377** [comment]
![image](https://user-images.githubusercontent.com/58632405/100524898-ee05b780-31f6-11eb-9427-a6cb2903fb8b.png)
I do, but I feel good about it
---
![image](https://user-images.githubusercontent.com/58632405/100524917-1f7e8300-31f7-11eb-8112-366887e9389a.png)

**Comment by hellresistor** [comment]
what distro?? I have tested this again yesterday on debian 10 and ubuntu 18 and 20 ... servers editions (no desktop)!!!
