### ISSUE TITLE
Auto Update Feature

### ISSUE THREAD

**Issue by A2116** [angristan/openvpn-install#723]
The script himself and all it's used modules and files are updated over time
and all become better and bugs become fixed
if the script has the feature for auto-update himself and all its related modules and file, all script users get latest updates and every problem issued one time, after every script update all similar problem and error become solved
so adding this feature lead to less effort on future
also, it's possible that a module update lead to OpenVPN configuration return error on the new module
with auto-update feature incompatibility path will apply to all users and solve all users problem

**Comment by angristan** [comment]
See https://github.com/angristan/openvpn-install/issues/179

**Comment by A2116** [comment]
I think adding this feature can decrease duplicated bugs report and efforts for fixing them and enhance the user experience
it's obvious that it's not the main feature, but adding this help all users, and maybe you as maintainer of the script
regards
