### ISSUE TITLE
How can we add obfuscation feature to this OpenVPN installation?

### ISSUE THREAD

**Issue by HeeraSinghKang** [angristan/openvpn-install#726]
**Checklist**

- [x] I read the [README](https://github.com/angristan/openvpn-install/blob/master/README.md)
- [x] I read the [FAQ](https://github.com/angristan/openvpn-install/blob/master/FAQ.md)
- [x] I searched the [issues](https://github.com/angristan/openvpn-install/issues?q=is%3Aissue+)
- [x] My issue is about the script, and not OpenVPN itself

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by HeeraSinghKang** [comment]
Is it possible to add obfuscation to this setup?

**Comment by iProdigy** [comment]
As in [obfsproxy](https://community.openvpn.net/openvpn/wiki/TrafficObfuscation)? 

See #413
