### ISSUE TITLE
certificate error

### ISSUE THREAD

**Issue by uricanezu** [angristan/openvpn-install#730]
EVENT: CERT_VERIFY_FAIL OpenSSLContext::SSL::read_cleartext: BIO_read failed, cap=2576 status=-1: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed⏎9/18/2020, 2:46:42 PM EVENT: DISCONNECTED ⏎9/18/2020, 2:46:42 PM Transport Error: OpenSSLContext::SSL::read_cleartext: BIO_read failed, cap=2576 status=-1: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed

any idea why this is happening, installed with defaults

**Comment by uricanezu** [comment]
server is configured behind nat

**Comment by randshell** [comment]
> certificate verify failed

Can you please reinstall openvpn and try again? If it doesn't work install it with `bash -x openvpn-install.sh` and post the debug log.

> server is configured behind nat

I think that getting a `certificate verify failed` means that at least you configured port forwarding correctly and you were able to communicate with it.
