### ISSUE TITLE
Remove certificate/duplicate name

### ISSUE THREAD

**Issue by g-pane** [angristan/openvpn-install#731]
**Checklist**

- [x] I read the [README](https://github.com/angristan/openvpn-install/blob/master/README.md)
- [x] I read the [FAQ](https://github.com/angristan/openvpn-install/blob/master/FAQ.md)
- [x] I searched the [issues](https://github.com/angristan/openvpn-install/issues?q=is%3Aissue+)
- [x] My issue is about the script, and not OpenVPN itself

**Describe the issue**
When i'm delete a user with the name, example user_1, i can't create another user with the same name. Why? If have removed doesn' not exist anymore

**To Reproduce**
Create a user named "user_1"
Delete the "user_1"
Create a user named "user_1"

**Expected behavior**
Creation of the user

**Comment by randshell** [comment]
Duplicate of #652
