### ISSUE TITLE
Txt file for multiple client creation

### ISSUE THREAD

**Issue by g-pane** [angristan/openvpn-install#732]
**Checklist**

- [x] I read the [README](https://github.com/angristan/openvpn-install/blob/master/README.md)
- [x] I read the [FAQ](https://github.com/angristan/openvpn-install/blob/master/FAQ.md)
- [x] I searched the [issues](https://github.com/angristan/openvpn-install/issues?q=is%3Aissue+)
- [x] My issue is about the script, and not OpenVPN itself

**Describe the solution you'd like**
Since i need to create many client always with the same "name style" (like vpn_001, vpn_002 and so on) was cool if i can pass a txt file with the all "certificates name" instead to create one to one, manually. The openvpn-install.sh ask only for the certificate name and password when create a new client.

5) Add new users from txt

Txt content:
vpn_001|mypass
vpn_002 //without password
vpn_003|another pass

The password thing can be skipped if isn't possible. It can be very useful to create users in this way

**Comment by randshell** [comment]
You can make a bash script that uses the headless user addition explained in the README:
```bash
while read USER
    do MENU_OPTION="1" CLIENT="$USER" PASS="1" ./openvpn-install.sh
done < users.txt
```

In `users.txt` each line contains a client name, setting a password headlessly is not supported yet by this script #389.

@angristan #521 is now a duplicate.

**Comment by g-pane** [comment]
Work fine thanks

**Comment by angristan** [comment]
~~Could this be added to the FAQ? 😄~~
