### ISSUE TITLE
Change ovpn path

### ISSUE THREAD

**Issue by g-pane** [angristan/openvpn-install#734]
How can I set the default path of all the generate ovpn? (instead of /root but something like /root/config)
Thanks

**Comment by randshell** [comment]
Replace `$homeDir` to `/root/config` in the script https://github.com/angristan/openvpn-install/blob/2950fd445752fd0515cdbf37b28ab8a494bc8299/openvpn-install.sh#L1083-L1090

**Comment by g-pane** [comment]
Is possible to do in command line without edit the SH? Since can be updated

**Comment by randshell** [comment]
The script doesn't allow customizing that path yet, but you can run `sed` to edit the line.
```bash
sed -i 's|homeDir="/root"$|homeDir="/root/config"|' openvpn-install.sh
```
