### ISSUE TITLE
exit statement prevents from re-creating ovpn file for existing user

### ISSUE THREAD

**Issue by Kassouma** [angristan/openvpn-install#738]
**Describe the issue**
If for some reason I delete the ovpn file for "client1"
When running again the script (manually or in headless mode), the script will return 
"The specified client CN was already found in easy-rsa, please choose another name."
While in the README it is specified that (at least in headlessmode):
"It will recreate all local config and re-generate the client file on each headless run."

It is also specified : 
" It will only install and regenerate the Easy-RSA PKI if it doesn't already exist,"
Which does not seems to be the case.

If a user is revoked then re-created 
`        CLIENTEXISTS=$(tail -n +2 /etc/openvpn/easy-rsa/pki/index.txt | grep -c -E "/CN=$CLIENT\$")`
returns 1.

In both cases the program exit on line 1068.
Removing the exit statement solves the issue in the case of re-creating the ovpn file for an existing user.
It does not solve the issue in the case where a user with the same name was revoked previously.

**To Reproduce**

1.create a new user called 'client1' (passwordless)
2.remove client1.ovpn
3.run again the script to add a user 'client1'
4.no client1.ovpn is generated
5.revoke the user client1
6.add a new user 'client1'
7.ovpn file is created with missing certs

**Expected behavior**
If I revoke a user 'user1' then I can add a new one with new keys and so on , having the same name.
If my .ovpn file was deleted or moved, it generates it again.

- OS: [e.g. Debian 10]

**Comment by randshell** [comment]
Duplicate of #652. @angristan
