### ISSUE TITLE
Errors running on Debian 9 Stretch

### ISSUE THREAD

**Issue by DavidCWGA** [angristan/openvpn-install#74]
Errors during setup, including the following:

````
Using configuration from /etc/openvpn/easy-rsa/openssl-1.0.cnf
Can't open /etc/openvpn/easy-rsa/pki/index.txt.attr for reading, No such file or directory
139969304495360:error:02001002:system library:fopen:No such file or directory:../crypto/bio/bss_file.c:74:fopen('/etc/openvpn/easy-rsa/pki/index.txt.attr','r')
139969304495360:error:2006D080:BIO routines:BIO_new_file:no such file:../crypto/bio/bss_file.c:81:
Check that the request matches the signature
````

````
cp: cannot stat 'dh.pem': No such file or directory
sed: can't read /etc/rc.local: No such file or directory
2006
Job for openvpn@server.service failed because the control process exited with error code.
See "systemctl status openvpn@server.service" and "journalctl -xe" for details.
````

Works OK on Debian 8.

**Comment by angristan** [comment]
The DH key is not properly generated, the syntax has changed : https://www.debian.org/releases/stretch/amd64/release-notes/ch-information.en.html#openssl-issues

It's generated but not written to the file. I'll see if the other syntax works on other distros

**Comment by angristan** [comment]
As for the first issue, it's strange because `/etc/openvpn/easy-rsa/pki/index.txt.attr` exists

**Comment by angristan** [comment]
And the file has the exact same permissions on Debian 8... 🤔

**Comment by Kcchouette** [comment]
For debian 9, shouldn't you add it to the list here? https://github.com/Angristan/OpenVPN-install/blob/d712e157951ff52dd3b4230c76403eda8f91755d/openvpn-install.sh#L28

**Comment by angristan** [comment]
> For debian 9, shouldn't you add it to the list here? https://github.com/Angristan/OpenVPN-install/blob/d712e157951ff52dd3b4230c76403eda8f91755d/openvpn-install.sh#L28

Yes but that's not the issue here, I'll add it when it will be compatible

**Comment by angristan** [comment]
I also get the "No such file or directory" error on Arch.

**Comment by angristan** [comment]
I just realized that in both case it has no impact at all. Feel free to open an issue if you find a problem about `index.txt.attr`.
