### ISSUE TITLE
Change Cipher on old Script

### ISSUE THREAD

**Issue by vahidx4r4x** [angristan/openvpn-install#741]
hi
i have installed older version of your script and back then it didnt offer any ciphers to choose!
and its the default cipher "AES-CBC-256" on both 'server.conf' and 'client_common'. i want to change the cipher to "AES-GCM-256" without reinstalling the script because then i will end up loosing all of my clients CERT_EXPIRE dates! and i dont want to recreate all of them again!

Is there any way to change the cipher in peace?

**Comment by angristan** [comment]
You can change this line in both your server and client configs

**Comment by vahidx4r4x** [comment]
> You can change this line in both your server and client configs

Which line???

**Comment by angristan** [comment]
The line with `cipher`
