### ISSUE TITLE
can not create client .ovpn file, error line 1045

### ISSUE THREAD

**Issue by hungchieu** [angristan/openvpn-install#742]
**Checklist**

- [x] I read the [README](https://github.com/angristan/openvpn-install/blob/master/README.md)
- [x] I read the [FAQ](https://github.com/angristan/openvpn-install/blob/master/FAQ.md)
- [x] I searched the [issues](https://github.com/angristan/openvpn-install/issues?q=is%3Aissue+)
- [x] My issue is about the script, and not OpenVPN itself

**Describe the issue**
when running the script, it shows error and can not create the client ovpn file, error line 1045. Check and the file is not created.
Check OpenVPN Status and it's active.

###Not all server has /home/root folder.

**To Reproduce**

1. ...

**Expected behavior**

**Logs**
If applicable, add logs or screenshots to help explain your problem.

If you can reproduce the issue, please run the script in debug mode and post the output: `bash -x openvpn-install.sh`

**Server if applicable):**

- OS: [e.g. Debian 10]
- Hosting provider (if applicable): [e.g. Vultr, AWS]
CLOUDLINUX 7.8

**Client (if applicable):**

- Client: [e.g. OpenVPN Connect]

**Additional context**

**Comment by angristan** [comment]
Can you post the specific error?

**Comment by hungchieu** [comment]
Hi,
The error is cannot create [clientname.ovpn] file on /home/root. Not all hosting have that directory. I think should have code to check if the directory exists or not, or create a whole new directory, says "/home/vpn_profile" and put all .ovpn files there.

**Comment by angristan** [comment]
There is already code for that:

https://github.com/angristan/openvpn-install/blob/2950fd445752fd0515cdbf37b28ab8a494bc8299/openvpn-install.sh#L1083-L1090

It would be useful if you could post the output of `bash -x openvpn-install.sh` in order for us to debug that.

**Comment by hungchieu** [comment]
Oh, by the time I comment, it is still not working for me. I’m using dedicate server, login as root, but I don’t have /home/root, and the error is “error line 1045” cannot create file on /home/root
so I manually create directory /home/root and everything working fine.
It’s not a big issue, it’s just for some totally beginners don’t know what to do.

**Comment by randshell** [comment]
Are there any cases where `/home/root` would exists in a distro? The check could be changed to `elif [ "${SUDO_USER}" =~ root];`


For me `${SUDO_USER}` depends on the command I use to elevate privileges:
```
$ su -
# echo ${SUDO_USER}

```

```
$ sudo su
# echo ${SUDO_USER}
randomshell
```

**Comment by angristan** [comment]
Closing as I can't see how this would happen, so we'll wait for other reports
