### ISSUE TITLE
Radius Server like feature.

### ISSUE THREAD

**Issue by vahidx4r4x** [angristan/openvpn-install#743]
hi
I would like to request a feature that asks the server admin for CERT_EXPIRE days when adding a new client.
and make it possible to renew the CERT_EXPIRE days for existing client.
In this way admins can easily manage all the clients without removing and recreating a client after CERT_EXPIRE, simply renewing a client and giving them more days to use the VPN.
kinda like a radius server.

**Comment by randshell** [comment]
I think you can add `set_var EASYRSA_CERT_EXPIRE 3650` to `/etc/openvpn/easy-rsa/vars` to customize the time for all users, or export in the terminal `EASYRSA_CERT_EXPIRE=3650` before creating a client (unset it after so it doesn't apply to other users) to customize only that one. @angristan may know if this could be a feature to this script.

To renew you can use `./easyrsa renew user` inside `/etc/openvpn/easy-rsa/`. Automating the renewal of one or all clients could definitely be a feature though. Note that certificates aren't renewable if the expire date is greater than the next 30 days.

**Comment by TinCanTech** [comment]
> Note that certificates aren't renewable if the expire date is greater than the next 30 days.

This is also configurable via `vars`

**Edit**: Also, `EASYRSA_CERT_RENEW=180 ./easyrsa renew user`

Beware: `easyrsa renew` is incomplete and will leave old certificates in the PKI, which should be revoked.

**Comment by vahidx4r4x** [comment]
> 
> 
> I think you can add `set_var EASYRSA_CERT_EXPIRE 3650` to `/etc/openvpn/easy-rsa/vars` to customize the time for all users, or export in the terminal `EASYRSA_CERT_EXPIRE=3650` before creating a client (unset it after so it doesn't apply to other users) to customize only that one. @angristan may know if this could be a feature to this script.
> 
> To renew you can use `./easyrsa renew user` inside `/etc/openvpn/easy-rsa/`. Automating the renewal of one or all clients could definitely be a feature though. Note that certificates aren't renewable if the expire date is greater than the next 30 days.

I did test it
but its kinda hard thing to do. it will be so easy if this feature implement in script.

also every time i want to add a user with CERT_EXPIRE days anything other than 825 days i should edit `/etc/openvpn/easy-rsa/easyrsa` file and search for `set_var EASYRSA_CERT_EXPIRE	825 # new default of 36 months` line and change the number, save it and run the script.

**Comment by angristan** [comment]
Feel free to come up with a PR for this

**Comment by TinCanTech** [comment]
Something like:
```
  ./easyrsa --days=$CERT_LIFETIME build-client-full "$CLIENT" nopass
```
https://github.com/angristan/openvpn-install/blob/ea236de3e32d2404632f6ccf63b1b4b9ee36f647/openvpn-install.sh#L1077

And in input dialogue to query the lifetime of the certificate..
