### ISSUE TITLE
Heads up -- GCP disables ip_forward=1

### ISSUE THREAD

**Issue by deargle** [angristan/openvpn-install#744]
I just hit a gotcha which I thought might be helpful to others. While your script enables ip_forward [here](https://github.com/angristan/openvpn-install/blob/2950fd445752fd0515cdbf37b28ab8a494bc8299/openvpn-install.sh#L891), instances running on GCP turn around and _disable_ that in [60-gce-network-security.conf](https://github.com/GoogleCloudPlatform/guest-configs/blob/master/src/etc/sysctl.d/60-gce-network-security.conf). I was head-scratching why my setup suddenly stopped working, and that's all it was.

Idk, what would be the implications of being more aggressive with the number prefix here? I'm going to `99-` it in my instance just because need it to work right meow, but in general?

**Comment by angristan** [comment]
Thanks for the report! Seem reasonable to me to use `99-`. You can open PR if you'd like!

**Comment by deargle** [comment]
:+1: Opened!

**Comment by angristan** [comment]
Thanks! 👍

**Comment by tpwo** [comment]
@deargle thanks a lot for creating that issue!

I had the same problem - I configured OpenVPN on GCP, and it worked fine and then got broken. Finally, I found the solution here.

However, the problematic line `net.ipv4.ip_forward = 0` was in the file `/etc/sysctl.d/99-gce.conf`.

I just changed this line in `99-gce.conf` to `net.ipv4.ip_forward = 1` and it works. It seems that `99` is the highest possible priority, so the potential update to the script is probably less obvious.

I found an old [gist](https://gist.github.com/jstangroome/be4bee805c97063c28869ff4d636ed26#file-99-gce-conf-L29) with this file, so it might not be present on every GCP image. I created an instance with Ubuntu 20.04 (ubuntu-2004-focal-v20210129 is the image name in GCP).

Edit: it seems that this file might be unique to Ubuntu image as I found an [old article](https://blog.stangroome.com/2017/08/16/beware-docker-and-sysctl-defaults-on-gce/) mentioning it.

**Comment by deargle** [comment]
You're trying to set it to 0? The openvpn-install script sets it to 1, and
I think this project's 99-openvpn.conf would win alphabetically over
99-gce.conf -- see the associated PR that closed this issue.

**Comment by tpwo** [comment]
Oh, it was too late for me... Of course, in gcp file it is set to `0` and I changed it to `1`, thanks.

Regarding the precedence it seems that you should be right. Here's the sysctl.d man page:


> All configuration files are sorted by their filename in lexicographic order, regardless of which of the directories they reside in. If multiple files specify the same option, the entry in the file with the lexicographically latest name will take precedence.


But it didn't work until I made the manual change. And I rebooted the machine at least a few times, so it should load the correct settings. I don't know, I'll check the log later to see what happens.

**Comment by tpwo** [comment]
@deargle ok, I've got it - you were totally right. Funnily, it turned out that I used a [different script](https://github.com/Nyr/openvpn-install) that has the same repo name, and it creates `30-openvpn-forward.conf` file so `99-gce.conf` takes precedence. I came back to this issue after some time and, thankfully, found this repo instead without noticing that it is a different project. Thanks again!
