### ISSUE TITLE
prompt for duplicate CN on easy-rsa after user revok

### ISSUE THREAD

**Issue by A2116** [angristan/openvpn-install#746]
**Describe the issue**

complete removal of the user after the revoke 

**To Reproduce**

0. install OpenVPN using the script on centos 8
1. create a user with a passphrase
2. revoke it
3. recreate the same user

**Expected behavior**

complete removal of the user after the revoke 

**Logs**

i see that the line for that user not removed from /etc/openvpn/easy-rsa/pki/index.txt
in process of recreation of user it prompt "The specified client CN was already found in easy-rsa, please choose another name."

**Server if applicable):**

Centos 8
OVH

**Comment by randshell** [comment]
The file `/etc/openvpn/easy-rsa/pki/index.txt` keeps track of issued certificates and their status, you don't remove anything from it. The line `The specified client CN was already found in easy-rsa, please choose another name.` is a bug in our script.

Duplicate of #652

**Comment by A2116** [comment]
I used the latest version of the script
in previous versions, I have not such a problem
so I should wait for a bugfix or...?

**Comment by randshell** [comment]
There is PR #680 opened to fix that. There is no ETA for when it will be merged, so you can make those changes manually in your script.

You can check the diff [here](https://github.com/angristan/openvpn-install/pull/680/files): add `^V.*` to `"^V.*/CN=$CLIENT\$"` and remove the exit command.

**Comment by undeadindustries** [comment]
Hey there. Just to clarify, once this fix is in, if a user is revoked, the same user name will be able to be added again?
Thanks so much and thanks for maintaining this project. It's a huge help!

**Comment by randshell** [comment]
> Hey there. Just to clarify, once this fix is in, if a user is revoked, the same user name will be able to be added again?

Yes, you got that right!

**Comment by undeadindustries** [comment]
Thanks so much! eagerly awaiting this to be merged into master :-)

**Comment by angristan** [comment]
Fixed with https://github.com/angristan/openvpn-install/commit/bda450948a933224f4f779a24a44c6279e1574a1 + https://github.com/angristan/openvpn-install/pull/1185 🙂
