### ISSUE TITLE
SLAAC & IPv6 Prefix delegation

### ISSUE THREAD

**Issue by Sunvas** [angristan/openvpn-install#757]
I'm always frustrated when all of the clients are shown to the world with the same IPv6 address, which genuinely is the IP of a server.
But my server has an entire /64 subnet for IPv6 purposes. So, is it possible for OpenVPN to provide prefix delegation for the possibility of Stateless Address Autoconfiguration (SLAAC) on clients?

**Comment by randshell** [comment]
It should be possible for the clients to have their own public IP when OpenVPN is set up in Bridge mode. Unfortunately this script supports NAT mode only and as I have never done that other one I can't help you with the steps involved.

**Comment by angristan** [comment]
I will close this for now, PRs welcome if they are simple enough.
