### ISSUE TITLE
Equivalent of openvpn-install for L2TP or PPTP?

### ISSUE THREAD

**Issue by jerkstorecaller** [angristan/openvpn-install#763]
Apologies for the off-topic question. I'll close it in a few days.

I'm a happy user of openvpn-install. However, I was wondering if anyone knew of an equally-simple script that would help me set up a Linux system to act as a L2TP or PPTP server. These are VPN protocols that work natively on every device (e.g. Windows and iOS) without the need for a custom client, as OpenVPN does.

**Comment by randshell** [comment]
Have you researched the subject and then are you sure you want to use these protocols just because they are native? To sum up, they are less secure and slower than OpenVPN, personally I wouldn't recommend them.
