### ISSUE TITLE
static_key_parse_error on Android

### ISSUE THREAD

**Issue by Silvers12** [angristan/openvpn-install#765]
Hello,
I have the same issue than here : https://github.com/angristan/openvpn-install/issues/500
```

The openvpn-install script ran successfully, on a Debian 10 server.
However when I tried to import it into an Android 7.0 device, running the official OpenVPN client, I got a "Failed to parse profile: static_key_parse_error".
After inspecting the .ovpn client file, I noticed that the tls-crypt section in it is empty:

<tls-crypt>
</tls-crypt>

Since this is the first time I've ran the openvpn-install script (with no other options passed to it), I have no idea if this is something that the script should have taken care of it, or I should do something

Thanks for any suggestions
```

Any Solution ? I can't use it on Android 10.
<tls-crypt>
</tls-crypt> empty .

Thanks ;)

**Comment by Silvers12** [comment]
Don't work on windows too
"Insufficient key material or header text not found in file '[[INLINE]]'"

I have an Debian 10 server

**Comment by Silvers12** [comment]
After do that :

> Add `/usr/sbin` to Debian `$PATH`
$ export PATH="/usr/sbin:$PATH"

and that :

> openvpn --genkey --secret /etc/openvpn/tls-auth.key

It's OK !

**Comment by randshell** [comment]
You have the same issue as #523 and #593. To fix use `su -` or `sudo -i` to get root, run the script to `Remove OpenVPN` and run again to reinstall.

EDIT:
> After do that :
>    Add /usr/sbin to Debian $PATH
> and that :
>    openvpn --genkey --secret /etc/openvpn/tls-auth.key
> It's OK !

I would strongly recommend to use the proper way to get root permission instead.
