### ISSUE TITLE
Cannot fix DNS leak on Android device

### ISSUE THREAD

**Issue by quyleanh** [angristan/openvpn-install#767]
How can I fix DNS leak on Android device?
As I read on [FAQ](https://github.com/angristan/openvpn-install/blob/master/FAQ.md), there is no option for Android device.

When I connect to OpenVPN server, then check on [browserleaks.com](https://browserleaks.com/dns), [ipleak.net](https://ipleak.net/), and [dnsleaktest.com](https://dnsleaktest.com/). It does not show the server IP.

How can I fix that? Thank you.

**Comment by randshell** [comment]
I suppose you are using the Openvpn Connect app? We had some issues with it in the past too. Try with "OpenVPN for Android" by "Arne Schwabe" please, it should work by default or after checking some option.

**Comment by quyleanh** [comment]
Yep. I use Openvpn Connect app. Tried your recommendation but still have DNS leak.

I would like to ask one question. If my resolv.conf on server use Cloudflare 1.1.1.1 DNS, when I check it will show Cloudflare address, right?

**Comment by randshell** [comment]
> If my resolv.conf on server use Cloudflare 1.1.1.1 DNS, when I check it will show Cloudflare address, right?

Depends on what DNS you chose during OpenVPN configuration. You can verify it by opening your `server.conf` and look for `dhcp-option DNS`.

**Comment by quyleanh** [comment]
`dhcp-option` is configured for Cloudflare now. But how can I config DNS with the public IP of server?

**Comment by angristan** [comment]
> When I connect to OpenVPN server, then check on browserleaks.com, ipleak.net, and dnsleaktest.com. It does not show the server IP.

If your home IP and your ISP's DNS servers' IPs are not shown, you're safe
