### ISSUE TITLE
IPv6 detection while using HE.net tunnel

### ISSUE THREAD

**Issue by Struart88** [angristan/openvpn-install#769]
Hello there is problem with ipv6 nat when server is using he-ipv6 tunnel.
Script when checks for ipv6 connectivity sets interface to eth0 instead of he-ipv6 virtual one.
Thats why all ip6tables are wrong because it points to eth0 interface all the time which is wrong as main interface for ipv6 while using tunnel is vitrual one. Default he-ipv6.

The problem is that scipt uses ONE variable for setting interface for ipv4 and ipv6.

```
	# Get the "public" interface from the default route
	NIC=$(ip -4 route ls | grep default | grep -Po '(?<=dev )(\S+)' | head -1)
	if [[ -z $NIC ]] && [[ $IPV6_SUPPORT == 'y' ]]; then
		NIC=$(ip -6 route show default | sed -ne 's/^default .* dev \([^ ]*\) .*$/\1/p')
	fi
```

the ipv6 detecting line above is resulting in correct interface but as variable $NIC already contains interface from ipv4 it stays there.

I think there should be 2 variables to get rid of that.

When i do all ip6tables by hand with correct $NIC (he-ipv6 instead of eth0) that ipv6 works everywhere.

Sorry for my bad english.

**Comment by angristan** [comment]
PRs welcome, closing this for now.
