### ISSUE TITLE
create user: copy config fails when user is root and script executed via sudo

### ISSUE THREAD

**Issue by mStirner** [angristan/openvpn-install#775]
**Checklist**

- [x] I read the [README](https://github.com/angristan/openvpn-install/blob/master/README.md)
- [x] I read the [FAQ](https://github.com/angristan/openvpn-install/blob/master/FAQ.md)
- [x] I searched the [issues](https://github.com/angristan/openvpn-install/issues?q=is%3Aissue+)
- [x] My issue is about the script, and not OpenVPN itself

**Describe the issue**
Creating client config, copy after generating, fails if you are root and run the script via "sudo".

**To Reproduce**
1) Become root 
2) Run the script via "sudo"
3) Create a new user.
4) Complete wizard
5) `cp ...` at the end fails (because of wrong home/destination path)

**Expected behavior**
The script should copy the client config to `/root/xxx` instead of `/home/root/xxx`

**Server:**
- OS: CentOS 8

**Comment by angristan** [comment]
Should be fixed with https://github.com/angristan/openvpn-install/commit/e965518dc7df1a1363be674455bb798b28727851
