### ISSUE TITLE
SSL routines:tls_process_client_certificate:certificate verify failed

### ISSUE THREAD

**Issue by openmotion** [angristan/openvpn-install#78]
hello
i cannot connect anymore to my vpn server (archlinux)
i have this message in the log

```
192.168.0.1:37072 VERIFY ERROR: depth=0, error=CRL has expired: CN=client
192.168.0.1:37072 OpenSSL: error:1417C086:SSL routines:tls_process_client_certificate:certificate verify failed
```

so i changed in openssl.cnf this values :
default_days   = 3650         # how long to certify for
default_crl_days= 3650         # how long before next CRL

but i am not sure where are the certificates to execute the renew command : 
`openssl ca  -gencrl -keyfile keys/ca.key -cert keys/ca.crt  -out keys/crl.pem -config ./openssl.cnf`

thnaks

**Comment by angristan** [comment]
Fixed by #109
