### ISSUE TITLE
Problem with OpenVPN server installation.

### ISSUE THREAD

**Issue by ghost** [angristan/openvpn-install#780]
So yesterday I bought a Ubuntu 20.04 VPS so I can setup my own VPN server.
The installation was complete but this came up at the end,
Is there any way I could fix this?
Thank you!
![emc0A921BE3F68c6Db](https://user-images.githubusercontent.com/57315730/103234181-fee83c80-490c-11eb-8e83-1171045fa6fa.png)

**Comment by angristan** [comment]
Should be fixed :)
