### ISSUE TITLE
Installation work but it doesn't change my ip adress :/

### ISSUE THREAD

**Issue by Teknival** [angristan/openvpn-install#784]
Hello friends,

Hi just install the script, it work perfectly but when i check my IP on whatsmyipadress.com, it's the same IP ..

I have done service openvpn start and openvpn status, I have this :

service openvpn status                                                                   2 ⚙
● openvpn.service - OpenVPN service
     Loaded: loaded (/lib/systemd/system/openvpn.service; disabled; vendor preset: disabled)
     Active: active (exited) since Fri 2021-01-08 02:26:46 UTC; 7s ago
    Process: 4199 ExecStart=/bin/true (code=exited, status=0/SUCCESS)
   Main PID: 4199 (code=exited, status=0/SUCCESS)
        CPU: 679us

Do I have missed something or is it normal to have my same ip adress not masked ?

Do I need a registration to NordVPN or something else to mask my IP ?

Thanks a lot to help my noobie skill, have an HAPPY NEW TEKNIVAL lol :)

See you !

**Comment by Teknival** [comment]
Maybe it's because it's my OWN VPN server it's why it doesn't change my IP lol ...

So do I need to buy a VPN to change my IP like NordVPN or all something services ? 

Thanksssssssssssssssss 💯

**Comment by angristan** [comment]
You have to use this script to install an OpenVPN server on some server (a VPS, a dedicated server, a cloud instance...) and then connect to it. Then you will "have" the server's IP :)
