### ISSUE TITLE
Add new user: auto detect if server is configured as TCP or UDP

### ISSUE THREAD

**Issue by deafbabe** [angristan/openvpn-install#790]
I've changed my server config to TCP, but the new user profiles still were created with "proto udp". I've found the template file and modified it, but it would be nice if that could be detected automatically.

**Comment by Stevemoretz** [comment]
> I've changed my server config to TCP, but the new user profiles still were created with "proto udp". I've found the template file and modified it, but it would be nice if that could be detected automatically.

Please explain how you did change server and client to tcp I really need this.

**Comment by angristan** [comment]
Yeah, I guess the best solution for now is to modify `/etc/openvpn/client-template.txt`.
