### ISSUE TITLE
Dont use "apt autoremove". Ever.

### ISSUE THREAD

**Issue by macruspareto** [angristan/openvpn-install#794]
This morning I tried your script on my Ubuntu 20 installation.

Then, once I've decided to uninstall it, it took me 5 hours to repair the system (and its still not over).
Only because you've put "apt-get autoremove --purge -y openvpn" there.

Never ever use "autoremove", please! Its the most broken option in Unix ecosystem. It has  completely wiped my VNC server, my PHP installation, my Python packages, my Go packages, libraries, and many many more.

There were tons of "orphaned/obsolete" packages that I never dare to "autoremove" because it would render any system unusable (happened before - once, twice, and so on), but this time I didn't pay attention and ran your script to remove itself and all traces of Openvpn.

I'm still fixing my system but would probably need a fresh install.

Dont do it.

**Comment by Rithari** [comment]
DO NOT run this script.

**Comment by Rithari** [comment]
Imagine censoring people's opinions...
