### ISSUE TITLE
Google Authenticator support

### ISSUE THREAD

**Issue by nicraMarcin** [angristan/openvpn-install#795]
Could You add to script Google Authenticator support?

for example [Using Google Authenticator MFA with OpenVPN on Ubuntu 16.04](https://egonbraun.medium.com/using-google-authenticator-mfa-with-openvpn-on-ubuntu-16-04-774e4acc2852)
[OpenVPN with Google 2-factor authentication on CentOS 7](https://velenux.wordpress.com/2019/03/12/openvpn-with-google-2-factor-authentication-on-centos-7/)

**Comment by zhangj3** [comment]
https://openvpn.net/openvpn-mfa-setup-community-edition/  here is the official document

**Comment by angristan** [comment]
Hello,

Multiple issues already exists about this.

Feel free to PR 🙂

**Comment by ufukty** [comment]
I started to develop a project as a solution to this problem. It supports password and otp at same time and in essence is the same thing with the official link above. I seek for security checks from contributors right now. If there is interest we can create a PR.

[https://github.com/ufukty/ovpn-auth](https://github.com/ufukty/ovpn-auth)

**Comment by perfecto25** [comment]
I'm working on setting this up using this openvpn-install script, have QR code working and user is passing the OTP code phase, but getting errors with Openvpn PAM auth, once I get this to work ill post link to description how to set this up

**Comment by opbod** [comment]
@perfecto25 did you get this to work with the script of this repo?
I've seen https://github.com/perfecto25/openvpn_2fa but yours is no longer synched with this repo and isn't updated 😉. Any possibility to backport by any chance?

**Comment by Shootify** [comment]
i am looking to have TOTP 2fa, anyone succeed?
