### ISSUE TITLE
Client files not beeing created in the right folder when using sudo

### ISSUE THREAD

**Issue by angristan** [angristan/openvpn-install#8]
As reported here : https://github.com/Angristan/OpenVPN-install/issues/3.

When a normal user run the script using sudo, the .ovpn client conf is created in /root/, until you use `sudo -E`.

I'll have to find another way to get the home directory of the user.

**Comment by timgurney-ee** [comment]
sudo sets the following environment variables:

   SUDO_UID        Set to the user ID of the user who invoked sudo
   SUDO_USER       Set to the login of the user who invoked sudo

So you should be able to check for the existence of SUDO_USER and use that home dir and if it doesnt exist use roots home dir.

Although an easier option might be to use the logname command.
