### ISSUE TITLE
support of openvpn 2.5.1

### ISSUE THREAD

**Issue by christospelekis** [angristan/openvpn-install#808]
Hello,
the script support openvpn 2.5.1?
I am thinking to use openvpn repositories in debian 10 but i not know if the installer is optimized for version 2.5.1

**Comment by hellresistor** [comment]
try it. and give feed back ;)

**Comment by angristan** [comment]
🙂 

There is also a discussion here: https://github.com/angristan/openvpn-install/discussions/761
