### ISSUE TITLE
Fix OpenVZ

### ISSUE THREAD

**Issue by SteffanWolter** [angristan/openvpn-install#81]
Hey,
you should add a fix for openvz vps server.
Openvpn worked after i commented out the line "LimitNPROC" in
/lib/systemd/system/openvpn@.service

Greetings

**Comment by angristan** [comment]
\o/

**Comment by angristan** [comment]
Fixed : https://github.com/Angristan/OpenVPN-install/commit/c703d41795def39b81b4a4ec6b2bda3f144b2a0a
