### ISSUE TITLE
Option to enable mfa with google authenticator

### ISSUE THREAD

**Issue by shshanmu** [angristan/openvpn-install#811]
**Checklist**

- [ ] I read the [README](https://github.com/angristan/openvpn-install/blob/master/README.md)
- [ ] I read the [FAQ](https://github.com/angristan/openvpn-install/blob/master/FAQ.md)
- [ ] I searched the [issues](https://github.com/angristan/openvpn-install/issues?q=is%3Aissue+)
- [X] My issue is about the script, and not OpenVPN itself

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
A way to enable MFA with openvpn-plugin-auth-pam.so would be a great addition to the script.
It would make life much easier for people who would like to use mfa.

**Describe alternatives you've considered**

**Additional context**

**Comment by angristan** [comment]
https://github.com/angristan/openvpn-install/search?q=google+authenticator&type=issues
