### ISSUE TITLE
No internet connection with VPN

### ISSUE THREAD

**Issue by riccardozjesolo** [angristan/openvpn-install#814]
with default installation the client no have internet access. is there a solution for this?
thanks

**Comment by chithanh12** [comment]
i got the same issue, any solution?

**Comment by chithanh12** [comment]
After do some research and i fixed this issue by adding the flowing statements on my client `.ovpn`

script-security 2
up /etc/openvpn/update-resolv-conf
down /etc/openvpn/update-resolv-conf
