### ISSUE TITLE
Headless User Addition with passphrase ?

### ISSUE THREAD

**Issue by Bartiff** [angristan/openvpn-install#821]
Hi

It is possible to automate the addition of a new user with the passphrase ?

For example with something like this... :

```
#!/bin/bash
export MENU_OPTION="1"
export CLIENT="foo"
export PASS="2"
export PASSPHRASE="bar"
./openvpn-install.sh
```

**Comment by angristan** [comment]
See: https://github.com/angristan/openvpn-install/issues/389
