### ISSUE TITLE
motd

### ISSUE THREAD

**Issue by rafalohaki** [angristan/openvpn-install#849]
![image](https://user-images.githubusercontent.com/20607107/120195309-e9aa6d80-c21e-11eb-9fbf-1802e28e2264.png)
![image](https://user-images.githubusercontent.com/20607107/120195329-efa04e80-c21e-11eb-99de-6b2cc9329c02.png)
which one is truth?
there isnt any deb 10 or ubuntu 20, they are recent distributions.
deb 9 and ubuntu 18 is old server.

**Comment by angristan** [comment]
It's `Debian >=9` and `Ubuntu >= 18.04`. So these version, or more recent ones
