### ISSUE TITLE
Serveur de mise à jour swupdate.openvpn.net mort/obsolète ?

### ISSUE THREAD

**Issue by Matthi3u** [angristan/openvpn-install#86]
Bonjour, merci encore pour ton script.

J'ai trouvé bizarre que mon openvpn 2.3.14; sous jessie, n'avait pas reçu de mise à jour depuis un moment et aujourd'hui j'ai une erreur de clé lors de ma mise à jour et j'ai trouvé ça : 
https://community.openvpn.net/openvpn/wiki/OpenvpnSoftwareRepos
avec un nouveau serveur de maj, je l'ai ajouté et là je suis passé en 2.3.17.
J'ai pas de serveur sous stretch donc à tester.

**Comment by angristan** [comment]
En effet ça installe la 2.3.14 sur un serveur neuf aussi. Je vais update ça
