### ISSUE TITLE
"local n.n.n.n" IP binding not added to server.config

### ISSUE THREAD

**Issue by clickworkorange** [angristan/openvpn-install#88]
I'm running OpenVPN on a secondary IP address and struggled for hours to figure out why UDP connections wouldn't work, while TCP connections did. Turned out to be something really simple: despite the openvpn-install script asking for which IP address to use, this is not added to the server config. All I needed to do was to add `local 22.33.44.55` to server.config and restart OpenVPN (with 22.33.44.55 being the secondary IP address) and I am now able to connect using UDP transport.

**Comment by clickworkorange** [comment]
See https://github.com/Angristan/OpenVPN-install/pull/91

**Comment by angristan** [comment]
Thanks :)
