### ISSUE TITLE
Parametrization of EASYRSA_CA_EXPIRE and EASYRSA_CERT_EXPIRE

### ISSUE THREAD

**Issue by msarvinen** [angristan/openvpn-install#890]
I think it would add value for this project if CA and CERT expiration times could be modified when creating a server or a client. Currently script makes it by using 825 days. And at least in my case I want to use shorter times for a certain cases and longer times for another cases.

To be exact, I'm referring to these parameters:
# In how many days should the root CA key expire?
#set_var EASYRSA_CA_EXPIRE	3650

# In how many days should certificates expire?
#set_var EASYRSA_CERT_EXPIRE	825

**Additional context**
You have madea great script, makes world more secure and allows many admins to save lot of hours. Thank You!

**Comment by angristan** [comment]
Closing to centralize in https://github.com/angristan/openvpn-install/issues/974
