### ISSUE TITLE
Failed to fetch http://swupdate.openvpn.net/ - 404 Not Found [IP: 104.20.194.50 80]

### ISSUE THREAD

**Issue by rhbkweb** [angristan/openvpn-install#90]
Hi,

Since a few days I'm getting this error message when I try to update my server:

`Err http://swupdate.openvpn.net jessie/main amd64 Packages                             
  404  Not Found [IP: 104.20.194.50 80]
Fetched 4,952 kB in 8s (562 kB/s)                                                      
W: Failed to fetch http://swupdate.openvpn.net/apt/dists/jessie/main/binary-amd64/Packages  404  Not Found [IP: 104.20.194.50 80]

E: Some index files failed to download. They have been ignored, or old ones used instead.
`

My server is running Debian 8.9 Jessie. Does anyone knows how to fix this issue?

Thanks

**Comment by angristan** [comment]
Yes, this repository seems to be unmaintained. Please use edit your `/etc/apt/sources.list.d/swupdate-openvpn.list` with build.openvpn.net like [this](https://github.com/Angristan/OpenVPN-install/commit/a3c005c556bc925af13f678aed8fa73515ca5f27).

**Comment by 45236** [comment]
then I get this message when running apt-get update:

W: Duplicate sources.list entry http://build.openvpn.net/debian/openvpn/stable/ jessie/main amd64 Packages (/var/lib/apt/lists/build.openvpn.net_debian_openvpn_stable_dists_jessie_main_binary-amd64_Packages)
W: Probieren Sie »apt-get update«, um diese Probleme zu korrigieren.

**Comment by angristan** [comment]
Did you remove the other entry ?

**Comment by 45236** [comment]
I have it re-installed and now works. Thank you :)
