### ISSUE TITLE
Change ifconfig.co to ipv6-test

### ISSUE THREAD

**Issue by devrandom0** [Angristan/OpenVPN-install#925]
**⚠️ Unless you are sure you find a bug with the script, please open a [discussion](https://github.com/angristan/openvpn-install/discussions) instead of an issue!**

**Checklist**

- [x] I read the [README](https://github.com/angristan/openvpn-install/blob/master/README.md)
- [x] I read the [FAQ](https://github.com/angristan/openvpn-install/blob/master/FAQ.md)
- [x] I searched the [issues](https://github.com/angristan/openvpn-install/issues?q=is%3Aissue+)
- [x] I searched the [discussion](https://github.com/angristan/openvpn-install/discussions)
- [x] My issue is about the script, and not OpenVPN itself

Please include as much details as possible in your issue:

- Description of the issue
- How to reproduce the issue
- What did you expect should happen
- Logs
- Server/Client versions (OS, OpenVPN, etc)
- Any context or information that could help

---

Dear guys
The https://ifconfig.co block some countries (eg. Iran) by Cloudflare and when you run the `curl ifconfig.co`, you will be getting `error code: 1020`

I created #924 according to this issue.

(Please add hacktoberfest label)

**Comment by wangzhenjjcn** [comment]
@angristan but these 2 option dont support ipv6 only network
these based on nat v4
