### ISSUE TITLE
Client can't connect because "Cannot ioctl TUNSETIFF tun: Operation not permitted"

### ISSUE THREAD

**Issue by jerkstorecaller** [angristan/openvpn-install#937]
**⚠️ Unless you are sure you find a bug with the script, please open a [discussion](https://github.com/angristan/openvpn-install/discussions) instead of an issue!**

**Checklist**

- [x] I read the [README](https://github.com/angristan/openvpn-install/blob/master/README.md)
- [x] I read the [FAQ](https://github.com/angristan/openvpn-install/blob/master/FAQ.md)
- [x] I searched the [issues](https://github.com/angristan/openvpn-install/issues?q=is%3Aissue+)
- [x] I searched the [discussion](https://github.com/angristan/openvpn-install/discussions)
- [ ] My issue is about the script, and not OpenVPN itself

Pease include as much details as possible in your issue:

- Description of the issue
- How to reproduce the issue
- What did you expected should happen
- Logs
- Server/Client versions (OS, OpenVPN, etc)
- Any context or information that could help

---

I bought a Ubuntu Server 20.04 KVM VPS and used this script to setup OpenVPN, answering with default answer every time.

I see openvpn running, packets sent to server's UDP 1194 arrive, so there's no firewall issues. But my client can't connect. When I run ```openvpn --config angristantest.ovpn``` from the command-line on the client, during the handshake with the server, half-way through it stops because "Cannot ioctl TUNSETIFF tun: Operation not permitted". 

I also tried desktop/GUI Ubuntu's VPN connection in Network Connections, that one doesn't give any more info, just says "Connecting" then times out.

Has anyone here ran into this issue? Is it possible the "nobody" user created by the script isn't given the permissions to use the tun device?

NOTE: after seeing the warning after creating this issue: I have no idea if the issue is with the script or with OpenVPN. I'm using this script specifically so I don't have to learn OpenVPN. What I do know is that searching for the error message in the closed issues and discussions shows nothing, so at least this issue can  help people googling the error message.

**Comment by rvva** [comment]
The problem is that the command:
`openvpn --config angristantest.ovpn`
needs to be used with sudo for a non-root user.

Just use command:
`sudo openvpn --config angristantest.ovpn`

At my linux enviroment i have the same problem if i run openvpn without sudo:
`ERROR: Cannot ioctl TUNSETIFF tun: Operation not permitted (errno=1)`
The error clearly indicates a permissions problem.

I was faced with the problem that network-manager-openvpn for gnome was having connection problems in Fedora 34. However, the openvpn program itself did not have. I recommend using the openvpn command directly from cli.

**Comment by jerkstorecaller** [comment]
I see, that was indeed the issue. I'm an idiot, I didn't think it was acting on the local (client-side) tun device, I thought it was the remote. Since the built-in Ubuntu VPN connection manager lets you add an ovpn file and try to connect, without ever asking for a sudo password, I didn't think of local permissions. But no excuse, my reflex should've been to use sudo :) 

Thanks!

The fact that the built-in Ubuntu VPN connection doesn't work is weird. Both my client machine and my server are Ubuntu 20.04, this is the most popular distro out there, you'd think this would be tested.
