### ISSUE TITLE
apt-get update not work

### ISSUE THREAD

**Issue by 45236** [angristan/openvpn-install#94]
Hello,

since the installation yesterday apt-get update does not work anymore. I get the error message:

**W: Fehlschlag beim Holen von http://swupdate.openvpn.net/apt/dists/jessie/main/binary-amd64/Packages  404  Not Found [IP: 104.20.195.50 80]

E: Einige Indexdateien konnten nicht heruntergeladen werden. Sie wurden ignoriert oder alte an ihrer Stelle benutzt.**

OS: Debian Jessie

Can anyone help?

**Comment by angristan** [comment]
Please look here : https://github.com/Angristan/OpenVPN-install/issues/90#issuecomment-323610299
