### ISSUE TITLE
Yealink older phone supporting.

### ISSUE THREAD

**Issue by oxess** [Angristan/OpenVPN-install#946]
**Checklist**

- [x] I read the [README](https://github.com/angristan/openvpn-install/blob/master/README.md)
- [x] I read the [FAQ](https://github.com/angristan/openvpn-install/blob/master/FAQ.md)
- [x] I searched the [issues](https://github.com/angristan/openvpn-install/issues?q=is%3Aissue+)
- [x] My issue is about the script, and not OpenVPN itself

**Is your feature request related to a problem? Please describe.**
I was configure client for Yealink T22P Phone. 
Script don't allow create a supported certificates.

**Describe the solution you'd like**
Yealink require set variable `EASYRSA_DIGEST` to `md5` or `sha1`.

**Comment by TinCanTech** [comment]
Both `MD5` and `SHA1` are proven to be broken.

If you want to support broken Yealink then simply edit the variables you require.

**Comment by oxess** [comment]
I know, but can be add this options with desc "MD5 (dangerous)". 
Yealink is popular IP Phone provider, this is very useful change.

**Comment by tpwo** [comment]
It might be useful for your needs but it's totally against the idea of this script:

> Note that whatever you choose, all the choices presented in the script are safe. (Unlike OpenVPN's defaults)

**Comment by oxess** [comment]
Ok, I understand
