### ISSUE TITLE
freebsd (freenas-jail)

### ISSUE THREAD

**Issue by z3r0l1nk** [angristan/openvpn-install#95]
Hello,
This is not an issue...but I don't know how to add a request or suggestion.
Is it possible to make this script compatible with FreeBSD so that it can be installed in FreeNAS?

Regards,
Mihai Stroescu

**Comment by angristan** [comment]
Hi, thanks for the suggestion, but I'm not familiar with BSD systems so I definitely won't support it in the near future.
