### ISSUE TITLE
Vpn Client not connected

### ISSUE THREAD

**Issue by shetubd** [Angristan/OpenVPN-install#953]
I run this script on fresh Debain10 vps. But I can not connect from client pc.
I use default settings. 

Log file from client:
Tue Dec 28 00:12:42 2021 OpenVPN 2.5.3 x86_64-w64-mingw32 [SSL (OpenSSL)] [LZO] [LZ4] [PKCS11] [AEAD] built on Jun 17 2021
Tue Dec 28 00:12:42 2021 Windows version 6.1 (Windows 7) 64bit
Tue Dec 28 00:12:42 2021 library versions: OpenSSL 1.1.1k  25 Mar 2021, LZO 2.10
Tue Dec 28 00:12:42 2021 MANAGEMENT: TCP Socket listening on [AF_INET]127.0.0.1:25341
Tue Dec 28 00:12:42 2021 Need hold release from management interface, waiting...
Tue Dec 28 00:12:42 2021 MANAGEMENT: Client connected from [AF_INET]127.0.0.1:25341
Tue Dec 28 00:12:42 2021 MANAGEMENT: CMD 'state on'
Tue Dec 28 00:12:42 2021 MANAGEMENT: CMD 'log all on'
Tue Dec 28 00:12:42 2021 MANAGEMENT: CMD 'echo all on'
Tue Dec 28 00:12:42 2021 MANAGEMENT: CMD 'bytecount 5'
Tue Dec 28 00:12:42 2021 MANAGEMENT: CMD 'hold off'
Tue Dec 28 00:12:42 2021 MANAGEMENT: CMD 'hold release'
Tue Dec 28 00:12:45 2021 Outgoing Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Tue Dec 28 00:12:45 2021 Outgoing Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Tue Dec 28 00:12:45 2021 Incoming Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Tue Dec 28 00:12:45 2021 Incoming Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Tue Dec 28 00:12:45 2021 TCP/UDP: Preserving recently used remote address: [AF_INET]......:1194
Tue Dec 28 00:12:45 2021 Socket Buffers: R=[8192->8192] S=[8192->8192]
Tue Dec 28 00:12:45 2021 UDP link local: (not bound)
Tue Dec 28 00:12:45 2021 UDP link remote: [AF_INET]........:1194
Tue Dec 28 00:12:45 2021 MANAGEMENT: >STATE:1640628765,WAIT,,,,,,

**Comment by Ahmed-Shabrawy** [comment]
check if the tun module loaded 

lsmod | grep tun 

IF not , load tun module

**Comment by shetubd** [comment]
Thanks. It was debain buster nftables problem. I nftables service then openvpn connect.
