### ISSUE TITLE
New client Connects previous clients stop working 

### ISSUE THREAD

**Issue by Pediiz** [Angristan/OpenVPN-install#954]
hi,
today I installed openvpn with angristan on my Centos 7 server 
the problem is when 2nd or 3rd client connects to server, first one still connected but doesn't have internet
I use separate profile for each user
all clients are on different locations
also I added "duplicate-cn" but its the same

the problem not solved , at moment new client connect to openvpn server all other still connected but without internet or ping
theres notin on log 
help please

**Comment by MistFenix** [comment]
How did you add dublicate-cn if it doesn't work in my server.conf

**Comment by TinCanTech** [comment]
Obviously, the problem is not related to `--duplicate-cn`.

**Comment by MistFenix** [comment]
> Obviously, the problem is not related to `--duplicate-cn`.

Could you help me with settings dublicate-cn, I wrote this in my server.conf but it get error and server stopped

**Comment by TinCanTech** [comment]
`--duplicate-cn` will **not** stop your server.

And, as I clearly pointed out, the problem is not caused by `--duplicate-cn`.

What-ever is wrong with your server, you will find in your logs.

**Comment by MistFenix** [comment]
Process: 17614 ExecStart=/usr/sbin/openvpn --status /run/openvpn-server/status-server.log --status-version 2 --suppress-timestamps --config server.conf (code=exited, status=1/FAILURE)
Main PID: 17614 (code=exited, status=1/FAILURE)

I wrote in server.conf dublicate-cn and client-to-client and status give me it

**Comment by TinCanTech** [comment]
Try this: `openvpn server.conf`

**Comment by MistFenix** [comment]
> Try this: `openvpn server.conf`

Tried but also the same result

**Comment by MansurFenix** [comment]
port 443
proto tcp
dev tun
user nobody
group nogroup
persist-key
persist-tun
keepalive 10 120
topology subnet
server 10.8.0.0 255.255.255.0
ifconfig-pool-persist ipp.txt
push "dhcp-option DNS *my ip here"
push "redirect-gateway def1 bypass-dhcp"
dh none
ecdh-curve prime256v1
tls-crypt tls-crypt.key
crl-verify crl.pem
ca ca.crt
cert server_j5Zx5gJ9iukEgVMq.crt
key server_j5Zx5gJ9iukEgVMq.key
auth SHA256
cipher AES-128-GCM
ncp-ciphers AES-128-GCM
tls-server
tls-version-min 1.2
tls-cipher TLS-ECDHE-ECDSA-WITH-AES-128-GCM-SHA256
client-config-dir /etc/openvpn/ccd
status /var/log/openvpn/status.log
verb 3


It's my server.conf, is there any mistake except my ip in dns?

**Comment by Pediiz** [comment]
I found the problem
the problem was about assign IP and persist pool i Disable it and it worked
about dublicate-cn ! you shoud add "dublicate-cn" not "--dublicate-cn"
