### ISSUE TITLE
Support udp2raw/stunnel application to baypass blocking in countries 

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [Angristan/OpenVPN-install#959]
I'm a user in one of countries where i can't use both actually wireguard and openvpn because my ISP is blocking both protocols 

So it would be nice idea to add support for application like udp2raw or really any other application to unblock udp protocol

heck! even if you want i could submit an PR to add it

**Comment by TinCanTech** [comment]
Submit submit submit!

**Comment by EsmailELBoBDev2** [comment]
Sure! i already got guides link just allow me some time to translate it into script and merge it 

PS: *my exams are near (24th this month so yup you need to wish me luck and allow me some time buddy!) but wish me luck i'm serious i did not study well*
