### ISSUE TITLE
OpenVPN 2.4 Ubuntu Server 16.04.03 LTS

### ISSUE THREAD

**Issue by fuddel18** [angristan/openvpn-install#98]
Hello Angristan,

first of all a big praise to your work. Find the script sher well.
I have one more question. I have an Ubuntu Server 16.04.03 LTS and there is only OpenVPN 2.3.10 installed.
But would like the new OpenVPN Verstion 2.4. Is it somehow possible to realize your script.

Many Thanks.

**Comment by angristan** [comment]
What do you want exactly ? If you just want to update the OpenVPN package, then do the following:

```
rm /etc/apt/sources.list.d/swupdate-openvpn.list
echo "deb http://build.openvpn.net/debian/openvpn/stable xenial main" > /etc/apt/sources.list.d/openvpn-aptrepo.list
apt update
apt full-upgrade

```

**Comment by fuddel18** [comment]
Thank you for your quick response.
I would like to use OpenVPN 2.4 on my Ubuntu 16.04.03 LTS server.
When I use the OpenVPN Script 2.4 I installed OpenVPN 2.3.10 but I would like OpenVPN 2.4.
Can I use the OpenVPN Script 2.4 when I have executed the commands above?

**Comment by angristan** [comment]
> OpenVPN Script 2.4

Could you be more precise?

**Comment by fuddel18** [comment]
OK.
I have an Ubuntu 16.04.3 Lts server. If you use your OpenVPN Script 2.4, but will install OpenVPN 2.3.10.
How can I set up the OpenVPN script 2.4 of you also OpenVPN 2.4 installed on an Ubuntu 16.04.03 Lts server

**Comment by angristan** [comment]
What do you mean by "OpenVPN Script 2.4" ?

**Comment by fuddel18** [comment]
That you have set at github. Ist das noch eine Beta version? 
[Link](https://github.com/Angristan/OpenVPN-install/blob/openvpn-2.4/openvpn-install.sh)

**Comment by angristan** [comment]
Yes. Please comment on https://github.com/Angristan/OpenVPN-install/pull/96 if you have any issue, but **only** on a fresh installed server.
