### ISSUE TITLE
Iptables error with Arch Linux on armhf (Scaleway)

### ISSUE THREAD

**Issue by angristan** [angristan/openvpn-install#99]
```
An updated CRL has been created.
CRL file: /etc/openvpn/easy-rsa/pki/crl.pem

Bad argument `eth0'
Try `iptables -h' or 'iptables --help' for more information.
sh: th0: command not found
sh: th0: command not found
2334
Created symlink /etc/systemd/system/multi-user.target.wants/openvpn-server@openvpn.service → /usr/lib/systemd/system/openvpn-server@.service.
```

I'm not sure if it's related to Arch Linux, armfh or Scaleway.

**Comment by ghost** [comment]
I've tested the 2.4-branch this morning and didn't get such an error on an arch system. (not scaleway)

**Comment by angristan** [comment]
I've tried on a Arch Linux VM too and I didn't get any issue. Well who wants to use Arch on a Scaleway C1 anyway

**Comment by angristan** [comment]
So this was fixed by https://github.com/Angristan/OpenVPN-install/commit/aca3b4a019c3545331e2f8e39af65ac730501d6a

However, the trafic is still not forwarded by the server. This issue looks a lot like https://github.com/Angristan/OpenVPN-install/issues/125, I wonder if they're related.

**Comment by angristan** [comment]
There is no Arch Linux available on the C1 anymore.
