### ISSUE TITLE
Files For Configs To Be Written To

### ISSUE THREAD

**Issue by CyberGhost047** [Angristan/OpenVPN-install#993]
**Checklist**

- [x] I read the [README](https://github.com/angristan/openvpn-install/blob/master/README.md)
- [x] I read the [FAQ](https://github.com/angristan/openvpn-install/blob/master/FAQ.md)
- [x] I searched the [issues](https://github.com/angristan/openvpn-install/issues?q=is%3Aissue+)
- [x] My issue is about the script, and not OpenVPN itself

To keep things neat, create a directory in the home directory where all openvpn configs are written to and stored.

**Comment by angristan** [comment]
PR welcome :)
